"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

import diff_co_lcm

class lcmt_global_solve(object):

    __slots__ = ["utime", "bspline_object", "bspline_robot_1", "bspline_robot_2"]

    __typenames__ = ["int64_t", "diff_co_lcm.lcmt_bspline", "diff_co_lcm.lcmt_bspline", "diff_co_lcm.lcmt_bspline"]

    __dimensions__ = [None, None, None, None]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.bspline_object = diff_co_lcm.lcmt_bspline()
        """ LCM Type: diff_co_lcm.lcmt_bspline """
        self.bspline_robot_1 = diff_co_lcm.lcmt_bspline()
        """ LCM Type: diff_co_lcm.lcmt_bspline """
        self.bspline_robot_2 = diff_co_lcm.lcmt_bspline()
        """ LCM Type: diff_co_lcm.lcmt_bspline """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_global_solve._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        assert self.bspline_object._get_packed_fingerprint() == diff_co_lcm.lcmt_bspline._get_packed_fingerprint()
        self.bspline_object._encode_one(buf)
        assert self.bspline_robot_1._get_packed_fingerprint() == diff_co_lcm.lcmt_bspline._get_packed_fingerprint()
        self.bspline_robot_1._encode_one(buf)
        assert self.bspline_robot_2._get_packed_fingerprint() == diff_co_lcm.lcmt_bspline._get_packed_fingerprint()
        self.bspline_robot_2._encode_one(buf)

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_global_solve._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_global_solve._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_global_solve()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.bspline_object = diff_co_lcm.lcmt_bspline._decode_one(buf)
        self.bspline_robot_1 = diff_co_lcm.lcmt_bspline._decode_one(buf)
        self.bspline_robot_2 = diff_co_lcm.lcmt_bspline._decode_one(buf)
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_global_solve in parents: return 0
        newparents = parents + [lcmt_global_solve]
        tmphash = (0x26fe16f86b1e6224+ diff_co_lcm.lcmt_bspline._get_hash_recursive(newparents)+ diff_co_lcm.lcmt_bspline._get_hash_recursive(newparents)+ diff_co_lcm.lcmt_bspline._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_global_solve._packed_fingerprint is None:
            lcmt_global_solve._packed_fingerprint = struct.pack(">Q", lcmt_global_solve._get_hash_recursive([]))
        return lcmt_global_solve._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_global_solve._get_packed_fingerprint())[0]

