"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class lcmt_bspline(object):

    __slots__ = ["utime", "order", "num_control_points", "num_positions", "control_points"]

    __typenames__ = ["int64_t", "int32_t", "int32_t", "int32_t", "double"]

    __dimensions__ = [None, None, None, None, ["num_positions", "num_control_points"]]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.order = 0
        """ LCM Type: int32_t """
        self.num_control_points = 0
        """ LCM Type: int32_t """
        self.num_positions = 0
        """ LCM Type: int32_t """
        self.control_points = []
        """ LCM Type: double[num_positions][num_control_points] """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_bspline._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qiii", self.utime, self.order, self.num_control_points, self.num_positions))
        for i0 in range(self.num_positions):
            buf.write(struct.pack('>%dd' % self.num_control_points, *self.control_points[i0][:self.num_control_points]))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_bspline._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_bspline._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_bspline()
        self.utime, self.order, self.num_control_points, self.num_positions = struct.unpack(">qiii", buf.read(20))
        self.control_points = []
        for i0 in range(self.num_positions):
            self.control_points.append(struct.unpack('>%dd' % self.num_control_points, buf.read(self.num_control_points * 8)))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_bspline in parents: return 0
        tmphash = (0x7ffa7a75ae4770f6) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_bspline._packed_fingerprint is None:
            lcmt_bspline._packed_fingerprint = struct.pack(">Q", lcmt_bspline._get_hash_recursive([]))
        return lcmt_bspline._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_bspline._get_packed_fingerprint())[0]

