"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class lcmt_support_vector(object):

    __slots__ = ["utime", "num_support_vectors", "num_weights", "support_vector_dimension", "weights_dimension", "support_vectors", "weights"]

    __typenames__ = ["int64_t", "int32_t", "int32_t", "int32_t", "int32_t", "double", "double"]

    __dimensions__ = [None, None, None, None, None, ["num_support_vectors", "support_vector_dimension"], ["num_weights", "weights_dimension"]]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.num_support_vectors = 0
        """ LCM Type: int32_t """
        self.num_weights = 0
        """ LCM Type: int32_t """
        self.support_vector_dimension = 0
        """ LCM Type: int32_t """
        self.weights_dimension = 0
        """ LCM Type: int32_t """
        self.support_vectors = []
        """ LCM Type: double[num_support_vectors][support_vector_dimension] """
        self.weights = []
        """ LCM Type: double[num_weights][weights_dimension] """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_support_vector._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qiiii", self.utime, self.num_support_vectors, self.num_weights, self.support_vector_dimension, self.weights_dimension))
        for i0 in range(self.num_support_vectors):
            buf.write(struct.pack('>%dd' % self.support_vector_dimension, *self.support_vectors[i0][:self.support_vector_dimension]))
        for i0 in range(self.num_weights):
            buf.write(struct.pack('>%dd' % self.weights_dimension, *self.weights[i0][:self.weights_dimension]))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_support_vector._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_support_vector._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_support_vector()
        self.utime, self.num_support_vectors, self.num_weights, self.support_vector_dimension, self.weights_dimension = struct.unpack(">qiiii", buf.read(24))
        self.support_vectors = []
        for i0 in range(self.num_support_vectors):
            self.support_vectors.append(struct.unpack('>%dd' % self.support_vector_dimension, buf.read(self.support_vector_dimension * 8)))
        self.weights = []
        for i0 in range(self.num_weights):
            self.weights.append(struct.unpack('>%dd' % self.weights_dimension, buf.read(self.weights_dimension * 8)))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_support_vector in parents: return 0
        tmphash = (0x16f810edff52c205) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_support_vector._packed_fingerprint is None:
            lcmt_support_vector._packed_fingerprint = struct.pack(">Q", lcmt_support_vector._get_hash_recursive([]))
        return lcmt_support_vector._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_support_vector._get_packed_fingerprint())[0]

