# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def frame_pose_in_frame_box_world(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix14_1

    Outputs:
        out: Matrix44


    """

    # Total ops: 36

    # Input arrays

    # Intermediate terms (12)
    _tmp0 = 2.0 / (_in0[10, 0] ** 2.0 + _in0[7, 0] ** 2.0 + _in0[8, 0] ** 2.0 + _in0[9, 0] ** 2.0)
    _tmp1 = -_in0[9, 0] ** 2 * _tmp0
    _tmp2 = -_in0[10, 0] ** 2 * _tmp0 + 1.0
    _tmp3 = _in0[8, 0] * _tmp0
    _tmp4 = _in0[9, 0] * _tmp3
    _tmp5 = _in0[10, 0] * _tmp0
    _tmp6 = _in0[7, 0] * _tmp5
    _tmp7 = _in0[7, 0] * _in0[9, 0] * _tmp0
    _tmp8 = _in0[8, 0] * _tmp5
    _tmp9 = -_in0[8, 0] ** 2 * _tmp0
    _tmp10 = _in0[7, 0] * _tmp3
    _tmp11 = _in0[9, 0] * _tmp5

    # Output terms
    _out = casadi.blockcat(
        [
            [_tmp1 + _tmp2, _tmp4 - _tmp6, _tmp7 + _tmp8, _in0[11, 0]],
            [_tmp4 + _tmp6, _tmp2 + _tmp9, -_tmp10 + _tmp11, _in0[12, 0]],
            [-_tmp7 + _tmp8, _tmp10 + _tmp11, _tmp1 + _tmp9 + 1.0, _in0[13, 0]],
            [0, 0, 0, 1.00000000000000],
        ]
    )

    return _out


_in0_sx = casadi.SX.sym("_in0", 14, 1)
frame_pose_in_frame_box_world = casadi.Function(
    "frame_pose_in_frame_box_world",
    [_in0_sx],
    [frame_pose_in_frame_box_world(_in0_sx)],
    dict([("cse", True)]),
)
