# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def all_geometries(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix72_3


    """

    # Total ops: 1030

    # Input arrays

    # Intermediate terms (244)
    _tmp0 = casadi.sin(_in0[0, 0])
    _tmp1 = 0.04 * _tmp0
    _tmp2 = 0.075 * _tmp0
    _tmp3 = 0.035 * _tmp0
    _tmp4 = casadi.cos(_in0[0, 0])
    _tmp5 = casadi.sin(_in0[1, 0])
    _tmp6 = 0.171 * _tmp5
    _tmp7 = 0.136 * _tmp5
    _tmp8 = 0.07 * _tmp5
    _tmp9 = 0.206 * _tmp5
    _tmp10 = 0.246 * _tmp5
    _tmp11 = 0.316 * _tmp5
    _tmp12 = casadi.sin(_in0[2, 0])
    _tmp13 = 0.0825 * _tmp12
    _tmp14 = casadi.cos(_in0[2, 0])
    _tmp15 = _tmp14 * _tmp4
    _tmp16 = casadi.cos(_in0[1, 0])
    _tmp17 = 0.0825 * _tmp16
    _tmp18 = -_tmp0 * _tmp13 + _tmp11 * _tmp4 + _tmp15 * _tmp17 - 0.62
    _tmp19 = _tmp0 * _tmp14
    _tmp20 = 0.03 * _tmp19
    _tmp21 = _tmp12 * _tmp16
    _tmp22 = 0.03 * _tmp21
    _tmp23 = _tmp22 * _tmp4
    _tmp24 = -_tmp20 - _tmp23
    _tmp25 = 0.06 * _tmp19
    _tmp26 = 0.06 * _tmp21
    _tmp27 = _tmp26 * _tmp4
    _tmp28 = 0.286 * _tmp5
    _tmp29 = _tmp1 * _tmp12
    _tmp30 = 0.04 * _tmp4
    _tmp31 = _tmp14 * _tmp30
    _tmp32 = casadi.sin(_in0[3, 0])
    _tmp33 = 1.0 * _tmp12
    _tmp34 = _tmp0 * _tmp33
    _tmp35 = 1.0 * _tmp15
    _tmp36 = _tmp16 * _tmp35 - _tmp34
    _tmp37 = _tmp32 * _tmp36
    _tmp38 = casadi.cos(_in0[3, 0])
    _tmp39 = _tmp36 * _tmp38
    _tmp40 = _tmp1 * _tmp14
    _tmp41 = _tmp12 * _tmp30
    _tmp42 = _tmp4 * _tmp5
    _tmp43 = 0.03 * _tmp38
    _tmp44 = 0.035 * _tmp4
    _tmp45 = _tmp32 * _tmp5
    _tmp46 = 0.01 * _tmp14
    _tmp47 = 0.01 * _tmp21
    _tmp48 = _tmp38 * _tmp5
    _tmp49 = _tmp32 * _tmp42
    _tmp50 = 0.064 * _tmp38
    _tmp51 = _tmp18 - 0.0825 * _tmp39 - 0.0825 * _tmp49
    _tmp52 = 0.104 * _tmp38
    _tmp53 = 0.144 * _tmp38
    _tmp54 = 0.174 * _tmp38
    _tmp55 = 0.329 * _tmp38
    _tmp56 = casadi.cos(_in0[4, 0])
    _tmp57 = 1.0 * _tmp19
    _tmp58 = _tmp33 * _tmp4
    _tmp59 = _tmp16 * _tmp58 + _tmp57
    _tmp60 = _tmp56 * _tmp59
    _tmp61 = casadi.sin(_in0[4, 0])
    _tmp62 = 1.0 * _tmp39 + 1.0 * _tmp49
    _tmp63 = _tmp61 * _tmp62
    _tmp64 = 0.304 * _tmp38
    _tmp65 = _tmp51 - 0.085 * _tmp60 - 0.085 * _tmp63
    _tmp66 = 0.274 * _tmp38
    _tmp67 = 0.254 * _tmp38
    _tmp68 = _tmp51 - 0.08 * _tmp60 - 0.08 * _tmp63
    _tmp69 = 0.234 * _tmp38
    _tmp70 = 0.224 * _tmp38
    _tmp71 = _tmp51 - 0.07 * _tmp60 - 0.07 * _tmp63
    _tmp72 = 0.364 * _tmp38
    _tmp73 = 0.384 * _tmp38
    _tmp74 = -0.384 * _tmp37 + _tmp42 * _tmp73
    _tmp75 = 0.184 * _tmp38
    _tmp76 = casadi.cos(_in0[5, 0])
    _tmp77 = 1.0 * _tmp38
    _tmp78 = -1.0 * _tmp37 + _tmp42 * _tmp77
    _tmp79 = _tmp76 * _tmp78
    _tmp80 = casadi.sin(_in0[5, 0])
    _tmp81 = 0.08 * _tmp80
    _tmp82 = 1.0 * _tmp61
    _tmp83 = 1.0 * _tmp56
    _tmp84 = -_tmp59 * _tmp82 + _tmp62 * _tmp83
    _tmp85 = 0.03 * _tmp80
    _tmp86 = _tmp76 * _tmp84
    _tmp87 = _tmp51 + _tmp74
    _tmp88 = 0.01 * _tmp79
    _tmp89 = _tmp80 * _tmp84
    _tmp90 = 0.01 * _tmp89
    _tmp91 = 0.04 * _tmp80
    _tmp92 = _tmp78 * _tmp91 + 0.04 * _tmp86 + _tmp87
    _tmp93 = 0.06 * _tmp80
    _tmp94 = 0.088 * _tmp80
    _tmp95 = _tmp78 * _tmp94 + 0.088 * _tmp86 + _tmp87
    _tmp96 = casadi.sin(_in0[6, 0])
    _tmp97 = 1.0 * _tmp80
    _tmp98 = _tmp78 * _tmp97 + 1.0 * _tmp86
    _tmp99 = _tmp96 * _tmp98
    _tmp100 = casadi.cos(_in0[6, 0])
    _tmp101 = _tmp100 * _tmp98
    _tmp102 = 0.087 * _tmp80
    _tmp103 = 1.0 * _tmp60 + 1.0 * _tmp63
    _tmp104 = _tmp100 * _tmp103
    _tmp105 = _tmp103 * _tmp96
    _tmp106 = 0.0424264068712119 * _tmp99
    _tmp107 = 0.0424264068711738 * _tmp101
    _tmp108 = 0.0424264068712119 * _tmp104
    _tmp109 = 0.0424264068711738 * _tmp105
    _tmp110 = _tmp106 - _tmp107 - _tmp108 - _tmp109
    _tmp111 = -0.137 * _tmp79 + 0.137 * _tmp89 + _tmp95
    _tmp112 = -0.207 * _tmp79 + 0.207 * _tmp89 + _tmp95
    _tmp113 = 0.0636396103067607 * _tmp96
    _tmp114 = 0.0636396103068178 * _tmp100
    _tmp115 = 0.0848528137423477 * _tmp100
    _tmp116 = 0.0848528137424237 * _tmp96
    _tmp117 = 0.00494974746830805 * _tmp99
    _tmp118 = 0.00494974746830361 * _tmp101
    _tmp119 = 0.00494974746830805 * _tmp104
    _tmp120 = 0.00494974746830361 * _tmp105
    _tmp121 = -0.2104 * _tmp79 + 0.2104 * _tmp89
    _tmp122 = 0.707106781186865 * _tmp96
    _tmp123 = (
        0.70710678118623 * _tmp101
        + 0.707106781186865 * _tmp104
        + 0.70710678118623 * _tmp105
        - 1.0 * _tmp122 * _tmp98
    )
    _tmp124 = _in0[7, 0] * _tmp123 + _tmp95
    _tmp125 = 0.010606601717803 * _tmp99
    _tmp126 = 0.0106066017177935 * _tmp101
    _tmp127 = 0.010606601717803 * _tmp104
    _tmp128 = 0.0106066017177935 * _tmp105
    _tmp129 = -0.1954 * _tmp79 + 0.1954 * _tmp89
    _tmp130 = -_in0[8, 0] * _tmp123 + _tmp95
    _tmp131 = 0.075 * _tmp4
    _tmp132 = _tmp0 * _tmp11 + _tmp13 * _tmp4 + _tmp17 * _tmp19
    _tmp133 = 0.03 * _tmp15
    _tmp134 = _tmp0 * _tmp22
    _tmp135 = _tmp133 - _tmp134
    _tmp136 = 0.06 * _tmp15
    _tmp137 = _tmp0 * _tmp26
    _tmp138 = _tmp0 * _tmp5
    _tmp139 = _tmp16 * _tmp57 + _tmp58
    _tmp140 = _tmp139 * _tmp32
    _tmp141 = _tmp139 * _tmp38
    _tmp142 = _tmp138 * _tmp32
    _tmp143 = _tmp132 - 0.0825 * _tmp141 - 0.0825 * _tmp142
    _tmp144 = 1.0 * _tmp141 + 1.0 * _tmp142
    _tmp145 = _tmp144 * _tmp61
    _tmp146 = _tmp16 * _tmp34 - _tmp35
    _tmp147 = _tmp146 * _tmp56
    _tmp148 = _tmp143 - 0.085 * _tmp145 - 0.085 * _tmp147
    _tmp149 = -0.08 * _tmp145 - 0.08 * _tmp147
    _tmp150 = _tmp143 + _tmp149
    _tmp151 = -0.07 * _tmp145 - 0.07 * _tmp147
    _tmp152 = _tmp138 * _tmp73 - 0.384 * _tmp140 + _tmp143
    _tmp153 = _tmp144 * _tmp83 - _tmp146 * _tmp82
    _tmp154 = _tmp153 * _tmp76
    _tmp155 = _tmp138 * _tmp77 - 1.0 * _tmp140
    _tmp156 = _tmp155 * _tmp76
    _tmp157 = _tmp153 * _tmp80
    _tmp158 = 0.01 * _tmp157
    _tmp159 = 0.01 * _tmp156
    _tmp160 = _tmp152 + 0.04 * _tmp154 + _tmp155 * _tmp91
    _tmp161 = _tmp152 + 0.088 * _tmp154 + _tmp155 * _tmp94
    _tmp162 = 1.0 * _tmp154 + _tmp155 * _tmp97
    _tmp163 = _tmp162 * _tmp96
    _tmp164 = _tmp100 * _tmp162
    _tmp165 = 1.0 * _tmp145 + 1.0 * _tmp147
    _tmp166 = _tmp165 * _tmp96
    _tmp167 = _tmp100 * _tmp165
    _tmp168 = 0.0424264068712119 * _tmp163
    _tmp169 = 0.0424264068711738 * _tmp164
    _tmp170 = 0.0424264068711738 * _tmp166
    _tmp171 = 0.0424264068712119 * _tmp167
    _tmp172 = _tmp168 - _tmp169 - _tmp170 - _tmp171
    _tmp173 = -0.137 * _tmp156 + 0.137 * _tmp157 + _tmp161
    _tmp174 = -0.207 * _tmp156 + 0.207 * _tmp157 + _tmp161
    _tmp175 = 0.00494974746830805 * _tmp163
    _tmp176 = 0.00494974746830361 * _tmp164
    _tmp177 = 0.00494974746830361 * _tmp166
    _tmp178 = 0.00494974746830805 * _tmp167
    _tmp179 = -0.2104 * _tmp156 + 0.2104 * _tmp157
    _tmp180 = (
        -1.0 * _tmp122 * _tmp162
        + 0.70710678118623 * _tmp164
        + 0.70710678118623 * _tmp166
        + 0.707106781186865 * _tmp167
    )
    _tmp181 = _in0[7, 0] * _tmp180 + _tmp161
    _tmp182 = 0.010606601717803 * _tmp163
    _tmp183 = 0.0106066017177935 * _tmp164
    _tmp184 = 0.0106066017177935 * _tmp166
    _tmp185 = 0.010606601717803 * _tmp167
    _tmp186 = -0.1954 * _tmp156 + 0.1954 * _tmp157
    _tmp187 = -_in0[8, 0] * _tmp180 + _tmp161
    _tmp188 = _tmp12 * _tmp5
    _tmp189 = 0.03 * _tmp188
    _tmp190 = _tmp14 * _tmp5
    _tmp191 = 0.0825 * _tmp190
    _tmp192 = 0.316 * _tmp16 - _tmp191 + 0.358
    _tmp193 = 0.06 * _tmp188
    _tmp194 = 0.04 * _tmp190
    _tmp195 = _tmp16 * _tmp32
    _tmp196 = _tmp16 * _tmp38
    _tmp197 = _tmp190 * _tmp38
    _tmp198 = _tmp190 * _tmp32
    _tmp199 = 0.01 * _tmp188
    _tmp200 = _tmp191 * _tmp38 + _tmp192 - 0.0825 * _tmp195
    _tmp201 = 1.0 * _tmp195 - 1.0 * _tmp197
    _tmp202 = _tmp201 * _tmp61
    _tmp203 = _tmp188 * _tmp56
    _tmp204 = _tmp200 - 0.085 * _tmp202 + 0.085 * _tmp203
    _tmp205 = _tmp200 - 0.08 * _tmp202 + 0.08 * _tmp203
    _tmp206 = _tmp200 - 0.07 * _tmp202 + 0.07 * _tmp203
    _tmp207 = 0.384 * _tmp196 + 0.384 * _tmp198
    _tmp208 = _tmp188 * _tmp82 + _tmp201 * _tmp83
    _tmp209 = _tmp208 * _tmp76
    _tmp210 = 1.0 * _tmp196 + 1.0 * _tmp198
    _tmp211 = _tmp210 * _tmp76
    _tmp212 = _tmp200 + _tmp207
    _tmp213 = _tmp208 * _tmp80
    _tmp214 = 0.01 * _tmp213
    _tmp215 = 0.01 * _tmp211
    _tmp216 = 0.04 * _tmp209 + _tmp210 * _tmp91 + _tmp212
    _tmp217 = 0.088 * _tmp209 + _tmp210 * _tmp94 + _tmp212
    _tmp218 = 1.0 * _tmp209 + _tmp210 * _tmp97
    _tmp219 = _tmp100 * _tmp218
    _tmp220 = _tmp218 * _tmp96
    _tmp221 = -_tmp188 * _tmp83 + 1.0 * _tmp202
    _tmp222 = _tmp100 * _tmp221
    _tmp223 = _tmp221 * _tmp96
    _tmp224 = 0.0424264068711738 * _tmp219
    _tmp225 = 0.0424264068712119 * _tmp220
    _tmp226 = 0.0424264068712119 * _tmp222
    _tmp227 = 0.0424264068711738 * _tmp223
    _tmp228 = -_tmp224 + _tmp225 - _tmp226 - _tmp227
    _tmp229 = -0.137 * _tmp211 + 0.137 * _tmp213 + _tmp217
    _tmp230 = -0.207 * _tmp211 + 0.207 * _tmp213 + _tmp217
    _tmp231 = 0.00494974746830361 * _tmp219
    _tmp232 = 0.00494974746830805 * _tmp220
    _tmp233 = 0.00494974746830805 * _tmp222
    _tmp234 = 0.00494974746830361 * _tmp223
    _tmp235 = (
        -1.0 * _tmp122 * _tmp218
        + 0.70710678118623 * _tmp219
        + 0.707106781186865 * _tmp222
        + 0.70710678118623 * _tmp223
    )
    _tmp236 = _in0[7, 0] * _tmp235 + _tmp217
    _tmp237 = -0.2104 * _tmp211 + 0.2104 * _tmp213
    _tmp238 = 0.0106066017177935 * _tmp219
    _tmp239 = 0.010606601717803 * _tmp220
    _tmp240 = 0.010606601717803 * _tmp222
    _tmp241 = 0.0106066017177935 * _tmp223
    _tmp242 = -0.1954 * _tmp211 + 0.1954 * _tmp213
    _tmp243 = -_in0[8, 0] * _tmp235 + _tmp217

    # Output terms
    _out = casadi.blockcat(
        [
            [-0.600000000000000, 0, 0.0650000000000000],
            [-0.610000000000000, 0.0500000000000000, 0.0850000000000000],
            [-0.610000000000000, -0.0500000000000000, 0.0850000000000000],
            [-0.680000000000000, 0, 0.0850000000000000],
            [-0.680000000000000, 0.0500000000000000, 0.0850000000000000],
            [-0.650000000000000, 0.0500000000000000, 0.0850000000000000],
            [-0.650000000000000, -0.0500000000000000, 0.0850000000000000],
            [-0.680000000000000, -0.0500000000000000, 0.0850000000000000],
            [-0.710000000000000, -0.0500000000000000, 0.0850000000000000],
            [-0.710000000000000, 0, 0.0850000000000000],
            [-0.710000000000000, 0.0500000000000000, 0.0850000000000000],
            [-0.740000000000000, 0, 0.0850000000000000],
            [-0.620000000000000, 0, 0.138000000000000],
            [-0.620000000000000, 0, 0.108000000000000],
            [-0.620000000000000, 0, 0.228000000000000],
            [-0.620000000000000, 0, 0.198000000000000],
            [-0.620000000000000, 0, 0.168000000000000],
            [_tmp1 - 0.62, -_tmp30, 0.298000000000000],
            [_tmp2 - 0.62, -_tmp131, 0.358000000000000],
            [_tmp3 - 0.62, -_tmp44, 0.358000000000000],
            [-0.620000000000000, 0, 0.358000000000000],
            [-_tmp3 - 0.62, _tmp44, 0.358000000000000],
            [-_tmp2 - 0.62, _tmp131, 0.358000000000000],
            [_tmp4 * _tmp6 - 0.62, _tmp0 * _tmp6, 0.171 * _tmp16 + 0.358],
            [_tmp4 * _tmp7 - 0.62, _tmp0 * _tmp7, 0.136 * _tmp16 + 0.358],
            [-_tmp1 + _tmp4 * _tmp8 - 0.62, _tmp0 * _tmp8 + _tmp30, 0.07 * _tmp16 + 0.358],
            [_tmp4 * _tmp9 - 0.62, _tmp0 * _tmp9, 0.206 * _tmp16 + 0.358],
            [_tmp10 * _tmp4 - 0.62, _tmp0 * _tmp10, 0.246 * _tmp16 + 0.358],
            [_tmp18 + _tmp24, _tmp132 + _tmp135, _tmp189 + _tmp192],
            [_tmp18 - _tmp25 - _tmp27, _tmp132 + _tmp136 - _tmp137, _tmp192 + _tmp193],
            [
                _tmp16 * _tmp31 + _tmp24 + _tmp28 * _tmp4 - _tmp29 - 0.62,
                _tmp0 * _tmp28 + _tmp135 + _tmp16 * _tmp40 + _tmp41,
                0.286 * _tmp16 + _tmp189 - _tmp194 + 0.358,
            ],
            [_tmp18 + _tmp25 + _tmp27, _tmp132 - _tmp136 + _tmp137, _tmp192 - _tmp193],
            [_tmp18 + _tmp20 + _tmp23, _tmp132 - _tmp133 + _tmp134, -_tmp189 + _tmp192],
            [
                _tmp16 * _tmp41
                + _tmp18
                - 0.03 * _tmp37
                - 0.035 * _tmp39
                + _tmp40
                + _tmp42 * _tmp43
                - _tmp44 * _tmp45,
                _tmp132
                + _tmp138 * _tmp43
                - 0.03 * _tmp140
                - 0.035 * _tmp141
                + _tmp16 * _tmp29
                - _tmp3 * _tmp45
                - _tmp31,
                -0.04 * _tmp188
                + _tmp192
                - 0.035 * _tmp195
                + 0.03 * _tmp196
                + 0.035 * _tmp197
                + 0.03 * _tmp198,
            ],
            [
                _tmp0 * _tmp46
                + _tmp18
                + _tmp30 * _tmp48
                - 0.04 * _tmp37
                - 0.05 * _tmp39
                + _tmp4 * _tmp47
                - 0.05 * _tmp49,
                _tmp0 * _tmp47
                + _tmp1 * _tmp48
                + _tmp132
                - 0.04 * _tmp140
                - 0.05 * _tmp141
                - 0.05 * _tmp142
                - _tmp4 * _tmp46,
                _tmp192
                + _tmp194 * _tmp32
                - 0.05 * _tmp195
                + 0.04 * _tmp196
                + 0.05 * _tmp197
                - _tmp199,
            ],
            [_tmp18, _tmp132, _tmp192],
            [
                -0.064 * _tmp37 + _tmp42 * _tmp50 + _tmp51,
                _tmp138 * _tmp50 - 0.064 * _tmp140 + _tmp143,
                0.064 * _tmp196 + 0.064 * _tmp198 + _tmp200,
            ],
            [
                -0.104 * _tmp37 + _tmp42 * _tmp52 + _tmp51,
                _tmp138 * _tmp52 - 0.104 * _tmp140 + _tmp143,
                0.104 * _tmp196 + 0.104 * _tmp198 + _tmp200,
            ],
            [
                -0.144 * _tmp37 + _tmp42 * _tmp53 + _tmp51,
                _tmp138 * _tmp53 - 0.144 * _tmp140 + _tmp143,
                0.144 * _tmp196 + 0.144 * _tmp198 + _tmp200,
            ],
            [
                -0.174 * _tmp37 + _tmp42 * _tmp54 + _tmp51,
                _tmp138 * _tmp54 - 0.174 * _tmp140 + _tmp143,
                0.174 * _tmp196 + 0.174 * _tmp198 + _tmp200,
            ],
            [
                -0.329 * _tmp37 + _tmp42 * _tmp55 + _tmp51 - 0.09 * _tmp60 - 0.09 * _tmp63,
                _tmp138 * _tmp55 - 0.329 * _tmp140 + _tmp143 - 0.09 * _tmp145 - 0.09 * _tmp147,
                0.329 * _tmp196 + 0.329 * _tmp198 + _tmp200 - 0.09 * _tmp202 + 0.09 * _tmp203,
            ],
            [
                -0.304 * _tmp37 + _tmp42 * _tmp64 + _tmp65,
                _tmp138 * _tmp64 - 0.304 * _tmp140 + _tmp148,
                0.304 * _tmp196 + 0.304 * _tmp198 + _tmp204,
            ],
            [
                -0.274 * _tmp37 + _tmp42 * _tmp66 + _tmp65,
                _tmp138 * _tmp66 - 0.274 * _tmp140 + _tmp148,
                0.274 * _tmp196 + 0.274 * _tmp198 + _tmp204,
            ],
            [
                -0.254 * _tmp37 + _tmp42 * _tmp67 + _tmp68,
                _tmp138 * _tmp67 - 0.254 * _tmp140 + _tmp150,
                0.254 * _tmp196 + 0.254 * _tmp198 + _tmp205,
            ],
            [
                -0.234 * _tmp37 + _tmp42 * _tmp69 + _tmp68,
                _tmp138 * _tmp69 - 0.234 * _tmp140 + _tmp150,
                0.234 * _tmp196 + 0.234 * _tmp198 + _tmp205,
            ],
            [
                -0.224 * _tmp37 + _tmp42 * _tmp70 + _tmp71,
                _tmp138 * _tmp70 - 0.224 * _tmp140 + _tmp143 + _tmp151,
                0.224 * _tmp196 + 0.224 * _tmp198 + _tmp206,
            ],
            [
                -0.364 * _tmp37 + _tmp42 * _tmp72 + _tmp68,
                _tmp138 * _tmp72 - 0.364 * _tmp140 + _tmp150,
                0.364 * _tmp196 + 0.364 * _tmp198 + _tmp205,
            ],
            [_tmp68 + _tmp74, _tmp149 + _tmp152, _tmp205 + _tmp207],
            [
                -0.184 * _tmp37 + _tmp42 * _tmp75 + _tmp51 - 0.05 * _tmp60 - 0.05 * _tmp63,
                _tmp138 * _tmp75 - 0.184 * _tmp140 + _tmp143 - 0.05 * _tmp145 - 0.05 * _tmp147,
                0.184 * _tmp196 + 0.184 * _tmp198 + _tmp200 - 0.05 * _tmp202 + 0.05 * _tmp203,
            ],
            [_tmp71 + _tmp74, _tmp151 + _tmp152, _tmp206 + _tmp207],
            [
                _tmp78 * _tmp81 + 0.03 * _tmp79 - _tmp84 * _tmp85 + 0.08 * _tmp86 + _tmp87,
                _tmp152 - _tmp153 * _tmp85 + 0.08 * _tmp154 + _tmp155 * _tmp81 + 0.03 * _tmp156,
                -_tmp208 * _tmp85 + 0.08 * _tmp209 + _tmp210 * _tmp81 + 0.03 * _tmp211 + _tmp212,
            ],
            [_tmp88 - _tmp90 + _tmp92, -_tmp158 + _tmp159 + _tmp160, -_tmp214 + _tmp215 + _tmp216],
            [_tmp92, _tmp160, _tmp216],
            [
                0.01 * _tmp60 + 0.01 * _tmp63 + _tmp87,
                0.01 * _tmp145 + 0.01 * _tmp147 + _tmp152,
                -_tmp199 * _tmp56 + 0.01 * _tmp202 + _tmp212,
            ],
            [
                -0.03 * _tmp60 - 0.03 * _tmp63 + _tmp87,
                -0.03 * _tmp145 - 0.03 * _tmp147 + _tmp152,
                _tmp189 * _tmp56 - 0.03 * _tmp202 + _tmp212,
            ],
            [
                -0.06 * _tmp79 + _tmp84 * _tmp93 + _tmp95,
                _tmp153 * _tmp93 - 0.06 * _tmp156 + _tmp161,
                _tmp208 * _tmp93 - 0.06 * _tmp211 + _tmp217,
            ],
            [-_tmp88 + _tmp90 + _tmp95, _tmp158 - _tmp159 + _tmp161, _tmp214 - _tmp215 + _tmp217],
            [
                0.042 * _tmp101
                + _tmp102 * _tmp84
                + 0.042 * _tmp104
                + 0.042 * _tmp105
                - 0.087 * _tmp79
                + _tmp95
                - 0.042 * _tmp99,
                _tmp102 * _tmp153
                - 0.087 * _tmp156
                + _tmp161
                - 0.042 * _tmp163
                + 0.042 * _tmp164
                + 0.042 * _tmp166
                + 0.042 * _tmp167,
                _tmp102 * _tmp208
                - 0.087 * _tmp211
                + _tmp217
                + 0.042 * _tmp219
                - 0.042 * _tmp220
                + 0.042 * _tmp222
                + 0.042 * _tmp223,
            ],
            [
                -0.107 * _tmp79 + 0.107 * _tmp89 + _tmp95,
                -0.107 * _tmp156 + 0.107 * _tmp157 + _tmp161,
                -0.107 * _tmp211 + 0.107 * _tmp213 + _tmp217,
            ],
            [
                _tmp110 - 0.122 * _tmp79 + 0.122 * _tmp89 + _tmp95,
                -0.122 * _tmp156 + 0.122 * _tmp157 + _tmp161 + _tmp172,
                -0.122 * _tmp211 + 0.122 * _tmp213 + _tmp217 + _tmp228,
            ],
            [_tmp110 + _tmp111, _tmp172 + _tmp173, _tmp228 + _tmp229],
            [_tmp111, _tmp173, _tmp229],
            [
                -_tmp106 + _tmp107 + _tmp108 + _tmp109 + _tmp111,
                -_tmp168 + _tmp169 + _tmp170 + _tmp171 + _tmp173,
                _tmp224 - _tmp225 + _tmp226 + _tmp227 + _tmp229,
            ],
            [_tmp112, _tmp174, _tmp230],
            [
                -0.0212132034356059 * _tmp101
                + 0.0212132034355869 * _tmp104
                - 0.0212132034356059 * _tmp105
                + _tmp112
                - 0.0212132034355869 * _tmp99,
                -0.0212132034355869 * _tmp163
                - 0.0212132034356059 * _tmp164
                - 0.0212132034356059 * _tmp166
                + 0.0212132034355869 * _tmp167
                + _tmp174,
                -0.0212132034356059 * _tmp219
                - 0.0212132034355869 * _tmp220
                + 0.0212132034355869 * _tmp222
                - 0.0212132034356059 * _tmp223
                + _tmp230,
            ],
            [
                -0.0424264068712119 * _tmp101
                + 0.0424264068711738 * _tmp104
                - 0.0424264068712119 * _tmp105
                + _tmp112
                - 0.0424264068711738 * _tmp99,
                -0.0424264068711738 * _tmp163
                - 0.0424264068712119 * _tmp164
                - 0.0424264068712119 * _tmp166
                + 0.0424264068711738 * _tmp167
                + _tmp174,
                -0.0424264068712119 * _tmp219
                - 0.0424264068711738 * _tmp220
                + 0.0424264068711738 * _tmp222
                - 0.0424264068712119 * _tmp223
                + _tmp230,
            ],
            [
                0.0636396103067607 * _tmp104
                - 0.0636396103068178 * _tmp105
                + _tmp112
                - _tmp113 * _tmp98
                - _tmp114 * _tmp98,
                -_tmp113 * _tmp162
                - _tmp114 * _tmp162
                - 0.0636396103068178 * _tmp166
                + 0.0636396103067607 * _tmp167
                + _tmp174,
                -_tmp113 * _tmp218
                - _tmp114 * _tmp218
                + 0.0636396103067607 * _tmp222
                - 0.0636396103068178 * _tmp223
                + _tmp230,
            ],
            [
                -0.0848528137424237 * _tmp101
                + _tmp103 * _tmp115
                - _tmp103 * _tmp116
                + _tmp112
                - 0.0848528137423477 * _tmp99,
                _tmp115 * _tmp165
                - _tmp116 * _tmp165
                - 0.0848528137423477 * _tmp163
                - 0.0848528137424237 * _tmp164
                + _tmp174,
                _tmp115 * _tmp221
                - _tmp116 * _tmp221
                - 0.0848528137424237 * _tmp219
                - 0.0848528137423477 * _tmp220
                + _tmp230,
            ],
            [
                -_tmp117 + _tmp118 + _tmp119 + _tmp120 + _tmp121 + _tmp124,
                -_tmp175 + _tmp176 + _tmp177 + _tmp178 + _tmp179 + _tmp181,
                _tmp231 - _tmp232 + _tmp233 + _tmp234 + _tmp236 + _tmp237,
            ],
            [
                _tmp124 - _tmp125 + _tmp126 + _tmp127 + _tmp128 + _tmp129,
                _tmp181 - _tmp182 + _tmp183 + _tmp184 + _tmp185 + _tmp186,
                _tmp236 + _tmp238 - _tmp239 + _tmp240 + _tmp241 + _tmp242,
            ],
            [
                _tmp117 - _tmp118 - _tmp119 - _tmp120 + _tmp121 + _tmp130,
                _tmp175 - _tmp176 - _tmp177 - _tmp178 + _tmp179 + _tmp187,
                -_tmp231 + _tmp232 - _tmp233 - _tmp234 + _tmp237 + _tmp243,
            ],
            [
                _tmp125 - _tmp126 - _tmp127 - _tmp128 + _tmp129 + _tmp130,
                _tmp182 - _tmp183 - _tmp184 - _tmp185 + _tmp186 + _tmp187,
                -_tmp238 + _tmp239 - _tmp240 - _tmp241 + _tmp242 + _tmp243,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
all_geometries = casadi.Function(
    "all_geometries",
    [_in0_mx],
    [all_geometries(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
