# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def group_1(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23


    """

    # Total ops: 14

    # Input arrays

    # Intermediate terms (3)
    _tmp0 = casadi.sin(_in0[0, 0])
    _tmp1 = casadi.cos(_in0[0, 0])
    _tmp2 = 0.136 * casadi.sin(_in0[1, 0])

    # Output terms
    _out = casadi.blockcat(
        [
            [0.075 * _tmp0 - 0.62, -0.075 * _tmp1, 0.358000000000000],
            [_tmp1 * _tmp2 - 0.62, _tmp0 * _tmp2, 0.136 * casadi.cos(_in0[1, 0]) + 0.358],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
group_1 = casadi.Function(
    "group_1",
    [_in0_mx],
    [group_1(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
