# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def group_3(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23


    """

    # Total ops: 119

    # Input arrays

    # Intermediate terms (39)
    _tmp0 = casadi.sin(_in0[3, 0])
    _tmp1 = casadi.sin(_in0[0, 0])
    _tmp2 = casadi.sin(_in0[2, 0])
    _tmp3 = 1.0 * _tmp2
    _tmp4 = _tmp1 * _tmp3
    _tmp5 = casadi.cos(_in0[1, 0])
    _tmp6 = casadi.cos(_in0[0, 0])
    _tmp7 = casadi.cos(_in0[2, 0])
    _tmp8 = 1.0 * _tmp7
    _tmp9 = _tmp6 * _tmp8
    _tmp10 = -_tmp4 + _tmp5 * _tmp9
    _tmp11 = _tmp0 * _tmp10
    _tmp12 = casadi.sin(_in0[1, 0])
    _tmp13 = _tmp12 * _tmp6
    _tmp14 = casadi.cos(_in0[3, 0])
    _tmp15 = 0.144 * _tmp14
    _tmp16 = 0.0825 * _tmp14
    _tmp17 = 0.316 * _tmp12
    _tmp18 = 0.0825 * _tmp2
    _tmp19 = _tmp5 * _tmp7
    _tmp20 = _tmp0 * _tmp13
    _tmp21 = (
        -_tmp1 * _tmp18
        - _tmp10 * _tmp16
        + _tmp17 * _tmp6
        + 0.0825 * _tmp19 * _tmp6
        - 0.0825 * _tmp20
        - 0.62
    )
    _tmp22 = 0.384 * _tmp14
    _tmp23 = _tmp1 * _tmp8
    _tmp24 = _tmp3 * _tmp6
    _tmp25 = 0.07 * casadi.cos(_in0[4, 0])
    _tmp26 = 1.0 * _tmp14
    _tmp27 = 0.07 * casadi.sin(_in0[4, 0])
    _tmp28 = _tmp1 * _tmp12
    _tmp29 = _tmp23 * _tmp5 + _tmp24
    _tmp30 = _tmp0 * _tmp29
    _tmp31 = 0.0825 * _tmp1
    _tmp32 = _tmp0 * _tmp12
    _tmp33 = _tmp1 * _tmp17 - _tmp16 * _tmp29 + _tmp18 * _tmp6 + _tmp19 * _tmp31 - _tmp31 * _tmp32
    _tmp34 = _tmp14 * _tmp5
    _tmp35 = _tmp12 * _tmp7
    _tmp36 = _tmp0 * _tmp35
    _tmp37 = _tmp0 * _tmp5
    _tmp38 = _tmp16 * _tmp35 - 0.0825 * _tmp35 - 0.0825 * _tmp37 + 0.316 * _tmp5 + 0.358

    # Output terms
    _out = casadi.blockcat(
        [
            [
                -0.144 * _tmp11 + _tmp13 * _tmp15 + _tmp21,
                _tmp15 * _tmp28 - 0.144 * _tmp30 + _tmp33,
                0.144 * _tmp34 + 0.144 * _tmp36 + _tmp38,
            ],
            [
                -0.384 * _tmp11
                + _tmp13 * _tmp22
                + _tmp21
                - _tmp25 * (_tmp23 + _tmp24 * _tmp5)
                - _tmp27 * (_tmp10 * _tmp26 + 1.0 * _tmp20),
                _tmp22 * _tmp28
                - _tmp25 * (_tmp4 * _tmp5 - _tmp9)
                - _tmp27 * (1.0 * _tmp1 * _tmp32 + _tmp26 * _tmp29)
                - 0.384 * _tmp30
                + _tmp33,
                _tmp12 * _tmp2 * _tmp25
                - _tmp27 * (-_tmp26 * _tmp35 + 1.0 * _tmp37)
                + 0.384 * _tmp34
                + 0.384 * _tmp36
                + _tmp38,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
group_3 = casadi.Function(
    "group_3",
    [_in0_mx],
    [group_3(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
