# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_link6_collision(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix53


    """

    # Total ops: 198

    # Input arrays

    # Intermediate terms (70)
    _tmp0 = casadi.sin(_in0[0, 0])
    _tmp1 = casadi.sin(_in0[2, 0])
    _tmp2 = 1.0 * _tmp1
    _tmp3 = _tmp0 * _tmp2
    _tmp4 = casadi.cos(_in0[1, 0])
    _tmp5 = casadi.cos(_in0[0, 0])
    _tmp6 = casadi.cos(_in0[2, 0])
    _tmp7 = 1.0 * _tmp6
    _tmp8 = _tmp5 * _tmp7
    _tmp9 = -_tmp3 + _tmp4 * _tmp8
    _tmp10 = casadi.sin(_in0[3, 0])
    _tmp11 = 1.0 * _tmp10
    _tmp12 = casadi.sin(_in0[1, 0])
    _tmp13 = casadi.cos(_in0[3, 0])
    _tmp14 = 1.0 * _tmp13
    _tmp15 = _tmp12 * _tmp14
    _tmp16 = -_tmp11 * _tmp9 + _tmp15 * _tmp5
    _tmp17 = casadi.cos(_in0[5, 0])
    _tmp18 = 0.03 * _tmp17
    _tmp19 = casadi.sin(_in0[5, 0])
    _tmp20 = 0.08 * _tmp19
    _tmp21 = _tmp0 * _tmp7
    _tmp22 = _tmp2 * _tmp5
    _tmp23 = _tmp21 + _tmp22 * _tmp4
    _tmp24 = casadi.sin(_in0[4, 0])
    _tmp25 = 1.0 * _tmp24
    _tmp26 = _tmp13 * _tmp9
    _tmp27 = _tmp11 * _tmp12
    _tmp28 = 1.0 * _tmp26 + _tmp27 * _tmp5
    _tmp29 = casadi.cos(_in0[4, 0])
    _tmp30 = 1.0 * _tmp29
    _tmp31 = -_tmp23 * _tmp25 + _tmp28 * _tmp30
    _tmp32 = 0.03 * _tmp19
    _tmp33 = 0.08 * _tmp17
    _tmp34 = 0.384 * _tmp10
    _tmp35 = 0.316 * _tmp12
    _tmp36 = 0.0825 * _tmp1
    _tmp37 = _tmp4 * _tmp6
    _tmp38 = 0.0825 * _tmp5
    _tmp39 = 0.384 * _tmp13
    _tmp40 = _tmp12 * _tmp39
    _tmp41 = _tmp10 * _tmp12
    _tmp42 = (
        -_tmp0 * _tmp36
        - 0.0825 * _tmp26
        - _tmp34 * _tmp9
        + _tmp35 * _tmp5
        + _tmp37 * _tmp38
        - _tmp38 * _tmp41
        + _tmp40 * _tmp5
        - 0.62
    )
    _tmp43 = 0.01 * _tmp17
    _tmp44 = 0.01 * _tmp19
    _tmp45 = 0.04 * _tmp19
    _tmp46 = 0.04 * _tmp17
    _tmp47 = _tmp16 * _tmp45 + _tmp31 * _tmp46 + _tmp42
    _tmp48 = 0.01 * _tmp29
    _tmp49 = 0.01 * _tmp24
    _tmp50 = 0.03 * _tmp29
    _tmp51 = 0.03 * _tmp24
    _tmp52 = _tmp21 * _tmp4 + _tmp22
    _tmp53 = _tmp0 * _tmp27 + _tmp14 * _tmp52
    _tmp54 = _tmp3 * _tmp4 - _tmp8
    _tmp55 = -_tmp25 * _tmp54 + _tmp30 * _tmp53
    _tmp56 = _tmp0 * _tmp15 - _tmp11 * _tmp52
    _tmp57 = 0.0825 * _tmp0
    _tmp58 = (
        _tmp0 * _tmp35
        + _tmp0 * _tmp40
        - 0.0825 * _tmp13 * _tmp52
        - _tmp34 * _tmp52
        + _tmp36 * _tmp5
        + _tmp37 * _tmp57
        - _tmp41 * _tmp57
    )
    _tmp59 = _tmp45 * _tmp56 + _tmp46 * _tmp55 + _tmp58
    _tmp60 = _tmp10 * _tmp4
    _tmp61 = _tmp12 * _tmp6
    _tmp62 = -_tmp14 * _tmp61 + 1.0 * _tmp60
    _tmp63 = _tmp12 * _tmp2 * _tmp24 + _tmp30 * _tmp62
    _tmp64 = _tmp11 * _tmp61 + _tmp14 * _tmp4
    _tmp65 = _tmp19 * _tmp64
    _tmp66 = 0.0825 * _tmp61
    _tmp67 = (
        _tmp13 * _tmp66
        + _tmp34 * _tmp61
        + _tmp39 * _tmp4
        + 0.316 * _tmp4
        - 0.0825 * _tmp60
        - _tmp66
        + 0.358
    )
    _tmp68 = _tmp46 * _tmp63 + 0.04 * _tmp65 + _tmp67
    _tmp69 = _tmp1 * _tmp12

    # Output terms
    _out = casadi.blockcat(
        [
            [
                _tmp16 * _tmp18 + _tmp16 * _tmp20 - _tmp31 * _tmp32 + _tmp31 * _tmp33 + _tmp42,
                _tmp18 * _tmp56 + _tmp20 * _tmp56 - _tmp32 * _tmp55 + _tmp33 * _tmp55 + _tmp58,
                _tmp18 * _tmp64 - _tmp32 * _tmp63 + _tmp33 * _tmp63 + 0.08 * _tmp65 + _tmp67,
            ],
            [
                _tmp16 * _tmp43 - _tmp31 * _tmp44 + _tmp47,
                _tmp43 * _tmp56 - _tmp44 * _tmp55 + _tmp59,
                _tmp43 * _tmp64 - _tmp44 * _tmp63 + _tmp68,
            ],
            [_tmp47, _tmp59, _tmp68],
            [
                _tmp23 * _tmp48 + _tmp28 * _tmp49 + _tmp42,
                _tmp48 * _tmp54 + _tmp49 * _tmp53 + _tmp58,
                -_tmp48 * _tmp69 + _tmp49 * _tmp62 + _tmp67,
            ],
            [
                -_tmp23 * _tmp50 - _tmp28 * _tmp51 + _tmp42,
                -_tmp50 * _tmp54 - _tmp51 * _tmp53 + _tmp58,
                _tmp50 * _tmp69 - _tmp51 * _tmp62 + _tmp67,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_link6_collision = casadi.Function(
    "panda_link6_collision",
    [_in0_mx],
    [panda_link6_collision(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
