# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def group_4(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23


    """

    # Total ops: 230

    # Input arrays

    # Intermediate terms (74)
    _tmp0 = casadi.cos(_in0[4, 0])
    _tmp1 = casadi.cos(_in0[3, 0])
    _tmp2 = casadi.sin(_in0[0, 0])
    _tmp3 = casadi.sin(_in0[2, 0])
    _tmp4 = 1.0 * _tmp3
    _tmp5 = _tmp2 * _tmp4
    _tmp6 = casadi.cos(_in0[1, 0])
    _tmp7 = casadi.cos(_in0[0, 0])
    _tmp8 = casadi.cos(_in0[2, 0])
    _tmp9 = 1.0 * _tmp8
    _tmp10 = _tmp7 * _tmp9
    _tmp11 = -_tmp10 * _tmp6 + _tmp5
    _tmp12 = _tmp1 * _tmp11
    _tmp13 = casadi.sin(_in0[1, 0])
    _tmp14 = casadi.sin(_in0[3, 0])
    _tmp15 = 1.0 * _tmp14
    _tmp16 = _tmp13 * _tmp15
    _tmp17 = 1.0 * _tmp12 - 1.0 * _tmp16 * _tmp7
    _tmp18 = casadi.sin(_in0[4, 0])
    _tmp19 = _tmp2 * _tmp9
    _tmp20 = _tmp4 * _tmp7
    _tmp21 = -1.0 * _tmp19 - 1.0 * _tmp20 * _tmp6
    _tmp22 = _tmp0 * _tmp17 - _tmp18 * _tmp21
    _tmp23 = casadi.sin(_in0[5, 0])
    _tmp24 = 0.03 * _tmp23
    _tmp25 = casadi.cos(_in0[5, 0])
    _tmp26 = _tmp22 * _tmp25
    _tmp27 = 1.0 * _tmp1
    _tmp28 = _tmp13 * _tmp27
    _tmp29 = -_tmp11 * _tmp15 - _tmp28 * _tmp7
    _tmp30 = 0.03 * _tmp25
    _tmp31 = _tmp23 * _tmp29
    _tmp32 = 0.384 * _tmp14
    _tmp33 = 0.316 * _tmp13
    _tmp34 = 0.0825 * _tmp3
    _tmp35 = 0.0825 * _tmp6 * _tmp8
    _tmp36 = 0.384 * _tmp1
    _tmp37 = _tmp13 * _tmp36
    _tmp38 = 0.0825 * _tmp13
    _tmp39 = _tmp14 * _tmp38
    _tmp40 = (
        -_tmp11 * _tmp32
        - 0.0825 * _tmp12
        + _tmp2 * _tmp34
        - _tmp33 * _tmp7
        - _tmp35 * _tmp7
        - _tmp37 * _tmp7
        + _tmp39 * _tmp7
        + 0.535
    )
    _tmp41 = 0.122 * _tmp23
    _tmp42 = _tmp0 * _tmp21 + _tmp17 * _tmp18
    _tmp43 = casadi.cos(_in0[6, 0])
    _tmp44 = 0.0424264068712119 * _tmp43
    _tmp45 = casadi.sin(_in0[6, 0])
    _tmp46 = 0.0424264068711738 * _tmp45
    _tmp47 = 0.122 * _tmp25
    _tmp48 = 0.088 * _tmp23
    _tmp49 = 1.0 * _tmp26 + 1.0 * _tmp31
    _tmp50 = 0.0424264068712119 * _tmp45
    _tmp51 = 0.0424264068711738 * _tmp43
    _tmp52 = -_tmp19 * _tmp6 - _tmp20
    _tmp53 = -_tmp15 * _tmp52 - _tmp2 * _tmp28
    _tmp54 = _tmp23 * _tmp53
    _tmp55 = 1.0 * _tmp10 - 1.0 * _tmp5 * _tmp6
    _tmp56 = -1.0 * _tmp16 * _tmp2 + 1.0 * _tmp27 * _tmp52
    _tmp57 = _tmp0 * _tmp56 - _tmp18 * _tmp55
    _tmp58 = _tmp25 * _tmp57
    _tmp59 = (
        -0.0825 * _tmp1 * _tmp52
        - _tmp2 * _tmp33
        - _tmp2 * _tmp35
        - _tmp2 * _tmp37
        + _tmp2 * _tmp39
        - _tmp32 * _tmp52
        - _tmp34 * _tmp7
    )
    _tmp60 = 1.0 * _tmp54 + 1.0 * _tmp58
    _tmp61 = _tmp0 * _tmp55 + _tmp18 * _tmp56
    _tmp62 = _tmp14 * _tmp6
    _tmp63 = _tmp13 * _tmp9
    _tmp64 = -1.0 * _tmp1 * _tmp63 + 1.0 * _tmp62
    _tmp65 = _tmp13 * _tmp4
    _tmp66 = _tmp0 * _tmp64 + _tmp18 * _tmp65
    _tmp67 = _tmp25 * _tmp66
    _tmp68 = _tmp14 * _tmp63 + _tmp27 * _tmp6
    _tmp69 = _tmp23 * _tmp68
    _tmp70 = _tmp38 * _tmp8
    _tmp71 = (
        _tmp1 * _tmp70
        + _tmp13 * _tmp32 * _tmp8
        + _tmp36 * _tmp6
        + 0.316 * _tmp6
        - 0.0825 * _tmp62
        - _tmp70
        + 0.358
    )
    _tmp72 = 1.0 * _tmp67 + 1.0 * _tmp69
    _tmp73 = -_tmp0 * _tmp65 + _tmp18 * _tmp64

    # Output terms
    _out = casadi.blockcat(
        [
            [
                -_tmp22 * _tmp24 + 0.08 * _tmp26 + _tmp29 * _tmp30 + 0.08 * _tmp31 + _tmp40,
                -_tmp24 * _tmp57 + _tmp30 * _tmp53 + 0.08 * _tmp54 + 0.08 * _tmp58 + _tmp59,
                -_tmp24 * _tmp66 + _tmp30 * _tmp68 + 0.08 * _tmp67 + 0.08 * _tmp69 + _tmp71,
            ],
            [
                _tmp22 * _tmp41
                + 0.088 * _tmp26
                - _tmp29 * _tmp47
                + _tmp29 * _tmp48
                + _tmp40
                - _tmp42 * _tmp44
                - _tmp42 * _tmp46
                + _tmp49 * _tmp50
                - _tmp49 * _tmp51,
                _tmp41 * _tmp57
                - _tmp44 * _tmp61
                - _tmp46 * _tmp61
                - _tmp47 * _tmp53
                + _tmp50 * _tmp60
                - _tmp51 * _tmp60
                + 0.088 * _tmp54
                + 0.088 * _tmp58
                + _tmp59,
                _tmp41 * _tmp66
                - _tmp44 * _tmp73
                - _tmp46 * _tmp73
                - _tmp47 * _tmp68
                + _tmp48 * _tmp68
                + _tmp50 * _tmp72
                - _tmp51 * _tmp72
                + 0.088 * _tmp67
                + _tmp71,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
group_4 = casadi.Function(
    "group_4",
    [_in0_mx],
    [group_4(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
