# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def group_2(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23


    """

    # Total ops: 82

    # Input arrays

    # Intermediate terms (29)
    _tmp0 = casadi.sin(_in0[0, 0])
    _tmp1 = casadi.cos(_in0[2, 0])
    _tmp2 = 0.06 * _tmp1
    _tmp3 = casadi.cos(_in0[0, 0])
    _tmp4 = casadi.cos(_in0[1, 0])
    _tmp5 = casadi.sin(_in0[2, 0])
    _tmp6 = 0.06 * _tmp5
    _tmp7 = _tmp4 * _tmp6
    _tmp8 = casadi.sin(_in0[1, 0])
    _tmp9 = 0.316 * _tmp8
    _tmp10 = 0.0825 * _tmp5
    _tmp11 = 0.0825 * _tmp4
    _tmp12 = _tmp1 * _tmp11
    _tmp13 = _tmp0 * _tmp10 - _tmp12 * _tmp3 - _tmp3 * _tmp9 + 0.535
    _tmp14 = 1.0 * _tmp5
    _tmp15 = 1.0 * _tmp1 * _tmp4
    _tmp16 = _tmp0 * _tmp14 - _tmp15 * _tmp3
    _tmp17 = casadi.sin(_in0[3, 0])
    _tmp18 = 0.104 * _tmp17
    _tmp19 = casadi.cos(_in0[3, 0])
    _tmp20 = 0.0825 * _tmp19
    _tmp21 = 0.104 * _tmp19
    _tmp22 = _tmp21 * _tmp8
    _tmp23 = 0.0825 * _tmp8
    _tmp24 = _tmp17 * _tmp23
    _tmp25 = -_tmp0 * _tmp12 - _tmp0 * _tmp9 - _tmp10 * _tmp3
    _tmp26 = -_tmp0 * _tmp15 - _tmp14 * _tmp3
    _tmp27 = _tmp1 * _tmp23
    _tmp28 = -_tmp27 + 0.316 * _tmp4 + 0.358

    # Output terms
    _out = casadi.blockcat(
        [
            [
                _tmp0 * _tmp2 + _tmp13 + _tmp3 * _tmp7,
                _tmp0 * _tmp7 - _tmp2 * _tmp3 + _tmp25,
                _tmp28 + _tmp6 * _tmp8,
            ],
            [
                _tmp13 - _tmp16 * _tmp18 - _tmp16 * _tmp20 - _tmp22 * _tmp3 + _tmp24 * _tmp3,
                -_tmp0 * _tmp22 + _tmp0 * _tmp24 - _tmp18 * _tmp26 - _tmp20 * _tmp26 + _tmp25,
                _tmp1 * _tmp18 * _tmp8
                - _tmp11 * _tmp17
                + _tmp19 * _tmp27
                + _tmp21 * _tmp4
                + _tmp28,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
group_2 = casadi.Function(
    "group_2",
    [_in0_mx],
    [group_2(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
