# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_leftfinger_collision(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23


    """

    # Total ops: 278

    # Input arrays

    # Intermediate terms (88)
    _tmp0 = casadi.sin(_in0[5, 0])
    _tmp1 = casadi.cos(_in0[4, 0])
    _tmp2 = casadi.sin(_in0[0, 0])
    _tmp3 = casadi.sin(_in0[2, 0])
    _tmp4 = 1.0 * _tmp3
    _tmp5 = _tmp2 * _tmp4
    _tmp6 = casadi.cos(_in0[1, 0])
    _tmp7 = casadi.cos(_in0[0, 0])
    _tmp8 = casadi.cos(_in0[2, 0])
    _tmp9 = 1.0 * _tmp8
    _tmp10 = _tmp7 * _tmp9
    _tmp11 = -_tmp10 * _tmp6 + _tmp5
    _tmp12 = casadi.cos(_in0[3, 0])
    _tmp13 = 1.0 * _tmp12
    _tmp14 = casadi.sin(_in0[1, 0])
    _tmp15 = casadi.sin(_in0[3, 0])
    _tmp16 = 1.0 * _tmp15
    _tmp17 = _tmp14 * _tmp16
    _tmp18 = 1.0 * _tmp11 * _tmp13 - 1.0 * _tmp17 * _tmp7
    _tmp19 = casadi.sin(_in0[4, 0])
    _tmp20 = _tmp2 * _tmp9
    _tmp21 = _tmp4 * _tmp7
    _tmp22 = -1.0 * _tmp20 - 1.0 * _tmp21 * _tmp6
    _tmp23 = _tmp1 * _tmp18 - _tmp19 * _tmp22
    _tmp24 = _tmp0 * _tmp23
    _tmp25 = _tmp1 * _tmp22 + _tmp18 * _tmp19
    _tmp26 = casadi.cos(_in0[6, 0])
    _tmp27 = 0.00494974746830805 * _tmp26
    _tmp28 = casadi.sin(_in0[6, 0])
    _tmp29 = _tmp25 * _tmp28
    _tmp30 = _tmp14 * _tmp7
    _tmp31 = -_tmp11 * _tmp16 - _tmp13 * _tmp30
    _tmp32 = casadi.cos(_in0[5, 0])
    _tmp33 = 0.2104 * _tmp32
    _tmp34 = _tmp23 * _tmp32
    _tmp35 = 1.0 * _tmp0
    _tmp36 = _tmp31 * _tmp35 + 1.0 * _tmp34
    _tmp37 = 0.00494974746830805 * _tmp28
    _tmp38 = 0.00494974746830361 * _tmp26
    _tmp39 = 0.384 * _tmp15
    _tmp40 = 0.0825 * _tmp12
    _tmp41 = 0.316 * _tmp14
    _tmp42 = 0.0825 * _tmp3
    _tmp43 = _tmp6 * _tmp8
    _tmp44 = 0.0825 * _tmp7
    _tmp45 = 0.384 * _tmp12
    _tmp46 = _tmp14 * _tmp15
    _tmp47 = 0.707106781186865 * _tmp26
    _tmp48 = 0.70710678118623 * _tmp28
    _tmp49 = 0.707106781186865 * _tmp28
    _tmp50 = 0.70710678118623 * _tmp26
    _tmp51 = 1.0 * _in0[7, 0]
    _tmp52 = 0.088 * _tmp0
    _tmp53 = (
        -_tmp11 * _tmp39
        - _tmp11 * _tmp40
        + _tmp2 * _tmp42
        - _tmp30 * _tmp45
        + _tmp31 * _tmp52
        + 0.088 * _tmp34
        - _tmp41 * _tmp7
        - _tmp43 * _tmp44
        + _tmp44 * _tmp46
        + _tmp51 * (_tmp25 * _tmp47 + _tmp25 * _tmp48 - _tmp36 * _tmp49 + _tmp36 * _tmp50)
        + 0.535
    )
    _tmp54 = 0.010606601717803 * _tmp26
    _tmp55 = 0.1954 * _tmp32
    _tmp56 = 0.010606601717803 * _tmp28
    _tmp57 = 0.0106066017177935 * _tmp26
    _tmp58 = _tmp14 * _tmp2
    _tmp59 = -_tmp20 * _tmp6 - _tmp21
    _tmp60 = -_tmp13 * _tmp58 - _tmp16 * _tmp59
    _tmp61 = _tmp0 * _tmp60
    _tmp62 = _tmp10 - _tmp5 * _tmp6
    _tmp63 = 1.0 * _tmp19
    _tmp64 = 1.0 * _tmp13 * _tmp59 - 1.0 * _tmp17 * _tmp2
    _tmp65 = _tmp1 * _tmp64 - _tmp62 * _tmp63
    _tmp66 = 1.0 * _tmp32
    _tmp67 = 1.0 * _tmp61 + _tmp65 * _tmp66
    _tmp68 = 1.0 * _tmp1
    _tmp69 = _tmp19 * _tmp64 + _tmp62 * _tmp68
    _tmp70 = _tmp28 * _tmp69
    _tmp71 = _tmp0 * _tmp65
    _tmp72 = 0.0825 * _tmp2
    _tmp73 = _tmp26 * _tmp69
    _tmp74 = 0.088 * _tmp32
    _tmp75 = (
        -_tmp2 * _tmp41
        - _tmp39 * _tmp59
        - _tmp40 * _tmp59
        - _tmp42 * _tmp7
        - _tmp43 * _tmp72
        - _tmp45 * _tmp58
        + _tmp46 * _tmp72
        + _tmp51
        * (_tmp48 * _tmp69 - _tmp49 * _tmp67 + _tmp50 * _tmp67 + 0.707106781186865 * _tmp73)
        + 0.088 * _tmp61
        + _tmp65 * _tmp74
    )
    _tmp76 = _tmp15 * _tmp6
    _tmp77 = _tmp14 * _tmp8
    _tmp78 = -_tmp13 * _tmp77 + 1.0 * _tmp76
    _tmp79 = _tmp14 * _tmp4
    _tmp80 = _tmp19 * _tmp79 + _tmp68 * _tmp78
    _tmp81 = _tmp13 * _tmp6 + _tmp16 * _tmp77
    _tmp82 = _tmp35 * _tmp81 + _tmp66 * _tmp80
    _tmp83 = -_tmp1 * _tmp79 + _tmp63 * _tmp78
    _tmp84 = _tmp28 * _tmp83
    _tmp85 = _tmp0 * _tmp80
    _tmp86 = 0.0825 * _tmp77
    _tmp87 = (
        _tmp12 * _tmp86
        + _tmp39 * _tmp77
        + _tmp45 * _tmp6
        + _tmp51 * (_tmp47 * _tmp83 - _tmp49 * _tmp82 + _tmp50 * _tmp82 + 0.70710678118623 * _tmp84)
        + _tmp52 * _tmp81
        + 0.316 * _tmp6
        + _tmp74 * _tmp80
        - 0.0825 * _tmp76
        - _tmp86
        + 0.358
    )

    # Output terms
    _out = casadi.blockcat(
        [
            [
                0.2104 * _tmp24
                + _tmp25 * _tmp27
                + 0.00494974746830361 * _tmp29
                - _tmp31 * _tmp33
                - _tmp36 * _tmp37
                + _tmp36 * _tmp38
                + _tmp53,
                _tmp27 * _tmp69
                - _tmp33 * _tmp60
                - _tmp37 * _tmp67
                + _tmp38 * _tmp67
                + 0.00494974746830361 * _tmp70
                + 0.2104 * _tmp71
                + _tmp75,
                _tmp27 * _tmp83
                - _tmp33 * _tmp81
                - _tmp37 * _tmp82
                + _tmp38 * _tmp82
                + 0.00494974746830361 * _tmp84
                + 0.2104 * _tmp85
                + _tmp87,
            ],
            [
                0.1954 * _tmp24
                + _tmp25 * _tmp54
                + 0.0106066017177935 * _tmp29
                - _tmp31 * _tmp55
                - _tmp36 * _tmp56
                + _tmp36 * _tmp57
                + _tmp53,
                -_tmp55 * _tmp60
                - _tmp56 * _tmp67
                + _tmp57 * _tmp67
                + 0.0106066017177935 * _tmp70
                + 0.1954 * _tmp71
                + 0.010606601717803 * _tmp73
                + _tmp75,
                _tmp54 * _tmp83
                - _tmp55 * _tmp81
                - _tmp56 * _tmp82
                + _tmp57 * _tmp82
                + 0.0106066017177935 * _tmp84
                + 0.1954 * _tmp85
                + _tmp87,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_leftfinger_collision = casadi.Function(
    "panda_leftfinger_collision",
    [_in0_mx],
    [panda_leftfinger_collision(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
