# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_link8_collision(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23


    """

    # Total ops: 223

    # Input arrays

    # Intermediate terms (71)
    _tmp0 = casadi.sin(_in0[5, 0])
    _tmp1 = casadi.cos(_in0[4, 0])
    _tmp2 = casadi.cos(_in0[3, 0])
    _tmp3 = casadi.sin(_in0[0, 0])
    _tmp4 = casadi.sin(_in0[2, 0])
    _tmp5 = 1.0 * _tmp4
    _tmp6 = _tmp3 * _tmp5
    _tmp7 = casadi.cos(_in0[1, 0])
    _tmp8 = casadi.cos(_in0[0, 0])
    _tmp9 = casadi.cos(_in0[2, 0])
    _tmp10 = 1.0 * _tmp9
    _tmp11 = _tmp10 * _tmp8
    _tmp12 = -_tmp11 * _tmp7 + _tmp6
    _tmp13 = _tmp12 * _tmp2
    _tmp14 = casadi.sin(_in0[1, 0])
    _tmp15 = casadi.sin(_in0[3, 0])
    _tmp16 = 1.0 * _tmp15
    _tmp17 = _tmp14 * _tmp16
    _tmp18 = 1.0 * _tmp13 - 1.0 * _tmp17 * _tmp8
    _tmp19 = casadi.sin(_in0[4, 0])
    _tmp20 = _tmp10 * _tmp3
    _tmp21 = _tmp5 * _tmp8
    _tmp22 = -1.0 * _tmp20 - 1.0 * _tmp21 * _tmp7
    _tmp23 = _tmp1 * _tmp18 - _tmp19 * _tmp22
    _tmp24 = _tmp0 * _tmp23
    _tmp25 = casadi.cos(_in0[6, 0])
    _tmp26 = 0.042 * _tmp1 * _tmp22 + 0.042 * _tmp18 * _tmp19
    _tmp27 = casadi.sin(_in0[6, 0])
    _tmp28 = casadi.cos(_in0[5, 0])
    _tmp29 = 1.0 * _tmp2
    _tmp30 = _tmp14 * _tmp29
    _tmp31 = -_tmp12 * _tmp16 - _tmp30 * _tmp8
    _tmp32 = _tmp28 * _tmp31
    _tmp33 = _tmp23 * _tmp28
    _tmp34 = _tmp0 * _tmp31
    _tmp35 = 0.042 * _tmp33 + 0.042 * _tmp34
    _tmp36 = 0.384 * _tmp15
    _tmp37 = 0.316 * _tmp14
    _tmp38 = 0.0825 * _tmp4
    _tmp39 = 0.0825 * _tmp7 * _tmp9
    _tmp40 = 0.384 * _tmp2
    _tmp41 = _tmp14 * _tmp40
    _tmp42 = 0.0825 * _tmp14
    _tmp43 = _tmp15 * _tmp42
    _tmp44 = (
        -_tmp12 * _tmp36
        - 0.0825 * _tmp13
        + _tmp3 * _tmp38
        + 0.088 * _tmp33
        + 0.088 * _tmp34
        - _tmp37 * _tmp8
        - _tmp39 * _tmp8
        - _tmp41 * _tmp8
        + _tmp43 * _tmp8
        + 0.535
    )
    _tmp45 = -_tmp20 * _tmp7 - _tmp21
    _tmp46 = -_tmp16 * _tmp45 - _tmp3 * _tmp30
    _tmp47 = _tmp28 * _tmp46
    _tmp48 = _tmp0 * _tmp46
    _tmp49 = 1.0 * _tmp11 - 1.0 * _tmp6 * _tmp7
    _tmp50 = -1.0 * _tmp17 * _tmp3 + 1.0 * _tmp29 * _tmp45
    _tmp51 = _tmp1 * _tmp50 - _tmp19 * _tmp49
    _tmp52 = 1.0 * _tmp28
    _tmp53 = 0.042 * _tmp48 + 0.042 * _tmp51 * _tmp52
    _tmp54 = 0.042 * _tmp1 * _tmp49 + 0.042 * _tmp19 * _tmp50
    _tmp55 = _tmp0 * _tmp51
    _tmp56 = 0.088 * _tmp28
    _tmp57 = (
        -0.0825 * _tmp2 * _tmp45
        - _tmp3 * _tmp37
        - _tmp3 * _tmp39
        - _tmp3 * _tmp41
        + _tmp3 * _tmp43
        - _tmp36 * _tmp45
        - _tmp38 * _tmp8
        + 0.088 * _tmp48
        + _tmp51 * _tmp56
    )
    _tmp58 = _tmp15 * _tmp7
    _tmp59 = _tmp10 * _tmp14
    _tmp60 = -1.0 * _tmp2 * _tmp59 + 1.0 * _tmp58
    _tmp61 = _tmp14 * _tmp5
    _tmp62 = _tmp1 * _tmp60 + _tmp19 * _tmp61
    _tmp63 = _tmp15 * _tmp59 + _tmp29 * _tmp7
    _tmp64 = _tmp0 * _tmp63
    _tmp65 = 0.042 * _tmp52 * _tmp62 + 0.042 * _tmp64
    _tmp66 = -0.042 * _tmp1 * _tmp61 + 0.042 * _tmp19 * _tmp60
    _tmp67 = _tmp0 * _tmp62
    _tmp68 = _tmp28 * _tmp63
    _tmp69 = _tmp42 * _tmp9
    _tmp70 = (
        _tmp14 * _tmp36 * _tmp9
        + _tmp2 * _tmp69
        + _tmp40 * _tmp7
        + _tmp56 * _tmp62
        - 0.0825 * _tmp58
        + 0.088 * _tmp64
        - _tmp69
        + 0.316 * _tmp7
        + 0.358
    )

    # Output terms
    _out = casadi.blockcat(
        [
            [
                0.087 * _tmp24
                + _tmp25 * _tmp26
                + _tmp25 * _tmp35
                + _tmp26 * _tmp27
                - _tmp27 * _tmp35
                - 0.087 * _tmp32
                + _tmp44,
                _tmp25 * _tmp53
                + _tmp25 * _tmp54
                - _tmp27 * _tmp53
                + _tmp27 * _tmp54
                - 0.087 * _tmp47
                + 0.087 * _tmp55
                + _tmp57,
                _tmp25 * _tmp65
                + _tmp25 * _tmp66
                - _tmp27 * _tmp65
                + _tmp27 * _tmp66
                + 0.087 * _tmp67
                - 0.087 * _tmp68
                + _tmp70,
            ],
            [
                0.107 * _tmp24 - 0.107 * _tmp32 + _tmp44,
                -0.107 * _tmp47 + 0.107 * _tmp55 + _tmp57,
                0.107 * _tmp67 - 0.107 * _tmp68 + _tmp70,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_link8_collision = casadi.Function(
    "panda_link8_collision",
    [_in0_mx],
    [panda_link8_collision(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
