# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def frame_pose_in_frame_carried_object_world(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix71

    Outputs:
        out: Matrix44


    """

    # Total ops: 33

    # Input arrays

    # Intermediate terms (15)
    _tmp0 = _in0[2, 0] ** 2
    _tmp1 = _in0[1, 0] ** 2
    _tmp2 = _in0[3, 0] ** 2
    _tmp3 = 2.0 / (_in0[0, 0] ** 2 + _tmp0 + _tmp1 + _tmp2)
    _tmp4 = -_tmp0 * _tmp3
    _tmp5 = -_tmp2 * _tmp3 + 1.0
    _tmp6 = _in0[1, 0] * _tmp3
    _tmp7 = _in0[2, 0] * _tmp6
    _tmp8 = _in0[0, 0] * _in0[3, 0] * _tmp3
    _tmp9 = _in0[3, 0] * _tmp6
    _tmp10 = _in0[2, 0] * _tmp3
    _tmp11 = _in0[0, 0] * _tmp10
    _tmp12 = -_tmp1 * _tmp3
    _tmp13 = _in0[0, 0] * _tmp6
    _tmp14 = _in0[3, 0] * _tmp10

    # Output terms
    _out = casadi.blockcat(
        [
            [_tmp4 + _tmp5, _tmp7 - _tmp8, _tmp11 + _tmp9, _in0[4, 0]],
            [_tmp7 + _tmp8, _tmp12 + _tmp5, -_tmp13 + _tmp14, _in0[5, 0]],
            [-_tmp11 + _tmp9, _tmp13 + _tmp14, _tmp12 + _tmp4 + 1.0, _in0[6, 0]],
            [0, 0, 0, 1],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 7, 1)
frame_pose_in_frame_carried_object_world = casadi.Function(
    "frame_pose_in_frame_carried_object_world",
    [_in0_mx],
    [frame_pose_in_frame_carried_object_world(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
