# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import torch


class TensorKwargs(T.TypedDict):
    """
    TypedDict representing args that will be passed to any torch.tensor calls
    """

    device: torch.device
    dtype: torch.dtype


def _broadcast_and_stack(tensors, dim=-1):
    # type: (T.List[torch.Tensor], int) -> torch.Tensor
    """
    broadcast tensors to common shape then stack along new dimension
    """

    broadcast_shape = torch.broadcast_shapes(*(x.size() for x in tensors))
    broadcast_tensors = [x.broadcast_to(broadcast_shape) for x in tensors]

    return torch.stack(broadcast_tensors, dim=dim)


def spatial_velocity_jacobian_kV_panda_link7_box_world(_in0, _in1, tensor_kwargs=None):
    # type: (torch.Tensor, torch.Tensor, TensorKwargs) -> torch.Tensor
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix14_1
        _in1: Matrix31

    Outputs:
        out: Matrix6_13

    The types for inputs and outputs above are the shapes of the symbolic matrices this function was
    generated from.  Tensors for both inputs and outputs are expected to have dimensions as follows:

    - (..., N, M) for sf.Matrix types of shape (N, M) where N != 1 and M != 1
    - (..., N) for sf.Matrix types of shape (N, M) where N != 1 and M == 1 (i.e. column vectors)
    - (..., M) for sf.Matrix types of shape (N, M) where N == 1 and M != 1 (i.e. row vectors)
    - (...) for sf.Matrix types of shape (1, 1) and sf.Scalar types

    Where `...` is an arbitrary number of batch dimensions that can be present on the front of input
    tensors.  The outputs will have the same batch dimensions as the inputs.

    The tensor_kwargs argument can be used to set the device and dtype to use.  If not provided, it will
    default to the device and dtype of the first input tensor, or the empty dict if there are no inputs.
    """

    # Total ops: 2406

    # Deduce expected tensor device and dtype if not provided
    if tensor_kwargs is None:
        tensor_kwargs = {"device": _in0.device, "dtype": _in0.dtype}

    # Input arrays

    cte_1 = torch.tensor(4.0, **tensor_kwargs)
    cte_2 = torch.tensor(-1.0, **tensor_kwargs)
    cte_3 = torch.tensor(3.0, **tensor_kwargs)
    cte_4 = torch.tensor(0.384, **tensor_kwargs)
    cte_5 = torch.tensor(2.0, **tensor_kwargs)
    cte_6 = torch.tensor(0.316, **tensor_kwargs)
    cte_7 = torch.tensor(0.088, **tensor_kwargs)
    cte_8 = torch.tensor(0.0, **tensor_kwargs)
    cte_9 = torch.tensor(0.0825, **tensor_kwargs)
    cte_10 = torch.tensor(0.5, **tensor_kwargs)
    cte_11 = torch.tensor(0.333, **tensor_kwargs)
    cte_12 = torch.tensor(1.0, **tensor_kwargs)

    # Intermediate terms (655)
    _tmp0 = torch.pow(_in0[..., 9], cte_5)
    _tmp1 = torch.pow(_in0[..., 8], cte_5)
    _tmp2 = torch.pow(_in0[..., 7], cte_5)
    _tmp3 = torch.pow(_in0[..., 10], cte_5)
    _tmp4 = _tmp0 + _tmp1 + _tmp2 + _tmp3
    _tmp5 = torch.pow(_tmp4, cte_2)
    _tmp6 = cte_5 * _tmp5
    _tmp7 = _in0[..., 7] * _tmp6
    _tmp8 = _in0[..., 9] * _tmp7
    _tmp9 = _in0[..., 8] * _tmp6
    _tmp10 = _in0[..., 10] * _tmp9
    _tmp11 = _tmp10 + _tmp8
    _tmp12 = _in0[..., 9] * _tmp6
    _tmp13 = _in0[..., 8] * _tmp12
    _tmp14 = _in0[..., 10] * _tmp7
    _tmp15 = _tmp13 + _tmp14
    _tmp16 = torch.sin(_in0[..., 0])
    _tmp17 = torch.cos(_in0[..., 3])
    _tmp18 = torch.sin(_in0[..., 1])
    _tmp19 = cte_12 * _tmp18
    _tmp20 = _tmp17 * _tmp19
    _tmp21 = _tmp16 * _tmp20
    _tmp22 = torch.sin(_in0[..., 3])
    _tmp23 = torch.sin(_in0[..., 2])
    _tmp24 = torch.cos(_in0[..., 0])
    _tmp25 = cte_12 * _tmp24
    _tmp26 = _tmp23 * _tmp25
    _tmp27 = torch.cos(_in0[..., 1])
    _tmp28 = torch.cos(_in0[..., 2])
    _tmp29 = cte_12 * _tmp16
    _tmp30 = _tmp28 * _tmp29
    _tmp31 = _tmp27 * _tmp30
    _tmp32 = _tmp26 + _tmp31
    _tmp33 = _tmp22 * _tmp32
    _tmp34 = _tmp21 - _tmp33
    _tmp35 = torch.cos(_in0[..., 5])
    _tmp36 = cte_12 * _tmp35
    _tmp37 = _tmp34 * _tmp36
    _tmp38 = torch.cos(_in0[..., 4])
    _tmp39 = _tmp19 * _tmp22
    _tmp40 = _tmp16 * _tmp39
    _tmp41 = _tmp17 * _tmp32
    _tmp42 = _tmp40 + cte_12 * _tmp41
    _tmp43 = torch.sin(_in0[..., 4])
    _tmp44 = _tmp25 * _tmp28
    _tmp45 = _tmp23 * _tmp29
    _tmp46 = _tmp27 * _tmp45
    _tmp47 = -_tmp44 + _tmp46
    _tmp48 = _tmp38 * _tmp42 - _tmp43 * _tmp47
    _tmp49 = torch.sin(_in0[..., 5])
    _tmp50 = cte_12 * _tmp49
    _tmp51 = _tmp48 * _tmp50
    _tmp52 = -_tmp37 + _tmp51
    _tmp53 = _tmp15 * _tmp52
    _tmp54 = cte_12 * _tmp27
    _tmp55 = _tmp17 * _tmp54
    _tmp56 = _tmp28 * _tmp39 + _tmp55
    _tmp57 = _tmp36 * _tmp56
    _tmp58 = _tmp22 * _tmp54
    _tmp59 = _tmp20 * _tmp28
    _tmp60 = _tmp58 - _tmp59
    _tmp61 = _tmp23 * _tmp43
    _tmp62 = _tmp19 * _tmp61
    _tmp63 = _tmp38 * _tmp60 + _tmp62
    _tmp64 = _tmp50 * _tmp63
    _tmp65 = -_tmp57 + _tmp64
    _tmp66 = -_tmp8
    _tmp67 = _tmp10 + _tmp66
    _tmp68 = torch.pow(_in0[..., 9], cte_5)
    _tmp69 = _tmp6 * _tmp68
    _tmp70 = -_tmp69
    _tmp71 = torch.pow(_in0[..., 10], cte_5)
    _tmp72 = _tmp6 * _tmp71
    _tmp73 = -_tmp72
    _tmp74 = _tmp70 + _tmp73 + cte_12
    _tmp75 = _tmp24 * _tmp54
    _tmp76 = _tmp28 * _tmp75
    _tmp77 = -_tmp45 + _tmp76
    _tmp78 = _tmp22 * _tmp77
    _tmp79 = _tmp20 * _tmp24
    _tmp80 = -_tmp78 + _tmp79
    _tmp81 = _tmp36 * _tmp80
    _tmp82 = _tmp23 * _tmp75
    _tmp83 = _tmp30 + _tmp82
    _tmp84 = _tmp17 * _tmp77
    _tmp85 = _tmp24 * _tmp39
    _tmp86 = cte_12 * _tmp84 + _tmp85
    _tmp87 = _tmp38 * _tmp86 - _tmp43 * _tmp83
    _tmp88 = cte_12 * _tmp87
    _tmp89 = _tmp49 * _tmp88
    _tmp90 = -_tmp81 + _tmp89
    _tmp91 = _tmp53 + _tmp65 * _tmp67 + _tmp74 * _tmp90
    _tmp92 = -_tmp14
    _tmp93 = _tmp13 + _tmp92
    _tmp94 = -_tmp26 - _tmp31
    _tmp95 = _tmp22 * _tmp94
    _tmp96 = -_tmp21 - _tmp95
    _tmp97 = cte_12 * _tmp96
    _tmp98 = _tmp44 - _tmp46
    _tmp99 = _tmp43 * _tmp98
    _tmp100 = -_tmp40
    _tmp101 = cte_12 * _tmp17
    _tmp102 = _tmp100 + _tmp101 * _tmp94
    _tmp103 = _tmp102 * _tmp38 - _tmp99
    _tmp104 = _tmp103 * _tmp50 - _tmp35 * _tmp97
    _tmp105 = torch.pow(_in0[..., 8], cte_5)
    _tmp106 = _tmp105 * _tmp6
    _tmp107 = cte_12 - _tmp106
    _tmp108 = _tmp107 + _tmp73
    _tmp109 = _tmp104 * _tmp93 + _tmp108 * _tmp90
    _tmp110 = _tmp38 * _tmp83
    _tmp111 = _tmp43 * _tmp86
    _tmp112 = _tmp110 + _tmp111
    _tmp113 = torch.sin(_in0[..., 6])
    _tmp114 = cte_12 * _tmp113
    _tmp115 = _tmp112 * _tmp114
    _tmp116 = _tmp50 * _tmp80
    _tmp117 = _tmp35 * _tmp88
    _tmp118 = _tmp116 + _tmp117
    _tmp119 = torch.cos(_in0[..., 6])
    _tmp120 = cte_12 * _tmp119
    _tmp121 = _tmp118 * _tmp120
    _tmp122 = _tmp115 + _tmp121
    _tmp123 = _tmp34 * _tmp50
    _tmp124 = _tmp36 * _tmp48
    _tmp125 = _tmp123 + _tmp124
    _tmp126 = _tmp42 * _tmp43
    _tmp127 = _tmp38 * _tmp47
    _tmp128 = _tmp126 + _tmp127
    _tmp129 = _tmp114 * _tmp128
    _tmp130 = _tmp120 * _tmp125 + _tmp129
    _tmp131 = _tmp43 * _tmp60
    _tmp132 = _tmp23 * _tmp38
    _tmp133 = _tmp132 * _tmp19
    _tmp134 = _tmp131 - _tmp133
    _tmp135 = _tmp114 * _tmp134
    _tmp136 = _tmp50 * _tmp56
    _tmp137 = _tmp136 + _tmp36 * _tmp63
    _tmp138 = _tmp120 * _tmp137
    _tmp139 = _tmp135 + _tmp138
    _tmp140 = _tmp122 * _tmp74 + _tmp130 * _tmp15 + _tmp139 * _tmp67
    _tmp141 = _tmp103 * _tmp36 + _tmp49 * _tmp97
    _tmp142 = _tmp38 * _tmp98
    _tmp143 = _tmp102 * _tmp43 + _tmp142
    _tmp144 = _tmp114 * _tmp143 + _tmp120 * _tmp141
    _tmp145 = _tmp108 * _tmp122 + _tmp144 * _tmp93
    _tmp146 = -_tmp123 - _tmp124
    _tmp147 = _tmp120 * _tmp128
    _tmp148 = _tmp114 * _tmp146 + _tmp147
    _tmp149 = _tmp112 * _tmp120
    _tmp150 = -_tmp114 * _tmp118 + _tmp149
    _tmp151 = -_tmp114 * _tmp137 + _tmp120 * _tmp134
    _tmp152 = _tmp150 * _tmp74 + _tmp151 * _tmp67
    _tmp153 = _tmp148 * _tmp15 + _tmp152
    _tmp154 = _tmp114 * (-_tmp116 - _tmp117) + _tmp149
    _tmp155 = -_tmp114 * _tmp141 + _tmp120 * _tmp143
    _tmp156 = _tmp108 * _tmp154 + _tmp155 * _tmp93
    _tmp157 = _tmp109 * _tmp91 + _tmp140 * _tmp145 + _tmp153 * _tmp156
    _tmp158 = _in0[..., 8] * _tmp7
    _tmp159 = _in0[..., 10] * _tmp12
    _tmp160 = _tmp158 + _tmp159
    _tmp161 = _tmp108 * _tmp52
    _tmp162 = _tmp160 * _tmp65 + _tmp161 + _tmp90 * _tmp93
    _tmp163 = -_tmp158
    _tmp164 = _tmp159 + _tmp163
    _tmp165 = _tmp104 * _tmp11 + _tmp164 * _tmp90
    _tmp166 = _tmp11 * _tmp155 + _tmp154 * _tmp164
    _tmp167 = _tmp150 * _tmp93 + _tmp151 * _tmp160
    _tmp168 = _tmp108 * _tmp148 + _tmp167
    _tmp169 = _tmp108 * _tmp130 + _tmp122 * _tmp93 + _tmp139 * _tmp160
    _tmp170 = _tmp11 * _tmp144 + _tmp122 * _tmp164
    _tmp171 = _tmp162 * _tmp165 + _tmp166 * _tmp168 + _tmp169 * _tmp170
    _tmp172 = _tmp15 * _tmp154 + _tmp155 * _tmp74
    _tmp173 = _tmp107 + _tmp70
    _tmp174 = _tmp11 * _tmp150 + _tmp151 * _tmp173
    _tmp175 = _tmp148 * _tmp164 + _tmp174
    _tmp176 = _tmp164 * _tmp52
    _tmp177 = _tmp11 * _tmp90 + _tmp173 * _tmp65 + _tmp176
    _tmp178 = _tmp104 * _tmp74 + _tmp15 * _tmp90
    _tmp179 = _tmp11 * _tmp122 + _tmp130 * _tmp164 + _tmp139 * _tmp173
    _tmp180 = _tmp122 * _tmp15 + _tmp144 * _tmp74
    _tmp181 = _tmp172 * _tmp175 + _tmp177 * _tmp178 + _tmp179 * _tmp180
    _tmp182 = cte_7 * _tmp49
    _tmp183 = cte_6 * _tmp18
    _tmp184 = _tmp16 * _tmp183
    _tmp185 = cte_9 * _tmp23
    _tmp186 = _tmp185 * _tmp24
    _tmp187 = cte_4 * _tmp17
    _tmp188 = _tmp18 * _tmp187
    _tmp189 = _tmp16 * _tmp188
    _tmp190 = cte_9 * _tmp28
    _tmp191 = _tmp190 * _tmp27
    _tmp192 = _tmp16 * _tmp191
    _tmp193 = cte_9 * _tmp22
    _tmp194 = _tmp18 * _tmp193
    _tmp195 = _tmp16 * _tmp194
    _tmp196 = cte_4 * _tmp95
    _tmp197 = cte_9 * _tmp17
    _tmp198 = cte_7 * _tmp35
    _tmp199 = (
        _tmp103 * _tmp198
        + _tmp182 * _tmp96
        - _tmp184
        - _tmp186
        - _tmp189
        - _tmp192
        + _tmp195
        - _tmp196
        - _tmp197 * _tmp94
    )
    _tmp200 = cte_12 * _tmp11
    _tmp201 = cte_4 * _tmp22
    _tmp202 = _tmp16 * _tmp185
    _tmp203 = cte_7 * _tmp80
    _tmp204 = (
        _tmp183 * _tmp24
        + _tmp188 * _tmp24
        + _tmp191 * _tmp24
        - _tmp194 * _tmp24
        + _tmp198 * _tmp87
        - _tmp202
        + _tmp203 * _tmp49
        - cte_9 * _tmp84
    )
    _tmp205 = _tmp201 * (_tmp45 - _tmp76) + _tmp204
    _tmp206 = cte_12 * _tmp164
    _tmp207 = (
        _in1[..., 0] * _tmp170
        + _in1[..., 1] * _tmp166
        + _in1[..., 2] * _tmp165
        + _tmp199 * _tmp200
        + _tmp205 * _tmp206
    )
    _tmp208 = cte_12 * _tmp108
    _tmp209 = cte_12 * _tmp93
    _tmp210 = (
        _in1[..., 0] * _tmp145
        + _in1[..., 1] * _tmp156
        + _in1[..., 2] * _tmp109
        + _tmp199 * _tmp209
        + _tmp205 * _tmp208
    )
    _tmp211 = cte_12 * _tmp15
    _tmp212 = cte_12 * _tmp74
    _tmp213 = (
        _in1[..., 0] * _tmp180
        + _in1[..., 1] * _tmp172
        + _in1[..., 2] * _tmp178
        + _tmp199 * _tmp212
        + _tmp205 * _tmp211
    )
    _tmp214 = _tmp24 * _tmp55 + _tmp28 * _tmp85
    _tmp215 = _tmp24 * _tmp58 - _tmp28 * _tmp79
    _tmp216 = _tmp215 * _tmp38 + _tmp24 * _tmp62
    _tmp217 = -_tmp214 * _tmp36 + _tmp216 * _tmp50
    _tmp218 = _tmp27 * _tmp29
    _tmp219 = _tmp17 * _tmp218 + _tmp28 * _tmp40
    _tmp220 = -_tmp21 * _tmp28 + _tmp218 * _tmp22
    _tmp221 = _tmp16 * _tmp62 + _tmp220 * _tmp38
    _tmp222 = -_tmp219 * _tmp36 + _tmp221 * _tmp50
    _tmp223 = -_tmp20 + _tmp28 * _tmp58
    _tmp224 = -_tmp28 * _tmp55 - _tmp39
    _tmp225 = _tmp224 * _tmp38 + _tmp54 * _tmp61
    _tmp226 = cte_12 * _tmp225
    _tmp227 = -_tmp223 * _tmp36 + _tmp226 * _tmp49
    _tmp228 = _tmp11 * _tmp217 + _tmp164 * _tmp222 + _tmp173 * _tmp227
    _tmp229 = _tmp223 * _tmp50 + _tmp226 * _tmp35
    _tmp230 = -_tmp132 * _tmp54 + _tmp224 * _tmp43
    _tmp231 = _tmp114 * _tmp230 + _tmp120 * _tmp229
    _tmp232 = -_tmp133 * _tmp16 + _tmp220 * _tmp43
    _tmp233 = _tmp219 * _tmp50
    _tmp234 = _tmp221 * _tmp36
    _tmp235 = _tmp114 * _tmp232 + _tmp120 * (_tmp233 + _tmp234)
    _tmp236 = _tmp214 * _tmp50 + _tmp216 * _tmp36
    _tmp237 = -_tmp133 * _tmp24 + _tmp215 * _tmp43
    _tmp238 = _tmp114 * _tmp237 + _tmp120 * _tmp236
    _tmp239 = _tmp11 * _tmp238 + _tmp164 * _tmp235 + _tmp173 * _tmp231
    _tmp240 = -_tmp114 * _tmp236 + _tmp120 * _tmp237
    _tmp241 = _tmp114 * (-_tmp233 - _tmp234) + _tmp120 * _tmp232
    _tmp242 = -_tmp114 * _tmp229 + _tmp120 * _tmp230
    _tmp243 = _tmp11 * _tmp240 + _tmp164 * _tmp241 + _tmp173 * _tmp242
    _tmp244 = _tmp162 * _tmp228 + _tmp168 * _tmp243 + _tmp169 * _tmp239
    _tmp245 = _tmp15 * _tmp222 + _tmp217 * _tmp74 + _tmp227 * _tmp67
    _tmp246 = _tmp15 * _tmp241 + _tmp240 * _tmp74 + _tmp242 * _tmp67
    _tmp247 = _tmp15 * _tmp235 + _tmp231 * _tmp67 + _tmp238 * _tmp74
    _tmp248 = _tmp175 * _tmp246 + _tmp177 * _tmp245 + _tmp179 * _tmp247
    _tmp249 = _tmp108 * _tmp235 + _tmp160 * _tmp231 + _tmp238 * _tmp93
    _tmp250 = _tmp108 * _tmp222 + _tmp160 * _tmp227 + _tmp217 * _tmp93
    _tmp251 = _tmp108 * _tmp241 + _tmp160 * _tmp242 + _tmp240 * _tmp93
    _tmp252 = _tmp140 * _tmp249 + _tmp153 * _tmp251 + _tmp250 * _tmp91
    _tmp253 = cte_6 * _tmp27
    _tmp254 = _tmp18 * _tmp190
    _tmp255 = _tmp187 * _tmp27
    _tmp256 = _tmp193 * _tmp27
    _tmp257 = _tmp18 * _tmp197
    _tmp258 = _tmp16 * _tmp257
    _tmp259 = _tmp18 * _tmp201
    _tmp260 = _tmp16 * _tmp259
    _tmp261 = (
        _tmp16 * _tmp253
        - _tmp16 * _tmp254
        + _tmp16 * _tmp255
        - _tmp16 * _tmp256
        + _tmp182 * _tmp219
        + _tmp198 * _tmp221
        + _tmp258 * _tmp28
        + _tmp260 * _tmp28
    )
    _tmp262 = _tmp257 * _tmp28
    _tmp263 = _tmp259 * _tmp28
    _tmp264 = (
        _tmp182 * _tmp214
        + _tmp198 * _tmp216
        + _tmp24 * _tmp253
        - _tmp24 * _tmp254
        + _tmp24 * _tmp255
        - _tmp24 * _tmp256
        + _tmp24 * _tmp262
        + _tmp24 * _tmp263
    )
    _tmp265 = _tmp197 * _tmp27
    _tmp266 = _tmp201 * _tmp27
    _tmp267 = (
        _tmp182 * _tmp223
        - _tmp183
        - _tmp188
        - _tmp191
        + _tmp194
        + _tmp198 * _tmp225
        + _tmp265 * _tmp28
        + _tmp266 * _tmp28
    )
    _tmp268 = cte_12 * _tmp160
    _tmp269 = (
        _in1[..., 0] * _tmp249
        + _in1[..., 1] * _tmp251
        + _in1[..., 2] * _tmp250
        + _tmp208 * _tmp261
        + _tmp209 * _tmp264
        + _tmp267 * _tmp268
    )
    _tmp270 = cte_12 * _tmp67
    _tmp271 = (
        _in1[..., 0] * _tmp247
        + _in1[..., 1] * _tmp246
        + _in1[..., 2] * _tmp245
        + _tmp211 * _tmp261
        + _tmp212 * _tmp264
        + _tmp267 * _tmp270
    )
    _tmp272 = cte_12 * _tmp173
    _tmp273 = (
        _in1[..., 0] * _tmp239
        + _in1[..., 1] * _tmp243
        + _in1[..., 2] * _tmp228
        + _tmp200 * _tmp264
        + _tmp206 * _tmp261
        + _tmp267 * _tmp272
    )
    _tmp274 = _tmp101 * _tmp142 - _tmp32 * _tmp43
    _tmp275 = cte_12 * _tmp274
    _tmp276 = _tmp22 * _tmp98
    _tmp277 = _tmp275 * _tmp49 + _tmp276 * _tmp36
    _tmp278 = _tmp19 * _tmp28
    _tmp279 = _tmp132 * _tmp20 + _tmp278 * _tmp43
    _tmp280 = _tmp23 * _tmp39
    _tmp281 = _tmp279 * _tmp50 + _tmp280 * _tmp35
    _tmp282 = -_tmp30 - _tmp82
    _tmp283 = _tmp101 * _tmp282
    _tmp284 = _tmp283 * _tmp38 - _tmp43 * _tmp77
    _tmp285 = _tmp22 * _tmp282
    _tmp286 = _tmp284 * _tmp50 + _tmp285 * _tmp36
    _tmp287 = _tmp15 * _tmp277 + _tmp281 * _tmp67 + _tmp286 * _tmp74
    _tmp288 = _tmp279 * _tmp36 - _tmp280 * _tmp49
    _tmp289 = _tmp20 * _tmp61 - _tmp278 * _tmp38
    _tmp290 = -_tmp114 * _tmp288 + _tmp120 * _tmp289
    _tmp291 = _tmp275 * _tmp35
    _tmp292 = _tmp276 * _tmp50
    _tmp293 = _tmp101 * _tmp99 + _tmp32 * _tmp38
    _tmp294 = _tmp114 * (-_tmp291 + _tmp292) + _tmp120 * _tmp293
    _tmp295 = (
        cte_12 * _tmp283 * _tmp43
        + cte_12 * _tmp38 * _tmp77
    )
    _tmp296 = _tmp284 * _tmp36 - _tmp285 * _tmp50
    _tmp297 = -_tmp114 * _tmp296 + _tmp119 * _tmp295
    _tmp298 = _tmp15 * _tmp294 + _tmp290 * _tmp67 + _tmp297 * _tmp74
    _tmp299 = _tmp113 * _tmp295 + _tmp120 * _tmp296
    _tmp300 = _tmp114 * _tmp293 + _tmp120 * (_tmp291 - _tmp292)
    _tmp301 = _tmp114 * _tmp289 + _tmp120 * _tmp288
    _tmp302 = _tmp15 * _tmp300 + _tmp299 * _tmp74 + _tmp301 * _tmp67
    _tmp303 = _tmp175 * _tmp298 + _tmp177 * _tmp287 + _tmp179 * _tmp302
    _tmp304 = _tmp108 * _tmp300 + _tmp160 * _tmp301 + _tmp299 * _tmp93
    _tmp305 = _tmp108 * _tmp277 + _tmp160 * _tmp281 + _tmp286 * _tmp93
    _tmp306 = _tmp108 * _tmp294 + _tmp160 * _tmp290 + _tmp297 * _tmp93
    _tmp307 = _tmp140 * _tmp304 + _tmp153 * _tmp306 + _tmp305 * _tmp91
    _tmp308 = _tmp11 * _tmp286 + _tmp164 * _tmp277 + _tmp173 * _tmp281
    _tmp309 = _tmp11 * _tmp299 + _tmp164 * _tmp300 + _tmp173 * _tmp301
    _tmp310 = _tmp11 * _tmp297 + _tmp164 * _tmp294 + _tmp173 * _tmp290
    _tmp311 = _tmp162 * _tmp308 + _tmp168 * _tmp310 + _tmp169 * _tmp309
    _tmp312 = _tmp182 * _tmp22
    _tmp313 = (
        _tmp190 * _tmp24
        - _tmp197 * _tmp98
        + _tmp198 * _tmp274
        + _tmp201 * _tmp47
        - _tmp202 * _tmp27
        - _tmp312 * _tmp98
    )
    _tmp314 = (
        _tmp18 * _tmp185
        - _tmp18 * _tmp23 * _tmp312
        + _tmp198 * _tmp279
        - _tmp23 * _tmp257
        - _tmp23 * _tmp259
    )
    _tmp315 = (
        -_tmp16 * _tmp190
        - _tmp186 * _tmp27
        - _tmp197 * _tmp282
        + _tmp198 * _tmp284
        - _tmp201 * _tmp282
        - _tmp282 * _tmp312
    )
    _tmp316 = (
        _in1[..., 0] * _tmp302
        + _in1[..., 1] * _tmp298
        + _in1[..., 2] * _tmp287
        + _tmp211 * _tmp313
        + _tmp212 * _tmp315
        + _tmp270 * _tmp314
    )
    _tmp317 = (
        _in1[..., 0] * _tmp309
        + _in1[..., 1] * _tmp310
        + _in1[..., 2] * _tmp308
        + _tmp200 * _tmp315
        + _tmp206 * _tmp313
        + _tmp272 * _tmp314
    )
    _tmp318 = (
        _in1[..., 0] * _tmp304
        + _in1[..., 1] * _tmp306
        + _in1[..., 2] * _tmp305
        + _tmp208 * _tmp313
        + _tmp209 * _tmp315
        + _tmp268 * _tmp314
    )
    _tmp319 = -cte_12 * _tmp78 + _tmp79
    _tmp320 = _tmp114 * _tmp43
    _tmp321 = _tmp319 * _tmp38
    _tmp322 = -_tmp84 - _tmp85
    _tmp323 = cte_12 * _tmp322
    _tmp324 = _tmp321 * _tmp36 + _tmp323 * _tmp49
    _tmp325 = _tmp120 * _tmp324 + _tmp319 * _tmp320
    _tmp326 = -_tmp58 + _tmp59
    _tmp327 = cte_12 * _tmp326
    _tmp328 = _tmp327 * _tmp49 + _tmp38 * _tmp57
    _tmp329 = _tmp120 * _tmp328 + _tmp320 * _tmp56
    _tmp330 = _tmp100 - _tmp41
    _tmp331 = cte_12 * _tmp330
    _tmp332 = _tmp331 * _tmp49
    _tmp333 = _tmp21 - cte_12 * _tmp33
    _tmp334 = _tmp333 * _tmp38
    _tmp335 = _tmp334 * _tmp36
    _tmp336 = _tmp120 * (_tmp332 + _tmp335) + _tmp320 * _tmp333
    _tmp337 = _tmp11 * _tmp325 + _tmp164 * _tmp336 + _tmp173 * _tmp329
    _tmp338 = _tmp120 * _tmp43
    _tmp339 = _tmp114 * (-_tmp332 - _tmp335) + _tmp333 * _tmp338
    _tmp340 = -_tmp114 * _tmp328 + _tmp338 * _tmp56
    _tmp341 = -_tmp114 * _tmp324 + _tmp319 * _tmp338
    _tmp342 = _tmp11 * _tmp341 + _tmp164 * _tmp339 + _tmp173 * _tmp340
    _tmp343 = _tmp321 * _tmp50 - _tmp323 * _tmp35
    _tmp344 = -_tmp331 * _tmp35 + _tmp334 * _tmp50
    _tmp345 = _tmp136 * _tmp38 - _tmp327 * _tmp35
    _tmp346 = _tmp11 * _tmp343 + _tmp164 * _tmp344 + _tmp173 * _tmp345
    _tmp347 = _tmp162 * _tmp346 + _tmp168 * _tmp342 + _tmp169 * _tmp337
    _tmp348 = _tmp108 * _tmp336 + _tmp160 * _tmp329 + _tmp325 * _tmp93
    _tmp349 = _tmp108 * _tmp344 + _tmp160 * _tmp345 + _tmp343 * _tmp93
    _tmp350 = _tmp108 * _tmp339 + _tmp160 * _tmp340 + _tmp341 * _tmp93
    _tmp351 = _tmp140 * _tmp348 + _tmp153 * _tmp350 + _tmp349 * _tmp91
    _tmp352 = _tmp15 * _tmp336 + _tmp325 * _tmp74 + _tmp329 * _tmp67
    _tmp353 = _tmp15 * _tmp339 + _tmp340 * _tmp67 + _tmp341 * _tmp74
    _tmp354 = _tmp15 * _tmp344 + _tmp343 * _tmp74 + _tmp345 * _tmp67
    _tmp355 = _tmp175 * _tmp353 + _tmp177 * _tmp354 + _tmp179 * _tmp352
    _tmp356 = _tmp198 * _tmp38
    _tmp357 = (
        _tmp182 * _tmp322
        - _tmp24 * _tmp257
        - _tmp24 * _tmp259
        + _tmp319 * _tmp356
        + cte_9 * _tmp78
        - cte_4 * _tmp84
    )
    _tmp358 = _tmp198 * _tmp56
    _tmp359 = (
        _tmp182 * _tmp326
        + _tmp188 * _tmp28
        - _tmp194 * _tmp28
        - _tmp265
        - _tmp266
        + _tmp358 * _tmp38
    )
    _tmp360 = (
        _tmp182 * _tmp330
        + _tmp187 * _tmp94
        - _tmp258
        - _tmp260
        + cte_9 * _tmp33
        + _tmp333 * _tmp356
    )
    _tmp361 = (
        _in1[..., 0] * _tmp337
        + _in1[..., 1] * _tmp342
        + _in1[..., 2] * _tmp346
        + _tmp200 * _tmp357
        + _tmp206 * _tmp360
        + _tmp272 * _tmp359
    )
    _tmp362 = (
        _in1[..., 0] * _tmp348
        + _in1[..., 1] * _tmp350
        + _in1[..., 2] * _tmp349
        + _tmp208 * _tmp360
        + _tmp209 * _tmp357
        + _tmp268 * _tmp359
    )
    _tmp363 = (
        _in1[..., 0] * _tmp352
        + _in1[..., 1] * _tmp353
        + _in1[..., 2] * _tmp354
        + _tmp211 * _tmp360
        + _tmp212 * _tmp357
        + _tmp270 * _tmp359
    )
    _tmp364 = -_tmp131 + _tmp133
    _tmp365 = _tmp35 * _tmp364
    _tmp366 = -_tmp114 * _tmp365 + _tmp120 * _tmp63
    _tmp367 = -_tmp110 - _tmp111
    _tmp368 = _tmp35 * _tmp367
    _tmp369 = -_tmp114 * _tmp368 + _tmp120 * _tmp87
    _tmp370 = -_tmp126 - _tmp127
    _tmp371 = _tmp35 * _tmp370
    _tmp372 = -_tmp114 * _tmp371 + _tmp120 * _tmp48
    _tmp373 = _tmp15 * _tmp372 + _tmp366 * _tmp67 + _tmp369 * _tmp74
    _tmp374 = _tmp367 * _tmp74
    _tmp375 = _tmp370 * _tmp49
    _tmp376 = _tmp364 * _tmp49
    _tmp377 = _tmp211 * _tmp375 + _tmp270 * _tmp376 + _tmp374 * _tmp50
    _tmp378 = _tmp114 * _tmp63 + _tmp120 * _tmp365
    _tmp379 = _tmp114 * _tmp48 + _tmp120 * _tmp371
    _tmp380 = _tmp114 * _tmp87 + _tmp120 * _tmp368
    _tmp381 = _tmp15 * _tmp379 + _tmp378 * _tmp67 + _tmp380 * _tmp74
    _tmp382 = _tmp175 * _tmp373 + _tmp177 * _tmp377 + _tmp179 * _tmp381
    _tmp383 = _tmp11 * _tmp380 + _tmp164 * _tmp379 + _tmp173 * _tmp378
    _tmp384 = _tmp11 * _tmp369 + _tmp164 * _tmp372 + _tmp173 * _tmp366
    _tmp385 = _tmp367 * _tmp49
    _tmp386 = _tmp200 * _tmp385 + _tmp206 * _tmp375 + _tmp272 * _tmp376
    _tmp387 = _tmp162 * _tmp386 + _tmp168 * _tmp384 + _tmp169 * _tmp383
    _tmp388 = _tmp108 * _tmp379 + _tmp160 * _tmp378 + _tmp380 * _tmp93
    _tmp389 = _tmp160 * _tmp364 * _tmp50 + _tmp208 * _tmp375 + _tmp209 * _tmp385
    _tmp390 = _tmp108 * _tmp372 + _tmp160 * _tmp366 + _tmp369 * _tmp93
    _tmp391 = _tmp140 * _tmp388 + _tmp153 * _tmp390 + _tmp389 * _tmp91
    _tmp392 = _tmp198 * _tmp364
    _tmp393 = _tmp198 * _tmp370
    _tmp394 = _tmp198 * _tmp367
    _tmp395 = (
        _in1[..., 0] * _tmp388
        + _in1[..., 1] * _tmp390
        + _in1[..., 2] * _tmp389
        + _tmp108 * _tmp393
        + _tmp160 * _tmp392
        + _tmp394 * _tmp93
    )
    _tmp396 = (
        _in1[..., 0] * _tmp381
        + _in1[..., 1] * _tmp373
        + _in1[..., 2] * _tmp377
        + _tmp15 * _tmp393
        + _tmp198 * _tmp374
        + _tmp392 * _tmp67
    )
    _tmp397 = (
        _in1[..., 0] * _tmp383
        + _in1[..., 1] * _tmp384
        + _in1[..., 2] * _tmp386
        + _tmp11 * _tmp394
        + _tmp164 * _tmp393
        + _tmp173 * _tmp392
    )
    _tmp398 = _tmp37 - _tmp51
    _tmp399 = _tmp119 * _tmp398
    _tmp400 = _tmp81 - _tmp89
    _tmp401 = _tmp120 * _tmp400
    _tmp402 = _tmp57 - _tmp64
    _tmp403 = _tmp270 * _tmp402
    _tmp404 = _tmp119 * _tmp403 + _tmp211 * _tmp399 + _tmp401 * _tmp74
    _tmp405 = _tmp118 * _tmp74 + _tmp125 * _tmp15 + _tmp137 * _tmp67
    _tmp406 = _tmp114 * _tmp400
    _tmp407 = -_tmp113 * _tmp403 + _tmp114 * _tmp53 - _tmp406 * _tmp74
    _tmp408 = _tmp175 * _tmp407 + _tmp177 * _tmp405 + _tmp179 * _tmp404
    _tmp409 = _tmp160 * _tmp402
    _tmp410 = _tmp108 * _tmp120 * _tmp398 + _tmp120 * _tmp409 + _tmp401 * _tmp93
    _tmp411 = _tmp108 * _tmp125 + _tmp118 * _tmp93 + _tmp137 * _tmp160
    _tmp412 = _tmp114 * _tmp161 - _tmp114 * _tmp409 - _tmp406 * _tmp93
    _tmp413 = _tmp140 * _tmp410 + _tmp153 * _tmp412 + _tmp411 * _tmp91
    _tmp414 = _tmp173 * _tmp402
    _tmp415 = -_tmp11 * _tmp406 + _tmp114 * _tmp176 - _tmp114 * _tmp414
    _tmp416 = _tmp11 * _tmp118 + _tmp125 * _tmp164 + _tmp137 * _tmp173
    _tmp417 = _tmp11 * _tmp401 + _tmp120 * _tmp414 + _tmp206 * _tmp399
    _tmp418 = _tmp162 * _tmp416 + _tmp168 * _tmp415 + _tmp169 * _tmp417
    _tmp419 = -_tmp182 * _tmp63 + _tmp358
    _tmp420 = -_tmp182 * _tmp48 + _tmp198 * _tmp34
    _tmp421 = -_tmp182 * _tmp87 + _tmp203 * _tmp35
    _tmp422 = (
        _in1[..., 0] * _tmp410
        + _in1[..., 1] * _tmp412
        + _in1[..., 2] * _tmp411
        + _tmp208 * _tmp420
        + _tmp209 * _tmp421
        + _tmp268 * _tmp419
    )
    _tmp423 = (
        _in1[..., 0] * _tmp404
        + _in1[..., 1] * _tmp407
        + _in1[..., 2] * _tmp405
        + _tmp211 * _tmp420
        + _tmp212 * _tmp421
        + _tmp270 * _tmp419
    )
    _tmp424 = (
        _in1[..., 0] * _tmp417
        + _in1[..., 1] * _tmp415
        + _in1[..., 2] * _tmp416
        + _tmp200 * _tmp421
        + _tmp206 * _tmp420
        + _tmp272 * _tmp419
    )
    _tmp425 = _tmp120 * _tmp146 - _tmp129
    _tmp426 = -_tmp115 - _tmp121
    _tmp427 = -_tmp135 - _tmp138
    _tmp428 = _tmp108 * _tmp425 + _tmp160 * _tmp427 + _tmp426 * _tmp93
    _tmp429 = -_tmp114 * _tmp125 + _tmp147
    _tmp430 = _tmp108 * _tmp429 + _tmp167
    _tmp431 = _tmp140 * _tmp430 + _tmp153 * _tmp428
    _tmp432 = _tmp11 * _tmp426 + _tmp164 * _tmp425 + _tmp173 * _tmp427
    _tmp433 = _tmp164 * _tmp429 + _tmp174
    _tmp434 = _tmp168 * _tmp432 + _tmp169 * _tmp433
    _tmp435 = _tmp15 * _tmp425 + _tmp426 * _tmp74 + _tmp427 * _tmp67
    _tmp436 = _tmp15 * _tmp429 + _tmp152
    _tmp437 = _tmp175 * _tmp435 + _tmp179 * _tmp436
    _tmp438 = _in1[..., 0] * _tmp430 + _in1[..., 1] * _tmp428
    _tmp439 = _in1[..., 0] * _tmp433 + _in1[..., 1] * _tmp432
    _tmp440 = _in1[..., 0] * _tmp436 + _in1[..., 1] * _tmp435
    _tmp441 = torch.pow(_in0[..., 9], cte_12)
    _tmp442 = cte_1 / torch.pow(
        _tmp4, cte_5
    )
    _tmp443 = _tmp441 * _tmp442
    _tmp444 = -_in0[..., 10] * _in0[..., 8] * _tmp443
    _tmp445 = _in0[..., 7] * _tmp442
    _tmp446 = _tmp0 * _tmp445
    _tmp447 = -_tmp7
    _tmp448 = _tmp444 + _tmp446 + _tmp447
    _tmp449 = _tmp443 * _tmp71
    _tmp450 = cte_1 * _tmp5
    _tmp451 = (
        -_in0[..., 9] * _tmp450
        + torch.pow(_in0[..., 9], cte_3) * _tmp442
    )
    _tmp452 = _tmp449 + _tmp451
    _tmp453 = _tmp441 * _tmp445
    _tmp454 = _in0[..., 10] * _tmp453
    _tmp455 = _tmp0 * _tmp442
    _tmp456 = -_in0[..., 8] * _tmp455 + _tmp9
    _tmp457 = -_tmp454 + _tmp456
    _tmp458 = _tmp122 * _tmp452 + _tmp130 * _tmp457 + _tmp139 * _tmp448
    _tmp459 = _tmp148 * _tmp457 + _tmp150 * _tmp452 + _tmp151 * _tmp448
    _tmp460 = _tmp448 * _tmp65 + _tmp452 * _tmp90 + _tmp457 * _tmp52
    _tmp461 = _tmp175 * _tmp459 + _tmp177 * _tmp460 + _tmp179 * _tmp458
    _tmp462 = _in0[..., 8] * _tmp453
    _tmp463 = _in0[..., 10] * _tmp6
    _tmp464 = -_in0[..., 10] * _tmp455 + _tmp463
    _tmp465 = _tmp462 + _tmp464
    _tmp466 = _tmp444 - _tmp446 + _tmp7
    _tmp467 = _tmp105 * _tmp443
    _tmp468 = _tmp451 + _tmp467
    _tmp469 = _tmp122 * _tmp466 + _tmp130 * _tmp465 + _tmp139 * _tmp468
    _tmp470 = _tmp148 * _tmp465 + _tmp150 * _tmp466 + _tmp151 * _tmp468
    _tmp471 = _tmp465 * _tmp52 + _tmp466 * _tmp90 + _tmp468 * _tmp65
    _tmp472 = _tmp162 * _tmp471 + _tmp168 * _tmp470 + _tmp169 * _tmp469
    _tmp473 = _tmp454 + _tmp456
    _tmp474 = -_tmp462 + _tmp464
    _tmp475 = _tmp449 + _tmp467
    _tmp476 = _tmp122 * _tmp473 + _tmp130 * _tmp475 + _tmp139 * _tmp474
    _tmp477 = _tmp473 * _tmp90 + _tmp474 * _tmp65 + _tmp475 * _tmp52
    _tmp478 = _tmp148 * _tmp475 + _tmp150 * _tmp473 + _tmp151 * _tmp474
    _tmp479 = _tmp140 * _tmp476 + _tmp153 * _tmp478 + _tmp477 * _tmp91
    _tmp480 = _tmp11 * _tmp479 + _tmp461 * _tmp93 + _tmp472 * _tmp74
    _tmp481 = cte_10 * _in0[..., 10]
    _tmp482 = torch.pow(_in0[..., 10], cte_12)
    _tmp483 = _tmp442 * _tmp482
    _tmp484 = _tmp105 * _tmp483
    _tmp485 = (
        -_in0[..., 10] * _tmp450
        + torch.pow(_in0[..., 10], cte_3) * _tmp442
    )
    _tmp486 = _tmp484 + _tmp485
    _tmp487 = _tmp3 * _tmp445
    _tmp488 = -_in0[..., 8] * _in0[..., 9] * _tmp483
    _tmp489 = _tmp447 + _tmp487 + _tmp488
    _tmp490 = _tmp445 * _tmp482
    _tmp491 = _in0[..., 8] * _tmp490
    _tmp492 = _tmp3 * _tmp442
    _tmp493 = -_in0[..., 9] * _tmp492 + _tmp12
    _tmp494 = -_tmp491 + _tmp493
    _tmp495 = _tmp486 * _tmp52 + _tmp489 * _tmp90 + _tmp494 * _tmp65
    _tmp496 = _tmp122 * _tmp489 + _tmp130 * _tmp486 + _tmp139 * _tmp494
    _tmp497 = _tmp148 * _tmp486 + _tmp150 * _tmp489 + _tmp151 * _tmp494
    _tmp498 = _tmp140 * _tmp496 + _tmp153 * _tmp497 + _tmp495 * _tmp91
    _tmp499 = _in0[..., 9] * _tmp490
    _tmp500 = -_in0[..., 8] * _tmp492 + _tmp9
    _tmp501 = _tmp499 + _tmp500
    _tmp502 = _tmp483 * _tmp68
    _tmp503 = _tmp485 + _tmp502
    _tmp504 = -_tmp487 + _tmp488 + _tmp7
    _tmp505 = _tmp501 * _tmp65 + _tmp503 * _tmp90 + _tmp504 * _tmp52
    _tmp506 = _tmp122 * _tmp503 + _tmp130 * _tmp504 + _tmp139 * _tmp501
    _tmp507 = _tmp148 * _tmp504 + _tmp150 * _tmp503 + _tmp151 * _tmp501
    _tmp508 = _tmp175 * _tmp507 + _tmp177 * _tmp505 + _tmp179 * _tmp506
    _tmp509 = _tmp491 + _tmp493
    _tmp510 = _tmp484 + _tmp502
    _tmp511 = -_tmp499 + _tmp500
    _tmp512 = _tmp148 * _tmp509 + _tmp150 * _tmp511 + _tmp151 * _tmp510
    _tmp513 = _tmp509 * _tmp52 + _tmp510 * _tmp65 + _tmp511 * _tmp90
    _tmp514 = _tmp122 * _tmp511 + _tmp130 * _tmp509 + _tmp139 * _tmp510
    _tmp515 = _tmp162 * _tmp513 + _tmp168 * _tmp512 + _tmp169 * _tmp514
    _tmp516 = (
        cte_10 * _tmp11 * _tmp498
        + cte_10 * _tmp508 * _tmp93
        + cte_10 * _tmp515 * _tmp74
    )
    _tmp517 = torch.pow(_in0[..., 8], cte_12)
    _tmp518 = _tmp445 * _tmp517
    _tmp519 = _in0[..., 9] * _tmp518
    _tmp520 = _in0[..., 10] * _tmp442
    _tmp521 = -_tmp1 * _tmp520 + _tmp463
    _tmp522 = _tmp519 + _tmp521
    _tmp523 = _tmp442 * _tmp517
    _tmp524 = _tmp523 * _tmp71
    _tmp525 = _tmp523 * _tmp68
    _tmp526 = _tmp524 + _tmp525
    _tmp527 = _in0[..., 10] * _tmp518
    _tmp528 = -_in0[..., 9] * _tmp1 * _tmp442 + _tmp12
    _tmp529 = -_tmp527 + _tmp528
    _tmp530 = _tmp122 * _tmp526 + _tmp130 * _tmp529 + _tmp139 * _tmp522
    _tmp531 = _tmp52 * _tmp529 + _tmp522 * _tmp65 + _tmp526 * _tmp90
    _tmp532 = _tmp148 * _tmp529 + _tmp150 * _tmp526 + _tmp151 * _tmp522
    _tmp533 = _tmp175 * _tmp532 + _tmp177 * _tmp531 + _tmp179 * _tmp530
    _tmp534 = _tmp527 + _tmp528
    _tmp535 = _tmp1 * _tmp445
    _tmp536 = _in0[..., 10] * _in0[..., 9]
    _tmp537 = -_tmp523 * _tmp536
    _tmp538 = -_tmp535 + _tmp537 + _tmp7
    _tmp539 = (
        -_in0[..., 8] * _tmp450
        + torch.pow(_in0[..., 8], cte_3) * _tmp442
    )
    _tmp540 = _tmp524 + _tmp539
    _tmp541 = _tmp148 * _tmp540 + _tmp150 * _tmp534 + _tmp151 * _tmp538
    _tmp542 = _tmp52 * _tmp540 + _tmp534 * _tmp90 + _tmp538 * _tmp65
    _tmp543 = _tmp122 * _tmp534 + _tmp130 * _tmp540 + _tmp139 * _tmp538
    _tmp544 = _tmp140 * _tmp543 + _tmp153 * _tmp541 + _tmp542 * _tmp91
    _tmp545 = -_tmp519 + _tmp521
    _tmp546 = _tmp447 + _tmp535 + _tmp537
    _tmp547 = _tmp525 + _tmp539
    _tmp548 = _tmp122 * _tmp545 + _tmp130 * _tmp546 + _tmp139 * _tmp547
    _tmp549 = _tmp148 * _tmp546 + _tmp150 * _tmp545 + _tmp151 * _tmp547
    _tmp550 = _tmp52 * _tmp546 + _tmp545 * _tmp90 + _tmp547 * _tmp65
    _tmp551 = _tmp162 * _tmp550 + _tmp168 * _tmp549 + _tmp169 * _tmp548
    _tmp552 = _tmp11 * _tmp544 + _tmp533 * _tmp93 + _tmp551 * _tmp74
    _tmp553 = cte_10 * _tmp552
    _tmp554 = torch.pow(_in0[..., 7], cte_12) * _tmp442
    _tmp555 = _in0[..., 8] * _tmp554
    _tmp556 = -_in0[..., 9] * _tmp555
    _tmp557 = _tmp2 * _tmp520
    _tmp558 = -_tmp463 + _tmp556 + _tmp557
    _tmp559 = _tmp2 * _tmp442
    _tmp560 = _in0[..., 8] * _tmp559
    _tmp561 = -_tmp536 * _tmp554
    _tmp562 = -_tmp560 + _tmp561 + _tmp9
    _tmp563 = _tmp554 * _tmp71
    _tmp564 = _tmp105 * _tmp554
    _tmp565 = _tmp563 + _tmp564
    _tmp566 = _tmp52 * _tmp565 + _tmp558 * _tmp90 + _tmp562 * _tmp65
    _tmp567 = _tmp122 * _tmp558 + _tmp130 * _tmp565 + _tmp139 * _tmp562
    _tmp568 = _tmp148 * _tmp565 + _tmp150 * _tmp558 + _tmp151 * _tmp562
    _tmp569 = _tmp140 * _tmp567 + _tmp153 * _tmp568 + _tmp566 * _tmp91
    _tmp570 = _tmp554 * _tmp68
    _tmp571 = _tmp564 + _tmp570
    _tmp572 = _tmp560 + _tmp561 - _tmp9
    _tmp573 = _in0[..., 9] * _tmp559
    _tmp574 = -_in0[..., 10] * _tmp555
    _tmp575 = _tmp12 - _tmp573 + _tmp574
    _tmp576 = _tmp122 * _tmp575 + _tmp130 * _tmp572 + _tmp139 * _tmp571
    _tmp577 = _tmp52 * _tmp572 + _tmp571 * _tmp65 + _tmp575 * _tmp90
    _tmp578 = _tmp148 * _tmp572 + _tmp150 * _tmp575 + _tmp151 * _tmp571
    _tmp579 = _tmp162 * _tmp577 + _tmp168 * _tmp578 + _tmp169 * _tmp576
    _tmp580 = _tmp463 + _tmp556 - _tmp557
    _tmp581 = -_tmp12 + _tmp573 + _tmp574
    _tmp582 = _tmp563 + _tmp570
    _tmp583 = _tmp52 * _tmp580 + _tmp581 * _tmp65 + _tmp582 * _tmp90
    _tmp584 = _tmp148 * _tmp580 + _tmp150 * _tmp582 + _tmp151 * _tmp581
    _tmp585 = _tmp122 * _tmp582 + _tmp130 * _tmp580 + _tmp139 * _tmp581
    _tmp586 = _tmp175 * _tmp584 + _tmp177 * _tmp583 + _tmp179 * _tmp585
    _tmp587 = _tmp11 * _tmp569 + _tmp579 * _tmp74 + _tmp586 * _tmp93
    _tmp588 = cte_10 * _tmp587
    _tmp589 = _tmp108 * _tmp586 + _tmp15 * _tmp579 + _tmp164 * _tmp569
    _tmp590 = cte_10 * _tmp589
    _tmp591 = (
        cte_10 * _tmp108 * _tmp533
        + cte_10 * _tmp15 * _tmp551
        + cte_10 * _tmp164 * _tmp544
    )
    _tmp592 = _tmp108 * _tmp461 + _tmp15 * _tmp472 + _tmp164 * _tmp479
    _tmp593 = (
        cte_10 * _tmp108 * _tmp508
        + cte_10 * _tmp15 * _tmp515
        + cte_10 * _tmp164 * _tmp498
    )
    _tmp594 = _tmp160 * _tmp533 + _tmp173 * _tmp544 + _tmp551 * _tmp67
    _tmp595 = cte_10 * _tmp594
    _tmp596 = _tmp160 * _tmp461 + _tmp173 * _tmp479 + _tmp472 * _tmp67
    _tmp597 = (
        cte_10 * _tmp160 * _tmp508
        + cte_10 * _tmp173 * _tmp498
        + cte_10 * _tmp515 * _tmp67
    )
    _tmp598 = _tmp160 * _tmp586 + _tmp173 * _tmp569 + _tmp579 * _tmp67
    _tmp599 = cte_10 * _tmp598
    _tmp600 = cte_12 * _in0[..., 11]
    _tmp601 = cte_12 * _in0[..., 12]
    _tmp602 = (
        cte_12 * _tmp182 * _tmp56
        + cte_12 * _tmp198 * _tmp63
        + cte_12 * _tmp253
        - cte_12 * _tmp254
        + cte_12 * _tmp255
        - cte_12 * _tmp256
        + cte_12 * _tmp262
        + cte_12 * _tmp263
        + cte_11
    )
    _tmp603 = (
        cte_12 * _tmp182 * _tmp34
        + cte_12 * _tmp184
        + cte_12 * _tmp186
        + cte_12 * _tmp189
        + cte_12 * _tmp192
        - cte_12 * _tmp195
        + cte_12 * _tmp196
        + cte_12 * _tmp198 * _tmp48
        - cte_9 * _tmp41
    )
    _tmp604 = (
        cte_12 * _tmp204 - cte_4 * _tmp78
    )
    _tmp605 = cte_12 * _in0[..., 13]
    _tmp606 = (
        _in1[..., 0] * _tmp548
        + _in1[..., 1] * _tmp549
        + _in1[..., 2] * _tmp550
        - _tmp545 * _tmp600
        + _tmp545 * _tmp604
        - _tmp546 * _tmp601
        + _tmp546 * _tmp603
        + _tmp547 * _tmp602
        - _tmp547 * _tmp605
    )
    _tmp607 = (
        _in1[..., 0] * _tmp543
        + _in1[..., 1] * _tmp541
        + _in1[..., 2] * _tmp542
        - _tmp534 * _tmp600
        + _tmp534 * _tmp604
        + _tmp538 * _tmp602
        - _tmp538 * _tmp605
        - _tmp540 * _tmp601
        + _tmp540 * _tmp603
    )
    _tmp608 = (
        _in1[..., 0] * _tmp530
        + _in1[..., 1] * _tmp532
        + _in1[..., 2] * _tmp531
        + _tmp522 * _tmp602
        - _tmp522 * _tmp605
        - _tmp526 * _tmp600
        + _tmp526 * _tmp604
        - _tmp529 * _tmp601
        + _tmp529 * _tmp603
    )
    _tmp609 = _tmp11 * _tmp606 + _tmp607 * _tmp93 + _tmp608 * _tmp74
    _tmp610 = cte_10 * _tmp609
    _tmp611 = (
        _in1[..., 0] * _tmp576
        + _in1[..., 1] * _tmp578
        + _in1[..., 2] * _tmp577
        + _tmp571 * _tmp602
        - _tmp571 * _tmp605
        - _tmp572 * _tmp601
        + _tmp572 * _tmp603
        - _tmp575 * _tmp600
        + _tmp575 * _tmp604
    )
    _tmp612 = (
        _in1[..., 0] * _tmp567
        + _in1[..., 1] * _tmp568
        + _in1[..., 2] * _tmp566
        - _tmp558 * _tmp600
        + _tmp558 * _tmp604
        + _tmp562 * _tmp602
        - _tmp562 * _tmp605
        - _tmp565 * _tmp601
        + _tmp565 * _tmp603
    )
    _tmp613 = (
        _in1[..., 0] * _tmp585
        + _in1[..., 1] * _tmp584
        + _in1[..., 2] * _tmp583
        - _tmp580 * _tmp601
        + _tmp580 * _tmp603
        + _tmp581 * _tmp602
        - _tmp581 * _tmp605
        - _tmp582 * _tmp600
        + _tmp582 * _tmp604
    )
    _tmp614 = _tmp11 * _tmp611 + _tmp612 * _tmp93 + _tmp613 * _tmp74
    _tmp615 = cte_10 * _tmp614
    _tmp616 = (
        _in1[..., 0] * _tmp514
        + _in1[..., 1] * _tmp512
        + _in1[..., 2] * _tmp513
        - _tmp509 * _tmp601
        + _tmp509 * _tmp603
        + _tmp510 * _tmp602
        - _tmp510 * _tmp605
        - _tmp511 * _tmp600
        + _tmp511 * _tmp604
    )
    _tmp617 = (
        _in1[..., 0] * _tmp506
        + _in1[..., 1] * _tmp507
        + _in1[..., 2] * _tmp505
        + _tmp501 * _tmp602
        - _tmp501 * _tmp605
        - _tmp503 * _tmp600
        + _tmp503 * _tmp604
        - _tmp504 * _tmp601
        + _tmp504 * _tmp603
    )
    _tmp618 = (
        _in1[..., 0] * _tmp496
        + _in1[..., 1] * _tmp497
        + _in1[..., 2] * _tmp495
        - _tmp486 * _tmp601
        + _tmp486 * _tmp603
        - _tmp489 * _tmp600
        + _tmp489 * _tmp604
        + _tmp494 * _tmp602
        - _tmp494 * _tmp605
    )
    _tmp619 = (
        cte_10 * _tmp11 * _tmp616
        + cte_10 * _tmp617 * _tmp74
        + cte_10 * _tmp618 * _tmp93
    )
    _tmp620 = (
        _in1[..., 0] * _tmp476
        + _in1[..., 1] * _tmp478
        + _in1[..., 2] * _tmp477
        - _tmp473 * _tmp600
        + _tmp473 * _tmp604
        + _tmp474 * _tmp602
        - _tmp474 * _tmp605
        - _tmp475 * _tmp601
        + _tmp475 * _tmp603
    )
    _tmp621 = (
        _in1[..., 0] * _tmp469
        + _in1[..., 1] * _tmp470
        + _in1[..., 2] * _tmp471
        - _tmp465 * _tmp601
        + _tmp465 * _tmp603
        - _tmp466 * _tmp600
        + _tmp466 * _tmp604
        + _tmp468 * _tmp602
        - _tmp468 * _tmp605
    )
    _tmp622 = (
        _in1[..., 0] * _tmp458
        + _in1[..., 1] * _tmp459
        + _in1[..., 2] * _tmp460
        + _tmp448 * _tmp602
        - _tmp448 * _tmp605
        - _tmp452 * _tmp600
        + _tmp452 * _tmp604
        - _tmp457 * _tmp601
        + _tmp457 * _tmp603
    )
    _tmp623 = _tmp11 * _tmp621 + _tmp620 * _tmp93 + _tmp622 * _tmp74
    _tmp624 = _tmp108 * _tmp620 + _tmp15 * _tmp622 + _tmp164 * _tmp621
    _tmp625 = _tmp108 * _tmp612 + _tmp15 * _tmp613 + _tmp164 * _tmp611
    _tmp626 = cte_10 * _tmp625
    _tmp627 = _tmp108 * _tmp607 + _tmp15 * _tmp608 + _tmp164 * _tmp606
    _tmp628 = cte_10 * _tmp627
    _tmp629 = (
        cte_10 * _tmp108 * _tmp618
        + cte_10 * _tmp15 * _tmp617
        + cte_10 * _tmp164 * _tmp616
    )
    _tmp630 = _tmp160 * _tmp612 + _tmp173 * _tmp611 + _tmp613 * _tmp67
    _tmp631 = cte_10 * _tmp630
    _tmp632 = (
        cte_10 * _tmp160 * _tmp618
        + cte_10 * _tmp173 * _tmp616
        + cte_10 * _tmp617 * _tmp67
    )
    _tmp633 = _tmp160 * _tmp620 + _tmp173 * _tmp621 + _tmp622 * _tmp67
    _tmp634 = _tmp160 * _tmp607 + _tmp173 * _tmp606 + _tmp608 * _tmp67
    _tmp635 = cte_10 * _tmp634
    _tmp636 = cte_10 * _tmp480
    _tmp637 = cte_10 * _tmp592
    _tmp638 = cte_10 * _tmp596
    _tmp639 = cte_10 * _tmp623
    _tmp640 = cte_10 * _tmp624
    _tmp641 = cte_10 * _tmp633
    _tmp642 = _tmp69 + cte_2
    _tmp643 = _tmp642 + _tmp72
    _tmp644 = -_tmp13
    _tmp645 = _tmp14 + _tmp644
    _tmp646 = -_tmp10
    _tmp647 = _tmp646 + _tmp66
    _tmp648 = -_tmp159
    _tmp649 = _tmp158 + _tmp648
    _tmp650 = _tmp106 + _tmp72 + cte_2
    _tmp651 = _tmp644 + _tmp92
    _tmp652 = _tmp163 + _tmp648
    _tmp653 = _tmp106 + _tmp642
    _tmp654 = _tmp646 + _tmp8

    # Output terms
    _out = _broadcast_and_stack(
        [
            _broadcast_and_stack(
                [
                    _tmp11 * _tmp157 + _tmp171 * _tmp74 + _tmp181 * _tmp93,
                    _tmp108 * _tmp181 + _tmp15 * _tmp171 + _tmp157 * _tmp164,
                    _tmp157 * _tmp173 + _tmp160 * _tmp181 + _tmp171 * _tmp67,
                    _tmp11 * _tmp207 + _tmp210 * _tmp93 + _tmp213 * _tmp74,
                    _tmp108 * _tmp210 + _tmp15 * _tmp213 + _tmp164 * _tmp207,
                    _tmp160 * _tmp210 + _tmp173 * _tmp207 + _tmp213 * _tmp67,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _tmp11 * _tmp252 + _tmp244 * _tmp74 + _tmp248 * _tmp93,
                    _tmp108 * _tmp248 + _tmp15 * _tmp244 + _tmp164 * _tmp252,
                    _tmp160 * _tmp248 + _tmp173 * _tmp252 + _tmp244 * _tmp67,
                    _tmp11 * _tmp273 + _tmp269 * _tmp93 + _tmp271 * _tmp74,
                    _tmp108 * _tmp269 + _tmp15 * _tmp271 + _tmp164 * _tmp273,
                    _tmp160 * _tmp269 + _tmp173 * _tmp273 + _tmp271 * _tmp67,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _tmp11 * _tmp307 + _tmp303 * _tmp93 + _tmp311 * _tmp74,
                    _tmp108 * _tmp303 + _tmp15 * _tmp311 + _tmp164 * _tmp307,
                    _tmp160 * _tmp303 + _tmp173 * _tmp307 + _tmp311 * _tmp67,
                    _tmp11 * _tmp317 + _tmp316 * _tmp74 + _tmp318 * _tmp93,
                    _tmp108 * _tmp318 + _tmp15 * _tmp316 + _tmp164 * _tmp317,
                    _tmp160 * _tmp318 + _tmp173 * _tmp317 + _tmp316 * _tmp67,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _tmp11 * _tmp351 + _tmp347 * _tmp74 + _tmp355 * _tmp93,
                    _tmp108 * _tmp355 + _tmp15 * _tmp347 + _tmp164 * _tmp351,
                    _tmp160 * _tmp355 + _tmp173 * _tmp351 + _tmp347 * _tmp67,
                    _tmp11 * _tmp361 + _tmp362 * _tmp93 + _tmp363 * _tmp74,
                    _tmp108 * _tmp362 + _tmp15 * _tmp363 + _tmp164 * _tmp361,
                    _tmp160 * _tmp362 + _tmp173 * _tmp361 + _tmp363 * _tmp67,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _tmp11 * _tmp391 + _tmp382 * _tmp93 + _tmp387 * _tmp74,
                    _tmp108 * _tmp382 + _tmp15 * _tmp387 + _tmp164 * _tmp391,
                    _tmp160 * _tmp382 + _tmp173 * _tmp391 + _tmp387 * _tmp67,
                    _tmp11 * _tmp397 + _tmp395 * _tmp93 + _tmp396 * _tmp74,
                    _tmp108 * _tmp395 + _tmp15 * _tmp396 + _tmp164 * _tmp397,
                    _tmp160 * _tmp395 + _tmp173 * _tmp397 + _tmp396 * _tmp67,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _tmp11 * _tmp413 + _tmp408 * _tmp93 + _tmp418 * _tmp74,
                    _tmp108 * _tmp408 + _tmp15 * _tmp418 + _tmp164 * _tmp413,
                    _tmp160 * _tmp408 + _tmp173 * _tmp413 + _tmp418 * _tmp67,
                    _tmp11 * _tmp424 + _tmp422 * _tmp93 + _tmp423 * _tmp74,
                    _tmp108 * _tmp422 + _tmp15 * _tmp423 + _tmp164 * _tmp424,
                    _tmp160 * _tmp422 + _tmp173 * _tmp424 + _tmp423 * _tmp67,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _tmp11 * _tmp431 + _tmp434 * _tmp74 + _tmp437 * _tmp93,
                    _tmp108 * _tmp437 + _tmp15 * _tmp434 + _tmp164 * _tmp431,
                    _tmp160 * _tmp437 + _tmp173 * _tmp431 + _tmp434 * _tmp67,
                    _tmp11 * _tmp439 + _tmp438 * _tmp93 + _tmp440 * _tmp74,
                    _tmp108 * _tmp438 + _tmp15 * _tmp440 + _tmp164 * _tmp439,
                    _tmp160 * _tmp438 + _tmp173 * _tmp439 + _tmp440 * _tmp67,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _in0[..., 7] * _tmp553
                    - _in0[..., 8] * _tmp588
                    + _in0[..., 9] * _tmp516
                    - _tmp480 * _tmp481,
                    _in0[..., 7] * _tmp591
                    - _in0[..., 8] * _tmp590
                    + _in0[..., 9] * _tmp593
                    - _tmp481 * _tmp592,
                    _in0[..., 7] * _tmp595
                    - _in0[..., 8] * _tmp599
                    + _in0[..., 9] * _tmp597
                    - _tmp481 * _tmp596,
                    _in0[..., 7] * _tmp610
                    - _in0[..., 8] * _tmp615
                    + _in0[..., 9] * _tmp619
                    - _tmp481 * _tmp623,
                    _in0[..., 7] * _tmp628
                    - _in0[..., 8] * _tmp626
                    + _in0[..., 9] * _tmp629
                    - _tmp481 * _tmp624,
                    _in0[..., 7] * _tmp635
                    - _in0[..., 8] * _tmp631
                    + _in0[..., 9] * _tmp632
                    - _tmp481 * _tmp633,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _in0[..., 7] * _tmp636
                    - _in0[..., 8] * _tmp516
                    - _in0[..., 9] * _tmp588
                    + _tmp481 * _tmp552,
                    _in0[..., 10] * _tmp591
                    + _in0[..., 7] * _tmp637
                    - _in0[..., 8] * _tmp593
                    - _in0[..., 9] * _tmp590,
                    _in0[..., 7] * _tmp638
                    - _in0[..., 8] * _tmp597
                    - _in0[..., 9] * _tmp599
                    + _tmp481 * _tmp594,
                    _in0[..., 7] * _tmp639
                    - _in0[..., 8] * _tmp619
                    - _in0[..., 9] * _tmp615
                    + _tmp481 * _tmp609,
                    _in0[..., 7] * _tmp640
                    - _in0[..., 8] * _tmp629
                    - _in0[..., 9] * _tmp626
                    + _tmp481 * _tmp627,
                    _in0[..., 7] * _tmp641
                    - _in0[..., 8] * _tmp632
                    - _in0[..., 9] * _tmp631
                    + _tmp481 * _tmp634,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _in0[..., 7] * _tmp516
                    + _in0[..., 8] * _tmp636
                    - _in0[..., 9] * _tmp553
                    - _tmp481 * _tmp587,
                    _in0[..., 7] * _tmp593
                    + _in0[..., 8] * _tmp637
                    - _in0[..., 9] * _tmp591
                    - _tmp481 * _tmp589,
                    _in0[..., 7] * _tmp597
                    + _in0[..., 8] * _tmp638
                    - _in0[..., 9] * _tmp595
                    - _tmp481 * _tmp598,
                    _in0[..., 7] * _tmp619
                    + _in0[..., 8] * _tmp639
                    - _in0[..., 9] * _tmp610
                    - _tmp481 * _tmp614,
                    _in0[..., 7] * _tmp629
                    + _in0[..., 8] * _tmp640
                    - _in0[..., 9] * _tmp628
                    - _tmp481 * _tmp625,
                    _in0[..., 7] * _tmp632
                    + _in0[..., 8] * _tmp641
                    - _in0[..., 9] * _tmp635
                    - _tmp481 * _tmp630,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    cte_8,
                    cte_8,
                    cte_8,
                    _tmp11 * _tmp647 + _tmp643 * _tmp74 + _tmp645 * _tmp93,
                    _tmp108 * _tmp645 + _tmp15 * _tmp643 + _tmp164 * _tmp647,
                    _tmp160 * _tmp645 + _tmp173 * _tmp647 + _tmp643 * _tmp67,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    cte_8,
                    cte_8,
                    cte_8,
                    _tmp11 * _tmp649 + _tmp650 * _tmp93 + _tmp651 * _tmp74,
                    _tmp108 * _tmp650 + _tmp15 * _tmp651 + _tmp164 * _tmp649,
                    _tmp160 * _tmp650 + _tmp173 * _tmp649 + _tmp651 * _tmp67,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    cte_8,
                    cte_8,
                    cte_8,
                    _tmp11 * _tmp653 + _tmp652 * _tmp93 + _tmp654 * _tmp74,
                    _tmp108 * _tmp652 + _tmp15 * _tmp654 + _tmp164 * _tmp653,
                    _tmp160 * _tmp652 + _tmp173 * _tmp653 + _tmp654 * _tmp67,
                ],
                dim=-1,
            ),
        ],
        dim=-1,
    )

    return _out
