# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def spatial_velocity_jacobian_kQDot_panda_link7_box_world(
    _in0,
    _in1,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix14_1
        _in1: Matrix31

    Outputs:
        out: Matrix6_14


    """

    # Total ops: 2252

    # Input arrays

    # Intermediate terms (595)
    _tmp0 = casadi.sin(_in0[0, 0])
    _tmp1 = casadi.sin(_in0[2, 0])
    _tmp2 = 1.0 * _tmp1
    _tmp3 = _tmp0 * _tmp2
    _tmp4 = casadi.cos(_in0[1, 0])
    _tmp5 = casadi.cos(_in0[0, 0])
    _tmp6 = casadi.cos(_in0[2, 0])
    _tmp7 = 1.0 * _tmp6
    _tmp8 = _tmp5 * _tmp7
    _tmp9 = -_tmp3 + _tmp4 * _tmp8
    _tmp10 = casadi.sin(_in0[3, 0])
    _tmp11 = 1.0 * _tmp10
    _tmp12 = casadi.cos(_in0[3, 0])
    _tmp13 = casadi.sin(_in0[1, 0])
    _tmp14 = 1.0 * _tmp13
    _tmp15 = _tmp12 * _tmp14
    _tmp16 = -_tmp11 * _tmp9 + _tmp15 * _tmp5
    _tmp17 = casadi.sin(_in0[5, 0])
    _tmp18 = 1.0 * _tmp17
    _tmp19 = _tmp16 * _tmp18
    _tmp20 = casadi.sin(_in0[4, 0])
    _tmp21 = _tmp0 * _tmp7
    _tmp22 = _tmp2 * _tmp5
    _tmp23 = _tmp22 * _tmp4
    _tmp24 = 1.0 * _tmp21 + 1.0 * _tmp23
    _tmp25 = casadi.cos(_in0[4, 0])
    _tmp26 = 1.0 * _tmp12
    _tmp27 = _tmp26 * _tmp9
    _tmp28 = _tmp10 * _tmp14
    _tmp29 = _tmp28 * _tmp5
    _tmp30 = 1.0 * _tmp27 + 1.0 * _tmp29
    _tmp31 = -_tmp20 * _tmp24 + _tmp25 * _tmp30
    _tmp32 = casadi.cos(_in0[5, 0])
    _tmp33 = 1.0 * _tmp32
    _tmp34 = _tmp19 + _tmp31 * _tmp33
    _tmp35 = casadi.sin(_in0[6, 0])
    _tmp36 = 1.0 * _tmp35
    _tmp37 = _tmp24 * _tmp25
    _tmp38 = _tmp20 * _tmp30
    _tmp39 = _tmp37 + _tmp38
    _tmp40 = casadi.cos(_in0[6, 0])
    _tmp41 = 1.0 * _tmp40
    _tmp42 = -_tmp34 * _tmp36 + _tmp39 * _tmp41
    _tmp43 = _in0[9, 0] ** 2.0
    _tmp44 = _in0[8, 0] ** 2.0
    _tmp45 = _in0[7, 0] ** 2.0
    _tmp46 = _in0[10, 0] ** 2.0
    _tmp47 = _tmp43 + _tmp44 + _tmp45 + _tmp46
    _tmp48 = 1 / _tmp47
    _tmp49 = 2.0 * _tmp48
    _tmp50 = _in0[7, 0] * _tmp49
    _tmp51 = _in0[9, 0] * _tmp50
    _tmp52 = _in0[8, 0] * _tmp49
    _tmp53 = _in0[10, 0] * _tmp52
    _tmp54 = _tmp51 + _tmp53
    _tmp55 = 1.0 * _tmp54
    _tmp56 = _in0[8, 0] ** 2
    _tmp57 = _tmp49 * _tmp56
    _tmp58 = -_tmp57
    _tmp59 = _in0[9, 0] ** 2
    _tmp60 = _tmp49 * _tmp59
    _tmp61 = -_tmp60
    _tmp62 = _tmp58 + _tmp61 + 1.0
    _tmp63 = _tmp11 * _tmp4
    _tmp64 = _tmp12 * _tmp13
    _tmp65 = _tmp64 * _tmp7
    _tmp66 = 1.0 * _tmp63 - 1.0 * _tmp65
    _tmp67 = _tmp1 * _tmp14
    _tmp68 = _tmp20 * _tmp67
    _tmp69 = _tmp25 * _tmp66 + _tmp68
    _tmp70 = _tmp12 * _tmp4
    _tmp71 = 1.0 * _tmp70
    _tmp72 = _tmp10 * _tmp7
    _tmp73 = _tmp13 * _tmp72 + _tmp71
    _tmp74 = _tmp18 * _tmp73
    _tmp75 = _tmp33 * _tmp69 + _tmp74
    _tmp76 = _tmp20 * _tmp66
    _tmp77 = _tmp25 * _tmp67
    _tmp78 = _tmp76 - _tmp77
    _tmp79 = -_tmp36 * _tmp75 + _tmp41 * _tmp78
    _tmp80 = 1.0 * _tmp79
    _tmp81 = _in0[7, 0] * _tmp52
    _tmp82 = -_tmp81
    _tmp83 = _in0[9, 0] * _tmp49
    _tmp84 = _in0[10, 0] * _tmp83
    _tmp85 = _tmp82 + _tmp84
    _tmp86 = _tmp0 * _tmp28
    _tmp87 = _tmp21 * _tmp4
    _tmp88 = _tmp22 + _tmp87
    _tmp89 = 1.0 * _tmp88
    _tmp90 = _tmp12 * _tmp89
    _tmp91 = 1.0 * _tmp86 + 1.0 * _tmp90
    _tmp92 = _tmp3 * _tmp4
    _tmp93 = -_tmp8 + _tmp92
    _tmp94 = 1.0 * _tmp20
    _tmp95 = _tmp25 * _tmp91 - _tmp93 * _tmp94
    _tmp96 = _tmp0 * _tmp15
    _tmp97 = -_tmp11 * _tmp88 + _tmp96
    _tmp98 = _tmp18 * _tmp97
    _tmp99 = _tmp33 * _tmp95 + _tmp98
    _tmp100 = _tmp20 * _tmp91
    _tmp101 = 1.0 * _tmp25
    _tmp102 = _tmp101 * _tmp93
    _tmp103 = _tmp100 + _tmp102
    _tmp104 = _tmp103 * _tmp41 - _tmp36 * _tmp99
    _tmp105 = 1.0 * _tmp104
    _tmp106 = _tmp105 * _tmp85 + _tmp42 * _tmp55 + _tmp62 * _tmp80
    _tmp107 = _in0[9, 0] * _tmp52
    _tmp108 = _in0[10, 0] * _tmp50
    _tmp109 = _tmp107 + _tmp108
    _tmp110 = 1.0 * _tmp109
    _tmp111 = -_tmp22 - _tmp87
    _tmp112 = -_tmp11 * _tmp111 - _tmp96
    _tmp113 = _tmp8 - _tmp92
    _tmp114 = -_tmp86
    _tmp115 = 1.0 * _tmp111 * _tmp26 + 1.0 * _tmp114
    _tmp116 = -_tmp113 * _tmp94 + _tmp115 * _tmp25
    _tmp117 = _tmp112 * _tmp18 + _tmp116 * _tmp33
    _tmp118 = _tmp101 * _tmp113 + _tmp115 * _tmp20
    _tmp119 = -_tmp117 * _tmp36 + _tmp118 * _tmp41
    _tmp120 = _in0[10, 0] ** 2
    _tmp121 = _tmp120 * _tmp49
    _tmp122 = 1.0 - _tmp121
    _tmp123 = _tmp122 + _tmp61
    _tmp124 = 1.0 * _tmp123
    _tmp125 = _tmp110 * _tmp42 + _tmp119 * _tmp124
    _tmp126 = -_tmp112 * _tmp33 + _tmp116 * _tmp18
    _tmp127 = _tmp16 * _tmp33
    _tmp128 = _tmp18 * _tmp31
    _tmp129 = -_tmp127 + _tmp128
    _tmp130 = _tmp110 * _tmp129 + _tmp124 * _tmp126
    _tmp131 = _tmp18 * _tmp69
    _tmp132 = _tmp33 * _tmp73
    _tmp133 = _tmp131 - _tmp132
    _tmp134 = 1.0 * _tmp62
    _tmp135 = _tmp18 * _tmp95
    _tmp136 = _tmp33 * _tmp97
    _tmp137 = _tmp135 - _tmp136
    _tmp138 = 1.0 * _tmp137
    _tmp139 = 1.0 * _tmp129
    _tmp140 = _tmp133 * _tmp134 + _tmp138 * _tmp85 + _tmp139 * _tmp54
    _tmp141 = _tmp117 * _tmp41 + _tmp118 * _tmp36
    _tmp142 = _tmp34 * _tmp41
    _tmp143 = _tmp36 * _tmp39
    _tmp144 = _tmp142 + _tmp143
    _tmp145 = _tmp110 * _tmp144 + _tmp124 * _tmp141
    _tmp146 = _tmp41 * _tmp99
    _tmp147 = _tmp103 * _tmp36
    _tmp148 = _tmp146 + _tmp147
    _tmp149 = 1.0 * _tmp148
    _tmp150 = _tmp41 * _tmp75
    _tmp151 = _tmp36 * _tmp78
    _tmp152 = _tmp150 + _tmp151
    _tmp153 = _tmp134 * _tmp152 + _tmp144 * _tmp55 + _tmp149 * _tmp85
    _tmp154 = _tmp106 * _tmp125 + _tmp130 * _tmp140 + _tmp145 * _tmp153
    _tmp155 = -_tmp108
    _tmp156 = _tmp107 + _tmp155
    _tmp157 = _tmp122 + _tmp58
    _tmp158 = 1.0 * _tmp144
    _tmp159 = 1.0 * _tmp156
    _tmp160 = _tmp141 * _tmp159 + _tmp157 * _tmp158
    _tmp161 = -_tmp51
    _tmp162 = _tmp161 + _tmp53
    _tmp163 = 1.0 * _tmp162
    _tmp164 = _tmp110 * _tmp148 + _tmp124 * _tmp144 + _tmp152 * _tmp163
    _tmp165 = _tmp104 * _tmp110 + _tmp124 * _tmp42 + _tmp163 * _tmp79
    _tmp166 = 1.0 * _tmp157
    _tmp167 = _tmp119 * _tmp159 + _tmp166 * _tmp42
    _tmp168 = _tmp126 * _tmp159 + _tmp139 * _tmp157
    _tmp169 = _tmp110 * _tmp137 + _tmp123 * _tmp139 + _tmp133 * _tmp163
    _tmp170 = _tmp160 * _tmp164 + _tmp165 * _tmp167 + _tmp168 * _tmp169
    _tmp171 = _tmp81 + _tmp84
    _tmp172 = 1.0 * _tmp171
    _tmp173 = _tmp105 * _tmp157 + _tmp159 * _tmp42 + _tmp172 * _tmp79
    _tmp174 = 1.0 * _tmp42
    _tmp175 = _tmp119 * _tmp55 + _tmp174 * _tmp85
    _tmp176 = _tmp141 * _tmp55 + _tmp158 * _tmp85
    _tmp177 = _tmp144 * _tmp159 + _tmp149 * _tmp157 + _tmp152 * _tmp172
    _tmp178 = _tmp126 * _tmp55 + _tmp139 * _tmp85
    _tmp179 = _tmp133 * _tmp172 + _tmp138 * _tmp157 + _tmp139 * _tmp156
    _tmp180 = _tmp173 * _tmp175 + _tmp176 * _tmp177 + _tmp178 * _tmp179
    _tmp181 = 0.384 * _tmp10
    _tmp182 = 0.0825 * _tmp9
    _tmp183 = 0.316 * _tmp13
    _tmp184 = 0.0825 * _tmp1
    _tmp185 = _tmp0 * _tmp184
    _tmp186 = 0.088 * _tmp17
    _tmp187 = 0.088 * _tmp32
    _tmp188 = 0.0825 * _tmp5
    _tmp189 = _tmp188 * _tmp6
    _tmp190 = 0.384 * _tmp12
    _tmp191 = _tmp13 * _tmp190
    _tmp192 = _tmp10 * _tmp188
    _tmp193 = (
        -1.0 * _tmp12 * _tmp182
        - 1.0 * _tmp13 * _tmp192
        + 1.0 * _tmp16 * _tmp186
        - 1.0 * _tmp181 * _tmp9
        + 1.0 * _tmp183 * _tmp5
        - 1.0 * _tmp185
        + 1.0 * _tmp187 * _tmp31
        + 1.0 * _tmp189 * _tmp4
        + 1.0 * _tmp191 * _tmp5
    )
    _tmp194 = _tmp0 * _tmp183
    _tmp195 = _tmp1 * _tmp188
    _tmp196 = _tmp0 * _tmp191
    _tmp197 = 0.0825 * _tmp6
    _tmp198 = _tmp0 * _tmp197
    _tmp199 = _tmp198 * _tmp4
    _tmp200 = 0.0825 * _tmp10
    _tmp201 = _tmp13 * _tmp200
    _tmp202 = _tmp0 * _tmp201
    _tmp203 = 0.0825 * _tmp12
    _tmp204 = (
        -_tmp111 * _tmp181
        - _tmp111 * _tmp203
        + _tmp112 * _tmp186
        + _tmp116 * _tmp187
        - _tmp194
        - _tmp195
        - _tmp196
        - _tmp199
        + _tmp202
    )
    _tmp205 = (
        _in1[0, 0] * _tmp160
        + _in1[1, 0] * _tmp167
        + _in1[2, 0] * _tmp168
        + _tmp157 * _tmp193
        + _tmp159 * _tmp204
    )
    _tmp206 = (
        _in1[0, 0] * _tmp145
        + _in1[1, 0] * _tmp125
        + _in1[2, 0] * _tmp130
        + _tmp109 * _tmp193
        + _tmp124 * _tmp204
    )
    _tmp207 = (
        _in1[0, 0] * _tmp176
        + _in1[1, 0] * _tmp175
        + _in1[2, 0] * _tmp178
        + _tmp193 * _tmp85
        + _tmp204 * _tmp55
    )
    _tmp208 = _tmp10 * _tmp13
    _tmp209 = _tmp208 * _tmp8 + _tmp5 * _tmp71
    _tmp210 = 1.0 * _tmp5 * _tmp63 - 1.0 * _tmp64 * _tmp8
    _tmp211 = _tmp210 * _tmp25 + _tmp5 * _tmp68
    _tmp212 = _tmp18 * _tmp211 - _tmp209 * _tmp33
    _tmp213 = _tmp0 * _tmp71 + _tmp208 * _tmp21
    _tmp214 = 1.0 * _tmp0 * _tmp63 - 1.0 * _tmp21 * _tmp64
    _tmp215 = _tmp0 * _tmp68 + _tmp214 * _tmp25
    _tmp216 = _tmp18 * _tmp215 - _tmp213 * _tmp33
    _tmp217 = -_tmp15 + _tmp4 * _tmp72
    _tmp218 = _tmp2 * _tmp4
    _tmp219 = -1.0 * _tmp28 - 1.0 * _tmp6 * _tmp71
    _tmp220 = _tmp20 * _tmp218 + _tmp219 * _tmp25
    _tmp221 = _tmp18 * _tmp220 - _tmp217 * _tmp33
    _tmp222 = _tmp110 * _tmp216 + _tmp124 * _tmp212 + _tmp163 * _tmp221
    _tmp223 = _tmp18 * _tmp209 + _tmp211 * _tmp33
    _tmp224 = _tmp20 * _tmp210 - _tmp5 * _tmp77
    _tmp225 = -_tmp223 * _tmp36 + _tmp224 * _tmp41
    _tmp226 = _tmp20 * _tmp219 - _tmp218 * _tmp25
    _tmp227 = _tmp18 * _tmp217 + _tmp220 * _tmp33
    _tmp228 = _tmp226 * _tmp41 - _tmp227 * _tmp36
    _tmp229 = -_tmp0 * _tmp77 + _tmp20 * _tmp214
    _tmp230 = _tmp18 * _tmp213 + _tmp215 * _tmp33
    _tmp231 = _tmp229 * _tmp41 - _tmp230 * _tmp36
    _tmp232 = _tmp110 * _tmp231 + _tmp124 * _tmp225 + _tmp163 * _tmp228
    _tmp233 = _tmp226 * _tmp36 + _tmp227 * _tmp41
    _tmp234 = _tmp223 * _tmp41 + _tmp224 * _tmp36
    _tmp235 = _tmp229 * _tmp36 + _tmp230 * _tmp41
    _tmp236 = _tmp110 * _tmp235 + _tmp124 * _tmp234 + _tmp163 * _tmp233
    _tmp237 = _tmp106 * _tmp232 + _tmp140 * _tmp222 + _tmp153 * _tmp236
    _tmp238 = _tmp159 * _tmp212 + _tmp166 * _tmp216 + _tmp172 * _tmp221
    _tmp239 = _tmp159 * _tmp234 + _tmp166 * _tmp235 + _tmp172 * _tmp233
    _tmp240 = _tmp159 * _tmp225 + _tmp166 * _tmp231 + _tmp172 * _tmp228
    _tmp241 = _tmp164 * _tmp239 + _tmp165 * _tmp240 + _tmp169 * _tmp238
    _tmp242 = 1.0 * _tmp85
    _tmp243 = _tmp134 * _tmp221 + _tmp212 * _tmp55 + _tmp216 * _tmp242
    _tmp244 = _tmp134 * _tmp228 + _tmp225 * _tmp55 + _tmp231 * _tmp242
    _tmp245 = _tmp134 * _tmp233 + _tmp234 * _tmp55 + _tmp235 * _tmp242
    _tmp246 = _tmp173 * _tmp244 + _tmp177 * _tmp245 + _tmp179 * _tmp243
    _tmp247 = 0.316 * _tmp4
    _tmp248 = 0.384 * _tmp70
    _tmp249 = _tmp13 * _tmp181
    _tmp250 = _tmp249 * _tmp6
    _tmp251 = (
        -_tmp13 * _tmp189
        + _tmp186 * _tmp209
        + _tmp187 * _tmp211
        + _tmp189 * _tmp64
        - _tmp192 * _tmp4
        + _tmp247 * _tmp5
        + _tmp248 * _tmp5
        + _tmp250 * _tmp5
    )
    _tmp252 = _tmp13 * _tmp198
    _tmp253 = _tmp200 * _tmp4
    _tmp254 = _tmp0 * _tmp13
    _tmp255 = _tmp181 * _tmp254
    _tmp256 = (
        _tmp0 * _tmp247
        + _tmp0 * _tmp248
        - _tmp0 * _tmp253
        + _tmp12 * _tmp252
        + _tmp186 * _tmp213
        + _tmp187 * _tmp215
        - _tmp252
        + _tmp255 * _tmp6
    )
    _tmp257 = _tmp181 * _tmp4
    _tmp258 = (
        -_tmp183
        + _tmp186 * _tmp217
        + _tmp187 * _tmp220
        - _tmp191
        - _tmp197 * _tmp4
        + _tmp197 * _tmp70
        + _tmp201
        + _tmp257 * _tmp6
    )
    _tmp259 = (
        _in1[0, 0] * _tmp236
        + _in1[1, 0] * _tmp232
        + _in1[2, 0] * _tmp222
        + _tmp110 * _tmp256
        + _tmp124 * _tmp251
        + _tmp163 * _tmp258
    )
    _tmp260 = (
        _in1[0, 0] * _tmp245
        + _in1[1, 0] * _tmp244
        + _in1[2, 0] * _tmp243
        + _tmp134 * _tmp258
        + _tmp242 * _tmp256
        + _tmp251 * _tmp55
    )
    _tmp261 = (
        _in1[0, 0] * _tmp239
        + _in1[1, 0] * _tmp240
        + _in1[2, 0] * _tmp238
        + _tmp159 * _tmp251
        + _tmp166 * _tmp256
        + _tmp172 * _tmp258
    )
    _tmp262 = _tmp13 * _tmp7
    _tmp263 = _tmp1 * _tmp15
    _tmp264 = _tmp20 * _tmp262 + _tmp25 * _tmp263
    _tmp265 = _tmp1 * _tmp208
    _tmp266 = -_tmp18 * _tmp265 + _tmp264 * _tmp33
    _tmp267 = _tmp20 * _tmp263 - _tmp25 * _tmp262
    _tmp268 = -_tmp266 * _tmp36 + _tmp267 * _tmp41
    _tmp269 = _tmp10 * _tmp113
    _tmp270 = _tmp113 * _tmp26
    _tmp271 = -_tmp20 * _tmp89 + _tmp25 * _tmp270
    _tmp272 = -_tmp18 * _tmp269 + _tmp271 * _tmp33
    _tmp273 = _tmp20 * _tmp270 + _tmp25 * _tmp89
    _tmp274 = -_tmp272 * _tmp36 + _tmp273 * _tmp41
    _tmp275 = -_tmp21 - _tmp23
    _tmp276 = _tmp26 * _tmp275
    _tmp277 = _tmp101 * _tmp9 + _tmp20 * _tmp276
    _tmp278 = _tmp25 * _tmp276 - _tmp9 * _tmp94
    _tmp279 = _tmp10 * _tmp275
    _tmp280 = -_tmp18 * _tmp279 + _tmp278 * _tmp33
    _tmp281 = _tmp277 * _tmp41 - _tmp280 * _tmp36
    _tmp282 = _tmp110 * _tmp274 + _tmp124 * _tmp281 + _tmp163 * _tmp268
    _tmp283 = _tmp18 * _tmp271 + _tmp269 * _tmp33
    _tmp284 = _tmp18 * _tmp264 + _tmp265 * _tmp33
    _tmp285 = _tmp18 * _tmp278 + _tmp279 * _tmp33
    _tmp286 = _tmp110 * _tmp283 + _tmp124 * _tmp285 + _tmp163 * _tmp284
    _tmp287 = _tmp277 * _tmp36 + _tmp280 * _tmp41
    _tmp288 = _tmp272 * _tmp41 + _tmp273 * _tmp36
    _tmp289 = _tmp266 * _tmp41 + _tmp267 * _tmp36
    _tmp290 = _tmp110 * _tmp288 + _tmp124 * _tmp287 + _tmp163 * _tmp289
    _tmp291 = _tmp106 * _tmp282 + _tmp140 * _tmp286 + _tmp153 * _tmp290
    _tmp292 = _tmp134 * _tmp284 + _tmp242 * _tmp283 + _tmp285 * _tmp55
    _tmp293 = _tmp134 * _tmp268 + _tmp242 * _tmp274 + _tmp281 * _tmp55
    _tmp294 = _tmp134 * _tmp289 + _tmp242 * _tmp288 + _tmp287 * _tmp55
    _tmp295 = _tmp173 * _tmp293 + _tmp177 * _tmp294 + _tmp179 * _tmp292
    _tmp296 = _tmp159 * _tmp285 + _tmp166 * _tmp283 + _tmp172 * _tmp284
    _tmp297 = _tmp159 * _tmp287 + _tmp166 * _tmp288 + _tmp172 * _tmp289
    _tmp298 = _tmp159 * _tmp281 + _tmp166 * _tmp274 + _tmp172 * _tmp268
    _tmp299 = _tmp164 * _tmp297 + _tmp165 * _tmp298 + _tmp169 * _tmp296
    _tmp300 = (
        -_tmp113 * _tmp181
        - _tmp113 * _tmp203
        - _tmp185 * _tmp4
        - _tmp186 * _tmp269
        + _tmp187 * _tmp271
        + _tmp189
    )
    _tmp301 = _tmp13 * _tmp184
    _tmp302 = -_tmp1 * _tmp249 - _tmp12 * _tmp301 - _tmp186 * _tmp265 + _tmp187 * _tmp264 + _tmp301
    _tmp303 = (
        -_tmp181 * _tmp275
        - _tmp186 * _tmp279
        + _tmp187 * _tmp278
        - _tmp195 * _tmp4
        - _tmp198
        - _tmp203 * _tmp275
    )
    _tmp304 = (
        _in1[0, 0] * _tmp290
        + _in1[1, 0] * _tmp282
        + _in1[2, 0] * _tmp286
        + _tmp110 * _tmp300
        + _tmp124 * _tmp303
        + _tmp163 * _tmp302
    )
    _tmp305 = (
        _in1[0, 0] * _tmp297
        + _in1[1, 0] * _tmp298
        + _in1[2, 0] * _tmp296
        + _tmp159 * _tmp303
        + _tmp166 * _tmp300
        + _tmp172 * _tmp302
    )
    _tmp306 = (
        _in1[0, 0] * _tmp294
        + _in1[1, 0] * _tmp293
        + _in1[2, 0] * _tmp292
        + _tmp134 * _tmp302
        + _tmp242 * _tmp300
        + _tmp303 * _tmp55
    )
    _tmp307 = _tmp20 * _tmp36
    _tmp308 = -_tmp27 - _tmp29
    _tmp309 = _tmp127 * _tmp25 + _tmp18 * _tmp308
    _tmp310 = _tmp16 * _tmp307 + _tmp309 * _tmp41
    _tmp311 = _tmp114 - _tmp90
    _tmp312 = _tmp136 * _tmp25 + _tmp18 * _tmp311
    _tmp313 = _tmp307 * _tmp97 + _tmp312 * _tmp41
    _tmp314 = -_tmp63 + _tmp65
    _tmp315 = _tmp132 * _tmp25 + _tmp18 * _tmp314
    _tmp316 = _tmp20 * _tmp73
    _tmp317 = _tmp315 * _tmp41 + _tmp316 * _tmp36
    _tmp318 = _tmp159 * _tmp310 + _tmp166 * _tmp313 + _tmp172 * _tmp317
    _tmp319 = _tmp19 * _tmp25 - _tmp308 * _tmp33
    _tmp320 = _tmp25 * _tmp74 - _tmp314 * _tmp33
    _tmp321 = _tmp25 * _tmp98 - _tmp311 * _tmp33
    _tmp322 = _tmp159 * _tmp319 + _tmp166 * _tmp321 + _tmp172 * _tmp320
    _tmp323 = _tmp20 * _tmp41
    _tmp324 = _tmp16 * _tmp323 - _tmp309 * _tmp36
    _tmp325 = -_tmp312 * _tmp36 + _tmp323 * _tmp97
    _tmp326 = -_tmp315 * _tmp36 + _tmp316 * _tmp41
    _tmp327 = _tmp159 * _tmp324 + _tmp166 * _tmp325 + _tmp172 * _tmp326
    _tmp328 = _tmp164 * _tmp318 + _tmp165 * _tmp327 + _tmp169 * _tmp322
    _tmp329 = _tmp110 * _tmp325 + _tmp124 * _tmp324 + _tmp163 * _tmp326
    _tmp330 = _tmp110 * _tmp313 + _tmp124 * _tmp310 + _tmp163 * _tmp317
    _tmp331 = _tmp110 * _tmp321 + _tmp124 * _tmp319 + _tmp163 * _tmp320
    _tmp332 = _tmp106 * _tmp329 + _tmp140 * _tmp331 + _tmp153 * _tmp330
    _tmp333 = _tmp134 * _tmp326 + _tmp242 * _tmp325 + _tmp324 * _tmp55
    _tmp334 = _tmp134 * _tmp317 + _tmp242 * _tmp313 + _tmp310 * _tmp55
    _tmp335 = _tmp134 * _tmp320 + _tmp242 * _tmp321 + _tmp319 * _tmp55
    _tmp336 = _tmp173 * _tmp333 + _tmp177 * _tmp334 + _tmp179 * _tmp335
    _tmp337 = _tmp187 * _tmp73
    _tmp338 = (
        _tmp186 * _tmp314
        + _tmp191 * _tmp6
        - _tmp201 * _tmp6
        + _tmp25 * _tmp337
        - _tmp257
        - 0.0825 * _tmp70
    )
    _tmp339 = _tmp187 * _tmp97
    _tmp340 = (
        _tmp186 * _tmp311
        - _tmp190 * _tmp88
        + _tmp200 * _tmp88
        - _tmp203 * _tmp254
        + _tmp25 * _tmp339
        - _tmp255
    )
    _tmp341 = _tmp16 * _tmp187
    _tmp342 = (
        _tmp10 * _tmp182
        + _tmp186 * _tmp308
        - _tmp188 * _tmp64
        - _tmp190 * _tmp9
        - _tmp249 * _tmp5
        + _tmp25 * _tmp341
    )
    _tmp343 = (
        _in1[0, 0] * _tmp318
        + _in1[1, 0] * _tmp327
        + _in1[2, 0] * _tmp322
        + _tmp159 * _tmp342
        + _tmp166 * _tmp340
        + _tmp172 * _tmp338
    )
    _tmp344 = (
        _in1[0, 0] * _tmp334
        + _in1[1, 0] * _tmp333
        + _in1[2, 0] * _tmp335
        + _tmp134 * _tmp338
        + _tmp242 * _tmp340
        + _tmp342 * _tmp55
    )
    _tmp345 = (
        _in1[0, 0] * _tmp330
        + _in1[1, 0] * _tmp329
        + _in1[2, 0] * _tmp331
        + _tmp110 * _tmp340
        + _tmp124 * _tmp342
        + _tmp163 * _tmp338
    )
    _tmp346 = -_tmp76 + _tmp77
    _tmp347 = _tmp32 * _tmp41
    _tmp348 = _tmp346 * _tmp347 + _tmp36 * _tmp69
    _tmp349 = -_tmp100 - _tmp102
    _tmp350 = _tmp347 * _tmp349 + _tmp36 * _tmp95
    _tmp351 = -_tmp37 - _tmp38
    _tmp352 = _tmp31 * _tmp36 + _tmp347 * _tmp351
    _tmp353 = _tmp110 * _tmp350 + _tmp124 * _tmp352 + _tmp163 * _tmp348
    _tmp354 = _tmp32 * _tmp36
    _tmp355 = -_tmp346 * _tmp354 + _tmp41 * _tmp69
    _tmp356 = -_tmp349 * _tmp354 + _tmp41 * _tmp95
    _tmp357 = _tmp31 * _tmp41 - _tmp351 * _tmp354
    _tmp358 = _tmp110 * _tmp356 + _tmp124 * _tmp357 + _tmp163 * _tmp355
    _tmp359 = _tmp18 * _tmp351
    _tmp360 = _tmp17 * _tmp346
    _tmp361 = _tmp110 * _tmp17 * _tmp349 + _tmp123 * _tmp359 + _tmp163 * _tmp360
    _tmp362 = _tmp106 * _tmp358 + _tmp140 * _tmp361 + _tmp153 * _tmp353
    _tmp363 = _tmp134 * _tmp355 + _tmp242 * _tmp356 + _tmp357 * _tmp55
    _tmp364 = _tmp18 * _tmp349
    _tmp365 = _tmp17 * _tmp351 * _tmp55 + _tmp18 * _tmp346 * _tmp62 + _tmp364 * _tmp85
    _tmp366 = _tmp134 * _tmp348 + _tmp242 * _tmp350 + _tmp352 * _tmp55
    _tmp367 = _tmp173 * _tmp363 + _tmp177 * _tmp366 + _tmp179 * _tmp365
    _tmp368 = _tmp159 * _tmp357 + _tmp166 * _tmp356 + _tmp172 * _tmp355
    _tmp369 = _tmp159 * _tmp352 + _tmp166 * _tmp350 + _tmp172 * _tmp348
    _tmp370 = _tmp156 * _tmp359 + _tmp157 * _tmp364 + _tmp172 * _tmp360
    _tmp371 = _tmp164 * _tmp369 + _tmp165 * _tmp368 + _tmp169 * _tmp370
    _tmp372 = _tmp187 * _tmp349
    _tmp373 = _tmp187 * _tmp346
    _tmp374 = _tmp187 * _tmp351
    _tmp375 = (
        _in1[0, 0] * _tmp366
        + _in1[1, 0] * _tmp363
        + _in1[2, 0] * _tmp365
        + _tmp372 * _tmp85
        + _tmp373 * _tmp62
        + _tmp374 * _tmp54
    )
    _tmp376 = (
        _in1[0, 0] * _tmp369
        + _in1[1, 0] * _tmp368
        + _in1[2, 0] * _tmp370
        + _tmp156 * _tmp374
        + _tmp157 * _tmp372
        + _tmp171 * _tmp373
    )
    _tmp377 = (
        _in1[0, 0] * _tmp353
        + _in1[1, 0] * _tmp358
        + _in1[2, 0] * _tmp361
        + _tmp109 * _tmp372
        + _tmp123 * _tmp374
        + _tmp162 * _tmp373
    )
    _tmp378 = -_tmp131 + _tmp132
    _tmp379 = _tmp127 - _tmp128
    _tmp380 = _tmp123 * _tmp379
    _tmp381 = -_tmp135 + _tmp136
    _tmp382 = _tmp110 * _tmp381
    _tmp383 = -_tmp162 * _tmp36 * _tmp378 - _tmp35 * _tmp382 - _tmp36 * _tmp380
    _tmp384 = _tmp110 * _tmp99 + _tmp124 * _tmp34 + _tmp163 * _tmp75
    _tmp385 = _tmp378 * _tmp40
    _tmp386 = _tmp163 * _tmp385 + _tmp380 * _tmp41 + _tmp382 * _tmp40
    _tmp387 = _tmp106 * _tmp383 + _tmp140 * _tmp384 + _tmp153 * _tmp386
    _tmp388 = _tmp157 * _tmp381
    _tmp389 = _tmp156 * _tmp379
    _tmp390 = _tmp172 * _tmp385 + _tmp388 * _tmp41 + _tmp389 * _tmp41
    _tmp391 = -_tmp172 * _tmp35 * _tmp378 - _tmp36 * _tmp388 - _tmp36 * _tmp389
    _tmp392 = _tmp159 * _tmp34 + _tmp166 * _tmp99 + _tmp172 * _tmp75
    _tmp393 = _tmp164 * _tmp390 + _tmp165 * _tmp391 + _tmp169 * _tmp392
    _tmp394 = _tmp378 * _tmp62
    _tmp395 = _tmp381 * _tmp85
    _tmp396 = -_tmp36 * _tmp379 * _tmp54 - _tmp36 * _tmp394 - _tmp36 * _tmp395
    _tmp397 = _tmp379 * _tmp40 * _tmp55 + _tmp394 * _tmp41 + _tmp395 * _tmp41
    _tmp398 = _tmp134 * _tmp75 + _tmp242 * _tmp99 + _tmp34 * _tmp55
    _tmp399 = _tmp173 * _tmp396 + _tmp177 * _tmp397 + _tmp179 * _tmp398
    _tmp400 = -_tmp186 * _tmp95 + _tmp339
    _tmp401 = -_tmp186 * _tmp31 + _tmp341
    _tmp402 = -_tmp186 * _tmp69 + _tmp337
    _tmp403 = (
        _in1[0, 0] * _tmp397
        + _in1[1, 0] * _tmp396
        + _in1[2, 0] * _tmp398
        + _tmp134 * _tmp402
        + _tmp242 * _tmp400
        + _tmp401 * _tmp55
    )
    _tmp404 = (
        _in1[0, 0] * _tmp386
        + _in1[1, 0] * _tmp383
        + _in1[2, 0] * _tmp384
        + _tmp110 * _tmp400
        + _tmp124 * _tmp401
        + _tmp163 * _tmp402
    )
    _tmp405 = (
        _in1[0, 0] * _tmp390
        + _in1[1, 0] * _tmp391
        + _in1[2, 0] * _tmp392
        + _tmp159 * _tmp401
        + _tmp166 * _tmp400
        + _tmp172 * _tmp402
    )
    _tmp406 = -_tmp146 - _tmp147
    _tmp407 = -_tmp150 - _tmp151
    _tmp408 = -_tmp142 - _tmp143
    _tmp409 = _tmp134 * _tmp407 + _tmp242 * _tmp406 + _tmp408 * _tmp55
    _tmp410 = _tmp106 * _tmp177 + _tmp173 * _tmp409
    _tmp411 = _tmp110 * _tmp406 + _tmp124 * _tmp408 + _tmp163 * _tmp407
    _tmp412 = _tmp106 * _tmp411 + _tmp153 * _tmp165
    _tmp413 = _tmp159 * _tmp408 + _tmp166 * _tmp406 + _tmp172 * _tmp407
    _tmp414 = _tmp164 * _tmp173 + _tmp165 * _tmp413
    _tmp415 = _in1[0, 0] * _tmp165 + _in1[1, 0] * _tmp411
    _tmp416 = _in1[0, 0] * _tmp106 + _in1[1, 0] * _tmp409
    _tmp417 = _in1[0, 0] * _tmp173 + _in1[1, 0] * _tmp413
    _tmp418 = _in0[7, 0] ** 1.0
    _tmp419 = 4.0 / _tmp47**2
    _tmp420 = _in0[8, 0] * _tmp419
    _tmp421 = _in0[9, 0] * _tmp420
    _tmp422 = -_tmp418 * _tmp421
    _tmp423 = _tmp419 * _tmp45
    _tmp424 = _in0[10, 0] * _tmp423
    _tmp425 = _in0[10, 0] * _tmp49
    _tmp426 = _tmp422 + _tmp424 - _tmp425
    _tmp427 = _tmp418 * _tmp419
    _tmp428 = _tmp120 * _tmp427
    _tmp429 = _tmp427 * _tmp56
    _tmp430 = _tmp428 + _tmp429
    _tmp431 = _tmp420 * _tmp45
    _tmp432 = _in0[10, 0] * _in0[9, 0]
    _tmp433 = -_tmp427 * _tmp432
    _tmp434 = -_tmp431 + _tmp433 + _tmp52
    _tmp435 = 1.0 * _tmp133
    _tmp436 = _tmp138 * _tmp430 + _tmp139 * _tmp426 + _tmp434 * _tmp435
    _tmp437 = _tmp105 * _tmp430 + _tmp174 * _tmp426 + _tmp434 * _tmp80
    _tmp438 = 1.0 * _tmp152
    _tmp439 = _tmp149 * _tmp430 + _tmp158 * _tmp426 + _tmp434 * _tmp438
    _tmp440 = _tmp164 * _tmp439 + _tmp165 * _tmp437 + _tmp169 * _tmp436
    _tmp441 = _tmp427 * _tmp59
    _tmp442 = _tmp429 + _tmp441
    _tmp443 = _tmp431 + _tmp433 - _tmp52
    _tmp444 = _in0[9, 0] * _tmp423
    _tmp445 = _in0[10, 0] * _tmp420
    _tmp446 = -_tmp418 * _tmp445
    _tmp447 = -_tmp444 + _tmp446 + _tmp83
    _tmp448 = _tmp138 * _tmp443 + _tmp139 * _tmp447 + _tmp435 * _tmp442
    _tmp449 = _tmp149 * _tmp443 + _tmp158 * _tmp447 + _tmp438 * _tmp442
    _tmp450 = _tmp105 * _tmp443 + _tmp174 * _tmp447 + _tmp442 * _tmp80
    _tmp451 = _tmp173 * _tmp450 + _tmp177 * _tmp449 + _tmp179 * _tmp448
    _tmp452 = _tmp428 + _tmp441
    _tmp453 = _tmp422 - _tmp424 + _tmp425
    _tmp454 = _tmp444 + _tmp446 - _tmp83
    _tmp455 = _tmp138 * _tmp453 + _tmp139 * _tmp452 + _tmp435 * _tmp454
    _tmp456 = _tmp149 * _tmp453 + _tmp158 * _tmp452 + _tmp438 * _tmp454
    _tmp457 = _tmp105 * _tmp453 + _tmp174 * _tmp452 + _tmp454 * _tmp80
    _tmp458 = _tmp106 * _tmp457 + _tmp140 * _tmp455 + _tmp153 * _tmp456
    _tmp459 = _tmp13 * _tmp197
    _tmp460 = (
        1.0 * _tmp12 * _tmp459
        + 1.0 * _tmp186 * _tmp73
        + 1.0 * _tmp187 * _tmp69
        + 1.0 * _tmp247
        + 1.0 * _tmp248
        + 1.0 * _tmp250
        - 1.0 * _tmp253
        - 1.0 * _tmp459
        + 0.333
    )
    _tmp461 = 1.0 * _in0[11, 0]
    _tmp462 = 1.0 * _in0[12, 0]
    _tmp463 = 1.0 * _in0[13, 0]
    _tmp464 = (
        -1.0 * _tmp181 * _tmp88
        + 1.0 * _tmp186 * _tmp97
        + 1.0 * _tmp187 * _tmp95
        + 1.0 * _tmp194
        + 1.0 * _tmp195
        + 1.0 * _tmp196
        + 1.0 * _tmp199
        - 1.0 * _tmp202
        - 1.0 * _tmp203 * _tmp88
    )
    _tmp465 = (
        _in1[0, 0] * _tmp439
        + _in1[1, 0] * _tmp437
        + _in1[2, 0] * _tmp436
        + _tmp193 * _tmp426
        - _tmp426 * _tmp461
        - _tmp430 * _tmp462
        + _tmp430 * _tmp464
        + _tmp434 * _tmp460
        - _tmp434 * _tmp463
    )
    _tmp466 = (
        _in1[0, 0] * _tmp456
        + _in1[1, 0] * _tmp457
        + _in1[2, 0] * _tmp455
        + _tmp193 * _tmp452
        - _tmp452 * _tmp461
        - _tmp453 * _tmp462
        + _tmp453 * _tmp464
        + _tmp454 * _tmp460
        - _tmp454 * _tmp463
    )
    _tmp467 = (
        _in1[0, 0] * _tmp449
        + _in1[1, 0] * _tmp450
        + _in1[2, 0] * _tmp448
        + _tmp193 * _tmp447
        + _tmp442 * _tmp460
        - _tmp442 * _tmp463
        - _tmp443 * _tmp462
        + _tmp443 * _tmp464
        - _tmp447 * _tmp461
    )
    _tmp468 = _tmp419 * _tmp44
    _tmp469 = _in0[7, 0] * _tmp468
    _tmp470 = _in0[8, 0] ** 1.0
    _tmp471 = _tmp419 * _tmp470
    _tmp472 = -_tmp432 * _tmp471
    _tmp473 = -_tmp469 + _tmp472 + _tmp50
    _tmp474 = _in0[10, 0] * _in0[7, 0]
    _tmp475 = _tmp471 * _tmp474
    _tmp476 = -_in0[9, 0] * _tmp468 + _tmp83
    _tmp477 = _tmp475 + _tmp476
    _tmp478 = _tmp120 * _tmp419
    _tmp479 = _tmp470 * _tmp478
    _tmp480 = 4.0 * _tmp48
    _tmp481 = -_in0[8, 0] * _tmp480 + _in0[8, 0] ** 3.0 * _tmp419
    _tmp482 = _tmp479 + _tmp481
    _tmp483 = _tmp105 * _tmp482 + _tmp174 * _tmp477 + _tmp473 * _tmp80
    _tmp484 = _tmp149 * _tmp482 + _tmp158 * _tmp477 + _tmp438 * _tmp473
    _tmp485 = _tmp138 * _tmp482 + _tmp139 * _tmp477 + _tmp435 * _tmp473
    _tmp486 = _tmp164 * _tmp484 + _tmp165 * _tmp483 + _tmp169 * _tmp485
    _tmp487 = -_tmp475 + _tmp476
    _tmp488 = _in0[7, 0] * _in0[9, 0]
    _tmp489 = _tmp471 * _tmp488
    _tmp490 = -_in0[10, 0] * _tmp468 + _tmp425
    _tmp491 = _tmp489 + _tmp490
    _tmp492 = _tmp419 * _tmp59
    _tmp493 = _tmp470 * _tmp492
    _tmp494 = _tmp479 + _tmp493
    _tmp495 = _tmp138 * _tmp487 + _tmp139 * _tmp494 + _tmp435 * _tmp491
    _tmp496 = _tmp105 * _tmp487 + _tmp174 * _tmp494 + _tmp491 * _tmp80
    _tmp497 = _tmp149 * _tmp487 + _tmp158 * _tmp494 + _tmp438 * _tmp491
    _tmp498 = _tmp106 * _tmp496 + _tmp140 * _tmp495 + _tmp153 * _tmp497
    _tmp499 = -_tmp489 + _tmp490
    _tmp500 = -_tmp50
    _tmp501 = _tmp469 + _tmp472 + _tmp500
    _tmp502 = _tmp481 + _tmp493
    _tmp503 = _tmp149 * _tmp501 + _tmp158 * _tmp499 + _tmp438 * _tmp502
    _tmp504 = _tmp105 * _tmp501 + _tmp174 * _tmp499 + _tmp502 * _tmp80
    _tmp505 = _tmp138 * _tmp501 + _tmp139 * _tmp499 + _tmp435 * _tmp502
    _tmp506 = _tmp173 * _tmp504 + _tmp177 * _tmp503 + _tmp179 * _tmp505
    _tmp507 = (
        _in1[0, 0] * _tmp503
        + _in1[1, 0] * _tmp504
        + _in1[2, 0] * _tmp505
        + _tmp193 * _tmp499
        + _tmp460 * _tmp502
        - _tmp461 * _tmp499
        - _tmp462 * _tmp501
        - _tmp463 * _tmp502
        + _tmp464 * _tmp501
    )
    _tmp508 = (
        _in1[0, 0] * _tmp484
        + _in1[1, 0] * _tmp483
        + _in1[2, 0] * _tmp485
        + _tmp193 * _tmp477
        + _tmp460 * _tmp473
        - _tmp461 * _tmp477
        - _tmp462 * _tmp482
        - _tmp463 * _tmp473
        + _tmp464 * _tmp482
    )
    _tmp509 = (
        _in1[0, 0] * _tmp497
        + _in1[1, 0] * _tmp496
        + _in1[2, 0] * _tmp495
        + _tmp193 * _tmp494
        + _tmp460 * _tmp491
        - _tmp461 * _tmp494
        - _tmp462 * _tmp487
        - _tmp463 * _tmp491
        + _tmp464 * _tmp487
    )
    _tmp510 = _in0[9, 0] ** 1.0
    _tmp511 = _tmp419 * _tmp56
    _tmp512 = _tmp510 * _tmp511
    _tmp513 = -_in0[9, 0] * _tmp480 + _in0[9, 0] ** 3.0 * _tmp419
    _tmp514 = _tmp512 + _tmp513
    _tmp515 = -_tmp445 * _tmp510
    _tmp516 = _tmp419 * _tmp43
    _tmp517 = _in0[7, 0] * _tmp516
    _tmp518 = _tmp50 + _tmp515 - _tmp517
    _tmp519 = _in0[7, 0] * _tmp420
    _tmp520 = _tmp510 * _tmp519
    _tmp521 = -_in0[10, 0] * _tmp516 + _tmp425
    _tmp522 = _tmp520 + _tmp521
    _tmp523 = _tmp105 * _tmp522 + _tmp174 * _tmp518 + _tmp514 * _tmp80
    _tmp524 = _tmp138 * _tmp522 + _tmp139 * _tmp518 + _tmp435 * _tmp514
    _tmp525 = _tmp149 * _tmp522 + _tmp158 * _tmp518 + _tmp438 * _tmp514
    _tmp526 = _tmp173 * _tmp523 + _tmp177 * _tmp525 + _tmp179 * _tmp524
    _tmp527 = _tmp419 * _tmp474 * _tmp510
    _tmp528 = -_tmp420 * _tmp43 + _tmp52
    _tmp529 = -_tmp527 + _tmp528
    _tmp530 = _tmp500 + _tmp515 + _tmp517
    _tmp531 = _tmp478 * _tmp510
    _tmp532 = _tmp513 + _tmp531
    _tmp533 = _tmp138 * _tmp529 + _tmp139 * _tmp532 + _tmp435 * _tmp530
    _tmp534 = _tmp105 * _tmp529 + _tmp174 * _tmp532 + _tmp530 * _tmp80
    _tmp535 = _tmp149 * _tmp529 + _tmp158 * _tmp532 + _tmp438 * _tmp530
    _tmp536 = _tmp106 * _tmp534 + _tmp140 * _tmp533 + _tmp153 * _tmp535
    _tmp537 = _tmp512 + _tmp531
    _tmp538 = _tmp527 + _tmp528
    _tmp539 = -_tmp520 + _tmp521
    _tmp540 = _tmp149 * _tmp537 + _tmp158 * _tmp538 + _tmp438 * _tmp539
    _tmp541 = _tmp138 * _tmp537 + _tmp139 * _tmp538 + _tmp435 * _tmp539
    _tmp542 = _tmp105 * _tmp537 + _tmp174 * _tmp538 + _tmp539 * _tmp80
    _tmp543 = _tmp164 * _tmp540 + _tmp165 * _tmp542 + _tmp169 * _tmp541
    _tmp544 = (
        _in1[0, 0] * _tmp535
        + _in1[1, 0] * _tmp534
        + _in1[2, 0] * _tmp533
        + _tmp193 * _tmp532
        + _tmp460 * _tmp530
        - _tmp461 * _tmp532
        - _tmp462 * _tmp529
        - _tmp463 * _tmp530
        + _tmp464 * _tmp529
    )
    _tmp545 = (
        _in1[0, 0] * _tmp540
        + _in1[1, 0] * _tmp542
        + _in1[2, 0] * _tmp541
        + _tmp193 * _tmp538
        + _tmp460 * _tmp539
        - _tmp461 * _tmp538
        - _tmp462 * _tmp537
        - _tmp463 * _tmp539
        + _tmp464 * _tmp537
    )
    _tmp546 = (
        _in1[0, 0] * _tmp525
        + _in1[1, 0] * _tmp523
        + _in1[2, 0] * _tmp524
        + _tmp193 * _tmp518
        + _tmp460 * _tmp514
        - _tmp461 * _tmp518
        - _tmp462 * _tmp522
        - _tmp463 * _tmp514
        + _tmp464 * _tmp522
    )
    _tmp547 = _tmp419 * _tmp46
    _tmp548 = _in0[7, 0] * _tmp547
    _tmp549 = _in0[10, 0] ** 1.0
    _tmp550 = -_tmp421 * _tmp549
    _tmp551 = _tmp50 - _tmp548 + _tmp550
    _tmp552 = _tmp492 * _tmp549
    _tmp553 = -_in0[10, 0] * _tmp480 + _in0[10, 0] ** 3.0 * _tmp419
    _tmp554 = _tmp552 + _tmp553
    _tmp555 = _tmp419 * _tmp488 * _tmp549
    _tmp556 = -_tmp420 * _tmp46 + _tmp52
    _tmp557 = _tmp555 + _tmp556
    _tmp558 = _tmp138 * _tmp551 + _tmp139 * _tmp554 + _tmp435 * _tmp557
    _tmp559 = _tmp149 * _tmp551 + _tmp158 * _tmp554 + _tmp438 * _tmp557
    _tmp560 = _tmp105 * _tmp551 + _tmp174 * _tmp554 + _tmp557 * _tmp80
    _tmp561 = _tmp106 * _tmp560 + _tmp140 * _tmp558 + _tmp153 * _tmp559
    _tmp562 = _tmp511 * _tmp549
    _tmp563 = _tmp552 + _tmp562
    _tmp564 = -_tmp555 + _tmp556
    _tmp565 = _tmp519 * _tmp549
    _tmp566 = -_in0[9, 0] * _tmp547 + _tmp83
    _tmp567 = _tmp565 + _tmp566
    _tmp568 = _tmp149 * _tmp567 + _tmp158 * _tmp564 + _tmp438 * _tmp563
    _tmp569 = _tmp105 * _tmp567 + _tmp174 * _tmp564 + _tmp563 * _tmp80
    _tmp570 = _tmp138 * _tmp567 + _tmp139 * _tmp564 + _tmp435 * _tmp563
    _tmp571 = _tmp173 * _tmp569 + _tmp177 * _tmp568 + _tmp179 * _tmp570
    _tmp572 = _tmp500 + _tmp548 + _tmp550
    _tmp573 = -_tmp565 + _tmp566
    _tmp574 = _tmp553 + _tmp562
    _tmp575 = _tmp105 * _tmp574 + _tmp174 * _tmp572 + _tmp573 * _tmp80
    _tmp576 = _tmp138 * _tmp574 + _tmp139 * _tmp572 + _tmp435 * _tmp573
    _tmp577 = _tmp149 * _tmp574 + _tmp158 * _tmp572 + _tmp438 * _tmp573
    _tmp578 = _tmp164 * _tmp577 + _tmp165 * _tmp575 + _tmp169 * _tmp576
    _tmp579 = (
        _in1[0, 0] * _tmp559
        + _in1[1, 0] * _tmp560
        + _in1[2, 0] * _tmp558
        + _tmp193 * _tmp554
        + _tmp460 * _tmp557
        - _tmp461 * _tmp554
        - _tmp462 * _tmp551
        - _tmp463 * _tmp557
        + _tmp464 * _tmp551
    )
    _tmp580 = (
        _in1[0, 0] * _tmp568
        + _in1[1, 0] * _tmp569
        + _in1[2, 0] * _tmp570
        + _tmp193 * _tmp564
        + _tmp460 * _tmp563
        - _tmp461 * _tmp564
        - _tmp462 * _tmp567
        - _tmp463 * _tmp563
        + _tmp464 * _tmp567
    )
    _tmp581 = (
        _in1[0, 0] * _tmp577
        + _in1[1, 0] * _tmp575
        + _in1[2, 0] * _tmp576
        + _tmp193 * _tmp572
        + _tmp460 * _tmp573
        - _tmp461 * _tmp572
        - _tmp462 * _tmp574
        - _tmp463 * _tmp573
        + _tmp464 * _tmp574
    )
    _tmp582 = _tmp60 - 1.0
    _tmp583 = _tmp121 + _tmp582
    _tmp584 = -_tmp107
    _tmp585 = _tmp108 + _tmp584
    _tmp586 = -_tmp53
    _tmp587 = _tmp161 + _tmp586
    _tmp588 = -_tmp84
    _tmp589 = _tmp588 + _tmp81
    _tmp590 = _tmp121 + _tmp57 - 1.0
    _tmp591 = _tmp155 + _tmp584
    _tmp592 = _tmp588 + _tmp82
    _tmp593 = _tmp57 + _tmp582
    _tmp594 = _tmp51 + _tmp586

    # Output terms
    _out = casadi.blockcat(
        [
            [
                _tmp123 * _tmp180 + _tmp154 * _tmp156 + _tmp170 * _tmp54,
                _tmp123 * _tmp246 + _tmp156 * _tmp237 + _tmp241 * _tmp54,
                _tmp123 * _tmp295 + _tmp156 * _tmp291 + _tmp299 * _tmp54,
                _tmp123 * _tmp336 + _tmp156 * _tmp332 + _tmp328 * _tmp54,
                _tmp123 * _tmp367 + _tmp156 * _tmp362 + _tmp371 * _tmp54,
                _tmp123 * _tmp399 + _tmp156 * _tmp387 + _tmp393 * _tmp54,
                _tmp123 * _tmp410 + _tmp156 * _tmp412 + _tmp414 * _tmp54,
                _tmp123 * _tmp451 + _tmp156 * _tmp458 + _tmp440 * _tmp54,
                _tmp123 * _tmp506 + _tmp156 * _tmp498 + _tmp486 * _tmp54,
                _tmp123 * _tmp526 + _tmp156 * _tmp536 + _tmp54 * _tmp543,
                _tmp123 * _tmp571 + _tmp156 * _tmp561 + _tmp54 * _tmp578,
                0,
                0,
                0,
            ],
            [
                _tmp109 * _tmp180 + _tmp154 * _tmp157 + _tmp170 * _tmp85,
                _tmp109 * _tmp246 + _tmp157 * _tmp237 + _tmp241 * _tmp85,
                _tmp109 * _tmp295 + _tmp157 * _tmp291 + _tmp299 * _tmp85,
                _tmp109 * _tmp336 + _tmp157 * _tmp332 + _tmp328 * _tmp85,
                _tmp109 * _tmp367 + _tmp157 * _tmp362 + _tmp371 * _tmp85,
                _tmp109 * _tmp399 + _tmp157 * _tmp387 + _tmp393 * _tmp85,
                _tmp109 * _tmp410 + _tmp157 * _tmp412 + _tmp414 * _tmp85,
                _tmp109 * _tmp451 + _tmp157 * _tmp458 + _tmp440 * _tmp85,
                _tmp109 * _tmp506 + _tmp157 * _tmp498 + _tmp486 * _tmp85,
                _tmp109 * _tmp526 + _tmp157 * _tmp536 + _tmp543 * _tmp85,
                _tmp109 * _tmp571 + _tmp157 * _tmp561 + _tmp578 * _tmp85,
                0,
                0,
                0,
            ],
            [
                _tmp154 * _tmp171 + _tmp162 * _tmp180 + _tmp170 * _tmp62,
                _tmp162 * _tmp246 + _tmp171 * _tmp237 + _tmp241 * _tmp62,
                _tmp162 * _tmp295 + _tmp171 * _tmp291 + _tmp299 * _tmp62,
                _tmp162 * _tmp336 + _tmp171 * _tmp332 + _tmp328 * _tmp62,
                _tmp162 * _tmp367 + _tmp171 * _tmp362 + _tmp371 * _tmp62,
                _tmp162 * _tmp399 + _tmp171 * _tmp387 + _tmp393 * _tmp62,
                _tmp162 * _tmp410 + _tmp171 * _tmp412 + _tmp414 * _tmp62,
                _tmp162 * _tmp451 + _tmp171 * _tmp458 + _tmp440 * _tmp62,
                _tmp162 * _tmp506 + _tmp171 * _tmp498 + _tmp486 * _tmp62,
                _tmp162 * _tmp526 + _tmp171 * _tmp536 + _tmp543 * _tmp62,
                _tmp162 * _tmp571 + _tmp171 * _tmp561 + _tmp578 * _tmp62,
                0,
                0,
                0,
            ],
            [
                _tmp123 * _tmp206 + _tmp156 * _tmp205 + _tmp207 * _tmp54,
                _tmp123 * _tmp259 + _tmp156 * _tmp261 + _tmp260 * _tmp54,
                _tmp123 * _tmp304 + _tmp156 * _tmp305 + _tmp306 * _tmp54,
                _tmp123 * _tmp345 + _tmp156 * _tmp343 + _tmp344 * _tmp54,
                _tmp123 * _tmp377 + _tmp156 * _tmp376 + _tmp375 * _tmp54,
                _tmp123 * _tmp404 + _tmp156 * _tmp405 + _tmp403 * _tmp54,
                _tmp123 * _tmp415 + _tmp156 * _tmp417 + _tmp416 * _tmp54,
                _tmp123 * _tmp466 + _tmp156 * _tmp465 + _tmp467 * _tmp54,
                _tmp123 * _tmp509 + _tmp156 * _tmp508 + _tmp507 * _tmp54,
                _tmp123 * _tmp544 + _tmp156 * _tmp545 + _tmp54 * _tmp546,
                _tmp123 * _tmp579 + _tmp156 * _tmp581 + _tmp54 * _tmp580,
                _tmp123 * _tmp583 + _tmp156 * _tmp585 + _tmp54 * _tmp587,
                _tmp123 * _tmp591 + _tmp156 * _tmp590 + _tmp54 * _tmp589,
                _tmp123 * _tmp594 + _tmp156 * _tmp592 + _tmp54 * _tmp593,
            ],
            [
                _tmp109 * _tmp206 + _tmp157 * _tmp205 + _tmp207 * _tmp85,
                _tmp109 * _tmp259 + _tmp157 * _tmp261 + _tmp260 * _tmp85,
                _tmp109 * _tmp304 + _tmp157 * _tmp305 + _tmp306 * _tmp85,
                _tmp109 * _tmp345 + _tmp157 * _tmp343 + _tmp344 * _tmp85,
                _tmp109 * _tmp377 + _tmp157 * _tmp376 + _tmp375 * _tmp85,
                _tmp109 * _tmp404 + _tmp157 * _tmp405 + _tmp403 * _tmp85,
                _tmp109 * _tmp415 + _tmp157 * _tmp417 + _tmp416 * _tmp85,
                _tmp109 * _tmp466 + _tmp157 * _tmp465 + _tmp467 * _tmp85,
                _tmp109 * _tmp509 + _tmp157 * _tmp508 + _tmp507 * _tmp85,
                _tmp109 * _tmp544 + _tmp157 * _tmp545 + _tmp546 * _tmp85,
                _tmp109 * _tmp579 + _tmp157 * _tmp581 + _tmp580 * _tmp85,
                _tmp109 * _tmp583 + _tmp157 * _tmp585 + _tmp587 * _tmp85,
                _tmp109 * _tmp591 + _tmp157 * _tmp590 + _tmp589 * _tmp85,
                _tmp109 * _tmp594 + _tmp157 * _tmp592 + _tmp593 * _tmp85,
            ],
            [
                _tmp162 * _tmp206 + _tmp171 * _tmp205 + _tmp207 * _tmp62,
                _tmp162 * _tmp259 + _tmp171 * _tmp261 + _tmp260 * _tmp62,
                _tmp162 * _tmp304 + _tmp171 * _tmp305 + _tmp306 * _tmp62,
                _tmp162 * _tmp345 + _tmp171 * _tmp343 + _tmp344 * _tmp62,
                _tmp162 * _tmp377 + _tmp171 * _tmp376 + _tmp375 * _tmp62,
                _tmp162 * _tmp404 + _tmp171 * _tmp405 + _tmp403 * _tmp62,
                _tmp162 * _tmp415 + _tmp171 * _tmp417 + _tmp416 * _tmp62,
                _tmp162 * _tmp466 + _tmp171 * _tmp465 + _tmp467 * _tmp62,
                _tmp162 * _tmp509 + _tmp171 * _tmp508 + _tmp507 * _tmp62,
                _tmp162 * _tmp544 + _tmp171 * _tmp545 + _tmp546 * _tmp62,
                _tmp162 * _tmp579 + _tmp171 * _tmp581 + _tmp580 * _tmp62,
                _tmp162 * _tmp583 + _tmp171 * _tmp585 + _tmp587 * _tmp62,
                _tmp162 * _tmp591 + _tmp171 * _tmp590 + _tmp589 * _tmp62,
                _tmp162 * _tmp594 + _tmp171 * _tmp592 + _tmp593 * _tmp62,
            ],
        ]
    )

    return _out


_in0_sx = casadi.SX.sym("_in0", 14, 1)
_in1_sx = casadi.SX.sym("_in1", 3, 1)
spatial_velocity_jacobian_kQDot_panda_link7_box_world = casadi.Function(
    "spatial_velocity_jacobian_kQDot_panda_link7_box_world",
    [_in0_sx, _in1_sx],
    [spatial_velocity_jacobian_kQDot_panda_link7_box_world(_in0_sx, _in1_sx)],
    dict([("cse", True)]),
)
