# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_link5_collision(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix12_3


    """

    # Total ops: 283

    # Input arrays

    # Intermediate terms (66)
    _tmp0 = casadi.sin(_in0[3, 0])
    _tmp1 = casadi.sin(_in0[0, 0])
    _tmp2 = casadi.sin(_in0[2, 0])
    _tmp3 = 1.0 * _tmp2
    _tmp4 = _tmp1 * _tmp3
    _tmp5 = casadi.cos(_in0[1, 0])
    _tmp6 = casadi.cos(_in0[0, 0])
    _tmp7 = casadi.cos(_in0[2, 0])
    _tmp8 = 1.0 * _tmp7
    _tmp9 = _tmp6 * _tmp8
    _tmp10 = -_tmp4 + _tmp5 * _tmp9
    _tmp11 = _tmp0 * _tmp10
    _tmp12 = casadi.sin(_in0[1, 0])
    _tmp13 = casadi.cos(_in0[3, 0])
    _tmp14 = _tmp12 * _tmp13
    _tmp15 = _tmp14 * _tmp6
    _tmp16 = _tmp10 * _tmp13
    _tmp17 = 0.316 * _tmp12
    _tmp18 = 0.0825 * _tmp2
    _tmp19 = _tmp5 * _tmp7
    _tmp20 = 0.0825 * _tmp6
    _tmp21 = _tmp0 * _tmp12
    _tmp22 = (
        -_tmp1 * _tmp18
        - 0.0825 * _tmp16
        + _tmp17 * _tmp6
        + _tmp19 * _tmp20
        - _tmp20 * _tmp21
        - 0.62
    )
    _tmp23 = casadi.cos(_in0[4, 0])
    _tmp24 = _tmp1 * _tmp8
    _tmp25 = _tmp3 * _tmp6
    _tmp26 = _tmp24 + _tmp25 * _tmp5
    _tmp27 = _tmp23 * _tmp26
    _tmp28 = casadi.sin(_in0[4, 0])
    _tmp29 = 1.0 * _tmp21
    _tmp30 = 1.0 * _tmp16 + _tmp29 * _tmp6
    _tmp31 = _tmp28 * _tmp30
    _tmp32 = 0.085 * _tmp28
    _tmp33 = _tmp22 - 0.085 * _tmp27 - _tmp30 * _tmp32
    _tmp34 = 0.08 * _tmp23
    _tmp35 = _tmp22 - _tmp26 * _tmp34 - 0.08 * _tmp31
    _tmp36 = _tmp22 - 0.07 * _tmp27 - 0.07 * _tmp31
    _tmp37 = -0.384 * _tmp11 + 0.384 * _tmp15
    _tmp38 = _tmp1 * _tmp14
    _tmp39 = _tmp24 * _tmp5 + _tmp25
    _tmp40 = _tmp0 * _tmp39
    _tmp41 = 0.0825 * _tmp1
    _tmp42 = _tmp13 * _tmp39
    _tmp43 = _tmp1 * _tmp17 + _tmp18 * _tmp6 + _tmp19 * _tmp41 - _tmp21 * _tmp41 - 0.0825 * _tmp42
    _tmp44 = _tmp1 * _tmp29 + 1.0 * _tmp42
    _tmp45 = _tmp28 * _tmp44
    _tmp46 = _tmp4 * _tmp5 - _tmp9
    _tmp47 = _tmp23 * _tmp46
    _tmp48 = -_tmp32 * _tmp44 + _tmp43 - 0.085 * _tmp47
    _tmp49 = -_tmp34 * _tmp46 + _tmp43 - 0.08 * _tmp45
    _tmp50 = _tmp43 - 0.07 * _tmp45 - 0.07 * _tmp47
    _tmp51 = 0.384 * _tmp38 - 0.384 * _tmp40
    _tmp52 = _tmp13 * _tmp5
    _tmp53 = _tmp12 * _tmp7
    _tmp54 = _tmp0 * _tmp53
    _tmp55 = _tmp0 * _tmp5
    _tmp56 = 0.0825 * _tmp53
    _tmp57 = _tmp13 * _tmp56 + 0.316 * _tmp5 - 0.0825 * _tmp55 - _tmp56 + 0.358
    _tmp58 = -1.0 * _tmp13 * _tmp53 + 1.0 * _tmp55
    _tmp59 = _tmp28 * _tmp58
    _tmp60 = _tmp12 * _tmp2
    _tmp61 = _tmp23 * _tmp60
    _tmp62 = -_tmp32 * _tmp58 + _tmp57 + 0.085 * _tmp61
    _tmp63 = _tmp34 * _tmp60 + _tmp57 - 0.08 * _tmp59
    _tmp64 = _tmp57 - 0.07 * _tmp59 + 0.07 * _tmp61
    _tmp65 = 0.384 * _tmp52 + 0.384 * _tmp54

    # Output terms
    _out = casadi.blockcat(
        [
            [
                -0.144 * _tmp11 + 0.144 * _tmp15 + _tmp22,
                0.144 * _tmp38 - 0.144 * _tmp40 + _tmp43,
                0.144 * _tmp52 + 0.144 * _tmp54 + _tmp57,
            ],
            [
                -0.174 * _tmp11 + 0.174 * _tmp15 + _tmp22,
                0.174 * _tmp38 - 0.174 * _tmp40 + _tmp43,
                0.174 * _tmp52 + 0.174 * _tmp54 + _tmp57,
            ],
            [
                -0.329 * _tmp11 + 0.329 * _tmp15 + _tmp22 - 0.09 * _tmp27 - 0.09 * _tmp31,
                0.329 * _tmp38 - 0.329 * _tmp40 + _tmp43 - 0.09 * _tmp45 - 0.09 * _tmp47,
                0.329 * _tmp52 + 0.329 * _tmp54 + _tmp57 - 0.09 * _tmp59 + 0.09 * _tmp61,
            ],
            [
                -0.304 * _tmp11 + 0.304 * _tmp15 + _tmp33,
                0.304 * _tmp38 - 0.304 * _tmp40 + _tmp48,
                0.304 * _tmp52 + 0.304 * _tmp54 + _tmp62,
            ],
            [
                -0.274 * _tmp11 + 0.274 * _tmp15 + _tmp33,
                0.274 * _tmp38 - 0.274 * _tmp40 + _tmp48,
                0.274 * _tmp52 + 0.274 * _tmp54 + _tmp62,
            ],
            [
                -0.254 * _tmp11 + 0.254 * _tmp15 + _tmp35,
                0.254 * _tmp38 - 0.254 * _tmp40 + _tmp49,
                0.254 * _tmp52 + 0.254 * _tmp54 + _tmp63,
            ],
            [
                -0.234 * _tmp11 + 0.234 * _tmp15 + _tmp35,
                0.234 * _tmp38 - 0.234 * _tmp40 + _tmp49,
                0.234 * _tmp52 + 0.234 * _tmp54 + _tmp63,
            ],
            [
                -0.224 * _tmp11 + 0.224 * _tmp15 + _tmp36,
                0.224 * _tmp38 - 0.224 * _tmp40 + _tmp50,
                0.224 * _tmp52 + 0.224 * _tmp54 + _tmp64,
            ],
            [
                -0.364 * _tmp11 + 0.364 * _tmp15 + _tmp35,
                0.364 * _tmp38 - 0.364 * _tmp40 + _tmp49,
                0.364 * _tmp52 + 0.364 * _tmp54 + _tmp63,
            ],
            [_tmp35 + _tmp37, _tmp49 + _tmp51, _tmp63 + _tmp65],
            [
                -0.184 * _tmp11 + 0.184 * _tmp15 + _tmp22 - 0.05 * _tmp27 - 0.05 * _tmp31,
                0.184 * _tmp38 - 0.184 * _tmp40 + _tmp43 - 0.05 * _tmp45 - 0.05 * _tmp47,
                0.184 * _tmp52 + 0.184 * _tmp54 + _tmp57 - 0.05 * _tmp59 + 0.05 * _tmp61,
            ],
            [_tmp36 + _tmp37, _tmp50 + _tmp51, _tmp64 + _tmp65],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_link5_collision = casadi.Function(
    "panda_link5_collision",
    [_in0_mx],
    [panda_link5_collision(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
