# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import torch


class TensorKwargs(T.TypedDict):
    """
    TypedDict representing args that will be passed to any torch.tensor calls
    """

    device: torch.device
    dtype: torch.dtype


def _broadcast_and_stack(tensors, dim=-1):
    # type: (T.List[torch.Tensor], int) -> torch.Tensor
    """
    broadcast tensors to common shape then stack along new dimension
    """

    broadcast_shape = torch.broadcast_shapes(*(x.size() for x in tensors))
    broadcast_tensors = [x.broadcast_to(broadcast_shape) for x in tensors]

    return torch.stack(broadcast_tensors, dim=dim)


def panda_link5_vision(_in0, tensor_kwargs=None):
    # type: (torch.Tensor, TensorKwargs) -> torch.Tensor
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix12_3

    The types for inputs and outputs above are the shapes of the symbolic matrices this function was
    generated from.  Tensors for both inputs and outputs are expected to have dimensions as follows:

    - (..., N, M) for sf.Matrix types of shape (N, M) where N != 1 and M != 1
    - (..., N) for sf.Matrix types of shape (N, M) where N != 1 and M == 1 (i.e. column vectors)
    - (..., M) for sf.Matrix types of shape (N, M) where N == 1 and M != 1 (i.e. row vectors)
    - (...) for sf.Matrix types of shape (1, 1) and sf.Scalar types

    Where `...` is an arbitrary number of batch dimensions that can be present on the front of input
    tensors.  The outputs will have the same batch dimensions as the inputs.

    The tensor_kwargs argument can be used to set the device and dtype to use.  If not provided, it will
    default to the device and dtype of the first input tensor, or the empty dict if there are no inputs.
    """

    # Total ops: 283

    # Deduce expected tensor device and dtype if not provided
    if tensor_kwargs is None:
        tensor_kwargs = {"device": _in0.device, "dtype": _in0.dtype}

    # Input arrays

    cte_1 = torch.tensor(0.304, **tensor_kwargs)
    cte_2 = torch.tensor(0.234, **tensor_kwargs)
    cte_3 = torch.tensor(0.274, **tensor_kwargs)
    cte_4 = torch.tensor(0.184, **tensor_kwargs)
    cte_5 = torch.tensor(0.07, **tensor_kwargs)
    cte_6 = torch.tensor(1.0, **tensor_kwargs)
    cte_7 = torch.tensor(0.254, **tensor_kwargs)
    cte_8 = torch.tensor(0.085, **tensor_kwargs)
    cte_9 = torch.tensor(0.316, **tensor_kwargs)
    cte_10 = torch.tensor(0.05, **tensor_kwargs)
    cte_11 = torch.tensor(0.358, **tensor_kwargs)
    cte_12 = torch.tensor(-0.62, **tensor_kwargs)
    cte_13 = torch.tensor(0.384, **tensor_kwargs)
    cte_14 = torch.tensor(0.144, **tensor_kwargs)
    cte_15 = torch.tensor(0.0825, **tensor_kwargs)
    cte_16 = torch.tensor(0.08, **tensor_kwargs)
    cte_17 = torch.tensor(0.174, **tensor_kwargs)
    cte_18 = torch.tensor(0.364, **tensor_kwargs)
    cte_19 = torch.tensor(0.09, **tensor_kwargs)
    cte_20 = torch.tensor(0.224, **tensor_kwargs)
    cte_21 = torch.tensor(0.329, **tensor_kwargs)

    # Intermediate terms (66)
    _tmp0 = torch.sin(_in0[..., 3])
    _tmp1 = torch.sin(_in0[..., 0])
    _tmp2 = torch.sin(_in0[..., 2])
    _tmp3 = cte_6 * _tmp2
    _tmp4 = _tmp1 * _tmp3
    _tmp5 = torch.cos(_in0[..., 1])
    _tmp6 = torch.cos(_in0[..., 0])
    _tmp7 = torch.cos(_in0[..., 2])
    _tmp8 = cte_6 * _tmp7
    _tmp9 = _tmp6 * _tmp8
    _tmp10 = -_tmp4 + _tmp5 * _tmp9
    _tmp11 = _tmp0 * _tmp10
    _tmp12 = torch.sin(_in0[..., 1])
    _tmp13 = torch.cos(_in0[..., 3])
    _tmp14 = _tmp12 * _tmp13
    _tmp15 = _tmp14 * _tmp6
    _tmp16 = _tmp10 * _tmp13
    _tmp17 = cte_9 * _tmp12
    _tmp18 = cte_15 * _tmp2
    _tmp19 = _tmp5 * _tmp7
    _tmp20 = cte_15 * _tmp6
    _tmp21 = _tmp0 * _tmp12
    _tmp22 = (
        -_tmp1 * _tmp18
        - cte_15 * _tmp16
        + _tmp17 * _tmp6
        + _tmp19 * _tmp20
        - _tmp20 * _tmp21
        + cte_12
    )
    _tmp23 = torch.cos(_in0[..., 4])
    _tmp24 = _tmp1 * _tmp8
    _tmp25 = _tmp3 * _tmp6
    _tmp26 = _tmp24 + _tmp25 * _tmp5
    _tmp27 = _tmp23 * _tmp26
    _tmp28 = torch.sin(_in0[..., 4])
    _tmp29 = cte_6 * _tmp21
    _tmp30 = cte_6 * _tmp16 + _tmp29 * _tmp6
    _tmp31 = _tmp28 * _tmp30
    _tmp32 = cte_8 * _tmp28
    _tmp33 = _tmp22 - cte_8 * _tmp27 - _tmp30 * _tmp32
    _tmp34 = cte_16 * _tmp23
    _tmp35 = _tmp22 - _tmp26 * _tmp34 - cte_16 * _tmp31
    _tmp36 = (
        _tmp22
        - cte_5 * _tmp27
        - cte_5 * _tmp31
    )
    _tmp37 = (
        -cte_13 * _tmp11
        + cte_13 * _tmp15
    )
    _tmp38 = _tmp1 * _tmp14
    _tmp39 = _tmp24 * _tmp5 + _tmp25
    _tmp40 = _tmp0 * _tmp39
    _tmp41 = cte_15 * _tmp1
    _tmp42 = _tmp13 * _tmp39
    _tmp43 = (
        _tmp1 * _tmp17
        + _tmp18 * _tmp6
        + _tmp19 * _tmp41
        - _tmp21 * _tmp41
        - cte_15 * _tmp42
    )
    _tmp44 = _tmp1 * _tmp29 + cte_6 * _tmp42
    _tmp45 = _tmp28 * _tmp44
    _tmp46 = _tmp4 * _tmp5 - _tmp9
    _tmp47 = _tmp23 * _tmp46
    _tmp48 = -_tmp32 * _tmp44 + _tmp43 - cte_8 * _tmp47
    _tmp49 = -_tmp34 * _tmp46 + _tmp43 - cte_16 * _tmp45
    _tmp50 = (
        _tmp43
        - cte_5 * _tmp45
        - cte_5 * _tmp47
    )
    _tmp51 = (
        cte_13 * _tmp38
        - cte_13 * _tmp40
    )
    _tmp52 = _tmp13 * _tmp5
    _tmp53 = _tmp12 * _tmp7
    _tmp54 = _tmp0 * _tmp53
    _tmp55 = _tmp0 * _tmp5
    _tmp56 = cte_15 * _tmp53
    _tmp57 = (
        _tmp13 * _tmp56
        + cte_9 * _tmp5
        - cte_15 * _tmp55
        - _tmp56
        + cte_11
    )
    _tmp58 = (
        -cte_6 * _tmp13 * _tmp53
        + cte_6 * _tmp55
    )
    _tmp59 = _tmp28 * _tmp58
    _tmp60 = _tmp12 * _tmp2
    _tmp61 = _tmp23 * _tmp60
    _tmp62 = -_tmp32 * _tmp58 + _tmp57 + cte_8 * _tmp61
    _tmp63 = _tmp34 * _tmp60 + _tmp57 - cte_16 * _tmp59
    _tmp64 = (
        _tmp57
        - cte_5 * _tmp59
        + cte_5 * _tmp61
    )
    _tmp65 = (
        cte_13 * _tmp52
        + cte_13 * _tmp54
    )

    # Output terms
    _out = _broadcast_and_stack(
        [
            _broadcast_and_stack(
                [
                    -cte_14 * _tmp11
                    + cte_14 * _tmp15
                    + _tmp22,
                    -cte_17 * _tmp11
                    + cte_17 * _tmp15
                    + _tmp22,
                    -cte_21 * _tmp11
                    + cte_21 * _tmp15
                    + _tmp22
                    - cte_19 * _tmp27
                    - cte_19 * _tmp31,
                    -cte_1 * _tmp11
                    + cte_1 * _tmp15
                    + _tmp33,
                    -cte_3 * _tmp11
                    + cte_3 * _tmp15
                    + _tmp33,
                    -cte_7 * _tmp11
                    + cte_7 * _tmp15
                    + _tmp35,
                    -cte_2 * _tmp11
                    + cte_2 * _tmp15
                    + _tmp35,
                    -cte_20 * _tmp11
                    + cte_20 * _tmp15
                    + _tmp36,
                    -cte_18 * _tmp11
                    + cte_18 * _tmp15
                    + _tmp35,
                    _tmp35 + _tmp37,
                    -cte_4 * _tmp11
                    + cte_4 * _tmp15
                    + _tmp22
                    - cte_10 * _tmp27
                    - cte_10 * _tmp31,
                    _tmp36 + _tmp37,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    cte_14 * _tmp38
                    - cte_14 * _tmp40
                    + _tmp43,
                    cte_17 * _tmp38
                    - cte_17 * _tmp40
                    + _tmp43,
                    cte_21 * _tmp38
                    - cte_21 * _tmp40
                    + _tmp43
                    - cte_19 * _tmp45
                    - cte_19 * _tmp47,
                    cte_1 * _tmp38
                    - cte_1 * _tmp40
                    + _tmp48,
                    cte_3 * _tmp38
                    - cte_3 * _tmp40
                    + _tmp48,
                    cte_7 * _tmp38
                    - cte_7 * _tmp40
                    + _tmp49,
                    cte_2 * _tmp38
                    - cte_2 * _tmp40
                    + _tmp49,
                    cte_20 * _tmp38
                    - cte_20 * _tmp40
                    + _tmp50,
                    cte_18 * _tmp38
                    - cte_18 * _tmp40
                    + _tmp49,
                    _tmp49 + _tmp51,
                    cte_4 * _tmp38
                    - cte_4 * _tmp40
                    + _tmp43
                    - cte_10 * _tmp45
                    - cte_10 * _tmp47,
                    _tmp50 + _tmp51,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    cte_14 * _tmp52
                    + cte_14 * _tmp54
                    + _tmp57,
                    cte_17 * _tmp52
                    + cte_17 * _tmp54
                    + _tmp57,
                    cte_21 * _tmp52
                    + cte_21 * _tmp54
                    + _tmp57
                    - cte_19 * _tmp59
                    + cte_19 * _tmp61,
                    cte_1 * _tmp52
                    + cte_1 * _tmp54
                    + _tmp62,
                    cte_3 * _tmp52
                    + cte_3 * _tmp54
                    + _tmp62,
                    cte_7 * _tmp52
                    + cte_7 * _tmp54
                    + _tmp63,
                    cte_2 * _tmp52
                    + cte_2 * _tmp54
                    + _tmp63,
                    cte_20 * _tmp52
                    + cte_20 * _tmp54
                    + _tmp64,
                    cte_18 * _tmp52
                    + cte_18 * _tmp54
                    + _tmp63,
                    _tmp63 + _tmp65,
                    cte_4 * _tmp52
                    + cte_4 * _tmp54
                    + _tmp57
                    - cte_10 * _tmp59
                    + cte_10 * _tmp61,
                    _tmp64 + _tmp65,
                ],
                dim=-1,
            ),
        ],
        dim=-1,
    )

    return _out
