# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_link3_vision(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix53


    """

    # Total ops: 87

    # Input arrays

    # Intermediate terms (27)
    _tmp0 = casadi.sin(_in0[1, 0])
    _tmp1 = casadi.cos(_in0[0, 0])
    _tmp2 = _tmp0 * _tmp1
    _tmp3 = 0.246 * _tmp0
    _tmp4 = casadi.sin(_in0[0, 0])
    _tmp5 = casadi.cos(_in0[2, 0])
    _tmp6 = 0.03 * _tmp5
    _tmp7 = casadi.sin(_in0[2, 0])
    _tmp8 = _tmp1 * _tmp7
    _tmp9 = casadi.cos(_in0[1, 0])
    _tmp10 = 0.03 * _tmp9
    _tmp11 = _tmp10 * _tmp8 + _tmp4 * _tmp6 + 0.535
    _tmp12 = _tmp4 * _tmp7
    _tmp13 = _tmp5 * _tmp9
    _tmp14 = 0.0825 * _tmp13
    _tmp15 = -_tmp1 * _tmp14 + 0.0825 * _tmp12 - 0.316 * _tmp2
    _tmp16 = 0.06 * _tmp5
    _tmp17 = 0.06 * _tmp9
    _tmp18 = 0.286 * _tmp0
    _tmp19 = 0.04 * _tmp13
    _tmp20 = _tmp0 * _tmp4
    _tmp21 = -_tmp1 * _tmp6 + _tmp10 * _tmp12
    _tmp22 = -_tmp14 * _tmp4 - 0.316 * _tmp20 - 0.0825 * _tmp8
    _tmp23 = _tmp0 * _tmp7
    _tmp24 = 0.03 * _tmp23 + 0.358
    _tmp25 = _tmp0 * _tmp5
    _tmp26 = -0.0825 * _tmp25 + 0.316 * _tmp9

    # Output terms
    _out = casadi.blockcat(
        [
            [0.535 - 0.206 * _tmp2, -0.206 * _tmp20, 0.206 * _tmp9 + 0.358],
            [-_tmp1 * _tmp3 + 0.535, -_tmp3 * _tmp4, 0.246 * _tmp9 + 0.358],
            [_tmp11 + _tmp15, _tmp21 + _tmp22, _tmp24 + _tmp26],
            [
                _tmp15 + _tmp16 * _tmp4 + _tmp17 * _tmp8 + 0.535,
                -_tmp1 * _tmp16 + _tmp12 * _tmp17 + _tmp22,
                0.06 * _tmp23 + _tmp26 + 0.358,
            ],
            [
                -_tmp1 * _tmp18 - _tmp1 * _tmp19 + _tmp11 + 0.04 * _tmp12,
                -_tmp18 * _tmp4 - _tmp19 * _tmp4 + _tmp21 - 0.04 * _tmp8,
                _tmp24 - 0.04 * _tmp25 + 0.286 * _tmp9,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_link3_vision = casadi.Function(
    "panda_link3_vision",
    [_in0_mx],
    [panda_link3_vision(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
