# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_link7_vision(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23


    """

    # Total ops: 161

    # Input arrays

    # Intermediate terms (54)
    _tmp0 = casadi.cos(_in0[3, 0])
    _tmp1 = casadi.sin(_in0[0, 0])
    _tmp2 = casadi.sin(_in0[2, 0])
    _tmp3 = 1.0 * _tmp2
    _tmp4 = _tmp1 * _tmp3
    _tmp5 = casadi.cos(_in0[1, 0])
    _tmp6 = casadi.cos(_in0[0, 0])
    _tmp7 = casadi.cos(_in0[2, 0])
    _tmp8 = 1.0 * _tmp7
    _tmp9 = _tmp6 * _tmp8
    _tmp10 = _tmp4 - _tmp5 * _tmp9
    _tmp11 = 1.0 * _tmp10
    _tmp12 = casadi.sin(_in0[1, 0])
    _tmp13 = casadi.sin(_in0[3, 0])
    _tmp14 = _tmp12 * _tmp13
    _tmp15 = 1.0 * _tmp14
    _tmp16 = 1.0 * casadi.cos(_in0[4, 0])
    _tmp17 = _tmp1 * _tmp8
    _tmp18 = _tmp3 * _tmp6
    _tmp19 = casadi.sin(_in0[4, 0])
    _tmp20 = 1.0 * _tmp19
    _tmp21 = _tmp16 * (_tmp0 * _tmp11 - _tmp15 * _tmp6) - _tmp20 * (-_tmp17 - _tmp18 * _tmp5)
    _tmp22 = casadi.sin(_in0[5, 0])
    _tmp23 = 0.06 * _tmp22
    _tmp24 = 1.0 * _tmp0
    _tmp25 = _tmp12 * _tmp24
    _tmp26 = -_tmp11 * _tmp13 - _tmp25 * _tmp6
    _tmp27 = casadi.cos(_in0[5, 0])
    _tmp28 = 0.06 * _tmp27
    _tmp29 = 0.384 * _tmp13
    _tmp30 = 0.0825 * _tmp0
    _tmp31 = 0.088 * _tmp27
    _tmp32 = 0.316 * _tmp12
    _tmp33 = 0.0825 * _tmp2
    _tmp34 = _tmp5 * _tmp7
    _tmp35 = 0.0825 * _tmp6
    _tmp36 = 0.384 * _tmp0 * _tmp12
    _tmp37 = 0.088 * _tmp22
    _tmp38 = (
        _tmp1 * _tmp33
        - _tmp10 * _tmp29
        - _tmp10 * _tmp30
        + _tmp14 * _tmp35
        + _tmp21 * _tmp31
        + _tmp26 * _tmp37
        - _tmp32 * _tmp6
        - _tmp34 * _tmp35
        - _tmp36 * _tmp6
        + 0.535
    )
    _tmp39 = 0.01 * _tmp22
    _tmp40 = 0.01 * _tmp27
    _tmp41 = -_tmp17 * _tmp5 - _tmp18
    _tmp42 = 1.0 * _tmp41
    _tmp43 = -_tmp1 * _tmp25 - _tmp13 * _tmp42
    _tmp44 = _tmp16 * (_tmp0 * _tmp42 - _tmp1 * _tmp15) - _tmp20 * (-_tmp4 * _tmp5 + _tmp9)
    _tmp45 = _tmp22 * _tmp44
    _tmp46 = 0.0825 * _tmp1
    _tmp47 = (
        -_tmp1 * _tmp32
        - _tmp1 * _tmp36
        + _tmp14 * _tmp46
        - _tmp29 * _tmp41
        - _tmp30 * _tmp41
        + _tmp31 * _tmp44
        - _tmp33 * _tmp6
        - _tmp34 * _tmp46
        + _tmp37 * _tmp43
    )
    _tmp48 = _tmp13 * _tmp5
    _tmp49 = _tmp12 * _tmp7
    _tmp50 = _tmp12 * _tmp19 * _tmp3 + _tmp16 * (-_tmp24 * _tmp49 + 1.0 * _tmp48)
    _tmp51 = _tmp0 * _tmp5
    _tmp52 = 1.0 * _tmp13 * _tmp49 + 1.0 * _tmp51
    _tmp53 = (
        _tmp29 * _tmp49
        + _tmp30 * _tmp49
        + _tmp31 * _tmp50
        + _tmp37 * _tmp52
        - 0.0825 * _tmp48
        - 0.0825 * _tmp49
        + 0.316 * _tmp5
        + 0.384 * _tmp51
        + 0.358
    )

    # Output terms
    _out = casadi.blockcat(
        [
            [
                _tmp21 * _tmp23 - _tmp26 * _tmp28 + _tmp38,
                -_tmp28 * _tmp43 + 0.06 * _tmp45 + _tmp47,
                _tmp23 * _tmp50 - _tmp28 * _tmp52 + _tmp53,
            ],
            [
                _tmp21 * _tmp39 - _tmp26 * _tmp40 + _tmp38,
                -_tmp40 * _tmp43 + 0.01 * _tmp45 + _tmp47,
                _tmp39 * _tmp50 - _tmp40 * _tmp52 + _tmp53,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_link7_vision = casadi.Function(
    "panda_link7_vision",
    [_in0_mx],
    [panda_link7_vision(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
