# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_link4_vision(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix73


    """

    # Total ops: 185

    # Input arrays

    # Intermediate terms (47)
    _tmp0 = casadi.sin(_in0[0, 0])
    _tmp1 = casadi.cos(_in0[2, 0])
    _tmp2 = _tmp0 * _tmp1
    _tmp3 = casadi.cos(_in0[0, 0])
    _tmp4 = casadi.cos(_in0[1, 0])
    _tmp5 = casadi.sin(_in0[2, 0])
    _tmp6 = _tmp4 * _tmp5
    _tmp7 = 0.06 * _tmp6
    _tmp8 = casadi.sin(_in0[1, 0])
    _tmp9 = 0.316 * _tmp8
    _tmp10 = 0.0825 * _tmp5
    _tmp11 = _tmp1 * _tmp3
    _tmp12 = 0.0825 * _tmp4
    _tmp13 = _tmp0 * _tmp10 - _tmp11 * _tmp12 - _tmp3 * _tmp9 + 0.535
    _tmp14 = _tmp3 * _tmp6
    _tmp15 = casadi.sin(_in0[3, 0])
    _tmp16 = 1.0 * _tmp5
    _tmp17 = 1.0 * _tmp4
    _tmp18 = _tmp0 * _tmp16 - _tmp11 * _tmp17
    _tmp19 = _tmp15 * _tmp18
    _tmp20 = casadi.cos(_in0[3, 0])
    _tmp21 = _tmp18 * _tmp20
    _tmp22 = 0.04 * _tmp6
    _tmp23 = _tmp3 * _tmp8
    _tmp24 = _tmp20 * _tmp23
    _tmp25 = 0.035 * _tmp15
    _tmp26 = 0.05 * _tmp15
    _tmp27 = 0.0825 * _tmp8
    _tmp28 = _tmp15 * _tmp27
    _tmp29 = _tmp13 - 0.0825 * _tmp21 + _tmp28 * _tmp3
    _tmp30 = -_tmp0 * _tmp9 - _tmp10 * _tmp3 - _tmp12 * _tmp2
    _tmp31 = _tmp0 * _tmp6
    _tmp32 = _tmp0 * _tmp8
    _tmp33 = _tmp20 * _tmp32
    _tmp34 = -_tmp16 * _tmp3 - _tmp17 * _tmp2
    _tmp35 = _tmp15 * _tmp34
    _tmp36 = _tmp20 * _tmp34
    _tmp37 = _tmp0 * _tmp28 + _tmp30 - 0.0825 * _tmp36
    _tmp38 = _tmp5 * _tmp8
    _tmp39 = _tmp1 * _tmp27
    _tmp40 = -_tmp39 + 0.316 * _tmp4 + 0.358
    _tmp41 = _tmp15 * _tmp4
    _tmp42 = _tmp20 * _tmp4
    _tmp43 = _tmp1 * _tmp8
    _tmp44 = _tmp20 * _tmp43
    _tmp45 = _tmp15 * _tmp43
    _tmp46 = _tmp20 * _tmp39 + _tmp40 - 0.0825 * _tmp41

    # Output terms
    _out = casadi.blockcat(
        [
            [
                _tmp13 - 0.06 * _tmp2 - _tmp3 * _tmp7,
                -_tmp0 * _tmp7 + 0.06 * _tmp11 + _tmp30,
                -0.06 * _tmp38 + _tmp40,
            ],
            [
                _tmp13 - 0.03 * _tmp14 - 0.03 * _tmp2,
                0.03 * _tmp11 + _tmp30 - 0.03 * _tmp31,
                -0.03 * _tmp38 + _tmp40,
            ],
            [
                _tmp13
                - 0.03 * _tmp19
                - 0.04 * _tmp2
                - 0.035 * _tmp21
                - _tmp22 * _tmp3
                + _tmp23 * _tmp25
                - 0.03 * _tmp24,
                -_tmp0 * _tmp22
                + 0.04 * _tmp11
                + _tmp25 * _tmp32
                + _tmp30
                - 0.03 * _tmp33
                - 0.03 * _tmp35
                - 0.035 * _tmp36,
                -0.04 * _tmp38
                + _tmp40
                - 0.035 * _tmp41
                + 0.03 * _tmp42
                + 0.035 * _tmp44
                + 0.03 * _tmp45,
            ],
            [
                _tmp13
                - 0.01 * _tmp14
                - 0.04 * _tmp19
                - 0.01 * _tmp2
                - 0.05 * _tmp21
                + _tmp23 * _tmp26
                - 0.04 * _tmp24,
                0.01 * _tmp11
                + _tmp26 * _tmp32
                + _tmp30
                - 0.01 * _tmp31
                - 0.04 * _tmp33
                - 0.04 * _tmp35
                - 0.05 * _tmp36,
                -0.01 * _tmp38
                + _tmp40
                - 0.05 * _tmp41
                + 0.04 * _tmp42
                + 0.05 * _tmp44
                + 0.04 * _tmp45,
            ],
            [_tmp13, _tmp30, _tmp40],
            [
                -0.064 * _tmp19 - 0.064 * _tmp24 + _tmp29,
                -0.064 * _tmp33 - 0.064 * _tmp35 + _tmp37,
                0.064 * _tmp42 + 0.064 * _tmp45 + _tmp46,
            ],
            [
                -0.104 * _tmp19 - 0.104 * _tmp24 + _tmp29,
                -0.104 * _tmp33 - 0.104 * _tmp35 + _tmp37,
                0.104 * _tmp42 + 0.104 * _tmp45 + _tmp46,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_link4_vision = casadi.Function(
    "panda_link4_vision",
    [_in0_mx],
    [panda_link4_vision(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
