# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_hand_vision(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix93


    """

    # Total ops: 354

    # Input arrays

    # Intermediate terms (112)
    _tmp0 = casadi.cos(_in0[5, 0])
    _tmp1 = casadi.sin(_in0[0, 0])
    _tmp2 = casadi.sin(_in0[2, 0])
    _tmp3 = 1.0 * _tmp2
    _tmp4 = _tmp1 * _tmp3
    _tmp5 = casadi.cos(_in0[1, 0])
    _tmp6 = casadi.cos(_in0[0, 0])
    _tmp7 = casadi.cos(_in0[2, 0])
    _tmp8 = 1.0 * _tmp7
    _tmp9 = _tmp6 * _tmp8
    _tmp10 = -_tmp4 + _tmp5 * _tmp9
    _tmp11 = casadi.sin(_in0[3, 0])
    _tmp12 = 1.0 * _tmp11
    _tmp13 = casadi.sin(_in0[1, 0])
    _tmp14 = casadi.cos(_in0[3, 0])
    _tmp15 = 1.0 * _tmp14
    _tmp16 = _tmp13 * _tmp15
    _tmp17 = -_tmp10 * _tmp12 + _tmp16 * _tmp6
    _tmp18 = _tmp0 * _tmp17
    _tmp19 = casadi.sin(_in0[4, 0])
    _tmp20 = _tmp1 * _tmp8
    _tmp21 = _tmp3 * _tmp6
    _tmp22 = 1.0 * _tmp20 + 1.0 * _tmp21 * _tmp5
    _tmp23 = casadi.cos(_in0[4, 0])
    _tmp24 = _tmp12 * _tmp13
    _tmp25 = 1.0 * _tmp10 * _tmp15 + 1.0 * _tmp24 * _tmp6
    _tmp26 = -_tmp19 * _tmp22 + _tmp23 * _tmp25
    _tmp27 = casadi.sin(_in0[5, 0])
    _tmp28 = 0.122 * _tmp27
    _tmp29 = 0.384 * _tmp11
    _tmp30 = 0.0825 * _tmp14
    _tmp31 = 0.316 * _tmp13
    _tmp32 = 0.0825 * _tmp2
    _tmp33 = 0.088 * _tmp27
    _tmp34 = 0.088 * _tmp0
    _tmp35 = _tmp5 * _tmp7
    _tmp36 = 0.0825 * _tmp6
    _tmp37 = 0.384 * _tmp14
    _tmp38 = _tmp13 * _tmp37
    _tmp39 = _tmp11 * _tmp13
    _tmp40 = (
        -_tmp1 * _tmp32
        - _tmp10 * _tmp29
        - _tmp10 * _tmp30
        + _tmp17 * _tmp33
        + _tmp26 * _tmp34
        + _tmp31 * _tmp6
        + _tmp35 * _tmp36
        - _tmp36 * _tmp39
        + _tmp38 * _tmp6
        - 0.62
    )
    _tmp41 = casadi.sin(_in0[6, 0])
    _tmp42 = 1.0 * _tmp27
    _tmp43 = 1.0 * _tmp0
    _tmp44 = _tmp17 * _tmp42 + _tmp26 * _tmp43
    _tmp45 = 0.0424264068712119 * _tmp44
    _tmp46 = _tmp41 * _tmp45
    _tmp47 = casadi.cos(_in0[6, 0])
    _tmp48 = 0.0424264068711738 * _tmp44
    _tmp49 = _tmp47 * _tmp48
    _tmp50 = _tmp19 * _tmp25 + _tmp22 * _tmp23
    _tmp51 = _tmp47 * _tmp50
    _tmp52 = 0.0424264068712119 * _tmp51
    _tmp53 = 0.0424264068711738 * _tmp50
    _tmp54 = _tmp41 * _tmp53
    _tmp55 = _tmp46 - _tmp49 - _tmp52 - _tmp54
    _tmp56 = _tmp26 * _tmp27
    _tmp57 = -0.137 * _tmp18 + _tmp40 + 0.137 * _tmp56
    _tmp58 = -0.207 * _tmp18 + _tmp40 + 0.207 * _tmp56
    _tmp59 = 0.0212132034355869 * _tmp41
    _tmp60 = 0.0212132034356059 * _tmp47
    _tmp61 = 0.0212132034356059 * _tmp41
    _tmp62 = 0.0636396103067607 * _tmp41
    _tmp63 = 0.0636396103068178 * _tmp47
    _tmp64 = 0.0636396103068178 * _tmp41
    _tmp65 = 0.0848528137423477 * _tmp41
    _tmp66 = 0.0848528137424237 * _tmp47
    _tmp67 = 0.0848528137424237 * _tmp41
    _tmp68 = _tmp20 * _tmp5 + _tmp21
    _tmp69 = 1.0 * _tmp1 * _tmp24 + 1.0 * _tmp15 * _tmp68
    _tmp70 = 1.0 * _tmp4 * _tmp5 - 1.0 * _tmp9
    _tmp71 = -_tmp19 * _tmp70 + _tmp23 * _tmp69
    _tmp72 = _tmp27 * _tmp71
    _tmp73 = _tmp1 * _tmp16 - _tmp12 * _tmp68
    _tmp74 = _tmp0 * _tmp73
    _tmp75 = 0.0825 * _tmp1
    _tmp76 = (
        _tmp1 * _tmp31
        + _tmp1 * _tmp38
        - _tmp29 * _tmp68
        - _tmp30 * _tmp68
        + _tmp32 * _tmp6
        + _tmp33 * _tmp73
        + _tmp34 * _tmp71
        + _tmp35 * _tmp75
        - _tmp39 * _tmp75
    )
    _tmp77 = _tmp42 * _tmp73 + _tmp43 * _tmp71
    _tmp78 = 0.0424264068712119 * _tmp77
    _tmp79 = _tmp41 * _tmp78
    _tmp80 = 0.0424264068711738 * _tmp77
    _tmp81 = _tmp47 * _tmp80
    _tmp82 = _tmp19 * _tmp69 + _tmp23 * _tmp70
    _tmp83 = _tmp41 * _tmp82
    _tmp84 = 0.0424264068711738 * _tmp83
    _tmp85 = _tmp47 * _tmp82
    _tmp86 = 0.0424264068712119 * _tmp85
    _tmp87 = _tmp79 - _tmp81 - _tmp84 - _tmp86
    _tmp88 = 0.137 * _tmp72 - 0.137 * _tmp74 + _tmp76
    _tmp89 = 0.207 * _tmp72 - 0.207 * _tmp74 + _tmp76
    _tmp90 = _tmp11 * _tmp5
    _tmp91 = _tmp13 * _tmp7
    _tmp92 = -1.0 * _tmp15 * _tmp91 + 1.0 * _tmp90
    _tmp93 = _tmp13 * _tmp3
    _tmp94 = _tmp19 * _tmp93 + _tmp23 * _tmp92
    _tmp95 = _tmp12 * _tmp91 + _tmp15 * _tmp5
    _tmp96 = _tmp0 * _tmp95
    _tmp97 = (
        _tmp29 * _tmp91
        + _tmp30 * _tmp91
        + _tmp33 * _tmp95
        + _tmp34 * _tmp94
        + _tmp37 * _tmp5
        + 0.316 * _tmp5
        - 0.0825 * _tmp90
        - 0.0825 * _tmp91
        + 0.358
    )
    _tmp98 = _tmp42 * _tmp95 + _tmp43 * _tmp94
    _tmp99 = 0.0424264068711738 * _tmp98
    _tmp100 = _tmp47 * _tmp99
    _tmp101 = 0.0424264068712119 * _tmp98
    _tmp102 = _tmp101 * _tmp41
    _tmp103 = _tmp19 * _tmp92 - _tmp23 * _tmp93
    _tmp104 = _tmp103 * _tmp47
    _tmp105 = 0.0424264068712119 * _tmp104
    _tmp106 = _tmp103 * _tmp41
    _tmp107 = 0.0424264068711738 * _tmp106
    _tmp108 = -_tmp100 + _tmp102 - _tmp105 - _tmp107
    _tmp109 = _tmp27 * _tmp94
    _tmp110 = 0.137 * _tmp109 - 0.137 * _tmp96 + _tmp97
    _tmp111 = 0.207 * _tmp109 - 0.207 * _tmp96 + _tmp97

    # Output terms
    _out = casadi.blockcat(
        [
            [
                -0.122 * _tmp18 + _tmp26 * _tmp28 + _tmp40 + _tmp55,
                0.122 * _tmp72 - 0.122 * _tmp74 + _tmp76 + _tmp87,
                _tmp108 + _tmp28 * _tmp94 - 0.122 * _tmp96 + _tmp97,
            ],
            [_tmp55 + _tmp57, _tmp87 + _tmp88, _tmp108 + _tmp110],
            [_tmp57, _tmp88, _tmp110],
            [
                -_tmp46 + _tmp49 + _tmp52 + _tmp54 + _tmp57,
                -_tmp79 + _tmp81 + _tmp84 + _tmp86 + _tmp88,
                _tmp100 - _tmp102 + _tmp105 + _tmp107 + _tmp110,
            ],
            [_tmp58, _tmp89, _tmp111],
            [
                -_tmp44 * _tmp59
                - _tmp44 * _tmp60
                - _tmp50 * _tmp61
                + 0.0212132034355869 * _tmp51
                + _tmp58,
                -_tmp59 * _tmp77
                - _tmp60 * _tmp77
                - _tmp61 * _tmp82
                + 0.0212132034355869 * _tmp85
                + _tmp89,
                -_tmp103 * _tmp61
                + 0.0212132034355869 * _tmp104
                + _tmp111
                - _tmp59 * _tmp98
                - _tmp60 * _tmp98,
            ],
            [
                -_tmp41 * _tmp48
                - 0.0424264068712119 * _tmp41 * _tmp50
                - _tmp45 * _tmp47
                + _tmp47 * _tmp53
                + _tmp58,
                -_tmp41 * _tmp80
                - _tmp47 * _tmp78
                - 0.0424264068712119 * _tmp83
                + 0.0424264068711738 * _tmp85
                + _tmp89,
                -_tmp101 * _tmp47
                + 0.0424264068711738 * _tmp104
                - 0.0424264068712119 * _tmp106
                + _tmp111
                - _tmp41 * _tmp99,
            ],
            [
                -_tmp44 * _tmp62
                - _tmp44 * _tmp63
                - _tmp50 * _tmp64
                + 0.0636396103067607 * _tmp51
                + _tmp58,
                -_tmp62 * _tmp77
                - _tmp63 * _tmp77
                - _tmp64 * _tmp82
                + 0.0636396103067607 * _tmp85
                + _tmp89,
                -_tmp103 * _tmp64
                + 0.0636396103067607 * _tmp104
                + _tmp111
                - _tmp62 * _tmp98
                - _tmp63 * _tmp98,
            ],
            [
                -_tmp44 * _tmp65
                - _tmp44 * _tmp66
                - _tmp50 * _tmp67
                + 0.0848528137423477 * _tmp51
                + _tmp58,
                -_tmp65 * _tmp77
                - _tmp66 * _tmp77
                - _tmp67 * _tmp82
                + 0.0848528137423477 * _tmp85
                + _tmp89,
                -_tmp103 * _tmp67
                + 0.0848528137423477 * _tmp104
                + _tmp111
                - _tmp65 * _tmp98
                - _tmp66 * _tmp98,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_hand_vision = casadi.Function(
    "panda_hand_vision",
    [_in0_mx],
    [panda_hand_vision(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
