# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import torch


class TensorKwargs(T.TypedDict):
    """
    TypedDict representing args that will be passed to any torch.tensor calls
    """

    device: torch.device
    dtype: torch.dtype


def _broadcast_and_stack(tensors, dim=-1):
    # type: (T.List[torch.Tensor], int) -> torch.Tensor
    """
    broadcast tensors to common shape then stack along new dimension
    """

    broadcast_shape = torch.broadcast_shapes(*(x.size() for x in tensors))
    broadcast_tensors = [x.broadcast_to(broadcast_shape) for x in tensors]

    return torch.stack(broadcast_tensors, dim=dim)


def all_geometries(_in0, tensor_kwargs=None):
    # type: (torch.Tensor, TensorKwargs) -> torch.Tensor
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix72_3

    The types for inputs and outputs above are the shapes of the symbolic matrices this function was
    generated from.  Tensors for both inputs and outputs are expected to have dimensions as follows:

    - (..., N, M) for sf.Matrix types of shape (N, M) where N != 1 and M != 1
    - (..., N) for sf.Matrix types of shape (N, M) where N != 1 and M == 1 (i.e. column vectors)
    - (..., M) for sf.Matrix types of shape (N, M) where N == 1 and M != 1 (i.e. row vectors)
    - (...) for sf.Matrix types of shape (1, 1) and sf.Scalar types

    Where `...` is an arbitrary number of batch dimensions that can be present on the front of input
    tensors.  The outputs will have the same batch dimensions as the inputs.

    The tensor_kwargs argument can be used to set the device and dtype to use.  If not provided, it will
    default to the device and dtype of the first input tensor, or the empty dict if there are no inputs.
    """

    # Total ops: 1023

    # Deduce expected tensor device and dtype if not provided
    if tensor_kwargs is None:
        tensor_kwargs = {"device": _in0.device, "dtype": _in0.dtype}

    # Input arrays

    cte_1 = torch.tensor(0.136, **tensor_kwargs)
    cte_2 = torch.tensor(0.0424264068711738, **tensor_kwargs)
    cte_3 = torch.tensor(0.535, **tensor_kwargs)
    cte_4 = torch.tensor(0.07, **tensor_kwargs)
    cte_5 = torch.tensor(0.137, **tensor_kwargs)
    cte_6 = torch.tensor(0.515, **tensor_kwargs)
    cte_7 = torch.tensor(0.274, **tensor_kwargs)
    cte_8 = torch.tensor(0.122, **tensor_kwargs)
    cte_9 = torch.tensor(0.171, **tensor_kwargs)
    cte_10 = torch.tensor(0.384, **tensor_kwargs)
    cte_11 = torch.tensor(0.1954, **tensor_kwargs)
    cte_12 = torch.tensor(0.358, **tensor_kwargs)
    cte_13 = torch.tensor(0.087, **tensor_kwargs)
    cte_14 = torch.tensor(0.0106066017177935, **tensor_kwargs)
    cte_15 = torch.tensor(0.138, **tensor_kwargs)
    cte_16 = torch.tensor(0.05, **tensor_kwargs)
    cte_17 = torch.tensor(0.085, **tensor_kwargs)
    cte_18 = torch.tensor(0.207, **tensor_kwargs)
    cte_19 = torch.tensor(0.364, **tensor_kwargs)
    cte_20 = torch.tensor(0.198, **tensor_kwargs)
    cte_21 = torch.tensor(0.595, **tensor_kwargs)
    cte_22 = torch.tensor(0.0424264068712119, **tensor_kwargs)
    cte_23 = torch.tensor(0.525, **tensor_kwargs)
    cte_24 = torch.tensor(0.0825, **tensor_kwargs)
    cte_25 = torch.tensor(0.565, **tensor_kwargs)
    cte_26 = torch.tensor(0.0212132034356059, **tensor_kwargs)
    cte_27 = torch.tensor(0.0, **tensor_kwargs)
    cte_28 = torch.tensor(0.228, **tensor_kwargs)
    cte_29 = torch.tensor(0.0212132034355869, **tensor_kwargs)
    cte_30 = torch.tensor(0.0636396103068178, **tensor_kwargs)
    cte_31 = torch.tensor(-0.05, **tensor_kwargs)
    cte_32 = torch.tensor(0.304, **tensor_kwargs)
    cte_33 = torch.tensor(0.234, **tensor_kwargs)
    cte_34 = torch.tensor(0.0848528137423477, **tensor_kwargs)
    cte_35 = torch.tensor(0.144, **tensor_kwargs)
    cte_36 = torch.tensor(1.0, **tensor_kwargs)
    cte_37 = torch.tensor(0.70710678118623, **tensor_kwargs)
    cte_38 = torch.tensor(0.06, **tensor_kwargs)
    cte_39 = torch.tensor(0.03, **tensor_kwargs)
    cte_40 = torch.tensor(0.329, **tensor_kwargs)
    cte_41 = torch.tensor(0.064, **tensor_kwargs)
    cte_42 = torch.tensor(0.707106781186865, **tensor_kwargs)
    cte_43 = torch.tensor(0.107, **tensor_kwargs)
    cte_44 = torch.tensor(0.09, **tensor_kwargs)
    cte_45 = torch.tensor(0.286, **tensor_kwargs)
    cte_46 = torch.tensor(0.00494974746830361, **tensor_kwargs)
    cte_47 = torch.tensor(0.0636396103067607, **tensor_kwargs)
    cte_48 = torch.tensor(0.01, **tensor_kwargs)
    cte_49 = torch.tensor(0.184, **tensor_kwargs)
    cte_50 = torch.tensor(0.104, **tensor_kwargs)
    cte_51 = torch.tensor(0.224, **tensor_kwargs)
    cte_52 = torch.tensor(0.0848528137424237, **tensor_kwargs)
    cte_53 = torch.tensor(0.108, **tensor_kwargs)
    cte_54 = torch.tensor(0.065, **tensor_kwargs)
    cte_55 = torch.tensor(0.298, **tensor_kwargs)
    cte_56 = torch.tensor(0.075, **tensor_kwargs)
    cte_57 = torch.tensor(0.254, **tensor_kwargs)
    cte_58 = torch.tensor(0.035, **tensor_kwargs)
    cte_59 = torch.tensor(0.010606601717803, **tensor_kwargs)
    cte_60 = torch.tensor(0.00494974746830805, **tensor_kwargs)
    cte_61 = torch.tensor(0.206, **tensor_kwargs)
    cte_62 = torch.tensor(0.246, **tensor_kwargs)
    cte_63 = torch.tensor(0.04, **tensor_kwargs)
    cte_64 = torch.tensor(0.316, **tensor_kwargs)
    cte_65 = torch.tensor(0.168, **tensor_kwargs)
    cte_66 = torch.tensor(0.2104, **tensor_kwargs)
    cte_67 = torch.tensor(0.08, **tensor_kwargs)
    cte_68 = torch.tensor(0.655, **tensor_kwargs)
    cte_69 = torch.tensor(0.625, **tensor_kwargs)
    cte_70 = torch.tensor(0.042, **tensor_kwargs)
    cte_71 = torch.tensor(0.174, **tensor_kwargs)
    cte_72 = torch.tensor(0.088, **tensor_kwargs)

    # Intermediate terms (232)
    _tmp0 = torch.sin(_in0[..., 0])
    _tmp1 = cte_63 * _tmp0
    _tmp2 = cte_56 * _tmp0
    _tmp3 = cte_58 * _tmp0
    _tmp4 = torch.cos(_in0[..., 0])
    _tmp5 = torch.sin(_in0[..., 1])
    _tmp6 = cte_9 * _tmp5
    _tmp7 = cte_1 * _tmp5
    _tmp8 = cte_4 * _tmp5
    _tmp9 = cte_61 * _tmp5
    _tmp10 = cte_62 * _tmp5
    _tmp11 = cte_64 * _tmp5
    _tmp12 = torch.sin(_in0[..., 2])
    _tmp13 = cte_24 * _tmp12
    _tmp14 = torch.cos(_in0[..., 2])
    _tmp15 = _tmp14 * _tmp4
    _tmp16 = torch.cos(_in0[..., 1])
    _tmp17 = cte_24 * _tmp16
    _tmp18 = (
        _tmp0 * _tmp13 - _tmp11 * _tmp4 - _tmp15 * _tmp17 + cte_3
    )
    _tmp19 = _tmp0 * _tmp14
    _tmp20 = cte_39 * _tmp19
    _tmp21 = _tmp12 * _tmp16
    _tmp22 = cte_39 * _tmp21
    _tmp23 = _tmp22 * _tmp4
    _tmp24 = _tmp20 + _tmp23
    _tmp25 = cte_38 * _tmp19
    _tmp26 = cte_38 * _tmp21
    _tmp27 = _tmp26 * _tmp4
    _tmp28 = cte_45 * _tmp5
    _tmp29 = _tmp1 * _tmp12
    _tmp30 = cte_63 * _tmp4
    _tmp31 = _tmp14 * _tmp30
    _tmp32 = torch.sin(_in0[..., 3])
    _tmp33 = cte_36 * _tmp12
    _tmp34 = _tmp0 * _tmp33
    _tmp35 = cte_36 * _tmp15
    _tmp36 = -_tmp16 * _tmp35 + _tmp34
    _tmp37 = _tmp32 * _tmp36
    _tmp38 = torch.cos(_in0[..., 3])
    _tmp39 = _tmp36 * _tmp38
    _tmp40 = _tmp1 * _tmp14
    _tmp41 = _tmp12 * _tmp30
    _tmp42 = _tmp4 * _tmp5
    _tmp43 = _tmp38 * _tmp42
    _tmp44 = cte_58 * _tmp4
    _tmp45 = _tmp32 * _tmp5
    _tmp46 = cte_48 * _tmp14
    _tmp47 = cte_48 * _tmp21
    _tmp48 = _tmp38 * _tmp5
    _tmp49 = cte_16 * _tmp32
    _tmp50 = cte_24 * _tmp32
    _tmp51 = _tmp18 - cte_24 * _tmp39 + _tmp42 * _tmp50
    _tmp52 = cte_35 * _tmp38
    _tmp53 = torch.sin(_in0[..., 4])
    _tmp54 = cte_36 * _tmp32
    _tmp55 = cte_36 * _tmp39 - _tmp42 * _tmp54
    _tmp56 = _tmp53 * _tmp55
    _tmp57 = torch.cos(_in0[..., 4])
    _tmp58 = cte_36 * _tmp19
    _tmp59 = _tmp33 * _tmp4
    _tmp60 = -_tmp16 * _tmp59 - _tmp58
    _tmp61 = _tmp57 * _tmp60
    _tmp62 = (
        _tmp51
        - cte_17 * _tmp56
        - cte_17 * _tmp61
    )
    _tmp63 = cte_7 * _tmp38
    _tmp64 = (
        -cte_67 * _tmp56 - cte_67 * _tmp61
    )
    _tmp65 = _tmp51 + _tmp64
    _tmp66 = (
        -cte_4 * _tmp56 - cte_4 * _tmp61
    )
    _tmp67 = (
        -cte_10 * _tmp37
        - cte_10 * _tmp43
        + _tmp51
    )
    _tmp68 = torch.sin(_in0[..., 5])
    _tmp69 = cte_36 * _tmp55
    _tmp70 = cte_36 * _tmp53
    _tmp71 = _tmp57 * _tmp69 - _tmp60 * _tmp70
    _tmp72 = _tmp68 * _tmp71
    _tmp73 = torch.cos(_in0[..., 5])
    _tmp74 = cte_67 * _tmp73
    _tmp75 = (
        -cte_36 * _tmp37 - cte_36 * _tmp43
    )
    _tmp76 = _tmp73 * _tmp75
    _tmp77 = _tmp68 * _tmp75
    _tmp78 = cte_48 * _tmp68
    _tmp79 = _tmp71 * _tmp78
    _tmp80 = cte_48 * _tmp76
    _tmp81 = cte_63 * _tmp73
    _tmp82 = cte_63 * _tmp68
    _tmp83 = _tmp67 + _tmp71 * _tmp81 + _tmp75 * _tmp82
    _tmp84 = cte_72 * _tmp73
    _tmp85 = _tmp67 + _tmp71 * _tmp84 + cte_72 * _tmp77
    _tmp86 = torch.cos(_in0[..., 6])
    _tmp87 = _tmp53 * _tmp69 + cte_36 * _tmp61
    _tmp88 = cte_70 * _tmp87
    _tmp89 = torch.sin(_in0[..., 6])
    _tmp90 = cte_36 * _tmp73
    _tmp91 = _tmp71 * _tmp90 + cte_36 * _tmp77
    _tmp92 = _tmp89 * _tmp91
    _tmp93 = _tmp86 * _tmp91
    _tmp94 = _tmp86 * _tmp87
    _tmp95 = cte_22 * _tmp94
    _tmp96 = _tmp87 * _tmp89
    _tmp97 = cte_2 * _tmp96
    _tmp98 = cte_22 * _tmp92
    _tmp99 = cte_2 * _tmp93
    _tmp100 = -_tmp95 - _tmp97 + _tmp98 - _tmp99
    _tmp101 = (
        cte_5 * _tmp72
        - cte_5 * _tmp76
        + _tmp85
    )
    _tmp102 = (
        cte_18 * _tmp72
        - cte_18 * _tmp76
        + _tmp85
    )
    _tmp103 = cte_60 * _tmp94
    _tmp104 = cte_46 * _tmp96
    _tmp105 = cte_60 * _tmp92
    _tmp106 = cte_46 * _tmp93
    _tmp107 = (
        cte_66 * _tmp72
        - cte_66 * _tmp76
    )
    _tmp108 = (
        -cte_42 * _tmp92
        + cte_37 * _tmp93
        + cte_42 * _tmp94
        + cte_37 * _tmp96
    )
    _tmp109 = cte_36 * _in0[..., 7]
    _tmp110 = _tmp108 * _tmp109 + _tmp85
    _tmp111 = cte_59 * _tmp94
    _tmp112 = cte_14 * _tmp96
    _tmp113 = cte_59 * _tmp92
    _tmp114 = cte_14 * _tmp93
    _tmp115 = (
        cte_11 * _tmp72
        - cte_11 * _tmp76
    )
    _tmp116 = cte_36 * _in0[..., 8]
    _tmp117 = -_tmp108 * _tmp116 + _tmp85
    _tmp118 = cte_56 * _tmp4
    _tmp119 = -_tmp0 * _tmp11 - _tmp13 * _tmp4 - _tmp17 * _tmp19
    _tmp120 = cte_39 * _tmp15
    _tmp121 = _tmp0 * _tmp22
    _tmp122 = -_tmp120 + _tmp121
    _tmp123 = cte_38 * _tmp15
    _tmp124 = _tmp0 * _tmp26
    _tmp125 = _tmp0 * _tmp5
    _tmp126 = _tmp125 * _tmp38
    _tmp127 = -_tmp16 * _tmp58 - _tmp59
    _tmp128 = _tmp127 * _tmp32
    _tmp129 = _tmp127 * _tmp38
    _tmp130 = _tmp119 + _tmp125 * _tmp50 - cte_24 * _tmp129
    _tmp131 = -_tmp16 * _tmp34 + _tmp35
    _tmp132 = _tmp131 * _tmp57
    _tmp133 = -_tmp125 * _tmp54 + cte_36 * _tmp129
    _tmp134 = _tmp133 * _tmp53
    _tmp135 = (
        _tmp130
        - cte_17 * _tmp132
        - cte_17 * _tmp134
    )
    _tmp136 = (
        -cte_67 * _tmp132
        - cte_67 * _tmp134
    )
    _tmp137 = _tmp130 + _tmp136
    _tmp138 = (
        -cte_4 * _tmp132
        - cte_4 * _tmp134
    )
    _tmp139 = (
        -cte_10 * _tmp126
        - cte_10 * _tmp128
        + _tmp130
    )
    _tmp140 = (
        -cte_36 * _tmp126 - cte_36 * _tmp128
    )
    _tmp141 = _tmp140 * _tmp73
    _tmp142 = _tmp140 * _tmp68
    _tmp143 = cte_36 * _tmp57
    _tmp144 = -_tmp131 * _tmp70 + _tmp133 * _tmp143
    _tmp145 = _tmp144 * _tmp68
    _tmp146 = cte_48 * _tmp141
    _tmp147 = _tmp144 * _tmp78
    _tmp148 = _tmp139 + cte_63 * _tmp142 + _tmp144 * _tmp81
    _tmp149 = _tmp139 + cte_72 * _tmp142 + _tmp144 * _tmp84
    _tmp150 = cte_36 * _tmp142 + _tmp144 * _tmp90
    _tmp151 = _tmp150 * _tmp89
    _tmp152 = _tmp150 * _tmp86
    _tmp153 = (
        cte_36 * _tmp132 + cte_36 * _tmp134
    )
    _tmp154 = _tmp153 * _tmp89
    _tmp155 = _tmp153 * _tmp86
    _tmp156 = cte_22 * _tmp151
    _tmp157 = cte_2 * _tmp152
    _tmp158 = cte_2 * _tmp154
    _tmp159 = cte_22 * _tmp155
    _tmp160 = _tmp156 - _tmp157 - _tmp158 - _tmp159
    _tmp161 = (
        -cte_5 * _tmp141
        + cte_5 * _tmp145
        + _tmp149
    )
    _tmp162 = (
        -cte_18 * _tmp141
        + cte_18 * _tmp145
        + _tmp149
    )
    _tmp163 = cte_60 * _tmp151
    _tmp164 = cte_46 * _tmp152
    _tmp165 = cte_46 * _tmp154
    _tmp166 = cte_60 * _tmp155
    _tmp167 = (
        -cte_66 * _tmp141
        + cte_66 * _tmp145
    )
    _tmp168 = (
        -cte_42 * _tmp151
        + cte_37 * _tmp152
        + cte_37 * _tmp154
        + cte_42 * _tmp155
    )
    _tmp169 = _tmp109 * _tmp168 + _tmp149
    _tmp170 = cte_59 * _tmp151
    _tmp171 = cte_14 * _tmp152
    _tmp172 = cte_14 * _tmp154
    _tmp173 = cte_59 * _tmp155
    _tmp174 = (
        -cte_11 * _tmp141
        + cte_11 * _tmp145
    )
    _tmp175 = -_tmp116 * _tmp168 + _tmp149
    _tmp176 = _tmp12 * _tmp5
    _tmp177 = cte_39 * _tmp176
    _tmp178 = _tmp14 * _tmp5
    _tmp179 = cte_24 * _tmp178
    _tmp180 = (
        cte_64 * _tmp16
        - _tmp179
        + cte_12
    )
    _tmp181 = cte_38 * _tmp176
    _tmp182 = cte_63 * _tmp178
    _tmp183 = _tmp16 * _tmp32
    _tmp184 = _tmp16 * _tmp38
    _tmp185 = _tmp178 * _tmp38
    _tmp186 = _tmp178 * _tmp32
    _tmp187 = cte_48 * _tmp176
    _tmp188 = _tmp179 * _tmp38 + _tmp180 - cte_24 * _tmp183
    _tmp189 = (
        cte_36 * _tmp183 - cte_36 * _tmp185
    )
    _tmp190 = _tmp189 * _tmp53
    _tmp191 = _tmp176 * _tmp57
    _tmp192 = (
        _tmp188
        - cte_17 * _tmp190
        + cte_17 * _tmp191
    )
    _tmp193 = (
        _tmp188
        - cte_67 * _tmp190
        + cte_67 * _tmp191
    )
    _tmp194 = (
        -cte_4 * _tmp190
        + cte_4 * _tmp191
    )
    _tmp195 = (
        cte_10 * _tmp184
        + cte_10 * _tmp186
    )
    _tmp196 = _tmp188 + _tmp195
    _tmp197 = _tmp143 * _tmp189 + _tmp176 * _tmp70
    _tmp198 = _tmp197 * _tmp68
    _tmp199 = (
        cte_36 * _tmp184 + cte_36 * _tmp186
    )
    _tmp200 = _tmp199 * _tmp68
    _tmp201 = _tmp199 * _tmp73
    _tmp202 = _tmp197 * _tmp78
    _tmp203 = cte_48 * _tmp201
    _tmp204 = _tmp196 + _tmp197 * _tmp81 + _tmp199 * _tmp82
    _tmp205 = _tmp196 + _tmp197 * _tmp84 + cte_72 * _tmp200
    _tmp206 = _tmp197 * _tmp90 + cte_36 * _tmp200
    _tmp207 = _tmp206 * _tmp86
    _tmp208 = _tmp206 * _tmp89
    _tmp209 = -_tmp143 * _tmp176 + cte_36 * _tmp190
    _tmp210 = _tmp209 * _tmp86
    _tmp211 = _tmp209 * _tmp89
    _tmp212 = cte_2 * _tmp207
    _tmp213 = cte_22 * _tmp208
    _tmp214 = cte_22 * _tmp210
    _tmp215 = cte_2 * _tmp211
    _tmp216 = -_tmp212 + _tmp213 - _tmp214 - _tmp215
    _tmp217 = (
        cte_5 * _tmp198
        - cte_5 * _tmp201
        + _tmp205
    )
    _tmp218 = (
        cte_18 * _tmp198
        - cte_18 * _tmp201
        + _tmp205
    )
    _tmp219 = cte_46 * _tmp207
    _tmp220 = cte_60 * _tmp208
    _tmp221 = cte_60 * _tmp210
    _tmp222 = cte_46 * _tmp211
    _tmp223 = (
        cte_37 * _tmp207
        - cte_42 * _tmp208
        + cte_42 * _tmp210
        + cte_37 * _tmp211
    )
    _tmp224 = _tmp109 * _tmp223 + _tmp205
    _tmp225 = (
        cte_66 * _tmp198
        - cte_66 * _tmp201
    )
    _tmp226 = cte_14 * _tmp207
    _tmp227 = cte_59 * _tmp208
    _tmp228 = cte_59 * _tmp210
    _tmp229 = cte_14 * _tmp211
    _tmp230 = (
        cte_11 * _tmp198
        - cte_11 * _tmp201
    )
    _tmp231 = -_tmp116 * _tmp223 + _tmp205

    # Output terms
    _out = _broadcast_and_stack(
        [
            _broadcast_and_stack(
                [
                    cte_6,
                    cte_23,
                    cte_23,
                    cte_21,
                    cte_21,
                    cte_25,
                    cte_25,
                    cte_21,
                    cte_69,
                    cte_69,
                    cte_69,
                    cte_68,
                    cte_3,
                    cte_3,
                    cte_3,
                    cte_3,
                    cte_3,
                    cte_3 - _tmp1,
                    cte_3 - _tmp2,
                    cte_3 - _tmp3,
                    cte_3,
                    _tmp3 + cte_3,
                    _tmp2 + cte_3,
                    -_tmp4 * _tmp6 + cte_3,
                    -_tmp4 * _tmp7 + cte_3,
                    _tmp1 - _tmp4 * _tmp8 + cte_3,
                    -_tmp4 * _tmp9 + cte_3,
                    -_tmp10 * _tmp4 + cte_3,
                    _tmp18 + _tmp24,
                    _tmp18 + _tmp25 + _tmp27,
                    -_tmp16 * _tmp31
                    + _tmp24
                    - _tmp28 * _tmp4
                    + _tmp29
                    + cte_3,
                    _tmp18 - _tmp25 - _tmp27,
                    _tmp18 - _tmp20 - _tmp23,
                    -_tmp16 * _tmp41
                    + _tmp18
                    - cte_39 * _tmp37
                    - cte_58 * _tmp39
                    - _tmp40
                    - cte_39 * _tmp43
                    + _tmp44 * _tmp45,
                    -_tmp0 * _tmp46
                    + _tmp18
                    - _tmp30 * _tmp48
                    - cte_63 * _tmp37
                    - cte_16 * _tmp39
                    - _tmp4 * _tmp47
                    + _tmp42 * _tmp49,
                    _tmp18,
                    -cte_41 * _tmp37
                    - cte_41 * _tmp43
                    + _tmp51,
                    -cte_50 * _tmp37
                    - cte_50 * _tmp43
                    + _tmp51,
                    -cte_35 * _tmp37 - _tmp42 * _tmp52 + _tmp51,
                    -cte_71 * _tmp37
                    - cte_71 * _tmp43
                    + _tmp51,
                    -cte_40 * _tmp37
                    - cte_40 * _tmp43
                    + _tmp51
                    - cte_44 * _tmp56
                    - cte_44 * _tmp61,
                    -cte_32 * _tmp37
                    - cte_32 * _tmp43
                    + _tmp62,
                    -cte_7 * _tmp37 - _tmp42 * _tmp63 + _tmp62,
                    -cte_57 * _tmp37
                    - cte_57 * _tmp43
                    + _tmp65,
                    -cte_33 * _tmp37
                    - cte_33 * _tmp43
                    + _tmp65,
                    -cte_51 * _tmp37
                    - cte_51 * _tmp43
                    + _tmp51
                    + _tmp66,
                    -cte_19 * _tmp37
                    - cte_19 * _tmp43
                    + _tmp65,
                    _tmp64 + _tmp67,
                    -cte_49 * _tmp37
                    - cte_49 * _tmp43
                    + _tmp51
                    - cte_16 * _tmp56
                    - cte_16 * _tmp61,
                    _tmp66 + _tmp67,
                    _tmp67
                    + _tmp71 * _tmp74
                    - cte_39 * _tmp72
                    + cte_39 * _tmp76
                    + cte_67 * _tmp77,
                    -_tmp79 + _tmp80 + _tmp83,
                    _tmp83,
                    cte_48 * _tmp56
                    + cte_48 * _tmp61
                    + _tmp67,
                    -cte_39 * _tmp56
                    - cte_39 * _tmp61
                    + _tmp67,
                    cte_38 * _tmp72
                    - cte_38 * _tmp76
                    + _tmp85,
                    _tmp79 - _tmp80 + _tmp85,
                    cte_13 * _tmp72
                    - cte_13 * _tmp76
                    + _tmp85
                    + _tmp86 * _tmp88
                    + _tmp88 * _tmp89
                    - cte_70 * _tmp92
                    + cte_70 * _tmp93,
                    cte_43 * _tmp72
                    - cte_43 * _tmp76
                    + _tmp85,
                    _tmp100
                    + cte_8 * _tmp72
                    - cte_8 * _tmp76
                    + _tmp85,
                    _tmp100 + _tmp101,
                    _tmp101,
                    _tmp101 + _tmp95 + _tmp97 - _tmp98 + _tmp99,
                    _tmp102,
                    _tmp102
                    - cte_29 * _tmp92
                    - cte_26 * _tmp93
                    + cte_29 * _tmp94
                    - cte_26 * _tmp96,
                    _tmp102
                    - cte_2 * _tmp92
                    - cte_22 * _tmp93
                    + cte_2 * _tmp94
                    - cte_22 * _tmp96,
                    _tmp102
                    - cte_47 * _tmp92
                    - cte_30 * _tmp93
                    + cte_47 * _tmp94
                    - cte_30 * _tmp96,
                    _tmp102
                    - cte_34 * _tmp92
                    - cte_52 * _tmp93
                    + cte_34 * _tmp94
                    - cte_52 * _tmp96,
                    _tmp103 + _tmp104 - _tmp105 + _tmp106 + _tmp107 + _tmp110,
                    _tmp110 + _tmp111 + _tmp112 - _tmp113 + _tmp114 + _tmp115,
                    -_tmp103 - _tmp104 + _tmp105 - _tmp106 + _tmp107 + _tmp117,
                    -_tmp111 - _tmp112 + _tmp113 - _tmp114 + _tmp115 + _tmp117,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    cte_27,
                    cte_31,
                    cte_16,
                    cte_27,
                    cte_31,
                    cte_31,
                    cte_16,
                    cte_16,
                    cte_16,
                    cte_27,
                    cte_31,
                    cte_27,
                    cte_27,
                    cte_27,
                    cte_27,
                    cte_27,
                    cte_27,
                    _tmp30,
                    _tmp118,
                    _tmp44,
                    cte_27,
                    -_tmp44,
                    -_tmp118,
                    -_tmp0 * _tmp6,
                    -_tmp0 * _tmp7,
                    -_tmp0 * _tmp8 - _tmp30,
                    -_tmp0 * _tmp9,
                    -_tmp0 * _tmp10,
                    _tmp119 + _tmp122,
                    _tmp119 - _tmp123 + _tmp124,
                    -_tmp0 * _tmp28 + _tmp122 - _tmp16 * _tmp40 - _tmp41,
                    _tmp119 + _tmp123 - _tmp124,
                    _tmp119 + _tmp120 - _tmp121,
                    _tmp119
                    - cte_39 * _tmp126
                    - cte_39 * _tmp128
                    - cte_58 * _tmp129
                    - _tmp16 * _tmp29
                    + _tmp3 * _tmp45
                    + _tmp31,
                    -_tmp0 * _tmp47
                    - _tmp1 * _tmp48
                    + _tmp119
                    + _tmp125 * _tmp49
                    - cte_63 * _tmp128
                    - cte_16 * _tmp129
                    + _tmp4 * _tmp46,
                    _tmp119,
                    -cte_41 * _tmp126
                    - cte_41 * _tmp128
                    + _tmp130,
                    -cte_50 * _tmp126
                    - cte_50 * _tmp128
                    + _tmp130,
                    -_tmp125 * _tmp52 - cte_35 * _tmp128 + _tmp130,
                    -cte_71 * _tmp126
                    - cte_71 * _tmp128
                    + _tmp130,
                    -cte_40 * _tmp126
                    - cte_40 * _tmp128
                    + _tmp130
                    - cte_44 * _tmp132
                    - cte_44 * _tmp134,
                    -cte_32 * _tmp126
                    - cte_32 * _tmp128
                    + _tmp135,
                    -_tmp125 * _tmp63 - cte_7 * _tmp128 + _tmp135,
                    -cte_57 * _tmp126
                    - cte_57 * _tmp128
                    + _tmp137,
                    -cte_33 * _tmp126
                    - cte_33 * _tmp128
                    + _tmp137,
                    -cte_51 * _tmp126
                    - cte_51 * _tmp128
                    + _tmp130
                    + _tmp138,
                    -cte_19 * _tmp126
                    - cte_19 * _tmp128
                    + _tmp137,
                    _tmp136 + _tmp139,
                    -cte_49 * _tmp126
                    - cte_49 * _tmp128
                    + _tmp130
                    - cte_16 * _tmp132
                    - cte_16 * _tmp134,
                    _tmp138 + _tmp139,
                    _tmp139
                    + cte_39 * _tmp141
                    + cte_67 * _tmp142
                    + _tmp144 * _tmp74
                    - cte_39 * _tmp145,
                    _tmp146 - _tmp147 + _tmp148,
                    _tmp148,
                    cte_48 * _tmp132
                    + cte_48 * _tmp134
                    + _tmp139,
                    -cte_39 * _tmp132
                    - cte_39 * _tmp134
                    + _tmp139,
                    -cte_38 * _tmp141
                    + cte_38 * _tmp145
                    + _tmp149,
                    -_tmp146 + _tmp147 + _tmp149,
                    -cte_13 * _tmp141
                    + cte_13 * _tmp145
                    + _tmp149
                    - cte_70 * _tmp151
                    + cte_70 * _tmp152
                    + cte_70 * _tmp154
                    + cte_70 * _tmp155,
                    -cte_43 * _tmp141
                    + cte_43 * _tmp145
                    + _tmp149,
                    -cte_8 * _tmp141
                    + cte_8 * _tmp145
                    + _tmp149
                    + _tmp160,
                    _tmp160 + _tmp161,
                    _tmp161,
                    -_tmp156 + _tmp157 + _tmp158 + _tmp159 + _tmp161,
                    _tmp162,
                    -cte_29 * _tmp151
                    - cte_26 * _tmp152
                    - cte_26 * _tmp154
                    + cte_29 * _tmp155
                    + _tmp162,
                    -cte_2 * _tmp151
                    - cte_22 * _tmp152
                    - cte_22 * _tmp154
                    + cte_2 * _tmp155
                    + _tmp162,
                    -cte_47 * _tmp151
                    - cte_30 * _tmp152
                    - cte_30 * _tmp154
                    + cte_47 * _tmp155
                    + _tmp162,
                    -cte_34 * _tmp151
                    - cte_52 * _tmp152
                    - cte_52 * _tmp154
                    + cte_34 * _tmp155
                    + _tmp162,
                    -_tmp163 + _tmp164 + _tmp165 + _tmp166 + _tmp167 + _tmp169,
                    _tmp169 - _tmp170 + _tmp171 + _tmp172 + _tmp173 + _tmp174,
                    _tmp163 - _tmp164 - _tmp165 - _tmp166 + _tmp167 + _tmp175,
                    _tmp170 - _tmp171 - _tmp172 - _tmp173 + _tmp174 + _tmp175,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    cte_54,
                    cte_17,
                    cte_17,
                    cte_17,
                    cte_17,
                    cte_17,
                    cte_17,
                    cte_17,
                    cte_17,
                    cte_17,
                    cte_17,
                    cte_17,
                    cte_15,
                    cte_53,
                    cte_28,
                    cte_20,
                    cte_65,
                    cte_55,
                    cte_12,
                    cte_12,
                    cte_12,
                    cte_12,
                    cte_12,
                    cte_9 * _tmp16
                    + cte_12,
                    cte_1 * _tmp16
                    + cte_12,
                    cte_4 * _tmp16
                    + cte_12,
                    cte_61 * _tmp16
                    + cte_12,
                    cte_62 * _tmp16
                    + cte_12,
                    _tmp177 + _tmp180,
                    _tmp180 + _tmp181,
                    cte_45 * _tmp16
                    + _tmp177
                    - _tmp182
                    + cte_12,
                    _tmp180 - _tmp181,
                    -_tmp177 + _tmp180,
                    -cte_63 * _tmp176
                    + _tmp180
                    - cte_58 * _tmp183
                    + cte_39 * _tmp184
                    + cte_58 * _tmp185
                    + cte_39 * _tmp186,
                    _tmp180
                    + _tmp182 * _tmp32
                    - cte_16 * _tmp183
                    + cte_63 * _tmp184
                    + cte_16 * _tmp185
                    - _tmp187,
                    _tmp180,
                    cte_41 * _tmp184
                    + cte_41 * _tmp186
                    + _tmp188,
                    cte_50 * _tmp184
                    + cte_50 * _tmp186
                    + _tmp188,
                    cte_35 * _tmp184
                    + cte_35 * _tmp186
                    + _tmp188,
                    cte_71 * _tmp184
                    + cte_71 * _tmp186
                    + _tmp188,
                    cte_40 * _tmp184
                    + cte_40 * _tmp186
                    + _tmp188
                    - cte_44 * _tmp190
                    + cte_44 * _tmp191,
                    cte_32 * _tmp184
                    + cte_32 * _tmp186
                    + _tmp192,
                    cte_7 * _tmp184
                    + cte_7 * _tmp186
                    + _tmp192,
                    cte_57 * _tmp184
                    + cte_57 * _tmp186
                    + _tmp193,
                    cte_33 * _tmp184
                    + cte_33 * _tmp186
                    + _tmp193,
                    cte_51 * _tmp184
                    + cte_51 * _tmp186
                    + _tmp188
                    + _tmp194,
                    cte_19 * _tmp184
                    + cte_19 * _tmp186
                    + _tmp193,
                    _tmp193 + _tmp195,
                    cte_49 * _tmp184
                    + cte_49 * _tmp186
                    + _tmp188
                    - cte_16 * _tmp190
                    + cte_16 * _tmp191,
                    _tmp194 + _tmp196,
                    _tmp196
                    + _tmp197 * _tmp74
                    - cte_39 * _tmp198
                    + cte_67 * _tmp200
                    + cte_39 * _tmp201,
                    -_tmp202 + _tmp203 + _tmp204,
                    _tmp204,
                    -_tmp187 * _tmp57 + cte_48 * _tmp190 + _tmp196,
                    _tmp177 * _tmp57 - cte_39 * _tmp190 + _tmp196,
                    cte_38 * _tmp198
                    - cte_38 * _tmp201
                    + _tmp205,
                    _tmp202 - _tmp203 + _tmp205,
                    cte_13 * _tmp198
                    - cte_13 * _tmp201
                    + _tmp205
                    + cte_70 * _tmp207
                    - cte_70 * _tmp208
                    + cte_70 * _tmp210
                    + cte_70 * _tmp211,
                    cte_43 * _tmp198
                    - cte_43 * _tmp201
                    + _tmp205,
                    cte_8 * _tmp198
                    - cte_8 * _tmp201
                    + _tmp205
                    + _tmp216,
                    _tmp216 + _tmp217,
                    _tmp217,
                    _tmp212 - _tmp213 + _tmp214 + _tmp215 + _tmp217,
                    _tmp218,
                    -cte_26 * _tmp207
                    - cte_29 * _tmp208
                    + cte_29 * _tmp210
                    - cte_26 * _tmp211
                    + _tmp218,
                    -cte_22 * _tmp207
                    - cte_2 * _tmp208
                    + cte_2 * _tmp210
                    - cte_22 * _tmp211
                    + _tmp218,
                    -cte_30 * _tmp207
                    - cte_47 * _tmp208
                    + cte_47 * _tmp210
                    - cte_30 * _tmp211
                    + _tmp218,
                    -cte_52 * _tmp207
                    - cte_34 * _tmp208
                    + cte_34 * _tmp210
                    - cte_52 * _tmp211
                    + _tmp218,
                    _tmp219 - _tmp220 + _tmp221 + _tmp222 + _tmp224 + _tmp225,
                    _tmp224 + _tmp226 - _tmp227 + _tmp228 + _tmp229 + _tmp230,
                    -_tmp219 + _tmp220 - _tmp221 - _tmp222 + _tmp225 + _tmp231,
                    -_tmp226 + _tmp227 - _tmp228 - _tmp229 + _tmp230 + _tmp231,
                ],
                dim=-1,
            ),
        ],
        dim=-1,
    )

    return _out
