"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

from io import BytesIO
import struct

class lcmt_gaze_polytopes(object):

    __slots__ = ["utime", "num_vertices", "num_simplices", "num_polytopes", "is_placing_spot_hidden", "vertices", "simplices", "indices"]

    __typenames__ = ["int64_t", "int32_t", "int32_t", "int32_t", "boolean", "double", "int32_t", "int32_t"]

    __dimensions__ = [None, None, None, None, None, ["num_vertices", 3], ["num_simplices", 3], ["num_polytopes", 4]]

    def __init__(self):
        self.utime = 0
        """ LCM Type: int64_t """
        self.num_vertices = 0
        """ LCM Type: int32_t """
        self.num_simplices = 0
        """ LCM Type: int32_t """
        self.num_polytopes = 0
        """ LCM Type: int32_t """
        self.is_placing_spot_hidden = False
        """ LCM Type: boolean """
        self.vertices = []
        """ LCM Type: double[num_vertices][3] """
        self.simplices = []
        """ LCM Type: int32_t[num_simplices][3] """
        self.indices = []
        """ LCM Type: int32_t[num_polytopes][4] """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_gaze_polytopes._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qiiib", self.utime, self.num_vertices, self.num_simplices, self.num_polytopes, self.is_placing_spot_hidden))
        for i0 in range(self.num_vertices):
            buf.write(struct.pack('>3d', *self.vertices[i0][:3]))
        for i0 in range(self.num_simplices):
            buf.write(struct.pack('>3i', *self.simplices[i0][:3]))
        for i0 in range(self.num_polytopes):
            buf.write(struct.pack('>4i', *self.indices[i0][:4]))

    @staticmethod
    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_gaze_polytopes._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_gaze_polytopes._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_gaze_polytopes()
        self.utime, self.num_vertices, self.num_simplices, self.num_polytopes = struct.unpack(">qiii", buf.read(20))
        self.is_placing_spot_hidden = bool(struct.unpack('b', buf.read(1))[0])
        self.vertices = []
        for i0 in range(self.num_vertices):
            self.vertices.append(struct.unpack('>3d', buf.read(24)))
        self.simplices = []
        for i0 in range(self.num_simplices):
            self.simplices.append(struct.unpack('>3i', buf.read(12)))
        self.indices = []
        for i0 in range(self.num_polytopes):
            self.indices.append(struct.unpack('>4i', buf.read(16)))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_gaze_polytopes in parents: return 0
        tmphash = (0xc97e659df0f33102) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_gaze_polytopes._packed_fingerprint is None:
            lcmt_gaze_polytopes._packed_fingerprint = struct.pack(">Q", lcmt_gaze_polytopes._get_hash_recursive([]))
        return lcmt_gaze_polytopes._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_gaze_polytopes._get_packed_fingerprint())[0]

