# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def velocity_to_generalized_velocity_matrix(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix14_1

    Outputs:
        out: Matrix14_13


    """

    # Total ops: 7

    # Input arrays

    # Intermediate terms (7)
    _tmp0 = 0.5 * _in0[8, 0]
    _tmp1 = -_tmp0
    _tmp2 = 0.5 * _in0[7, 0]
    _tmp3 = 0.5 * _in0[10, 0]
    _tmp4 = -_tmp3
    _tmp5 = 0.5 * _in0[9, 0]
    _tmp6 = -_tmp5

    # Output terms
    _out = casadi.blockcat(
        [
            [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, _tmp1, _tmp6, _tmp4, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, _tmp2, _tmp3, _tmp6, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, _tmp4, _tmp2, _tmp0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, _tmp5, _tmp1, _tmp2, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
        ]
    )

    return _out


_in0_sx = casadi.SX.sym("_in0", 14, 1)
velocity_to_generalized_velocity_matrix = casadi.Function(
    "velocity_to_generalized_velocity_matrix",
    [_in0_sx],
    [velocity_to_generalized_velocity_matrix(_in0_sx)],
    dict([("cse", True)]),
)
