# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import torch


class TensorKwargs(T.TypedDict):
    """
    TypedDict representing args that will be passed to any torch.tensor calls
    """

    device: torch.device
    dtype: torch.dtype


def _broadcast_and_stack(tensors, dim=-1):
    # type: (T.List[torch.Tensor], int) -> torch.Tensor
    """
    broadcast tensors to common shape then stack along new dimension
    """

    broadcast_shape = torch.broadcast_shapes(*(x.size() for x in tensors))
    broadcast_tensors = [x.broadcast_to(broadcast_shape) for x in tensors]

    return torch.stack(broadcast_tensors, dim=dim)


def panda_link8_vision(_in0, tensor_kwargs=None):
    # type: (torch.Tensor, TensorKwargs) -> torch.Tensor
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23

    The types for inputs and outputs above are the shapes of the symbolic matrices this function was
    generated from.  Tensors for both inputs and outputs are expected to have dimensions as follows:

    - (..., N, M) for sf.Matrix types of shape (N, M) where N != 1 and M != 1
    - (..., N) for sf.Matrix types of shape (N, M) where N != 1 and M == 1 (i.e. column vectors)
    - (..., M) for sf.Matrix types of shape (N, M) where N == 1 and M != 1 (i.e. row vectors)
    - (...) for sf.Matrix types of shape (1, 1) and sf.Scalar types

    Where `...` is an arbitrary number of batch dimensions that can be present on the front of input
    tensors.  The outputs will have the same batch dimensions as the inputs.

    The tensor_kwargs argument can be used to set the device and dtype to use.  If not provided, it will
    default to the device and dtype of the first input tensor, or the empty dict if there are no inputs.
    """

    # Total ops: 223

    # Deduce expected tensor device and dtype if not provided
    if tensor_kwargs is None:
        tensor_kwargs = {"device": _in0.device, "dtype": _in0.dtype}

    # Input arrays

    cte_1 = torch.tensor(0.535, **tensor_kwargs)
    cte_2 = torch.tensor(0.358, **tensor_kwargs)
    cte_3 = torch.tensor(0.107, **tensor_kwargs)
    cte_4 = torch.tensor(0.0825, **tensor_kwargs)
    cte_5 = torch.tensor(0.042, **tensor_kwargs)
    cte_6 = torch.tensor(1.0, **tensor_kwargs)
    cte_7 = torch.tensor(0.088, **tensor_kwargs)
    cte_8 = torch.tensor(0.384, **tensor_kwargs)
    cte_9 = torch.tensor(0.087, **tensor_kwargs)
    cte_10 = torch.tensor(0.316, **tensor_kwargs)

    # Intermediate terms (71)
    _tmp0 = torch.sin(_in0[..., 5])
    _tmp1 = torch.cos(_in0[..., 4])
    _tmp2 = torch.cos(_in0[..., 3])
    _tmp3 = torch.sin(_in0[..., 0])
    _tmp4 = torch.sin(_in0[..., 2])
    _tmp5 = cte_6 * _tmp4
    _tmp6 = _tmp3 * _tmp5
    _tmp7 = torch.cos(_in0[..., 1])
    _tmp8 = torch.cos(_in0[..., 0])
    _tmp9 = torch.cos(_in0[..., 2])
    _tmp10 = cte_6 * _tmp9
    _tmp11 = _tmp10 * _tmp8
    _tmp12 = -_tmp11 * _tmp7 + _tmp6
    _tmp13 = _tmp12 * _tmp2
    _tmp14 = torch.sin(_in0[..., 1])
    _tmp15 = torch.sin(_in0[..., 3])
    _tmp16 = cte_6 * _tmp15
    _tmp17 = _tmp14 * _tmp16
    _tmp18 = (
        cte_6 * _tmp13
        - cte_6 * _tmp17 * _tmp8
    )
    _tmp19 = torch.sin(_in0[..., 4])
    _tmp20 = _tmp10 * _tmp3
    _tmp21 = _tmp5 * _tmp8
    _tmp22 = (
        -cte_6 * _tmp20
        - cte_6 * _tmp21 * _tmp7
    )
    _tmp23 = _tmp1 * _tmp18 - _tmp19 * _tmp22
    _tmp24 = _tmp0 * _tmp23
    _tmp25 = torch.cos(_in0[..., 6])
    _tmp26 = (
        cte_5 * _tmp1 * _tmp22
        + cte_5 * _tmp18 * _tmp19
    )
    _tmp27 = torch.sin(_in0[..., 6])
    _tmp28 = torch.cos(_in0[..., 5])
    _tmp29 = cte_6 * _tmp2
    _tmp30 = _tmp14 * _tmp29
    _tmp31 = -_tmp12 * _tmp16 - _tmp30 * _tmp8
    _tmp32 = _tmp28 * _tmp31
    _tmp33 = _tmp23 * _tmp28
    _tmp34 = _tmp0 * _tmp31
    _tmp35 = (
        cte_5 * _tmp33
        + cte_5 * _tmp34
    )
    _tmp36 = cte_8 * _tmp15
    _tmp37 = cte_10 * _tmp14
    _tmp38 = cte_4 * _tmp4
    _tmp39 = cte_4 * _tmp7 * _tmp9
    _tmp40 = cte_8 * _tmp2
    _tmp41 = _tmp14 * _tmp40
    _tmp42 = cte_4 * _tmp14
    _tmp43 = _tmp15 * _tmp42
    _tmp44 = (
        -_tmp12 * _tmp36
        - cte_4 * _tmp13
        + _tmp3 * _tmp38
        + cte_7 * _tmp33
        + cte_7 * _tmp34
        - _tmp37 * _tmp8
        - _tmp39 * _tmp8
        - _tmp41 * _tmp8
        + _tmp43 * _tmp8
        + cte_1
    )
    _tmp45 = -_tmp20 * _tmp7 - _tmp21
    _tmp46 = -_tmp16 * _tmp45 - _tmp3 * _tmp30
    _tmp47 = _tmp28 * _tmp46
    _tmp48 = _tmp0 * _tmp46
    _tmp49 = (
        cte_6 * _tmp11
        - cte_6 * _tmp6 * _tmp7
    )
    _tmp50 = (
        -cte_6 * _tmp17 * _tmp3
        + cte_6 * _tmp29 * _tmp45
    )
    _tmp51 = _tmp1 * _tmp50 - _tmp19 * _tmp49
    _tmp52 = cte_6 * _tmp28
    _tmp53 = (
        cte_5 * _tmp48
        + cte_5 * _tmp51 * _tmp52
    )
    _tmp54 = (
        cte_5 * _tmp1 * _tmp49
        + cte_5 * _tmp19 * _tmp50
    )
    _tmp55 = _tmp0 * _tmp51
    _tmp56 = cte_7 * _tmp28
    _tmp57 = (
        -cte_4 * _tmp2 * _tmp45
        - _tmp3 * _tmp37
        - _tmp3 * _tmp39
        - _tmp3 * _tmp41
        + _tmp3 * _tmp43
        - _tmp36 * _tmp45
        - _tmp38 * _tmp8
        + cte_7 * _tmp48
        + _tmp51 * _tmp56
    )
    _tmp58 = _tmp15 * _tmp7
    _tmp59 = _tmp10 * _tmp14
    _tmp60 = (
        -cte_6 * _tmp2 * _tmp59
        + cte_6 * _tmp58
    )
    _tmp61 = _tmp14 * _tmp5
    _tmp62 = _tmp1 * _tmp60 + _tmp19 * _tmp61
    _tmp63 = _tmp15 * _tmp59 + _tmp29 * _tmp7
    _tmp64 = _tmp0 * _tmp63
    _tmp65 = (
        cte_5 * _tmp52 * _tmp62
        + cte_5 * _tmp64
    )
    _tmp66 = (
        -cte_5 * _tmp1 * _tmp61
        + cte_5 * _tmp19 * _tmp60
    )
    _tmp67 = _tmp0 * _tmp62
    _tmp68 = _tmp28 * _tmp63
    _tmp69 = _tmp42 * _tmp9
    _tmp70 = (
        _tmp14 * _tmp36 * _tmp9
        + _tmp2 * _tmp69
        + _tmp40 * _tmp7
        + _tmp56 * _tmp62
        - cte_4 * _tmp58
        + cte_7 * _tmp64
        - _tmp69
        + cte_10 * _tmp7
        + cte_2
    )

    # Output terms
    _out = _broadcast_and_stack(
        [
            _broadcast_and_stack(
                [
                    cte_9 * _tmp24
                    + _tmp25 * _tmp26
                    + _tmp25 * _tmp35
                    + _tmp26 * _tmp27
                    - _tmp27 * _tmp35
                    - cte_9 * _tmp32
                    + _tmp44,
                    cte_3 * _tmp24
                    - cte_3 * _tmp32
                    + _tmp44,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _tmp25 * _tmp53
                    + _tmp25 * _tmp54
                    - _tmp27 * _tmp53
                    + _tmp27 * _tmp54
                    - cte_9 * _tmp47
                    + cte_9 * _tmp55
                    + _tmp57,
                    -cte_3 * _tmp47
                    + cte_3 * _tmp55
                    + _tmp57,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _tmp25 * _tmp65
                    + _tmp25 * _tmp66
                    - _tmp27 * _tmp65
                    + _tmp27 * _tmp66
                    + cte_9 * _tmp67
                    - cte_9 * _tmp68
                    + _tmp70,
                    cte_3 * _tmp67
                    - cte_3 * _tmp68
                    + _tmp70,
                ],
                dim=-1,
            ),
        ],
        dim=-1,
    )

    return _out
