# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import torch


class TensorKwargs(T.TypedDict):
    """
    TypedDict representing args that will be passed to any torch.tensor calls
    """

    device: torch.device
    dtype: torch.dtype


def _broadcast_and_stack(tensors, dim=-1):
    # type: (T.List[torch.Tensor], int) -> torch.Tensor
    """
    broadcast tensors to common shape then stack along new dimension
    """

    broadcast_shape = torch.broadcast_shapes(*(x.size() for x in tensors))
    broadcast_tensors = [x.broadcast_to(broadcast_shape) for x in tensors]

    return torch.stack(broadcast_tensors, dim=dim)


def group_4(_in0, tensor_kwargs=None):
    # type: (torch.Tensor, TensorKwargs) -> torch.Tensor
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23

    The types for inputs and outputs above are the shapes of the symbolic matrices this function was
    generated from.  Tensors for both inputs and outputs are expected to have dimensions as follows:

    - (..., N, M) for sf.Matrix types of shape (N, M) where N != 1 and M != 1
    - (..., N) for sf.Matrix types of shape (N, M) where N != 1 and M == 1 (i.e. column vectors)
    - (..., M) for sf.Matrix types of shape (N, M) where N == 1 and M != 1 (i.e. row vectors)
    - (...) for sf.Matrix types of shape (1, 1) and sf.Scalar types

    Where `...` is an arbitrary number of batch dimensions that can be present on the front of input
    tensors.  The outputs will have the same batch dimensions as the inputs.

    The tensor_kwargs argument can be used to set the device and dtype to use.  If not provided, it will
    default to the device and dtype of the first input tensor, or the empty dict if there are no inputs.
    """

    # Total ops: 217

    # Deduce expected tensor device and dtype if not provided
    if tensor_kwargs is None:
        tensor_kwargs = {"device": _in0.device, "dtype": _in0.dtype}

    # Input arrays

    cte_1 = torch.tensor(0.0424264068712119, **tensor_kwargs)
    cte_2 = torch.tensor(1.0, **tensor_kwargs)
    cte_3 = torch.tensor(0.358, **tensor_kwargs)
    cte_4 = torch.tensor(0.122, **tensor_kwargs)
    cte_5 = torch.tensor(-0.62, **tensor_kwargs)
    cte_6 = torch.tensor(0.384, **tensor_kwargs)
    cte_7 = torch.tensor(0.03, **tensor_kwargs)
    cte_8 = torch.tensor(0.088, **tensor_kwargs)
    cte_9 = torch.tensor(0.0424264068711738, **tensor_kwargs)
    cte_10 = torch.tensor(0.316, **tensor_kwargs)
    cte_11 = torch.tensor(0.0825, **tensor_kwargs)
    cte_12 = torch.tensor(0.08, **tensor_kwargs)

    # Intermediate terms (71)
    _tmp0 = torch.sin(_in0[..., 0])
    _tmp1 = torch.sin(_in0[..., 2])
    _tmp2 = cte_2 * _tmp1
    _tmp3 = _tmp0 * _tmp2
    _tmp4 = torch.cos(_in0[..., 1])
    _tmp5 = torch.cos(_in0[..., 0])
    _tmp6 = torch.cos(_in0[..., 2])
    _tmp7 = cte_2 * _tmp6
    _tmp8 = _tmp5 * _tmp7
    _tmp9 = -_tmp3 + _tmp4 * _tmp8
    _tmp10 = torch.sin(_in0[..., 3])
    _tmp11 = cte_2 * _tmp10
    _tmp12 = torch.cos(_in0[..., 3])
    _tmp13 = cte_2 * _tmp12
    _tmp14 = torch.sin(_in0[..., 1])
    _tmp15 = _tmp14 * _tmp5
    _tmp16 = -_tmp11 * _tmp9 + _tmp13 * _tmp15
    _tmp17 = torch.cos(_in0[..., 5])
    _tmp18 = cte_7 * _tmp17
    _tmp19 = torch.sin(_in0[..., 5])
    _tmp20 = cte_12 * _tmp19
    _tmp21 = _tmp0 * _tmp7
    _tmp22 = _tmp2 * _tmp5
    _tmp23 = _tmp21 + _tmp22 * _tmp4
    _tmp24 = cte_2 * torch.sin(_in0[..., 4])
    _tmp25 = _tmp11 * _tmp15 + _tmp13 * _tmp9
    _tmp26 = cte_2 * torch.cos(_in0[..., 4])
    _tmp27 = -_tmp23 * _tmp24 + _tmp25 * _tmp26
    _tmp28 = cte_7 * _tmp19
    _tmp29 = _tmp17 * _tmp27
    _tmp30 = cte_6 * _tmp10
    _tmp31 = cte_11 * _tmp12
    _tmp32 = cte_10 * _tmp14
    _tmp33 = cte_11 * _tmp1
    _tmp34 = _tmp4 * _tmp6
    _tmp35 = cte_6 * _tmp12
    _tmp36 = (
        -_tmp0 * _tmp33
        - cte_11 * _tmp10 * _tmp15
        + _tmp15 * _tmp35
        - _tmp30 * _tmp9
        - _tmp31 * _tmp9
        + _tmp32 * _tmp5
        + cte_11 * _tmp34 * _tmp5
        + cte_5
    )
    _tmp37 = cte_2 * _tmp19
    _tmp38 = _tmp16 * _tmp37 + cte_2 * _tmp29
    _tmp39 = torch.sin(_in0[..., 6])
    _tmp40 = cte_1 * _tmp39
    _tmp41 = torch.cos(_in0[..., 6])
    _tmp42 = cte_9 * _tmp41
    _tmp43 = cte_4 * _tmp17
    _tmp44 = cte_8 * _tmp19
    _tmp45 = cte_4 * _tmp19
    _tmp46 = _tmp23 * _tmp26 + _tmp24 * _tmp25
    _tmp47 = cte_1 * _tmp41
    _tmp48 = cte_9 * _tmp39
    _tmp49 = _tmp0 * _tmp14
    _tmp50 = _tmp21 * _tmp4 + _tmp22
    _tmp51 = _tmp11 * _tmp49 + _tmp13 * _tmp50
    _tmp52 = _tmp3 * _tmp4 - _tmp8
    _tmp53 = -_tmp24 * _tmp52 + _tmp26 * _tmp51
    _tmp54 = _tmp17 * _tmp53
    _tmp55 = -_tmp11 * _tmp50 + _tmp13 * _tmp49
    _tmp56 = cte_11 * _tmp0
    _tmp57 = (
        _tmp0 * _tmp32
        - _tmp10 * _tmp14 * _tmp56
        - _tmp30 * _tmp50
        - _tmp31 * _tmp50
        + _tmp33 * _tmp5
        + _tmp34 * _tmp56
        + _tmp35 * _tmp49
    )
    _tmp58 = _tmp37 * _tmp55 + cte_2 * _tmp54
    _tmp59 = _tmp24 * _tmp51 + _tmp26 * _tmp52
    _tmp60 = _tmp10 * _tmp4
    _tmp61 = _tmp14 * _tmp6
    _tmp62 = -_tmp13 * _tmp61 + cte_2 * _tmp60
    _tmp63 = _tmp1 * _tmp14
    _tmp64 = _tmp24 * _tmp63 + _tmp26 * _tmp62
    _tmp65 = _tmp17 * _tmp64
    _tmp66 = _tmp11 * _tmp61 + _tmp13 * _tmp4
    _tmp67 = cte_11 * _tmp61
    _tmp68 = (
        _tmp12 * _tmp67
        + _tmp30 * _tmp61
        + _tmp35 * _tmp4
        + cte_10 * _tmp4
        - cte_11 * _tmp60
        - _tmp67
        + cte_3
    )
    _tmp69 = _tmp37 * _tmp66 + cte_2 * _tmp65
    _tmp70 = _tmp24 * _tmp62 - _tmp26 * _tmp63

    # Output terms
    _out = _broadcast_and_stack(
        [
            _broadcast_and_stack(
                [
                    _tmp16 * _tmp18
                    + _tmp16 * _tmp20
                    - _tmp27 * _tmp28
                    + cte_12 * _tmp29
                    + _tmp36,
                    -_tmp16 * _tmp43
                    + _tmp16 * _tmp44
                    + _tmp27 * _tmp45
                    + cte_8 * _tmp29
                    + _tmp36
                    + _tmp38 * _tmp40
                    - _tmp38 * _tmp42
                    - _tmp46 * _tmp47
                    - _tmp46 * _tmp48,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _tmp18 * _tmp55
                    + _tmp20 * _tmp55
                    - _tmp28 * _tmp53
                    + cte_12 * _tmp54
                    + _tmp57,
                    _tmp40 * _tmp58
                    - _tmp42 * _tmp58
                    - _tmp43 * _tmp55
                    + _tmp44 * _tmp55
                    + _tmp45 * _tmp53
                    - _tmp47 * _tmp59
                    - _tmp48 * _tmp59
                    + cte_8 * _tmp54
                    + _tmp57,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _tmp18 * _tmp66
                    + _tmp20 * _tmp66
                    - _tmp28 * _tmp64
                    + cte_12 * _tmp65
                    + _tmp68,
                    _tmp40 * _tmp69
                    - _tmp42 * _tmp69
                    - _tmp43 * _tmp66
                    + _tmp44 * _tmp66
                    + _tmp45 * _tmp64
                    - _tmp47 * _tmp70
                    - _tmp48 * _tmp70
                    + cte_8 * _tmp65
                    + _tmp68,
                ],
                dim=-1,
            ),
        ],
        dim=-1,
    )

    return _out
