# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import torch


class TensorKwargs(T.TypedDict):
    """
    TypedDict representing args that will be passed to any torch.tensor calls
    """

    device: torch.device
    dtype: torch.dtype


def _broadcast_and_stack(tensors, dim=-1):
    # type: (T.List[torch.Tensor], int) -> torch.Tensor
    """
    broadcast tensors to common shape then stack along new dimension
    """

    broadcast_shape = torch.broadcast_shapes(*(x.size() for x in tensors))
    broadcast_tensors = [x.broadcast_to(broadcast_shape) for x in tensors]

    return torch.stack(broadcast_tensors, dim=dim)


def panda_leftfinger_collision(_in0, tensor_kwargs=None):
    # type: (torch.Tensor, TensorKwargs) -> torch.Tensor
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23

    The types for inputs and outputs above are the shapes of the symbolic matrices this function was
    generated from.  Tensors for both inputs and outputs are expected to have dimensions as follows:

    - (..., N, M) for sf.Matrix types of shape (N, M) where N != 1 and M != 1
    - (..., N) for sf.Matrix types of shape (N, M) where N != 1 and M == 1 (i.e. column vectors)
    - (..., M) for sf.Matrix types of shape (N, M) where N == 1 and M != 1 (i.e. row vectors)
    - (...) for sf.Matrix types of shape (1, 1) and sf.Scalar types

    Where `...` is an arbitrary number of batch dimensions that can be present on the front of input
    tensors.  The outputs will have the same batch dimensions as the inputs.

    The tensor_kwargs argument can be used to set the device and dtype to use.  If not provided, it will
    default to the device and dtype of the first input tensor, or the empty dict if there are no inputs.
    """

    # Total ops: 272

    # Deduce expected tensor device and dtype if not provided
    if tensor_kwargs is None:
        tensor_kwargs = {"device": _in0.device, "dtype": _in0.dtype}

    # Input arrays

    cte_1 = torch.tensor(0.2104, **tensor_kwargs)
    cte_2 = torch.tensor(0.010606601717803, **tensor_kwargs)
    cte_3 = torch.tensor(1.0, **tensor_kwargs)
    cte_4 = torch.tensor(0.0106066017177935, **tensor_kwargs)
    cte_5 = torch.tensor(0.358, **tensor_kwargs)
    cte_6 = torch.tensor(-0.62, **tensor_kwargs)
    cte_7 = torch.tensor(0.384, **tensor_kwargs)
    cte_8 = torch.tensor(0.088, **tensor_kwargs)
    cte_9 = torch.tensor(0.707106781186865, **tensor_kwargs)
    cte_10 = torch.tensor(0.1954, **tensor_kwargs)
    cte_11 = torch.tensor(0.00494974746830361, **tensor_kwargs)
    cte_12 = torch.tensor(0.316, **tensor_kwargs)
    cte_13 = torch.tensor(0.0825, **tensor_kwargs)
    cte_14 = torch.tensor(0.00494974746830805, **tensor_kwargs)
    cte_15 = torch.tensor(0.70710678118623, **tensor_kwargs)

    # Intermediate terms (81)
    _tmp0 = torch.sin(_in0[..., 0])
    _tmp1 = torch.sin(_in0[..., 2])
    _tmp2 = cte_3 * _tmp1
    _tmp3 = _tmp0 * _tmp2
    _tmp4 = torch.cos(_in0[..., 1])
    _tmp5 = torch.cos(_in0[..., 0])
    _tmp6 = torch.cos(_in0[..., 2])
    _tmp7 = cte_3 * _tmp6
    _tmp8 = _tmp5 * _tmp7
    _tmp9 = -_tmp3 + _tmp4 * _tmp8
    _tmp10 = torch.sin(_in0[..., 3])
    _tmp11 = cte_3 * _tmp10
    _tmp12 = torch.sin(_in0[..., 1])
    _tmp13 = torch.cos(_in0[..., 3])
    _tmp14 = cte_3 * _tmp13
    _tmp15 = _tmp12 * _tmp14
    _tmp16 = -_tmp11 * _tmp9 + _tmp15 * _tmp5
    _tmp17 = torch.sin(_in0[..., 5])
    _tmp18 = cte_3 * _tmp17
    _tmp19 = torch.sin(_in0[..., 4])
    _tmp20 = _tmp0 * _tmp7
    _tmp21 = _tmp2 * _tmp5
    _tmp22 = (
        cte_3 * _tmp20
        + cte_3 * _tmp21 * _tmp4
    )
    _tmp23 = torch.cos(_in0[..., 4])
    _tmp24 = _tmp13 * _tmp9
    _tmp25 = _tmp11 * _tmp12
    _tmp26 = (
        cte_3 * _tmp24
        + cte_3 * _tmp25 * _tmp5
    )
    _tmp27 = -_tmp19 * _tmp22 + _tmp23 * _tmp26
    _tmp28 = torch.cos(_in0[..., 5])
    _tmp29 = cte_3 * _tmp28
    _tmp30 = _tmp16 * _tmp18 + _tmp27 * _tmp29
    _tmp31 = torch.sin(_in0[..., 6])
    _tmp32 = cte_14 * _tmp31
    _tmp33 = torch.cos(_in0[..., 6])
    _tmp34 = cte_11 * _tmp33
    _tmp35 = cte_1 * _tmp28
    _tmp36 = cte_1 * _tmp17
    _tmp37 = _tmp19 * _tmp26 + _tmp22 * _tmp23
    _tmp38 = cte_14 * _tmp33
    _tmp39 = _tmp31 * _tmp37
    _tmp40 = cte_7 * _tmp10
    _tmp41 = cte_12 * _tmp12
    _tmp42 = cte_13 * _tmp1
    _tmp43 = cte_8 * _tmp17
    _tmp44 = cte_8 * _tmp28
    _tmp45 = cte_13 * _tmp6
    _tmp46 = _tmp4 * _tmp45
    _tmp47 = cte_7 * _tmp13
    _tmp48 = _tmp12 * _tmp47
    _tmp49 = _tmp10 * _tmp12
    _tmp50 = cte_13 * _tmp49
    _tmp51 = cte_9 * _tmp31
    _tmp52 = cte_15 * _tmp33
    _tmp53 = cte_9 * _tmp33
    _tmp54 = cte_3 * _in0[..., 7]
    _tmp55 = (
        -_tmp0 * _tmp42
        + _tmp16 * _tmp43
        - cte_13 * _tmp24
        + _tmp27 * _tmp44
        - _tmp40 * _tmp9
        + _tmp41 * _tmp5
        + _tmp46 * _tmp5
        + _tmp48 * _tmp5
        - _tmp5 * _tmp50
        + _tmp54
        * (
            -_tmp30 * _tmp51
            + _tmp30 * _tmp52
            + _tmp37 * _tmp53
            + cte_15 * _tmp39
        )
        + cte_6
    )
    _tmp56 = cte_2 * _tmp31
    _tmp57 = cte_4 * _tmp33
    _tmp58 = cte_10 * _tmp28
    _tmp59 = cte_10 * _tmp17
    _tmp60 = cte_2 * _tmp33
    _tmp61 = _tmp20 * _tmp4 + _tmp21
    _tmp62 = (
        cte_3 * _tmp0 * _tmp25
        + cte_3 * _tmp14 * _tmp61
    )
    _tmp63 = (
        cte_3 * _tmp3 * _tmp4
        - cte_3 * _tmp8
    )
    _tmp64 = -_tmp19 * _tmp63 + _tmp23 * _tmp62
    _tmp65 = _tmp0 * _tmp15 - _tmp11 * _tmp61
    _tmp66 = _tmp18 * _tmp65 + _tmp29 * _tmp64
    _tmp67 = _tmp33 * _tmp66
    _tmp68 = _tmp19 * _tmp62 + _tmp23 * _tmp63
    _tmp69 = _tmp31 * _tmp68
    _tmp70 = (
        _tmp0 * _tmp41
        + _tmp0 * _tmp46
        + _tmp0 * _tmp48
        - _tmp0 * _tmp50
        - cte_13 * _tmp13 * _tmp61
        - _tmp40 * _tmp61
        + _tmp42 * _tmp5
        + _tmp43 * _tmp65
        + _tmp44 * _tmp64
        + _tmp54
        * (
            -_tmp51 * _tmp66
            + _tmp53 * _tmp68
            + cte_15 * _tmp67
            + cte_15 * _tmp69
        )
    )
    _tmp71 = _tmp10 * _tmp4
    _tmp72 = (
        -cte_3 * _tmp12 * _tmp13 * _tmp7
        + cte_3 * _tmp71
    )
    _tmp73 = _tmp12 * _tmp2
    _tmp74 = _tmp19 * _tmp73 + _tmp23 * _tmp72
    _tmp75 = _tmp14 * _tmp4 + _tmp49 * _tmp7
    _tmp76 = _tmp18 * _tmp75 + _tmp29 * _tmp74
    _tmp77 = _tmp19 * _tmp72 - _tmp23 * _tmp73
    _tmp78 = _tmp31 * _tmp77
    _tmp79 = _tmp12 * _tmp45
    _tmp80 = (
        _tmp12 * _tmp40 * _tmp6
        + _tmp13 * _tmp79
        + _tmp4 * _tmp47
        + cte_12 * _tmp4
        + _tmp43 * _tmp75
        + _tmp44 * _tmp74
        + _tmp54
        * (
            -_tmp51 * _tmp76
            + _tmp52 * _tmp76
            + _tmp53 * _tmp77
            + cte_15 * _tmp78
        )
        - cte_13 * _tmp71
        - _tmp79
        + cte_5
    )

    # Output terms
    _out = _broadcast_and_stack(
        [
            _broadcast_and_stack(
                [
                    -_tmp16 * _tmp35
                    + _tmp27 * _tmp36
                    - _tmp30 * _tmp32
                    + _tmp30 * _tmp34
                    + _tmp37 * _tmp38
                    + cte_11 * _tmp39
                    + _tmp55,
                    -_tmp16 * _tmp58
                    + _tmp27 * _tmp59
                    - _tmp30 * _tmp56
                    + _tmp30 * _tmp57
                    + _tmp37 * _tmp60
                    + cte_4 * _tmp39
                    + _tmp55,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    -_tmp32 * _tmp66
                    - _tmp35 * _tmp65
                    + _tmp36 * _tmp64
                    + _tmp38 * _tmp68
                    + cte_11 * _tmp67
                    + cte_11 * _tmp69
                    + _tmp70,
                    -_tmp56 * _tmp66
                    - _tmp58 * _tmp65
                    + _tmp59 * _tmp64
                    + _tmp60 * _tmp68
                    + cte_4 * _tmp67
                    + cte_4 * _tmp69
                    + _tmp70,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    -_tmp32 * _tmp76
                    + _tmp34 * _tmp76
                    - _tmp35 * _tmp75
                    + _tmp36 * _tmp74
                    + _tmp38 * _tmp77
                    + cte_11 * _tmp78
                    + _tmp80,
                    -_tmp56 * _tmp76
                    + _tmp57 * _tmp76
                    - _tmp58 * _tmp75
                    + _tmp59 * _tmp74
                    + _tmp60 * _tmp77
                    + cte_4 * _tmp78
                    + _tmp80,
                ],
                dim=-1,
            ),
        ],
        dim=-1,
    )

    return _out
