# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import torch


class TensorKwargs(T.TypedDict):
    """
    TypedDict representing args that will be passed to any torch.tensor calls
    """

    device: torch.device
    dtype: torch.dtype


def _broadcast_and_stack(tensors, dim=-1):
    # type: (T.List[torch.Tensor], int) -> torch.Tensor
    """
    broadcast tensors to common shape then stack along new dimension
    """

    broadcast_shape = torch.broadcast_shapes(*(x.size() for x in tensors))
    broadcast_tensors = [x.broadcast_to(broadcast_shape) for x in tensors]

    return torch.stack(broadcast_tensors, dim=dim)


def panda_link3_vision(_in0, tensor_kwargs=None):
    # type: (torch.Tensor, TensorKwargs) -> torch.Tensor
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix53

    The types for inputs and outputs above are the shapes of the symbolic matrices this function was
    generated from.  Tensors for both inputs and outputs are expected to have dimensions as follows:

    - (..., N, M) for sf.Matrix types of shape (N, M) where N != 1 and M != 1
    - (..., N) for sf.Matrix types of shape (N, M) where N != 1 and M == 1 (i.e. column vectors)
    - (..., M) for sf.Matrix types of shape (N, M) where N == 1 and M != 1 (i.e. row vectors)
    - (...) for sf.Matrix types of shape (1, 1) and sf.Scalar types

    Where `...` is an arbitrary number of batch dimensions that can be present on the front of input
    tensors.  The outputs will have the same batch dimensions as the inputs.

    The tensor_kwargs argument can be used to set the device and dtype to use.  If not provided, it will
    default to the device and dtype of the first input tensor, or the empty dict if there are no inputs.
    """

    # Total ops: 85

    # Deduce expected tensor device and dtype if not provided
    if tensor_kwargs is None:
        tensor_kwargs = {"device": _in0.device, "dtype": _in0.dtype}

    # Input arrays

    cte_1 = torch.tensor(0.06, **tensor_kwargs)
    cte_2 = torch.tensor(0.286, **tensor_kwargs)
    cte_3 = torch.tensor(0.04, **tensor_kwargs)
    cte_4 = torch.tensor(0.206, **tensor_kwargs)
    cte_5 = torch.tensor(0.358, **tensor_kwargs)
    cte_6 = torch.tensor(-0.62, **tensor_kwargs)
    cte_7 = torch.tensor(0.246, **tensor_kwargs)
    cte_8 = torch.tensor(0.03, **tensor_kwargs)
    cte_9 = torch.tensor(0.316, **tensor_kwargs)
    cte_10 = torch.tensor(0.0825, **tensor_kwargs)

    # Intermediate terms (27)
    _tmp0 = torch.sin(_in0[..., 1])
    _tmp1 = torch.cos(_in0[..., 0])
    _tmp2 = _tmp0 * _tmp1
    _tmp3 = cte_7 * _tmp0
    _tmp4 = torch.sin(_in0[..., 0])
    _tmp5 = torch.cos(_in0[..., 2])
    _tmp6 = cte_8 * _tmp5
    _tmp7 = torch.sin(_in0[..., 2])
    _tmp8 = _tmp1 * _tmp7
    _tmp9 = torch.cos(_in0[..., 1])
    _tmp10 = cte_8 * _tmp9
    _tmp11 = -_tmp10 * _tmp8 - _tmp4 * _tmp6 + cte_6
    _tmp12 = _tmp4 * _tmp7
    _tmp13 = _tmp5 * _tmp9
    _tmp14 = cte_10 * _tmp13
    _tmp15 = (
        _tmp1 * _tmp14
        - cte_10 * _tmp12
        + cte_9 * _tmp2
    )
    _tmp16 = cte_1 * _tmp5
    _tmp17 = cte_1 * _tmp9
    _tmp18 = cte_2 * _tmp0
    _tmp19 = cte_3 * _tmp13
    _tmp20 = _tmp0 * _tmp4
    _tmp21 = _tmp1 * _tmp6 - _tmp10 * _tmp12
    _tmp22 = (
        _tmp14 * _tmp4
        + cte_9 * _tmp20
        + cte_10 * _tmp8
    )
    _tmp23 = _tmp0 * _tmp7
    _tmp24 = cte_8 * _tmp23 + cte_5
    _tmp25 = _tmp0 * _tmp5
    _tmp26 = (
        -cte_10 * _tmp25
        + cte_9 * _tmp9
    )

    # Output terms
    _out = _broadcast_and_stack(
        [
            _broadcast_and_stack(
                [
                    cte_4 * _tmp2
                    + cte_6,
                    _tmp1 * _tmp3 + cte_6,
                    _tmp11 + _tmp15,
                    _tmp15 - _tmp16 * _tmp4 - _tmp17 * _tmp8 + cte_6,
                    _tmp1 * _tmp18
                    + _tmp1 * _tmp19
                    + _tmp11
                    - cte_3 * _tmp12,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    cte_4 * _tmp20,
                    _tmp3 * _tmp4,
                    _tmp21 + _tmp22,
                    _tmp1 * _tmp16 - _tmp12 * _tmp17 + _tmp22,
                    _tmp18 * _tmp4
                    + _tmp19 * _tmp4
                    + _tmp21
                    + cte_3 * _tmp8,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    cte_4 * _tmp9
                    + cte_5,
                    cte_7 * _tmp9
                    + cte_5,
                    _tmp24 + _tmp26,
                    cte_1 * _tmp23
                    + _tmp26
                    + cte_5,
                    _tmp24
                    - cte_3 * _tmp25
                    + cte_2 * _tmp9,
                ],
                dim=-1,
            ),
        ],
        dim=-1,
    )

    return _out
