# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def group_3(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23


    """

    # Total ops: 118

    # Input arrays

    # Intermediate terms (39)
    _tmp0 = casadi.sin(_in0[0, 0])
    _tmp1 = casadi.sin(_in0[2, 0])
    _tmp2 = 1.0 * _tmp1
    _tmp3 = _tmp0 * _tmp2
    _tmp4 = casadi.cos(_in0[1, 0])
    _tmp5 = casadi.cos(_in0[0, 0])
    _tmp6 = casadi.cos(_in0[2, 0])
    _tmp7 = 1.0 * _tmp6
    _tmp8 = _tmp5 * _tmp7
    _tmp9 = _tmp3 - _tmp4 * _tmp8
    _tmp10 = casadi.sin(_in0[3, 0])
    _tmp11 = 0.144 * _tmp10
    _tmp12 = casadi.sin(_in0[1, 0])
    _tmp13 = casadi.cos(_in0[3, 0])
    _tmp14 = _tmp12 * _tmp13
    _tmp15 = 0.144 * _tmp14
    _tmp16 = _tmp13 * _tmp9
    _tmp17 = 0.316 * _tmp12
    _tmp18 = 0.0825 * _tmp1
    _tmp19 = 0.0825 * _tmp6
    _tmp20 = _tmp19 * _tmp4
    _tmp21 = _tmp10 * _tmp12
    _tmp22 = _tmp21 * _tmp5
    _tmp23 = (
        _tmp0 * _tmp18 - 0.0825 * _tmp16 - _tmp17 * _tmp5 - _tmp20 * _tmp5 + 0.0825 * _tmp22 + 0.535
    )
    _tmp24 = 0.384 * _tmp10
    _tmp25 = 0.07 * casadi.sin(_in0[4, 0])
    _tmp26 = 0.384 * _tmp14
    _tmp27 = _tmp0 * _tmp7
    _tmp28 = _tmp2 * _tmp5
    _tmp29 = 0.07 * casadi.cos(_in0[4, 0])
    _tmp30 = -_tmp27 * _tmp4 - _tmp28
    _tmp31 = _tmp0 * _tmp21
    _tmp32 = _tmp13 * _tmp30
    _tmp33 = -_tmp0 * _tmp17 - _tmp0 * _tmp20 - _tmp18 * _tmp5 + 0.0825 * _tmp31 - 0.0825 * _tmp32
    _tmp34 = _tmp13 * _tmp4
    _tmp35 = _tmp12 * _tmp6
    _tmp36 = _tmp10 * _tmp4
    _tmp37 = _tmp12 * _tmp19
    _tmp38 = _tmp13 * _tmp37 - 0.0825 * _tmp36 - _tmp37 + 0.316 * _tmp4 + 0.358

    # Output terms
    _out = casadi.blockcat(
        [
            [
                -_tmp11 * _tmp9 - _tmp15 * _tmp5 + _tmp23,
                -_tmp0 * _tmp15 - _tmp11 * _tmp30 + _tmp33,
                _tmp11 * _tmp35 + 0.144 * _tmp34 + _tmp38,
            ],
            [
                _tmp23
                - _tmp24 * _tmp9
                - _tmp25 * (1.0 * _tmp16 - 1.0 * _tmp22)
                - _tmp26 * _tmp5
                - _tmp29 * (-_tmp27 - _tmp28 * _tmp4),
                -_tmp0 * _tmp26
                - _tmp24 * _tmp30
                - _tmp25 * (-1.0 * _tmp31 + 1.0 * _tmp32)
                - _tmp29 * (-_tmp3 * _tmp4 + _tmp8)
                + _tmp33,
                _tmp1 * _tmp12 * _tmp29
                + _tmp24 * _tmp35
                - _tmp25 * (-_tmp14 * _tmp7 + 1.0 * _tmp36)
                + 0.384 * _tmp34
                + _tmp38,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
group_3 = casadi.Function(
    "group_3",
    [_in0_mx],
    [group_3(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
