# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_link1_collision_radii(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix61


    """

    # Total ops: 0

    # Input arrays

    # Intermediate terms (0)

    # Output terms
    _out = casadi.blockcat(
        [
            [0.0600000000000000],
            [0.0600000000000000],
            [0.0600000000000000],
            [0.0600000000000000],
            [0.0600000000000000],
            [0.0600000000000000],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_link1_collision_radii = casadi.Function(
    "panda_link1_collision_radii",
    [_in0_mx],
    [panda_link1_collision_radii(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
