# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_link0_collision(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix14_3


    """

    # Total ops: 0

    # Input arrays

    # Intermediate terms (0)

    # Output terms
    _out = casadi.blockcat(
        [
            [0.515000000000000, 0, 0.0650000000000000],
            [0.525000000000000, -0.0500000000000000, 0.0850000000000000],
            [0.525000000000000, 0.0500000000000000, 0.0850000000000000],
            [0.595000000000000, 0, 0.0850000000000000],
            [0.595000000000000, -0.0500000000000000, 0.0850000000000000],
            [0.565000000000000, -0.0500000000000000, 0.0850000000000000],
            [0.565000000000000, 0.0500000000000000, 0.0850000000000000],
            [0.595000000000000, 0.0500000000000000, 0.0850000000000000],
            [0.625000000000000, 0.0500000000000000, 0.0850000000000000],
            [0.625000000000000, 0, 0.0850000000000000],
            [0.625000000000000, -0.0500000000000000, 0.0850000000000000],
            [0.655000000000000, 0, 0.0850000000000000],
            [0.535000000000000, 0, 0.138000000000000],
            [0.535000000000000, 0, 0.108000000000000],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_link0_collision = casadi.Function(
    "panda_link0_collision",
    [_in0_mx],
    [panda_link0_collision(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
