# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def frame_pose_in_frame_EE_frame_world(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix44


    """

    # Total ops: 233

    # Input arrays

    # Intermediate terms (77)
    _tmp0 = casadi.sin(_in0[6, 0])
    _tmp1 = casadi.sin(_in0[5, 0])
    _tmp2 = casadi.sin(_in0[0, 0])
    _tmp3 = casadi.sin(_in0[2, 0])
    _tmp4 = 1.0 * _tmp3
    _tmp5 = _tmp2 * _tmp4
    _tmp6 = casadi.cos(_in0[1, 0])
    _tmp7 = casadi.cos(_in0[0, 0])
    _tmp8 = casadi.cos(_in0[2, 0])
    _tmp9 = 1.0 * _tmp8
    _tmp10 = _tmp7 * _tmp9
    _tmp11 = _tmp10 * _tmp6 - _tmp5
    _tmp12 = casadi.sin(_in0[3, 0])
    _tmp13 = 1.0 * _tmp12
    _tmp14 = casadi.sin(_in0[1, 0])
    _tmp15 = casadi.cos(_in0[3, 0])
    _tmp16 = 1.0 * _tmp15
    _tmp17 = _tmp14 * _tmp16
    _tmp18 = -_tmp11 * _tmp13 + _tmp17 * _tmp7
    _tmp19 = 1.0 * _tmp18
    _tmp20 = casadi.sin(_in0[4, 0])
    _tmp21 = _tmp2 * _tmp9
    _tmp22 = _tmp4 * _tmp7
    _tmp23 = 1.0 * _tmp21 + 1.0 * _tmp22 * _tmp6
    _tmp24 = casadi.cos(_in0[4, 0])
    _tmp25 = _tmp11 * _tmp15
    _tmp26 = _tmp13 * _tmp14
    _tmp27 = 1.0 * _tmp25 + 1.0 * _tmp26 * _tmp7
    _tmp28 = -_tmp20 * _tmp23 + _tmp24 * _tmp27
    _tmp29 = casadi.cos(_in0[5, 0])
    _tmp30 = 1.0 * _tmp29
    _tmp31 = _tmp1 * _tmp19 + _tmp28 * _tmp30
    _tmp32 = 0.707106781186547 * _tmp31
    _tmp33 = casadi.cos(_in0[6, 0])
    _tmp34 = 0.707106781186548 * _tmp31
    _tmp35 = _tmp20 * _tmp27 + _tmp23 * _tmp24
    _tmp36 = 0.707106781186547 * _tmp35
    _tmp37 = 0.707106781186548 * _tmp35
    _tmp38 = _tmp21 * _tmp6 + _tmp22
    _tmp39 = 1.0 * _tmp16 * _tmp38 + 1.0 * _tmp2 * _tmp26
    _tmp40 = -1.0 * _tmp10 + 1.0 * _tmp5 * _tmp6
    _tmp41 = -_tmp20 * _tmp40 + _tmp24 * _tmp39
    _tmp42 = 1.0 * _tmp41
    _tmp43 = -_tmp13 * _tmp38 + _tmp17 * _tmp2
    _tmp44 = 1.0 * _tmp1
    _tmp45 = _tmp29 * _tmp42 + _tmp43 * _tmp44
    _tmp46 = 0.707106781186547 * _tmp45
    _tmp47 = 0.707106781186548 * _tmp45
    _tmp48 = _tmp20 * _tmp39 + _tmp24 * _tmp40
    _tmp49 = 0.707106781186548 * _tmp48
    _tmp50 = 0.707106781186547 * _tmp48
    _tmp51 = _tmp12 * _tmp6
    _tmp52 = _tmp14 * _tmp8
    _tmp53 = -1.0 * _tmp16 * _tmp52 + 1.0 * _tmp51
    _tmp54 = _tmp14 * _tmp4
    _tmp55 = _tmp20 * _tmp54 + _tmp24 * _tmp53
    _tmp56 = _tmp13 * _tmp52 + _tmp16 * _tmp6
    _tmp57 = _tmp30 * _tmp55 + _tmp44 * _tmp56
    _tmp58 = 0.707106781186548 * _tmp57
    _tmp59 = 0.707106781186547 * _tmp57
    _tmp60 = _tmp20 * _tmp53 - _tmp24 * _tmp54
    _tmp61 = 0.707106781186547 * _tmp60
    _tmp62 = 0.707106781186548 * _tmp60
    _tmp63 = 0.384 * _tmp12
    _tmp64 = 0.316 * _tmp14
    _tmp65 = 0.0825 * _tmp3
    _tmp66 = 0.2104 * _tmp29
    _tmp67 = 0.088 * _tmp1
    _tmp68 = 0.2104 * _tmp1
    _tmp69 = 0.088 * _tmp29
    _tmp70 = _tmp6 * _tmp8
    _tmp71 = 0.0825 * _tmp7
    _tmp72 = 0.384 * _tmp15
    _tmp73 = _tmp14 * _tmp72
    _tmp74 = _tmp12 * _tmp14
    _tmp75 = 0.0825 * _tmp2
    _tmp76 = 0.0825 * _tmp52

    # Output terms
    _out = casadi.blockcat(
        [
            [
                _tmp0 * _tmp32 + _tmp0 * _tmp37 + _tmp33 * _tmp34 - _tmp33 * _tmp36,
                -_tmp0 * _tmp34 + _tmp0 * _tmp36 + _tmp32 * _tmp33 + _tmp33 * _tmp37,
                -_tmp19 * _tmp29 + _tmp28 * _tmp44,
                -_tmp11 * _tmp63
                - _tmp18 * _tmp66
                + _tmp18 * _tmp67
                - _tmp2 * _tmp65
                - 0.0825 * _tmp25
                + _tmp28 * _tmp68
                + _tmp28 * _tmp69
                + _tmp64 * _tmp7
                + _tmp7 * _tmp73
                + _tmp70 * _tmp71
                - _tmp71 * _tmp74
                - 0.62,
            ],
            [
                _tmp0 * _tmp46 + _tmp0 * _tmp49 + _tmp33 * _tmp47 - _tmp33 * _tmp50,
                -_tmp0 * _tmp47 + _tmp0 * _tmp50 + _tmp33 * _tmp46 + _tmp33 * _tmp49,
                _tmp1 * _tmp42 - _tmp30 * _tmp43,
                -0.0825 * _tmp15 * _tmp38
                + _tmp2 * _tmp64
                + _tmp2 * _tmp73
                - _tmp38 * _tmp63
                + _tmp41 * _tmp68
                + _tmp41 * _tmp69
                - _tmp43 * _tmp66
                + _tmp43 * _tmp67
                + _tmp65 * _tmp7
                + _tmp70 * _tmp75
                - _tmp74 * _tmp75,
            ],
            [
                _tmp0 * _tmp59 + _tmp0 * _tmp62 + _tmp33 * _tmp58 - _tmp33 * _tmp61,
                -_tmp0 * _tmp58 + _tmp0 * _tmp61 + _tmp33 * _tmp59 + _tmp33 * _tmp62,
                -_tmp30 * _tmp56 + _tmp44 * _tmp55,
                _tmp15 * _tmp76
                - 0.0825 * _tmp51
                + _tmp52 * _tmp63
                + _tmp55 * _tmp68
                + _tmp55 * _tmp69
                - _tmp56 * _tmp66
                + _tmp56 * _tmp67
                + _tmp6 * _tmp72
                + 0.316 * _tmp6
                - _tmp76
                + 0.358,
            ],
            [0, 0, 0, 1],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
frame_pose_in_frame_EE_frame_world = casadi.Function(
    "frame_pose_in_frame_EE_frame_world",
    [_in0_mx],
    [frame_pose_in_frame_EE_frame_world(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
