# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def frame_pose_in_frame_EE_frame_world(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix44


    """

    # Total ops: 235

    # Input arrays

    # Intermediate terms (75)
    _tmp0 = casadi.cos(_in0[6, 0])
    _tmp1 = casadi.sin(_in0[4, 0])
    _tmp2 = casadi.cos(_in0[3, 0])
    _tmp3 = casadi.sin(_in0[0, 0])
    _tmp4 = casadi.sin(_in0[2, 0])
    _tmp5 = 1.0 * _tmp4
    _tmp6 = _tmp3 * _tmp5
    _tmp7 = casadi.cos(_in0[1, 0])
    _tmp8 = casadi.cos(_in0[0, 0])
    _tmp9 = casadi.cos(_in0[2, 0])
    _tmp10 = 1.0 * _tmp9
    _tmp11 = _tmp10 * _tmp8
    _tmp12 = -_tmp11 * _tmp7 + _tmp6
    _tmp13 = _tmp12 * _tmp2
    _tmp14 = casadi.sin(_in0[3, 0])
    _tmp15 = 1.0 * _tmp14
    _tmp16 = casadi.sin(_in0[1, 0])
    _tmp17 = _tmp16 * _tmp8
    _tmp18 = 1.0 * _tmp13 - 1.0 * _tmp15 * _tmp17
    _tmp19 = casadi.cos(_in0[4, 0])
    _tmp20 = _tmp10 * _tmp3
    _tmp21 = _tmp5 * _tmp8
    _tmp22 = -1.0 * _tmp20 - 1.0 * _tmp21 * _tmp7
    _tmp23 = _tmp1 * _tmp18 + _tmp19 * _tmp22
    _tmp24 = 0.707106781186547 * _tmp23
    _tmp25 = casadi.sin(_in0[6, 0])
    _tmp26 = 0.707106781186548 * _tmp25
    _tmp27 = casadi.cos(_in0[5, 0])
    _tmp28 = -_tmp1 * _tmp22 + _tmp18 * _tmp19
    _tmp29 = _tmp27 * _tmp28
    _tmp30 = casadi.sin(_in0[5, 0])
    _tmp31 = 1.0 * _tmp2
    _tmp32 = -_tmp12 * _tmp15 - _tmp17 * _tmp31
    _tmp33 = 1.0 * _tmp32
    _tmp34 = 1.0 * _tmp29 + _tmp30 * _tmp33
    _tmp35 = 0.707106781186547 * _tmp34
    _tmp36 = 0.707106781186548 * _tmp0
    _tmp37 = _tmp16 * _tmp3
    _tmp38 = -_tmp20 * _tmp7 - _tmp21
    _tmp39 = -_tmp15 * _tmp38 - _tmp31 * _tmp37
    _tmp40 = 1.0 * _tmp39
    _tmp41 = _tmp11 - _tmp6 * _tmp7
    _tmp42 = 1.0 * _tmp1
    _tmp43 = -1.0 * _tmp15 * _tmp37 + 1.0 * _tmp31 * _tmp38
    _tmp44 = _tmp19 * _tmp43 - _tmp41 * _tmp42
    _tmp45 = _tmp27 * _tmp44
    _tmp46 = _tmp30 * _tmp40 + 1.0 * _tmp45
    _tmp47 = 0.707106781186547 * _tmp46
    _tmp48 = 1.0 * _tmp19
    _tmp49 = _tmp1 * _tmp43 + _tmp41 * _tmp48
    _tmp50 = 0.707106781186547 * _tmp49
    _tmp51 = _tmp14 * _tmp7
    _tmp52 = _tmp10 * _tmp16
    _tmp53 = -_tmp2 * _tmp52 + 1.0 * _tmp51
    _tmp54 = _tmp16 * _tmp5
    _tmp55 = _tmp1 * _tmp54 + _tmp48 * _tmp53
    _tmp56 = 1.0 * _tmp55
    _tmp57 = _tmp14 * _tmp52 + _tmp31 * _tmp7
    _tmp58 = 1.0 * _tmp57
    _tmp59 = _tmp27 * _tmp56 + _tmp30 * _tmp58
    _tmp60 = 0.707106781186547 * _tmp59
    _tmp61 = -_tmp19 * _tmp54 + _tmp42 * _tmp53
    _tmp62 = 0.707106781186547 * _tmp61
    _tmp63 = _tmp28 * _tmp30
    _tmp64 = _tmp30 * _tmp44
    _tmp65 = 0.384 * _tmp14
    _tmp66 = 0.316 * _tmp16
    _tmp67 = 0.0825 * _tmp4
    _tmp68 = 0.0825 * _tmp9
    _tmp69 = _tmp68 * _tmp7
    _tmp70 = 0.384 * _tmp2
    _tmp71 = 0.0825 * _tmp14
    _tmp72 = 0.2104 * _tmp27
    _tmp73 = 0.088 * _tmp30
    _tmp74 = _tmp16 * _tmp68

    # Output terms
    _out = casadi.blockcat(
        [
            [
                -_tmp0 * _tmp24 + _tmp23 * _tmp26 + _tmp25 * _tmp35 + _tmp34 * _tmp36,
                _tmp0 * _tmp35 + _tmp23 * _tmp36 + _tmp24 * _tmp25 - _tmp26 * _tmp34,
                -_tmp27 * _tmp33 + 1.0 * _tmp63,
                -_tmp12 * _tmp65
                - 0.0825 * _tmp13
                - _tmp17 * _tmp70
                + _tmp17 * _tmp71
                + 0.088 * _tmp29
                + _tmp3 * _tmp67
                - _tmp32 * _tmp72
                + _tmp32 * _tmp73
                + 0.2104 * _tmp63
                - _tmp66 * _tmp8
                - _tmp69 * _tmp8
                + 0.535,
            ],
            [
                -_tmp0 * _tmp50 + _tmp25 * _tmp47 + _tmp26 * _tmp49 + _tmp36 * _tmp46,
                _tmp0 * _tmp47 + _tmp25 * _tmp50 - _tmp26 * _tmp46 + _tmp36 * _tmp49,
                -_tmp27 * _tmp40 + 1.0 * _tmp64,
                -0.0825 * _tmp2 * _tmp38
                - _tmp3 * _tmp66
                - _tmp3 * _tmp69
                - _tmp37 * _tmp70
                + _tmp37 * _tmp71
                - _tmp38 * _tmp65
                - _tmp39 * _tmp72
                + _tmp39 * _tmp73
                + 0.088 * _tmp45
                + 0.2104 * _tmp64
                - _tmp67 * _tmp8,
            ],
            [
                -_tmp0 * _tmp62 + _tmp25 * _tmp60 + _tmp26 * _tmp61 + _tmp36 * _tmp59,
                _tmp0 * _tmp60 + _tmp25 * _tmp62 - _tmp26 * _tmp59 + _tmp36 * _tmp61,
                -_tmp27 * _tmp58 + _tmp30 * _tmp56,
                _tmp16 * _tmp65 * _tmp9
                + _tmp2 * _tmp74
                + 0.088 * _tmp27 * _tmp55
                + 0.2104 * _tmp30 * _tmp55
                - 0.0825 * _tmp51
                - _tmp57 * _tmp72
                + _tmp57 * _tmp73
                + _tmp7 * _tmp70
                + 0.316 * _tmp7
                - _tmp74
                + 0.358,
            ],
            [0, 0, 0, 1],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
frame_pose_in_frame_EE_frame_world = casadi.Function(
    "frame_pose_in_frame_EE_frame_world",
    [_in0_mx],
    [frame_pose_in_frame_EE_frame_world(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
