# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def group_1(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23


    """

    # Total ops: 169

    # Input arrays

    # Intermediate terms (55)
    _tmp0 = casadi.sin(_in0[0, 0])
    _tmp1 = casadi.sin(_in0[2, 0])
    _tmp2 = 1.0 * _tmp1
    _tmp3 = _tmp0 * _tmp2
    _tmp4 = casadi.cos(_in0[1, 0])
    _tmp5 = casadi.cos(_in0[0, 0])
    _tmp6 = casadi.cos(_in0[2, 0])
    _tmp7 = 1.0 * _tmp6
    _tmp8 = _tmp5 * _tmp7
    _tmp9 = -_tmp3 + _tmp4 * _tmp8
    _tmp10 = casadi.sin(_in0[3, 0])
    _tmp11 = 1.0 * _tmp10
    _tmp12 = casadi.sin(_in0[1, 0])
    _tmp13 = _tmp12 * _tmp5
    _tmp14 = casadi.cos(_in0[3, 0])
    _tmp15 = 1.0 * _tmp14
    _tmp16 = -_tmp11 * _tmp9 + _tmp13 * _tmp15
    _tmp17 = casadi.cos(_in0[5, 0])
    _tmp18 = 0.03 * _tmp17
    _tmp19 = casadi.sin(_in0[5, 0])
    _tmp20 = _tmp16 * _tmp19
    _tmp21 = _tmp0 * _tmp7
    _tmp22 = _tmp2 * _tmp5
    _tmp23 = casadi.sin(_in0[4, 0])
    _tmp24 = 1.0 * _tmp23
    _tmp25 = _tmp14 * _tmp9
    _tmp26 = 1.0 * casadi.cos(_in0[4, 0])
    _tmp27 = -_tmp24 * (_tmp21 + _tmp22 * _tmp4) + _tmp26 * (_tmp11 * _tmp13 + 1.0 * _tmp25)
    _tmp28 = 0.03 * _tmp19
    _tmp29 = 0.08 * _tmp17
    _tmp30 = 0.384 * _tmp10
    _tmp31 = 0.316 * _tmp12
    _tmp32 = 0.0825 * _tmp1
    _tmp33 = 0.0825 * _tmp4 * _tmp6
    _tmp34 = 0.384 * _tmp14
    _tmp35 = 0.0825 * _tmp10
    _tmp36 = (
        -_tmp0 * _tmp32
        + _tmp13 * _tmp34
        - _tmp13 * _tmp35
        - 0.0825 * _tmp25
        - _tmp30 * _tmp9
        + _tmp31 * _tmp5
        + _tmp33 * _tmp5
        - 0.62
    )
    _tmp37 = 0.137 * _tmp17
    _tmp38 = 0.137 * _tmp19
    _tmp39 = 0.088 * _tmp17
    _tmp40 = _tmp0 * _tmp12
    _tmp41 = _tmp21 * _tmp4 + _tmp22
    _tmp42 = 1.0 * _tmp41
    _tmp43 = -_tmp24 * (_tmp3 * _tmp4 - _tmp8) + _tmp26 * (_tmp11 * _tmp40 + _tmp14 * _tmp42)
    _tmp44 = -_tmp10 * _tmp42 + _tmp15 * _tmp40
    _tmp45 = _tmp19 * _tmp44
    _tmp46 = (
        _tmp0 * _tmp31
        + _tmp0 * _tmp33
        - 0.0825 * _tmp14 * _tmp41
        - _tmp30 * _tmp41
        + _tmp32 * _tmp5
        + _tmp34 * _tmp40
        - _tmp35 * _tmp40
    )
    _tmp47 = _tmp10 * _tmp4
    _tmp48 = _tmp12 * _tmp6
    _tmp49 = _tmp12 * _tmp2 * _tmp23 + _tmp26 * (-_tmp15 * _tmp48 + 1.0 * _tmp47)
    _tmp50 = _tmp14 * _tmp4
    _tmp51 = _tmp11 * _tmp48 + 1.0 * _tmp50
    _tmp52 = _tmp19 * _tmp51
    _tmp53 = 0.0825 * _tmp48
    _tmp54 = (
        _tmp14 * _tmp53
        + _tmp30 * _tmp48
        + 0.316 * _tmp4
        - 0.0825 * _tmp47
        + 0.384 * _tmp50
        - _tmp53
        + 0.358
    )

    # Output terms
    _out = casadi.blockcat(
        [
            [
                _tmp16 * _tmp18 + 0.08 * _tmp20 - _tmp27 * _tmp28 + _tmp27 * _tmp29 + _tmp36,
                _tmp18 * _tmp44 - _tmp28 * _tmp43 + _tmp29 * _tmp43 + 0.08 * _tmp45 + _tmp46,
                _tmp18 * _tmp51 - _tmp28 * _tmp49 + _tmp29 * _tmp49 + 0.08 * _tmp52 + _tmp54,
            ],
            [
                -_tmp16 * _tmp37 + 0.088 * _tmp20 + _tmp27 * _tmp38 + _tmp27 * _tmp39 + _tmp36,
                -_tmp37 * _tmp44 + _tmp38 * _tmp43 + _tmp39 * _tmp43 + 0.088 * _tmp45 + _tmp46,
                -_tmp37 * _tmp51 + _tmp38 * _tmp49 + _tmp39 * _tmp49 + 0.088 * _tmp52 + _tmp54,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
group_1 = casadi.Function(
    "group_1",
    [_in0_mx],
    [group_1(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
