# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_link7_vision(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23


    """

    # Total ops: 156

    # Input arrays

    # Intermediate terms (54)
    _tmp0 = casadi.sin(_in0[3, 0])
    _tmp1 = casadi.sin(_in0[0, 0])
    _tmp2 = casadi.sin(_in0[2, 0])
    _tmp3 = 1.0 * _tmp2
    _tmp4 = _tmp1 * _tmp3
    _tmp5 = casadi.cos(_in0[1, 0])
    _tmp6 = casadi.cos(_in0[0, 0])
    _tmp7 = casadi.cos(_in0[2, 0])
    _tmp8 = 1.0 * _tmp7
    _tmp9 = _tmp6 * _tmp8
    _tmp10 = -_tmp4 + _tmp5 * _tmp9
    _tmp11 = 1.0 * _tmp10
    _tmp12 = casadi.cos(_in0[3, 0])
    _tmp13 = casadi.sin(_in0[1, 0])
    _tmp14 = _tmp12 * _tmp13
    _tmp15 = _tmp14 * _tmp6
    _tmp16 = -_tmp0 * _tmp11 + 1.0 * _tmp15
    _tmp17 = casadi.cos(_in0[5, 0])
    _tmp18 = 0.06 * _tmp17
    _tmp19 = casadi.sin(_in0[5, 0])
    _tmp20 = _tmp1 * _tmp8
    _tmp21 = _tmp3 * _tmp6
    _tmp22 = casadi.sin(_in0[4, 0])
    _tmp23 = 1.0 * _tmp22
    _tmp24 = _tmp0 * _tmp13
    _tmp25 = _tmp24 * _tmp6
    _tmp26 = 1.0 * casadi.cos(_in0[4, 0])
    _tmp27 = -_tmp23 * (_tmp20 + _tmp21 * _tmp5) + _tmp26 * (_tmp11 * _tmp12 + 1.0 * _tmp25)
    _tmp28 = _tmp19 * _tmp27
    _tmp29 = 0.384 * _tmp0
    _tmp30 = 0.0825 * _tmp12
    _tmp31 = 0.316 * _tmp13
    _tmp32 = 0.0825 * _tmp2
    _tmp33 = 0.088 * _tmp19
    _tmp34 = 0.088 * _tmp17
    _tmp35 = 0.0825 * _tmp5 * _tmp7
    _tmp36 = (
        -_tmp1 * _tmp32
        - _tmp10 * _tmp29
        - _tmp10 * _tmp30
        + 0.384 * _tmp15
        + _tmp16 * _tmp33
        - 0.0825 * _tmp25
        + _tmp27 * _tmp34
        + _tmp31 * _tmp6
        + _tmp35 * _tmp6
        - 0.62
    )
    _tmp37 = 0.01 * _tmp17
    _tmp38 = _tmp1 * _tmp24
    _tmp39 = _tmp20 * _tmp5 + _tmp21
    _tmp40 = 1.0 * _tmp39
    _tmp41 = -_tmp23 * (_tmp4 * _tmp5 - _tmp9) + _tmp26 * (_tmp12 * _tmp40 + 1.0 * _tmp38)
    _tmp42 = _tmp19 * _tmp41
    _tmp43 = _tmp1 * _tmp14
    _tmp44 = -_tmp0 * _tmp40 + 1.0 * _tmp43
    _tmp45 = (
        _tmp1 * _tmp31
        + _tmp1 * _tmp35
        - _tmp29 * _tmp39
        - _tmp30 * _tmp39
        + _tmp32 * _tmp6
        + _tmp33 * _tmp44
        + _tmp34 * _tmp41
        - 0.0825 * _tmp38
        + 0.384 * _tmp43
    )
    _tmp46 = _tmp0 * _tmp5
    _tmp47 = _tmp13 * _tmp7
    _tmp48 = 1.0 * _tmp47
    _tmp49 = _tmp13 * _tmp22 * _tmp3 + _tmp26 * (-_tmp12 * _tmp48 + 1.0 * _tmp46)
    _tmp50 = _tmp19 * _tmp49
    _tmp51 = _tmp12 * _tmp5
    _tmp52 = _tmp0 * _tmp48 + 1.0 * _tmp51
    _tmp53 = (
        _tmp29 * _tmp47
        + _tmp30 * _tmp47
        + _tmp33 * _tmp52
        + _tmp34 * _tmp49
        - 0.0825 * _tmp46
        - 0.0825 * _tmp47
        + 0.316 * _tmp5
        + 0.384 * _tmp51
        + 0.358
    )

    # Output terms
    _out = casadi.blockcat(
        [
            [
                -_tmp16 * _tmp18 + 0.06 * _tmp28 + _tmp36,
                -_tmp18 * _tmp44 + 0.06 * _tmp42 + _tmp45,
                -_tmp18 * _tmp52 + 0.06 * _tmp50 + _tmp53,
            ],
            [
                -_tmp16 * _tmp37 + 0.01 * _tmp28 + _tmp36,
                -_tmp37 * _tmp44 + 0.01 * _tmp42 + _tmp45,
                -_tmp37 * _tmp52 + 0.01 * _tmp50 + _tmp53,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_link7_vision = casadi.Function(
    "panda_link7_vision",
    [_in0_mx],
    [panda_link7_vision(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
