# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_leftfinger_vision(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23


    """

    # Total ops: 272

    # Input arrays

    # Intermediate terms (81)
    _tmp0 = casadi.sin(_in0[0, 0])
    _tmp1 = casadi.sin(_in0[2, 0])
    _tmp2 = 1.0 * _tmp1
    _tmp3 = _tmp0 * _tmp2
    _tmp4 = casadi.cos(_in0[1, 0])
    _tmp5 = casadi.cos(_in0[0, 0])
    _tmp6 = casadi.cos(_in0[2, 0])
    _tmp7 = 1.0 * _tmp6
    _tmp8 = _tmp5 * _tmp7
    _tmp9 = -_tmp3 + _tmp4 * _tmp8
    _tmp10 = casadi.sin(_in0[3, 0])
    _tmp11 = 1.0 * _tmp10
    _tmp12 = casadi.sin(_in0[1, 0])
    _tmp13 = casadi.cos(_in0[3, 0])
    _tmp14 = 1.0 * _tmp13
    _tmp15 = _tmp12 * _tmp14
    _tmp16 = -_tmp11 * _tmp9 + _tmp15 * _tmp5
    _tmp17 = casadi.sin(_in0[5, 0])
    _tmp18 = 1.0 * _tmp17
    _tmp19 = casadi.sin(_in0[4, 0])
    _tmp20 = _tmp0 * _tmp7
    _tmp21 = _tmp2 * _tmp5
    _tmp22 = 1.0 * _tmp20 + 1.0 * _tmp21 * _tmp4
    _tmp23 = casadi.cos(_in0[4, 0])
    _tmp24 = _tmp13 * _tmp9
    _tmp25 = _tmp11 * _tmp12
    _tmp26 = 1.0 * _tmp24 + 1.0 * _tmp25 * _tmp5
    _tmp27 = -_tmp19 * _tmp22 + _tmp23 * _tmp26
    _tmp28 = casadi.cos(_in0[5, 0])
    _tmp29 = 1.0 * _tmp28
    _tmp30 = _tmp16 * _tmp18 + _tmp27 * _tmp29
    _tmp31 = casadi.sin(_in0[6, 0])
    _tmp32 = 0.00494974746830805 * _tmp31
    _tmp33 = casadi.cos(_in0[6, 0])
    _tmp34 = 0.00494974746830361 * _tmp33
    _tmp35 = 0.2104 * _tmp28
    _tmp36 = 0.2104 * _tmp17
    _tmp37 = _tmp19 * _tmp26 + _tmp22 * _tmp23
    _tmp38 = 0.00494974746830805 * _tmp33
    _tmp39 = _tmp31 * _tmp37
    _tmp40 = 0.384 * _tmp10
    _tmp41 = 0.316 * _tmp12
    _tmp42 = 0.0825 * _tmp1
    _tmp43 = 0.088 * _tmp17
    _tmp44 = 0.088 * _tmp28
    _tmp45 = 0.0825 * _tmp6
    _tmp46 = _tmp4 * _tmp45
    _tmp47 = 0.384 * _tmp13
    _tmp48 = _tmp12 * _tmp47
    _tmp49 = _tmp10 * _tmp12
    _tmp50 = 0.0825 * _tmp49
    _tmp51 = 0.707106781186865 * _tmp31
    _tmp52 = 0.70710678118623 * _tmp33
    _tmp53 = 0.707106781186865 * _tmp33
    _tmp54 = 1.0 * _in0[7, 0]
    _tmp55 = (
        -_tmp0 * _tmp42
        + _tmp16 * _tmp43
        - 0.0825 * _tmp24
        + _tmp27 * _tmp44
        - _tmp40 * _tmp9
        + _tmp41 * _tmp5
        + _tmp46 * _tmp5
        + _tmp48 * _tmp5
        - _tmp5 * _tmp50
        + _tmp54
        * (-_tmp30 * _tmp51 + _tmp30 * _tmp52 + _tmp37 * _tmp53 + 0.70710678118623 * _tmp39)
        - 0.62
    )
    _tmp56 = 0.010606601717803 * _tmp31
    _tmp57 = 0.0106066017177935 * _tmp33
    _tmp58 = 0.1954 * _tmp28
    _tmp59 = 0.1954 * _tmp17
    _tmp60 = 0.010606601717803 * _tmp33
    _tmp61 = _tmp20 * _tmp4 + _tmp21
    _tmp62 = 1.0 * _tmp0 * _tmp25 + 1.0 * _tmp14 * _tmp61
    _tmp63 = 1.0 * _tmp3 * _tmp4 - 1.0 * _tmp8
    _tmp64 = -_tmp19 * _tmp63 + _tmp23 * _tmp62
    _tmp65 = _tmp0 * _tmp15 - _tmp11 * _tmp61
    _tmp66 = _tmp18 * _tmp65 + _tmp29 * _tmp64
    _tmp67 = _tmp33 * _tmp66
    _tmp68 = _tmp19 * _tmp62 + _tmp23 * _tmp63
    _tmp69 = _tmp31 * _tmp68
    _tmp70 = (
        _tmp0 * _tmp41
        + _tmp0 * _tmp46
        + _tmp0 * _tmp48
        - _tmp0 * _tmp50
        - 0.0825 * _tmp13 * _tmp61
        - _tmp40 * _tmp61
        + _tmp42 * _tmp5
        + _tmp43 * _tmp65
        + _tmp44 * _tmp64
        + _tmp54
        * (
            -_tmp51 * _tmp66
            + _tmp53 * _tmp68
            + 0.70710678118623 * _tmp67
            + 0.70710678118623 * _tmp69
        )
    )
    _tmp71 = _tmp10 * _tmp4
    _tmp72 = -1.0 * _tmp12 * _tmp13 * _tmp7 + 1.0 * _tmp71
    _tmp73 = _tmp12 * _tmp2
    _tmp74 = _tmp19 * _tmp73 + _tmp23 * _tmp72
    _tmp75 = _tmp14 * _tmp4 + _tmp49 * _tmp7
    _tmp76 = _tmp18 * _tmp75 + _tmp29 * _tmp74
    _tmp77 = _tmp19 * _tmp72 - _tmp23 * _tmp73
    _tmp78 = _tmp31 * _tmp77
    _tmp79 = _tmp12 * _tmp45
    _tmp80 = (
        _tmp12 * _tmp40 * _tmp6
        + _tmp13 * _tmp79
        + _tmp4 * _tmp47
        + 0.316 * _tmp4
        + _tmp43 * _tmp75
        + _tmp44 * _tmp74
        + _tmp54
        * (-_tmp51 * _tmp76 + _tmp52 * _tmp76 + _tmp53 * _tmp77 + 0.70710678118623 * _tmp78)
        - 0.0825 * _tmp71
        - _tmp79
        + 0.358
    )

    # Output terms
    _out = casadi.blockcat(
        [
            [
                -_tmp16 * _tmp35
                + _tmp27 * _tmp36
                - _tmp30 * _tmp32
                + _tmp30 * _tmp34
                + _tmp37 * _tmp38
                + 0.00494974746830361 * _tmp39
                + _tmp55,
                -_tmp32 * _tmp66
                - _tmp35 * _tmp65
                + _tmp36 * _tmp64
                + _tmp38 * _tmp68
                + 0.00494974746830361 * _tmp67
                + 0.00494974746830361 * _tmp69
                + _tmp70,
                -_tmp32 * _tmp76
                + _tmp34 * _tmp76
                - _tmp35 * _tmp75
                + _tmp36 * _tmp74
                + _tmp38 * _tmp77
                + 0.00494974746830361 * _tmp78
                + _tmp80,
            ],
            [
                -_tmp16 * _tmp58
                + _tmp27 * _tmp59
                - _tmp30 * _tmp56
                + _tmp30 * _tmp57
                + _tmp37 * _tmp60
                + 0.0106066017177935 * _tmp39
                + _tmp55,
                -_tmp56 * _tmp66
                - _tmp58 * _tmp65
                + _tmp59 * _tmp64
                + _tmp60 * _tmp68
                + 0.0106066017177935 * _tmp67
                + 0.0106066017177935 * _tmp69
                + _tmp70,
                -_tmp56 * _tmp76
                + _tmp57 * _tmp76
                - _tmp58 * _tmp75
                + _tmp59 * _tmp74
                + _tmp60 * _tmp77
                + 0.0106066017177935 * _tmp78
                + _tmp80,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_leftfinger_vision = casadi.Function(
    "panda_leftfinger_vision",
    [_in0_mx],
    [panda_leftfinger_vision(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
