# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_link8_vision(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23


    """

    # Total ops: 210

    # Input arrays

    # Intermediate terms (70)
    _tmp0 = casadi.sin(_in0[3, 0])
    _tmp1 = casadi.sin(_in0[0, 0])
    _tmp2 = casadi.sin(_in0[2, 0])
    _tmp3 = 1.0 * _tmp2
    _tmp4 = _tmp1 * _tmp3
    _tmp5 = casadi.cos(_in0[1, 0])
    _tmp6 = casadi.cos(_in0[0, 0])
    _tmp7 = casadi.cos(_in0[2, 0])
    _tmp8 = 1.0 * _tmp7
    _tmp9 = _tmp6 * _tmp8
    _tmp10 = -_tmp4 + _tmp5 * _tmp9
    _tmp11 = _tmp0 * _tmp10
    _tmp12 = casadi.sin(_in0[1, 0])
    _tmp13 = casadi.cos(_in0[3, 0])
    _tmp14 = 1.0 * _tmp13
    _tmp15 = _tmp12 * _tmp14
    _tmp16 = -1.0 * _tmp11 + _tmp15 * _tmp6
    _tmp17 = casadi.sin(_in0[5, 0])
    _tmp18 = 1.0 * _tmp17
    _tmp19 = casadi.sin(_in0[4, 0])
    _tmp20 = _tmp1 * _tmp8
    _tmp21 = _tmp3 * _tmp6
    _tmp22 = 1.0 * _tmp20 + 1.0 * _tmp21 * _tmp5
    _tmp23 = casadi.cos(_in0[4, 0])
    _tmp24 = _tmp10 * _tmp13
    _tmp25 = _tmp0 * _tmp12
    _tmp26 = 1.0 * _tmp25
    _tmp27 = 1.0 * _tmp24 + 1.0 * _tmp26 * _tmp6
    _tmp28 = -_tmp19 * _tmp22 + _tmp23 * _tmp27
    _tmp29 = casadi.cos(_in0[5, 0])
    _tmp30 = 1.0 * _tmp29
    _tmp31 = _tmp16 * _tmp18 + _tmp28 * _tmp30
    _tmp32 = 0.042 * casadi.sin(_in0[6, 0])
    _tmp33 = 0.042 * casadi.cos(_in0[6, 0])
    _tmp34 = _tmp16 * _tmp29
    _tmp35 = 0.087 * _tmp17
    _tmp36 = _tmp19 * _tmp27 + _tmp22 * _tmp23
    _tmp37 = 0.316 * _tmp12
    _tmp38 = 0.0825 * _tmp2
    _tmp39 = 0.088 * _tmp17
    _tmp40 = 0.088 * _tmp29
    _tmp41 = _tmp5 * _tmp7
    _tmp42 = 0.0825 * _tmp6
    _tmp43 = 0.384 * _tmp13
    _tmp44 = _tmp12 * _tmp43
    _tmp45 = (
        -_tmp1 * _tmp38
        - 0.384 * _tmp11
        + _tmp16 * _tmp39
        - 0.0825 * _tmp24
        - _tmp25 * _tmp42
        + _tmp28 * _tmp40
        + _tmp37 * _tmp6
        + _tmp41 * _tmp42
        + _tmp44 * _tmp6
        - 0.62
    )
    _tmp46 = 0.107 * _tmp17
    _tmp47 = _tmp20 * _tmp5 + _tmp21
    _tmp48 = 1.0 * _tmp1 * _tmp26 + 1.0 * _tmp14 * _tmp47
    _tmp49 = 1.0 * _tmp4 * _tmp5 - 1.0 * _tmp9
    _tmp50 = -_tmp19 * _tmp49 + _tmp23 * _tmp48
    _tmp51 = _tmp0 * _tmp47
    _tmp52 = _tmp1 * _tmp15 - 1.0 * _tmp51
    _tmp53 = _tmp18 * _tmp52 + _tmp30 * _tmp50
    _tmp54 = _tmp29 * _tmp52
    _tmp55 = _tmp19 * _tmp48 + _tmp23 * _tmp49
    _tmp56 = 0.0825 * _tmp1
    _tmp57 = (
        _tmp1 * _tmp37
        + _tmp1 * _tmp44
        - 0.0825 * _tmp13 * _tmp47
        - _tmp25 * _tmp56
        + _tmp38 * _tmp6
        + _tmp39 * _tmp52
        + _tmp40 * _tmp50
        + _tmp41 * _tmp56
        - 0.384 * _tmp51
    )
    _tmp58 = _tmp0 * _tmp5
    _tmp59 = _tmp12 * _tmp7
    _tmp60 = -1.0 * _tmp14 * _tmp59 + 1.0 * _tmp58
    _tmp61 = _tmp12 * _tmp3
    _tmp62 = _tmp19 * _tmp61 + _tmp23 * _tmp60
    _tmp63 = _tmp0 * _tmp59
    _tmp64 = _tmp14 * _tmp5 + 1.0 * _tmp63
    _tmp65 = _tmp18 * _tmp64 + _tmp30 * _tmp62
    _tmp66 = _tmp19 * _tmp60 - _tmp23 * _tmp61
    _tmp67 = _tmp29 * _tmp64
    _tmp68 = 0.0825 * _tmp59
    _tmp69 = (
        _tmp13 * _tmp68
        + _tmp39 * _tmp64
        + _tmp40 * _tmp62
        + _tmp43 * _tmp5
        + 0.316 * _tmp5
        - 0.0825 * _tmp58
        + 0.384 * _tmp63
        - _tmp68
        + 0.358
    )

    # Output terms
    _out = casadi.blockcat(
        [
            [
                _tmp28 * _tmp35
                - _tmp31 * _tmp32
                + _tmp31 * _tmp33
                + _tmp32 * _tmp36
                + _tmp33 * _tmp36
                - 0.087 * _tmp34
                + _tmp45,
                -_tmp32 * _tmp53
                + _tmp32 * _tmp55
                + _tmp33 * _tmp53
                + _tmp33 * _tmp55
                + _tmp35 * _tmp50
                - 0.087 * _tmp54
                + _tmp57,
                -_tmp32 * _tmp65
                + _tmp32 * _tmp66
                + _tmp33 * _tmp65
                + _tmp33 * _tmp66
                + _tmp35 * _tmp62
                - 0.087 * _tmp67
                + _tmp69,
            ],
            [
                _tmp28 * _tmp46 - 0.107 * _tmp34 + _tmp45,
                _tmp46 * _tmp50 - 0.107 * _tmp54 + _tmp57,
                _tmp46 * _tmp62 - 0.107 * _tmp67 + _tmp69,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_link8_vision = casadi.Function(
    "panda_link8_vision",
    [_in0_mx],
    [panda_link8_vision(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
