# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import torch


class TensorKwargs(T.TypedDict):
    """
    TypedDict representing args that will be passed to any torch.tensor calls
    """

    device: torch.device
    dtype: torch.dtype


def _broadcast_and_stack(tensors, dim=-1):
    # type: (T.List[torch.Tensor], int) -> torch.Tensor
    """
    broadcast tensors to common shape then stack along new dimension
    """

    broadcast_shape = torch.broadcast_shapes(*(x.size() for x in tensors))
    broadcast_tensors = [x.broadcast_to(broadcast_shape) for x in tensors]

    return torch.stack(broadcast_tensors, dim=dim)


def group_3(_in0, tensor_kwargs=None):
    # type: (torch.Tensor, TensorKwargs) -> torch.Tensor
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23

    The types for inputs and outputs above are the shapes of the symbolic matrices this function was
    generated from.  Tensors for both inputs and outputs are expected to have dimensions as follows:

    - (..., N, M) for sf.Matrix types of shape (N, M) where N != 1 and M != 1
    - (..., N) for sf.Matrix types of shape (N, M) where N != 1 and M == 1 (i.e. column vectors)
    - (..., M) for sf.Matrix types of shape (N, M) where N == 1 and M != 1 (i.e. row vectors)
    - (...) for sf.Matrix types of shape (1, 1) and sf.Scalar types

    Where `...` is an arbitrary number of batch dimensions that can be present on the front of input
    tensors.  The outputs will have the same batch dimensions as the inputs.

    The tensor_kwargs argument can be used to set the device and dtype to use.  If not provided, it will
    default to the device and dtype of the first input tensor, or the empty dict if there are no inputs.
    """

    # Total ops: 118

    # Deduce expected tensor device and dtype if not provided
    if tensor_kwargs is None:
        tensor_kwargs = {"device": _in0.device, "dtype": _in0.dtype}

    # Input arrays

    cte_1 = torch.tensor(0.144, **tensor_kwargs)
    cte_2 = torch.tensor(0.535, **tensor_kwargs)
    cte_3 = torch.tensor(0.358, **tensor_kwargs)
    cte_4 = torch.tensor(0.0825, **tensor_kwargs)
    cte_5 = torch.tensor(0.07, **tensor_kwargs)
    cte_6 = torch.tensor(1.0, **tensor_kwargs)
    cte_7 = torch.tensor(0.384, **tensor_kwargs)
    cte_8 = torch.tensor(0.316, **tensor_kwargs)

    # Intermediate terms (39)
    _tmp0 = torch.sin(_in0[..., 0])
    _tmp1 = torch.sin(_in0[..., 2])
    _tmp2 = cte_6 * _tmp1
    _tmp3 = _tmp0 * _tmp2
    _tmp4 = torch.cos(_in0[..., 1])
    _tmp5 = torch.cos(_in0[..., 0])
    _tmp6 = torch.cos(_in0[..., 2])
    _tmp7 = cte_6 * _tmp6
    _tmp8 = _tmp5 * _tmp7
    _tmp9 = _tmp3 - _tmp4 * _tmp8
    _tmp10 = torch.sin(_in0[..., 3])
    _tmp11 = cte_1 * _tmp10
    _tmp12 = torch.sin(_in0[..., 1])
    _tmp13 = torch.cos(_in0[..., 3])
    _tmp14 = _tmp12 * _tmp13
    _tmp15 = cte_1 * _tmp14
    _tmp16 = _tmp13 * _tmp9
    _tmp17 = cte_8 * _tmp12
    _tmp18 = cte_4 * _tmp1
    _tmp19 = cte_4 * _tmp6
    _tmp20 = _tmp19 * _tmp4
    _tmp21 = _tmp10 * _tmp12
    _tmp22 = _tmp21 * _tmp5
    _tmp23 = (
        _tmp0 * _tmp18
        - cte_4 * _tmp16
        - _tmp17 * _tmp5
        - _tmp20 * _tmp5
        + cte_4 * _tmp22
        + cte_2
    )
    _tmp24 = cte_7 * _tmp10
    _tmp25 = cte_5 * torch.sin(_in0[..., 4])
    _tmp26 = cte_7 * _tmp14
    _tmp27 = _tmp0 * _tmp7
    _tmp28 = _tmp2 * _tmp5
    _tmp29 = cte_5 * torch.cos(_in0[..., 4])
    _tmp30 = -_tmp27 * _tmp4 - _tmp28
    _tmp31 = _tmp0 * _tmp21
    _tmp32 = _tmp13 * _tmp30
    _tmp33 = (
        -_tmp0 * _tmp17
        - _tmp0 * _tmp20
        - _tmp18 * _tmp5
        + cte_4 * _tmp31
        - cte_4 * _tmp32
    )
    _tmp34 = _tmp13 * _tmp4
    _tmp35 = _tmp12 * _tmp6
    _tmp36 = _tmp10 * _tmp4
    _tmp37 = _tmp12 * _tmp19
    _tmp38 = (
        _tmp13 * _tmp37
        - cte_4 * _tmp36
        - _tmp37
        + cte_8 * _tmp4
        + cte_3
    )

    # Output terms
    _out = _broadcast_and_stack(
        [
            _broadcast_and_stack(
                [
                    -_tmp11 * _tmp9 - _tmp15 * _tmp5 + _tmp23,
                    _tmp23
                    - _tmp24 * _tmp9
                    - _tmp25
                    * (
                        cte_6 * _tmp16
                        - cte_6 * _tmp22
                    )
                    - _tmp26 * _tmp5
                    - _tmp29 * (-_tmp27 - _tmp28 * _tmp4),
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    -_tmp0 * _tmp15 - _tmp11 * _tmp30 + _tmp33,
                    -_tmp0 * _tmp26
                    - _tmp24 * _tmp30
                    - _tmp25
                    * (
                        -cte_6 * _tmp31
                        + cte_6 * _tmp32
                    )
                    - _tmp29 * (-_tmp3 * _tmp4 + _tmp8)
                    + _tmp33,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _tmp11 * _tmp35 + cte_1 * _tmp34 + _tmp38,
                    _tmp1 * _tmp12 * _tmp29
                    + _tmp24 * _tmp35
                    - _tmp25 * (-_tmp14 * _tmp7 + cte_6 * _tmp36)
                    + cte_7 * _tmp34
                    + _tmp38,
                ],
                dim=-1,
            ),
        ],
        dim=-1,
    )

    return _out
