# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import torch


class TensorKwargs(T.TypedDict):
    """
    TypedDict representing args that will be passed to any torch.tensor calls
    """

    device: torch.device
    dtype: torch.dtype


def _broadcast_and_stack(tensors, dim=-1):
    # type: (T.List[torch.Tensor], int) -> torch.Tensor
    """
    broadcast tensors to common shape then stack along new dimension
    """

    broadcast_shape = torch.broadcast_shapes(*(x.size() for x in tensors))
    broadcast_tensors = [x.broadcast_to(broadcast_shape) for x in tensors]

    return torch.stack(broadcast_tensors, dim=dim)


def panda_hand_collision(_in0, tensor_kwargs=None):
    # type: (torch.Tensor, TensorKwargs) -> torch.Tensor
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix93

    The types for inputs and outputs above are the shapes of the symbolic matrices this function was
    generated from.  Tensors for both inputs and outputs are expected to have dimensions as follows:

    - (..., N, M) for sf.Matrix types of shape (N, M) where N != 1 and M != 1
    - (..., N) for sf.Matrix types of shape (N, M) where N != 1 and M == 1 (i.e. column vectors)
    - (..., M) for sf.Matrix types of shape (N, M) where N == 1 and M != 1 (i.e. row vectors)
    - (...) for sf.Matrix types of shape (1, 1) and sf.Scalar types

    Where `...` is an arbitrary number of batch dimensions that can be present on the front of input
    tensors.  The outputs will have the same batch dimensions as the inputs.

    The tensor_kwargs argument can be used to set the device and dtype to use.  If not provided, it will
    default to the device and dtype of the first input tensor, or the empty dict if there are no inputs.
    """

    # Total ops: 352

    # Deduce expected tensor device and dtype if not provided
    if tensor_kwargs is None:
        tensor_kwargs = {"device": _in0.device, "dtype": _in0.dtype}

    # Input arrays

    cte_1 = torch.tensor(0.0636396103067607, **tensor_kwargs)
    cte_2 = torch.tensor(0.535, **tensor_kwargs)
    cte_3 = torch.tensor(0.207, **tensor_kwargs)
    cte_4 = torch.tensor(0.358, **tensor_kwargs)
    cte_5 = torch.tensor(0.0825, **tensor_kwargs)
    cte_6 = torch.tensor(0.122, **tensor_kwargs)
    cte_7 = torch.tensor(0.0848528137424237, **tensor_kwargs)
    cte_8 = torch.tensor(0.0848528137423477, **tensor_kwargs)
    cte_9 = torch.tensor(1.0, **tensor_kwargs)
    cte_10 = torch.tensor(0.0212132034356059, **tensor_kwargs)
    cte_11 = torch.tensor(0.088, **tensor_kwargs)
    cte_12 = torch.tensor(0.0424264068711738, **tensor_kwargs)
    cte_13 = torch.tensor(0.0212132034355869, **tensor_kwargs)
    cte_14 = torch.tensor(0.384, **tensor_kwargs)
    cte_15 = torch.tensor(0.0636396103068178, **tensor_kwargs)
    cte_16 = torch.tensor(0.0424264068712119, **tensor_kwargs)
    cte_17 = torch.tensor(0.137, **tensor_kwargs)
    cte_18 = torch.tensor(0.316, **tensor_kwargs)

    # Intermediate terms (105)
    _tmp0 = torch.cos(_in0[..., 4])
    _tmp1 = torch.sin(_in0[..., 0])
    _tmp2 = torch.sin(_in0[..., 2])
    _tmp3 = cte_9 * _tmp2
    _tmp4 = _tmp1 * _tmp3
    _tmp5 = torch.cos(_in0[..., 1])
    _tmp6 = torch.cos(_in0[..., 0])
    _tmp7 = torch.cos(_in0[..., 2])
    _tmp8 = cte_9 * _tmp7
    _tmp9 = _tmp6 * _tmp8
    _tmp10 = _tmp4 - _tmp5 * _tmp9
    _tmp11 = torch.cos(_in0[..., 3])
    _tmp12 = cte_9 * _tmp11
    _tmp13 = torch.sin(_in0[..., 3])
    _tmp14 = cte_9 * _tmp13
    _tmp15 = torch.sin(_in0[..., 1])
    _tmp16 = _tmp15 * _tmp6
    _tmp17 = (
        cte_9 * _tmp10 * _tmp12
        - cte_9 * _tmp14 * _tmp16
    )
    _tmp18 = torch.sin(_in0[..., 4])
    _tmp19 = _tmp1 * _tmp8
    _tmp20 = _tmp3 * _tmp6
    _tmp21 = (
        -cte_9 * _tmp19
        - cte_9 * _tmp20 * _tmp5
    )
    _tmp22 = _tmp0 * _tmp17 - _tmp18 * _tmp21
    _tmp23 = torch.sin(_in0[..., 5])
    _tmp24 = cte_6 * _tmp23
    _tmp25 = torch.cos(_in0[..., 5])
    _tmp26 = -_tmp10 * _tmp14 - _tmp12 * _tmp16
    _tmp27 = _tmp25 * _tmp26
    _tmp28 = cte_14 * _tmp13
    _tmp29 = cte_5 * _tmp11
    _tmp30 = _tmp22 * _tmp25
    _tmp31 = cte_18 * _tmp15
    _tmp32 = cte_5 * _tmp2
    _tmp33 = _tmp5 * _tmp7
    _tmp34 = cte_14 * _tmp11
    _tmp35 = _tmp23 * _tmp26
    _tmp36 = (
        _tmp1 * _tmp32
        - _tmp10 * _tmp28
        - _tmp10 * _tmp29
        + cte_5 * _tmp13 * _tmp16
        - _tmp16 * _tmp34
        + cte_11 * _tmp30
        - _tmp31 * _tmp6
        - cte_5 * _tmp33 * _tmp6
        + cte_11 * _tmp35
        + cte_2
    )
    _tmp37 = torch.cos(_in0[..., 6])
    _tmp38 = _tmp0 * _tmp21 + _tmp17 * _tmp18
    _tmp39 = _tmp37 * _tmp38
    _tmp40 = cte_16 * _tmp39
    _tmp41 = torch.sin(_in0[..., 6])
    _tmp42 = _tmp38 * _tmp41
    _tmp43 = cte_12 * _tmp42
    _tmp44 = (
        cte_9 * _tmp30 + cte_9 * _tmp35
    )
    _tmp45 = _tmp41 * _tmp44
    _tmp46 = cte_16 * _tmp45
    _tmp47 = _tmp37 * _tmp44
    _tmp48 = cte_12 * _tmp47
    _tmp49 = -_tmp40 - _tmp43 + _tmp46 - _tmp48
    _tmp50 = cte_17 * _tmp23
    _tmp51 = cte_17 * _tmp25
    _tmp52 = _tmp22 * _tmp50 - _tmp26 * _tmp51 + _tmp36
    _tmp53 = cte_3 * _tmp23
    _tmp54 = _tmp22 * _tmp53 - cte_3 * _tmp27 + _tmp36
    _tmp55 = cte_16 * _tmp41
    _tmp56 = _tmp1 * _tmp15
    _tmp57 = -_tmp19 * _tmp5 - _tmp20
    _tmp58 = -_tmp12 * _tmp56 - _tmp14 * _tmp57
    _tmp59 = _tmp25 * _tmp58
    _tmp60 = (
        -cte_9 * _tmp4 * _tmp5
        + cte_9 * _tmp9
    )
    _tmp61 = (
        cte_9 * _tmp12 * _tmp57
        - cte_9 * _tmp14 * _tmp56
    )
    _tmp62 = _tmp0 * _tmp61 - _tmp18 * _tmp60
    _tmp63 = _tmp23 * _tmp58
    _tmp64 = cte_5 * _tmp1
    _tmp65 = _tmp25 * _tmp62
    _tmp66 = (
        -_tmp1 * _tmp31
        + _tmp13 * _tmp15 * _tmp64
        - _tmp28 * _tmp57
        - _tmp29 * _tmp57
        - _tmp32 * _tmp6
        - _tmp33 * _tmp64
        - _tmp34 * _tmp56
        + cte_11 * _tmp63
        + cte_11 * _tmp65
    )
    _tmp67 = (
        cte_9 * _tmp63 + cte_9 * _tmp65
    )
    _tmp68 = _tmp55 * _tmp67
    _tmp69 = _tmp37 * _tmp67
    _tmp70 = cte_12 * _tmp69
    _tmp71 = _tmp0 * _tmp60 + _tmp18 * _tmp61
    _tmp72 = cte_12 * _tmp71
    _tmp73 = _tmp41 * _tmp72
    _tmp74 = _tmp37 * _tmp71
    _tmp75 = cte_16 * _tmp74
    _tmp76 = _tmp68 - _tmp70 - _tmp73 - _tmp75
    _tmp77 = _tmp50 * _tmp62 - _tmp51 * _tmp58 + _tmp66
    _tmp78 = _tmp53 * _tmp62 - cte_3 * _tmp59 + _tmp66
    _tmp79 = _tmp41 * _tmp67
    _tmp80 = _tmp41 * _tmp71
    _tmp81 = _tmp13 * _tmp5
    _tmp82 = _tmp15 * _tmp7
    _tmp83 = (
        -cte_9 * _tmp12 * _tmp82
        + cte_9 * _tmp81
    )
    _tmp84 = _tmp15 * _tmp3
    _tmp85 = _tmp0 * _tmp83 + _tmp18 * _tmp84
    _tmp86 = _tmp12 * _tmp5 + _tmp14 * _tmp82
    _tmp87 = _tmp25 * _tmp86
    _tmp88 = cte_5 * _tmp82
    _tmp89 = _tmp25 * _tmp85
    _tmp90 = _tmp23 * _tmp86
    _tmp91 = (
        _tmp11 * _tmp88
        + _tmp28 * _tmp82
        + _tmp34 * _tmp5
        + cte_18 * _tmp5
        - cte_5 * _tmp81
        - _tmp88
        + cte_11 * _tmp89
        + cte_11 * _tmp90
        + cte_4
    )
    _tmp92 = (
        cte_9 * _tmp89 + cte_9 * _tmp90
    )
    _tmp93 = _tmp37 * _tmp92
    _tmp94 = cte_12 * _tmp93
    _tmp95 = _tmp41 * _tmp92
    _tmp96 = cte_16 * _tmp95
    _tmp97 = -_tmp0 * _tmp84 + _tmp18 * _tmp83
    _tmp98 = _tmp37 * _tmp97
    _tmp99 = cte_16 * _tmp98
    _tmp100 = _tmp41 * _tmp97
    _tmp101 = cte_12 * _tmp100
    _tmp102 = -_tmp101 - _tmp94 + _tmp96 - _tmp99
    _tmp103 = _tmp50 * _tmp85 - _tmp51 * _tmp86 + _tmp91
    _tmp104 = _tmp53 * _tmp85 - cte_3 * _tmp87 + _tmp91

    # Output terms
    _out = _broadcast_and_stack(
        [
            _broadcast_and_stack(
                [
                    _tmp22 * _tmp24
                    - cte_6 * _tmp27
                    + _tmp36
                    + _tmp49,
                    _tmp49 + _tmp52,
                    _tmp52,
                    _tmp40 + _tmp43 - _tmp46 + _tmp48 + _tmp52,
                    _tmp54,
                    cte_13 * _tmp39
                    - cte_10 * _tmp42
                    - cte_13 * _tmp45
                    - cte_10 * _tmp47
                    + _tmp54,
                    -_tmp38 * _tmp55
                    + cte_12 * _tmp39
                    - cte_12 * _tmp45
                    - cte_16 * _tmp47
                    + _tmp54,
                    cte_1 * _tmp39
                    - cte_15 * _tmp42
                    - cte_1 * _tmp45
                    - cte_15 * _tmp47
                    + _tmp54,
                    cte_8 * _tmp39
                    - cte_7 * _tmp42
                    - cte_8 * _tmp45
                    - cte_7 * _tmp47
                    + _tmp54,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _tmp24 * _tmp62
                    - cte_6 * _tmp59
                    + _tmp66
                    + _tmp76,
                    _tmp76 + _tmp77,
                    _tmp77,
                    -_tmp68 + _tmp70 + _tmp73 + _tmp75 + _tmp77,
                    _tmp78,
                    -cte_10 * _tmp69
                    + cte_13 * _tmp74
                    + _tmp78
                    - cte_13 * _tmp79
                    - cte_10 * _tmp80,
                    _tmp37 * _tmp72
                    - _tmp55 * _tmp71
                    - cte_16 * _tmp69
                    + _tmp78
                    - cte_12 * _tmp79,
                    -cte_15 * _tmp69
                    + cte_1 * _tmp74
                    + _tmp78
                    - cte_1 * _tmp79
                    - cte_15 * _tmp80,
                    -cte_7 * _tmp69
                    + cte_8 * _tmp74
                    + _tmp78
                    - cte_8 * _tmp79
                    - cte_7 * _tmp80,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _tmp102
                    + _tmp24 * _tmp85
                    - cte_6 * _tmp87
                    + _tmp91,
                    _tmp102 + _tmp103,
                    _tmp103,
                    _tmp101 + _tmp103 + _tmp94 - _tmp96 + _tmp99,
                    _tmp104,
                    -cte_10 * _tmp100
                    + _tmp104
                    - cte_10 * _tmp93
                    - cte_13 * _tmp95
                    + cte_13 * _tmp98,
                    _tmp104
                    - _tmp55 * _tmp97
                    - cte_16 * _tmp93
                    - cte_12 * _tmp95
                    + cte_12 * _tmp98,
                    -cte_15 * _tmp100
                    + _tmp104
                    - cte_15 * _tmp93
                    - cte_1 * _tmp95
                    + cte_1 * _tmp98,
                    -cte_7 * _tmp100
                    + _tmp104
                    - cte_7 * _tmp93
                    - cte_8 * _tmp95
                    + cte_8 * _tmp98,
                ],
                dim=-1,
            ),
        ],
        dim=-1,
    )

    return _out
