# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import torch


class TensorKwargs(T.TypedDict):
    """
    TypedDict representing args that will be passed to any torch.tensor calls
    """

    device: torch.device
    dtype: torch.dtype


def _broadcast_and_stack(tensors, dim=-1):
    # type: (T.List[torch.Tensor], int) -> torch.Tensor
    """
    broadcast tensors to common shape then stack along new dimension
    """

    broadcast_shape = torch.broadcast_shapes(*(x.size() for x in tensors))
    broadcast_tensors = [x.broadcast_to(broadcast_shape) for x in tensors]

    return torch.stack(broadcast_tensors, dim=dim)


def group_4(_in0, tensor_kwargs=None):
    # type: (torch.Tensor, TensorKwargs) -> torch.Tensor
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix23

    The types for inputs and outputs above are the shapes of the symbolic matrices this function was
    generated from.  Tensors for both inputs and outputs are expected to have dimensions as follows:

    - (..., N, M) for sf.Matrix types of shape (N, M) where N != 1 and M != 1
    - (..., N) for sf.Matrix types of shape (N, M) where N != 1 and M == 1 (i.e. column vectors)
    - (..., M) for sf.Matrix types of shape (N, M) where N == 1 and M != 1 (i.e. row vectors)
    - (...) for sf.Matrix types of shape (1, 1) and sf.Scalar types

    Where `...` is an arbitrary number of batch dimensions that can be present on the front of input
    tensors.  The outputs will have the same batch dimensions as the inputs.

    The tensor_kwargs argument can be used to set the device and dtype to use.  If not provided, it will
    default to the device and dtype of the first input tensor, or the empty dict if there are no inputs.
    """

    # Total ops: 230

    # Deduce expected tensor device and dtype if not provided
    if tensor_kwargs is None:
        tensor_kwargs = {"device": _in0.device, "dtype": _in0.dtype}

    # Input arrays

    cte_1 = torch.tensor(0.0424264068712119, **tensor_kwargs)
    cte_2 = torch.tensor(0.0825, **tensor_kwargs)
    cte_3 = torch.tensor(0.0424264068711738, **tensor_kwargs)
    cte_4 = torch.tensor(0.122, **tensor_kwargs)
    cte_5 = torch.tensor(0.088, **tensor_kwargs)
    cte_6 = torch.tensor(0.384, **tensor_kwargs)
    cte_7 = torch.tensor(0.316, **tensor_kwargs)
    cte_8 = torch.tensor(0.535, **tensor_kwargs)
    cte_9 = torch.tensor(0.358, **tensor_kwargs)
    cte_10 = torch.tensor(0.08, **tensor_kwargs)
    cte_11 = torch.tensor(1.0, **tensor_kwargs)
    cte_12 = torch.tensor(0.03, **tensor_kwargs)

    # Intermediate terms (74)
    _tmp0 = torch.cos(_in0[..., 4])
    _tmp1 = torch.cos(_in0[..., 3])
    _tmp2 = torch.sin(_in0[..., 0])
    _tmp3 = torch.sin(_in0[..., 2])
    _tmp4 = cte_11 * _tmp3
    _tmp5 = _tmp2 * _tmp4
    _tmp6 = torch.cos(_in0[..., 1])
    _tmp7 = torch.cos(_in0[..., 0])
    _tmp8 = torch.cos(_in0[..., 2])
    _tmp9 = cte_11 * _tmp8
    _tmp10 = _tmp7 * _tmp9
    _tmp11 = -_tmp10 * _tmp6 + _tmp5
    _tmp12 = _tmp1 * _tmp11
    _tmp13 = torch.sin(_in0[..., 1])
    _tmp14 = torch.sin(_in0[..., 3])
    _tmp15 = cte_11 * _tmp14
    _tmp16 = _tmp13 * _tmp15
    _tmp17 = (
        cte_11 * _tmp12
        - cte_11 * _tmp16 * _tmp7
    )
    _tmp18 = torch.sin(_in0[..., 4])
    _tmp19 = _tmp2 * _tmp9
    _tmp20 = _tmp4 * _tmp7
    _tmp21 = (
        -cte_11 * _tmp19
        - cte_11 * _tmp20 * _tmp6
    )
    _tmp22 = _tmp0 * _tmp17 - _tmp18 * _tmp21
    _tmp23 = torch.sin(_in0[..., 5])
    _tmp24 = cte_12 * _tmp23
    _tmp25 = torch.cos(_in0[..., 5])
    _tmp26 = _tmp22 * _tmp25
    _tmp27 = cte_11 * _tmp1
    _tmp28 = _tmp13 * _tmp27
    _tmp29 = -_tmp11 * _tmp15 - _tmp28 * _tmp7
    _tmp30 = cte_12 * _tmp25
    _tmp31 = _tmp23 * _tmp29
    _tmp32 = cte_6 * _tmp14
    _tmp33 = cte_7 * _tmp13
    _tmp34 = cte_2 * _tmp3
    _tmp35 = cte_2 * _tmp6 * _tmp8
    _tmp36 = cte_6 * _tmp1
    _tmp37 = _tmp13 * _tmp36
    _tmp38 = cte_2 * _tmp13
    _tmp39 = _tmp14 * _tmp38
    _tmp40 = (
        -_tmp11 * _tmp32
        - cte_2 * _tmp12
        + _tmp2 * _tmp34
        - _tmp33 * _tmp7
        - _tmp35 * _tmp7
        - _tmp37 * _tmp7
        + _tmp39 * _tmp7
        + cte_8
    )
    _tmp41 = cte_4 * _tmp23
    _tmp42 = _tmp0 * _tmp21 + _tmp17 * _tmp18
    _tmp43 = torch.cos(_in0[..., 6])
    _tmp44 = cte_1 * _tmp43
    _tmp45 = torch.sin(_in0[..., 6])
    _tmp46 = cte_3 * _tmp45
    _tmp47 = cte_4 * _tmp25
    _tmp48 = cte_5 * _tmp23
    _tmp49 = (
        cte_11 * _tmp26 + cte_11 * _tmp31
    )
    _tmp50 = cte_1 * _tmp45
    _tmp51 = cte_3 * _tmp43
    _tmp52 = -_tmp19 * _tmp6 - _tmp20
    _tmp53 = -_tmp15 * _tmp52 - _tmp2 * _tmp28
    _tmp54 = _tmp23 * _tmp53
    _tmp55 = (
        cte_11 * _tmp10
        - cte_11 * _tmp5 * _tmp6
    )
    _tmp56 = (
        -cte_11 * _tmp16 * _tmp2
        + cte_11 * _tmp27 * _tmp52
    )
    _tmp57 = _tmp0 * _tmp56 - _tmp18 * _tmp55
    _tmp58 = _tmp25 * _tmp57
    _tmp59 = (
        -cte_2 * _tmp1 * _tmp52
        - _tmp2 * _tmp33
        - _tmp2 * _tmp35
        - _tmp2 * _tmp37
        + _tmp2 * _tmp39
        - _tmp32 * _tmp52
        - _tmp34 * _tmp7
    )
    _tmp60 = (
        cte_11 * _tmp54 + cte_11 * _tmp58
    )
    _tmp61 = _tmp0 * _tmp55 + _tmp18 * _tmp56
    _tmp62 = _tmp14 * _tmp6
    _tmp63 = _tmp13 * _tmp9
    _tmp64 = (
        -cte_11 * _tmp1 * _tmp63
        + cte_11 * _tmp62
    )
    _tmp65 = _tmp13 * _tmp4
    _tmp66 = _tmp0 * _tmp64 + _tmp18 * _tmp65
    _tmp67 = _tmp25 * _tmp66
    _tmp68 = _tmp14 * _tmp63 + _tmp27 * _tmp6
    _tmp69 = _tmp23 * _tmp68
    _tmp70 = _tmp38 * _tmp8
    _tmp71 = (
        _tmp1 * _tmp70
        + _tmp13 * _tmp32 * _tmp8
        + _tmp36 * _tmp6
        + cte_7 * _tmp6
        - cte_2 * _tmp62
        - _tmp70
        + cte_9
    )
    _tmp72 = (
        cte_11 * _tmp67 + cte_11 * _tmp69
    )
    _tmp73 = -_tmp0 * _tmp65 + _tmp18 * _tmp64

    # Output terms
    _out = _broadcast_and_stack(
        [
            _broadcast_and_stack(
                [
                    -_tmp22 * _tmp24
                    + cte_10 * _tmp26
                    + _tmp29 * _tmp30
                    + cte_10 * _tmp31
                    + _tmp40,
                    _tmp22 * _tmp41
                    + cte_5 * _tmp26
                    - _tmp29 * _tmp47
                    + _tmp29 * _tmp48
                    + _tmp40
                    - _tmp42 * _tmp44
                    - _tmp42 * _tmp46
                    + _tmp49 * _tmp50
                    - _tmp49 * _tmp51,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    -_tmp24 * _tmp57
                    + _tmp30 * _tmp53
                    + cte_10 * _tmp54
                    + cte_10 * _tmp58
                    + _tmp59,
                    _tmp41 * _tmp57
                    - _tmp44 * _tmp61
                    - _tmp46 * _tmp61
                    - _tmp47 * _tmp53
                    + _tmp50 * _tmp60
                    - _tmp51 * _tmp60
                    + cte_5 * _tmp54
                    + cte_5 * _tmp58
                    + _tmp59,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    -_tmp24 * _tmp66
                    + _tmp30 * _tmp68
                    + cte_10 * _tmp67
                    + cte_10 * _tmp69
                    + _tmp71,
                    _tmp41 * _tmp66
                    - _tmp44 * _tmp73
                    - _tmp46 * _tmp73
                    - _tmp47 * _tmp68
                    + _tmp48 * _tmp68
                    + _tmp50 * _tmp72
                    - _tmp51 * _tmp72
                    + cte_5 * _tmp67
                    + _tmp71,
                ],
                dim=-1,
            ),
        ],
        dim=-1,
    )

    return _out
