# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import torch


class TensorKwargs(T.TypedDict):
    """
    TypedDict representing args that will be passed to any torch.tensor calls
    """

    device: torch.device
    dtype: torch.dtype


def _broadcast_and_stack(tensors, dim=-1):
    # type: (T.List[torch.Tensor], int) -> torch.Tensor
    """
    broadcast tensors to common shape then stack along new dimension
    """

    broadcast_shape = torch.broadcast_shapes(*(x.size() for x in tensors))
    broadcast_tensors = [x.broadcast_to(broadcast_shape) for x in tensors]

    return torch.stack(broadcast_tensors, dim=dim)


def panda_link6_collision(_in0, tensor_kwargs=None):
    # type: (torch.Tensor, TensorKwargs) -> torch.Tensor
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix53

    The types for inputs and outputs above are the shapes of the symbolic matrices this function was
    generated from.  Tensors for both inputs and outputs are expected to have dimensions as follows:

    - (..., N, M) for sf.Matrix types of shape (N, M) where N != 1 and M != 1
    - (..., N) for sf.Matrix types of shape (N, M) where N != 1 and M == 1 (i.e. column vectors)
    - (..., M) for sf.Matrix types of shape (N, M) where N == 1 and M != 1 (i.e. row vectors)
    - (...) for sf.Matrix types of shape (1, 1) and sf.Scalar types

    Where `...` is an arbitrary number of batch dimensions that can be present on the front of input
    tensors.  The outputs will have the same batch dimensions as the inputs.

    The tensor_kwargs argument can be used to set the device and dtype to use.  If not provided, it will
    default to the device and dtype of the first input tensor, or the empty dict if there are no inputs.
    """

    # Total ops: 203

    # Deduce expected tensor device and dtype if not provided
    if tensor_kwargs is None:
        tensor_kwargs = {"device": _in0.device, "dtype": _in0.dtype}

    # Input arrays

    cte_1 = torch.tensor(0.0825, **tensor_kwargs)
    cte_2 = torch.tensor(0.01, **tensor_kwargs)
    cte_3 = torch.tensor(0.04, **tensor_kwargs)
    cte_4 = torch.tensor(0.384, **tensor_kwargs)
    cte_5 = torch.tensor(0.316, **tensor_kwargs)
    cte_6 = torch.tensor(0.535, **tensor_kwargs)
    cte_7 = torch.tensor(0.358, **tensor_kwargs)
    cte_8 = torch.tensor(0.08, **tensor_kwargs)
    cte_9 = torch.tensor(1.0, **tensor_kwargs)
    cte_10 = torch.tensor(0.03, **tensor_kwargs)

    # Intermediate terms (72)
    _tmp0 = torch.cos(_in0[..., 3])
    _tmp1 = torch.sin(_in0[..., 0])
    _tmp2 = torch.sin(_in0[..., 2])
    _tmp3 = cte_9 * _tmp2
    _tmp4 = _tmp1 * _tmp3
    _tmp5 = torch.cos(_in0[..., 1])
    _tmp6 = torch.cos(_in0[..., 0])
    _tmp7 = torch.cos(_in0[..., 2])
    _tmp8 = cte_9 * _tmp7
    _tmp9 = _tmp6 * _tmp8
    _tmp10 = _tmp4 - _tmp5 * _tmp9
    _tmp11 = cte_9 * _tmp10
    _tmp12 = torch.sin(_in0[..., 1])
    _tmp13 = torch.sin(_in0[..., 3])
    _tmp14 = _tmp12 * _tmp13
    _tmp15 = cte_9 * _tmp14
    _tmp16 = _tmp0 * _tmp11 - _tmp15 * _tmp6
    _tmp17 = torch.cos(_in0[..., 4])
    _tmp18 = cte_9 * _tmp17
    _tmp19 = _tmp1 * _tmp8
    _tmp20 = _tmp3 * _tmp6
    _tmp21 = -_tmp19 - _tmp20 * _tmp5
    _tmp22 = torch.sin(_in0[..., 4])
    _tmp23 = cte_9 * _tmp22
    _tmp24 = _tmp16 * _tmp18 - _tmp21 * _tmp23
    _tmp25 = torch.sin(_in0[..., 5])
    _tmp26 = cte_10 * _tmp25
    _tmp27 = torch.cos(_in0[..., 5])
    _tmp28 = cte_8 * _tmp27
    _tmp29 = _tmp0 * _tmp12
    _tmp30 = cte_9 * _tmp29
    _tmp31 = -_tmp11 * _tmp13 - _tmp30 * _tmp6
    _tmp32 = cte_10 * _tmp27
    _tmp33 = cte_8 * _tmp25
    _tmp34 = cte_4 * _tmp13
    _tmp35 = cte_1 * _tmp0
    _tmp36 = cte_5 * _tmp12
    _tmp37 = cte_1 * _tmp2
    _tmp38 = cte_1 * _tmp6
    _tmp39 = _tmp5 * _tmp7
    _tmp40 = cte_4 * _tmp29
    _tmp41 = (
        _tmp1 * _tmp37
        - _tmp10 * _tmp34
        - _tmp10 * _tmp35
        + _tmp14 * _tmp38
        - _tmp36 * _tmp6
        - _tmp38 * _tmp39
        - _tmp40 * _tmp6
        + cte_6
    )
    _tmp42 = cte_2 * _tmp25
    _tmp43 = cte_2 * _tmp27
    _tmp44 = cte_3 * _tmp27
    _tmp45 = cte_3 * _tmp25
    _tmp46 = _tmp24 * _tmp44 + _tmp31 * _tmp45 + _tmp41
    _tmp47 = _tmp16 * _tmp22
    _tmp48 = cte_2 * _tmp17
    _tmp49 = cte_10 * _tmp17
    _tmp50 = -_tmp19 * _tmp5 - _tmp20
    _tmp51 = cte_9 * _tmp50
    _tmp52 = -_tmp1 * _tmp30 - _tmp13 * _tmp51
    _tmp53 = -_tmp4 * _tmp5 + _tmp9
    _tmp54 = _tmp0 * _tmp51 - _tmp1 * _tmp15
    _tmp55 = _tmp18 * _tmp54 - _tmp23 * _tmp53
    _tmp56 = cte_1 * _tmp1
    _tmp57 = (
        -_tmp1 * _tmp36
        - _tmp1 * _tmp40
        + _tmp14 * _tmp56
        - _tmp34 * _tmp50
        - _tmp35 * _tmp50
        - _tmp37 * _tmp6
        - _tmp39 * _tmp56
    )
    _tmp58 = _tmp44 * _tmp55 + _tmp45 * _tmp52 + _tmp57
    _tmp59 = _tmp22 * _tmp54
    _tmp60 = _tmp13 * _tmp5
    _tmp61 = _tmp12 * _tmp7
    _tmp62 = cte_9 * _tmp61
    _tmp63 = -_tmp0 * _tmp62 + cte_9 * _tmp60
    _tmp64 = _tmp12 * _tmp22 * _tmp3 + _tmp18 * _tmp63
    _tmp65 = _tmp0 * _tmp5
    _tmp66 = _tmp13 * _tmp62 + cte_9 * _tmp65
    _tmp67 = cte_1 * _tmp61
    _tmp68 = (
        _tmp0 * _tmp67
        + _tmp34 * _tmp61
        + cte_5 * _tmp5
        - cte_1 * _tmp60
        + cte_4 * _tmp65
        - _tmp67
        + cte_7
    )
    _tmp69 = _tmp44 * _tmp64 + _tmp45 * _tmp66 + _tmp68
    _tmp70 = _tmp22 * _tmp63
    _tmp71 = _tmp12 * _tmp2

    # Output terms
    _out = _broadcast_and_stack(
        [
            _broadcast_and_stack(
                [
                    -_tmp24 * _tmp26 + _tmp24 * _tmp28 + _tmp31 * _tmp32 + _tmp31 * _tmp33 + _tmp41,
                    -_tmp24 * _tmp42 + _tmp31 * _tmp43 + _tmp46,
                    _tmp46,
                    _tmp21 * _tmp48 + _tmp41 + cte_2 * _tmp47,
                    -_tmp21 * _tmp49 + _tmp41 - cte_10 * _tmp47,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    -_tmp26 * _tmp55 + _tmp28 * _tmp55 + _tmp32 * _tmp52 + _tmp33 * _tmp52 + _tmp57,
                    -_tmp42 * _tmp55 + _tmp43 * _tmp52 + _tmp58,
                    _tmp58,
                    _tmp48 * _tmp53 + _tmp57 + cte_2 * _tmp59,
                    -_tmp49 * _tmp53 + _tmp57 - cte_10 * _tmp59,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    -_tmp26 * _tmp64 + _tmp28 * _tmp64 + _tmp32 * _tmp66 + _tmp33 * _tmp66 + _tmp68,
                    -_tmp42 * _tmp64 + _tmp43 * _tmp66 + _tmp69,
                    _tmp69,
                    -_tmp48 * _tmp71 + _tmp68 + cte_2 * _tmp70,
                    _tmp49 * _tmp71 + _tmp68 - cte_10 * _tmp70,
                ],
                dim=-1,
            ),
        ],
        dim=-1,
    )

    return _out
