# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_hand_vision(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix93


    """

    # Total ops: 352

    # Input arrays

    # Intermediate terms (105)
    _tmp0 = casadi.cos(_in0[4, 0])
    _tmp1 = casadi.sin(_in0[0, 0])
    _tmp2 = casadi.sin(_in0[2, 0])
    _tmp3 = 1.0 * _tmp2
    _tmp4 = _tmp1 * _tmp3
    _tmp5 = casadi.cos(_in0[1, 0])
    _tmp6 = casadi.cos(_in0[0, 0])
    _tmp7 = casadi.cos(_in0[2, 0])
    _tmp8 = 1.0 * _tmp7
    _tmp9 = _tmp6 * _tmp8
    _tmp10 = _tmp4 - _tmp5 * _tmp9
    _tmp11 = casadi.cos(_in0[3, 0])
    _tmp12 = 1.0 * _tmp11
    _tmp13 = casadi.sin(_in0[3, 0])
    _tmp14 = 1.0 * _tmp13
    _tmp15 = casadi.sin(_in0[1, 0])
    _tmp16 = _tmp15 * _tmp6
    _tmp17 = 1.0 * _tmp10 * _tmp12 - 1.0 * _tmp14 * _tmp16
    _tmp18 = casadi.sin(_in0[4, 0])
    _tmp19 = _tmp1 * _tmp8
    _tmp20 = _tmp3 * _tmp6
    _tmp21 = -1.0 * _tmp19 - 1.0 * _tmp20 * _tmp5
    _tmp22 = _tmp0 * _tmp17 - _tmp18 * _tmp21
    _tmp23 = casadi.sin(_in0[5, 0])
    _tmp24 = 0.122 * _tmp23
    _tmp25 = casadi.cos(_in0[5, 0])
    _tmp26 = -_tmp10 * _tmp14 - _tmp12 * _tmp16
    _tmp27 = _tmp25 * _tmp26
    _tmp28 = 0.384 * _tmp13
    _tmp29 = 0.0825 * _tmp11
    _tmp30 = _tmp22 * _tmp25
    _tmp31 = 0.316 * _tmp15
    _tmp32 = 0.0825 * _tmp2
    _tmp33 = _tmp5 * _tmp7
    _tmp34 = 0.384 * _tmp11
    _tmp35 = _tmp23 * _tmp26
    _tmp36 = (
        _tmp1 * _tmp32
        - _tmp10 * _tmp28
        - _tmp10 * _tmp29
        + 0.0825 * _tmp13 * _tmp16
        - _tmp16 * _tmp34
        + 0.088 * _tmp30
        - _tmp31 * _tmp6
        - 0.0825 * _tmp33 * _tmp6
        + 0.088 * _tmp35
        + 0.535
    )
    _tmp37 = casadi.cos(_in0[6, 0])
    _tmp38 = _tmp0 * _tmp21 + _tmp17 * _tmp18
    _tmp39 = _tmp37 * _tmp38
    _tmp40 = 0.0424264068712119 * _tmp39
    _tmp41 = casadi.sin(_in0[6, 0])
    _tmp42 = _tmp38 * _tmp41
    _tmp43 = 0.0424264068711738 * _tmp42
    _tmp44 = 1.0 * _tmp30 + 1.0 * _tmp35
    _tmp45 = _tmp41 * _tmp44
    _tmp46 = 0.0424264068712119 * _tmp45
    _tmp47 = _tmp37 * _tmp44
    _tmp48 = 0.0424264068711738 * _tmp47
    _tmp49 = -_tmp40 - _tmp43 + _tmp46 - _tmp48
    _tmp50 = 0.137 * _tmp23
    _tmp51 = 0.137 * _tmp25
    _tmp52 = _tmp22 * _tmp50 - _tmp26 * _tmp51 + _tmp36
    _tmp53 = 0.207 * _tmp23
    _tmp54 = _tmp22 * _tmp53 - 0.207 * _tmp27 + _tmp36
    _tmp55 = 0.0424264068712119 * _tmp41
    _tmp56 = _tmp1 * _tmp15
    _tmp57 = -_tmp19 * _tmp5 - _tmp20
    _tmp58 = -_tmp12 * _tmp56 - _tmp14 * _tmp57
    _tmp59 = _tmp25 * _tmp58
    _tmp60 = -1.0 * _tmp4 * _tmp5 + 1.0 * _tmp9
    _tmp61 = 1.0 * _tmp12 * _tmp57 - 1.0 * _tmp14 * _tmp56
    _tmp62 = _tmp0 * _tmp61 - _tmp18 * _tmp60
    _tmp63 = _tmp23 * _tmp58
    _tmp64 = 0.0825 * _tmp1
    _tmp65 = _tmp25 * _tmp62
    _tmp66 = (
        -_tmp1 * _tmp31
        + _tmp13 * _tmp15 * _tmp64
        - _tmp28 * _tmp57
        - _tmp29 * _tmp57
        - _tmp32 * _tmp6
        - _tmp33 * _tmp64
        - _tmp34 * _tmp56
        + 0.088 * _tmp63
        + 0.088 * _tmp65
    )
    _tmp67 = 1.0 * _tmp63 + 1.0 * _tmp65
    _tmp68 = _tmp55 * _tmp67
    _tmp69 = _tmp37 * _tmp67
    _tmp70 = 0.0424264068711738 * _tmp69
    _tmp71 = _tmp0 * _tmp60 + _tmp18 * _tmp61
    _tmp72 = 0.0424264068711738 * _tmp71
    _tmp73 = _tmp41 * _tmp72
    _tmp74 = _tmp37 * _tmp71
    _tmp75 = 0.0424264068712119 * _tmp74
    _tmp76 = _tmp68 - _tmp70 - _tmp73 - _tmp75
    _tmp77 = _tmp50 * _tmp62 - _tmp51 * _tmp58 + _tmp66
    _tmp78 = _tmp53 * _tmp62 - 0.207 * _tmp59 + _tmp66
    _tmp79 = _tmp41 * _tmp67
    _tmp80 = _tmp41 * _tmp71
    _tmp81 = _tmp13 * _tmp5
    _tmp82 = _tmp15 * _tmp7
    _tmp83 = -1.0 * _tmp12 * _tmp82 + 1.0 * _tmp81
    _tmp84 = _tmp15 * _tmp3
    _tmp85 = _tmp0 * _tmp83 + _tmp18 * _tmp84
    _tmp86 = _tmp12 * _tmp5 + _tmp14 * _tmp82
    _tmp87 = _tmp25 * _tmp86
    _tmp88 = 0.0825 * _tmp82
    _tmp89 = _tmp25 * _tmp85
    _tmp90 = _tmp23 * _tmp86
    _tmp91 = (
        _tmp11 * _tmp88
        + _tmp28 * _tmp82
        + _tmp34 * _tmp5
        + 0.316 * _tmp5
        - 0.0825 * _tmp81
        - _tmp88
        + 0.088 * _tmp89
        + 0.088 * _tmp90
        + 0.358
    )
    _tmp92 = 1.0 * _tmp89 + 1.0 * _tmp90
    _tmp93 = _tmp37 * _tmp92
    _tmp94 = 0.0424264068711738 * _tmp93
    _tmp95 = _tmp41 * _tmp92
    _tmp96 = 0.0424264068712119 * _tmp95
    _tmp97 = -_tmp0 * _tmp84 + _tmp18 * _tmp83
    _tmp98 = _tmp37 * _tmp97
    _tmp99 = 0.0424264068712119 * _tmp98
    _tmp100 = _tmp41 * _tmp97
    _tmp101 = 0.0424264068711738 * _tmp100
    _tmp102 = -_tmp101 - _tmp94 + _tmp96 - _tmp99
    _tmp103 = _tmp50 * _tmp85 - _tmp51 * _tmp86 + _tmp91
    _tmp104 = _tmp53 * _tmp85 - 0.207 * _tmp87 + _tmp91

    # Output terms
    _out = casadi.blockcat(
        [
            [
                _tmp22 * _tmp24 - 0.122 * _tmp27 + _tmp36 + _tmp49,
                _tmp24 * _tmp62 - 0.122 * _tmp59 + _tmp66 + _tmp76,
                _tmp102 + _tmp24 * _tmp85 - 0.122 * _tmp87 + _tmp91,
            ],
            [_tmp49 + _tmp52, _tmp76 + _tmp77, _tmp102 + _tmp103],
            [_tmp52, _tmp77, _tmp103],
            [
                _tmp40 + _tmp43 - _tmp46 + _tmp48 + _tmp52,
                -_tmp68 + _tmp70 + _tmp73 + _tmp75 + _tmp77,
                _tmp101 + _tmp103 + _tmp94 - _tmp96 + _tmp99,
            ],
            [_tmp54, _tmp78, _tmp104],
            [
                0.0212132034355869 * _tmp39
                - 0.0212132034356059 * _tmp42
                - 0.0212132034355869 * _tmp45
                - 0.0212132034356059 * _tmp47
                + _tmp54,
                -0.0212132034356059 * _tmp69
                + 0.0212132034355869 * _tmp74
                + _tmp78
                - 0.0212132034355869 * _tmp79
                - 0.0212132034356059 * _tmp80,
                -0.0212132034356059 * _tmp100
                + _tmp104
                - 0.0212132034356059 * _tmp93
                - 0.0212132034355869 * _tmp95
                + 0.0212132034355869 * _tmp98,
            ],
            [
                -_tmp38 * _tmp55
                + 0.0424264068711738 * _tmp39
                - 0.0424264068711738 * _tmp45
                - 0.0424264068712119 * _tmp47
                + _tmp54,
                _tmp37 * _tmp72
                - _tmp55 * _tmp71
                - 0.0424264068712119 * _tmp69
                + _tmp78
                - 0.0424264068711738 * _tmp79,
                _tmp104
                - _tmp55 * _tmp97
                - 0.0424264068712119 * _tmp93
                - 0.0424264068711738 * _tmp95
                + 0.0424264068711738 * _tmp98,
            ],
            [
                0.0636396103067607 * _tmp39
                - 0.0636396103068178 * _tmp42
                - 0.0636396103067607 * _tmp45
                - 0.0636396103068178 * _tmp47
                + _tmp54,
                -0.0636396103068178 * _tmp69
                + 0.0636396103067607 * _tmp74
                + _tmp78
                - 0.0636396103067607 * _tmp79
                - 0.0636396103068178 * _tmp80,
                -0.0636396103068178 * _tmp100
                + _tmp104
                - 0.0636396103068178 * _tmp93
                - 0.0636396103067607 * _tmp95
                + 0.0636396103067607 * _tmp98,
            ],
            [
                0.0848528137423477 * _tmp39
                - 0.0848528137424237 * _tmp42
                - 0.0848528137423477 * _tmp45
                - 0.0848528137424237 * _tmp47
                + _tmp54,
                -0.0848528137424237 * _tmp69
                + 0.0848528137423477 * _tmp74
                + _tmp78
                - 0.0848528137423477 * _tmp79
                - 0.0848528137424237 * _tmp80,
                -0.0848528137424237 * _tmp100
                + _tmp104
                - 0.0848528137424237 * _tmp93
                - 0.0848528137423477 * _tmp95
                + 0.0848528137423477 * _tmp98,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_hand_vision = casadi.Function(
    "panda_hand_vision",
    [_in0_mx],
    [panda_hand_vision(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
