# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import casadi


def panda_link6_vision(
    _in0,
):
    # type: (casadi.SX | casadi.MX | casadi.DM, ) -> casadi.SX | casadi.MX | casadi.DM
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix53


    """

    # Total ops: 203

    # Input arrays

    # Intermediate terms (72)
    _tmp0 = casadi.cos(_in0[3, 0])
    _tmp1 = casadi.sin(_in0[0, 0])
    _tmp2 = casadi.sin(_in0[2, 0])
    _tmp3 = 1.0 * _tmp2
    _tmp4 = _tmp1 * _tmp3
    _tmp5 = casadi.cos(_in0[1, 0])
    _tmp6 = casadi.cos(_in0[0, 0])
    _tmp7 = casadi.cos(_in0[2, 0])
    _tmp8 = 1.0 * _tmp7
    _tmp9 = _tmp6 * _tmp8
    _tmp10 = _tmp4 - _tmp5 * _tmp9
    _tmp11 = 1.0 * _tmp10
    _tmp12 = casadi.sin(_in0[1, 0])
    _tmp13 = casadi.sin(_in0[3, 0])
    _tmp14 = _tmp12 * _tmp13
    _tmp15 = 1.0 * _tmp14
    _tmp16 = _tmp0 * _tmp11 - _tmp15 * _tmp6
    _tmp17 = casadi.cos(_in0[4, 0])
    _tmp18 = 1.0 * _tmp17
    _tmp19 = _tmp1 * _tmp8
    _tmp20 = _tmp3 * _tmp6
    _tmp21 = -_tmp19 - _tmp20 * _tmp5
    _tmp22 = casadi.sin(_in0[4, 0])
    _tmp23 = 1.0 * _tmp22
    _tmp24 = _tmp16 * _tmp18 - _tmp21 * _tmp23
    _tmp25 = casadi.sin(_in0[5, 0])
    _tmp26 = 0.03 * _tmp25
    _tmp27 = casadi.cos(_in0[5, 0])
    _tmp28 = 0.08 * _tmp27
    _tmp29 = _tmp0 * _tmp12
    _tmp30 = 1.0 * _tmp29
    _tmp31 = -_tmp11 * _tmp13 - _tmp30 * _tmp6
    _tmp32 = 0.03 * _tmp27
    _tmp33 = 0.08 * _tmp25
    _tmp34 = 0.384 * _tmp13
    _tmp35 = 0.0825 * _tmp0
    _tmp36 = 0.316 * _tmp12
    _tmp37 = 0.0825 * _tmp2
    _tmp38 = 0.0825 * _tmp6
    _tmp39 = _tmp5 * _tmp7
    _tmp40 = 0.384 * _tmp29
    _tmp41 = (
        _tmp1 * _tmp37
        - _tmp10 * _tmp34
        - _tmp10 * _tmp35
        + _tmp14 * _tmp38
        - _tmp36 * _tmp6
        - _tmp38 * _tmp39
        - _tmp40 * _tmp6
        + 0.535
    )
    _tmp42 = 0.01 * _tmp25
    _tmp43 = 0.01 * _tmp27
    _tmp44 = 0.04 * _tmp27
    _tmp45 = 0.04 * _tmp25
    _tmp46 = _tmp24 * _tmp44 + _tmp31 * _tmp45 + _tmp41
    _tmp47 = _tmp16 * _tmp22
    _tmp48 = 0.01 * _tmp17
    _tmp49 = 0.03 * _tmp17
    _tmp50 = -_tmp19 * _tmp5 - _tmp20
    _tmp51 = 1.0 * _tmp50
    _tmp52 = -_tmp1 * _tmp30 - _tmp13 * _tmp51
    _tmp53 = -_tmp4 * _tmp5 + _tmp9
    _tmp54 = _tmp0 * _tmp51 - _tmp1 * _tmp15
    _tmp55 = _tmp18 * _tmp54 - _tmp23 * _tmp53
    _tmp56 = 0.0825 * _tmp1
    _tmp57 = (
        -_tmp1 * _tmp36
        - _tmp1 * _tmp40
        + _tmp14 * _tmp56
        - _tmp34 * _tmp50
        - _tmp35 * _tmp50
        - _tmp37 * _tmp6
        - _tmp39 * _tmp56
    )
    _tmp58 = _tmp44 * _tmp55 + _tmp45 * _tmp52 + _tmp57
    _tmp59 = _tmp22 * _tmp54
    _tmp60 = _tmp13 * _tmp5
    _tmp61 = _tmp12 * _tmp7
    _tmp62 = 1.0 * _tmp61
    _tmp63 = -_tmp0 * _tmp62 + 1.0 * _tmp60
    _tmp64 = _tmp12 * _tmp22 * _tmp3 + _tmp18 * _tmp63
    _tmp65 = _tmp0 * _tmp5
    _tmp66 = _tmp13 * _tmp62 + 1.0 * _tmp65
    _tmp67 = 0.0825 * _tmp61
    _tmp68 = (
        _tmp0 * _tmp67
        + _tmp34 * _tmp61
        + 0.316 * _tmp5
        - 0.0825 * _tmp60
        + 0.384 * _tmp65
        - _tmp67
        + 0.358
    )
    _tmp69 = _tmp44 * _tmp64 + _tmp45 * _tmp66 + _tmp68
    _tmp70 = _tmp22 * _tmp63
    _tmp71 = _tmp12 * _tmp2

    # Output terms
    _out = casadi.blockcat(
        [
            [
                -_tmp24 * _tmp26 + _tmp24 * _tmp28 + _tmp31 * _tmp32 + _tmp31 * _tmp33 + _tmp41,
                -_tmp26 * _tmp55 + _tmp28 * _tmp55 + _tmp32 * _tmp52 + _tmp33 * _tmp52 + _tmp57,
                -_tmp26 * _tmp64 + _tmp28 * _tmp64 + _tmp32 * _tmp66 + _tmp33 * _tmp66 + _tmp68,
            ],
            [
                -_tmp24 * _tmp42 + _tmp31 * _tmp43 + _tmp46,
                -_tmp42 * _tmp55 + _tmp43 * _tmp52 + _tmp58,
                -_tmp42 * _tmp64 + _tmp43 * _tmp66 + _tmp69,
            ],
            [_tmp46, _tmp58, _tmp69],
            [
                _tmp21 * _tmp48 + _tmp41 + 0.01 * _tmp47,
                _tmp48 * _tmp53 + _tmp57 + 0.01 * _tmp59,
                -_tmp48 * _tmp71 + _tmp68 + 0.01 * _tmp70,
            ],
            [
                -_tmp21 * _tmp49 + _tmp41 - 0.03 * _tmp47,
                -_tmp49 * _tmp53 + _tmp57 - 0.03 * _tmp59,
                _tmp49 * _tmp71 + _tmp68 - 0.03 * _tmp70,
            ],
        ]
    )

    return _out


_in0_mx = casadi.MX.sym("_in0", 9, 1)
panda_link6_vision = casadi.Function(
    "panda_link6_vision",
    [_in0_mx],
    [panda_link6_vision(_in0_mx)],
    dict(
        [
            (
                "cse",
                True,
            ),
            ("always_inline", True),
        ]
    ),
)
