# -----------------------------------------------------------------------------
# This file was autogenerated by symforce from template:
#     function/FUNCTION.py.jinja
# Do NOT modify by hand.
# -----------------------------------------------------------------------------

# pylint: disable=too-many-locals,too-many-lines,too-many-statements,unused-argument

import math  # pylint: disable=unused-import
import typing as T

import torch


class TensorKwargs(T.TypedDict):
    """
    TypedDict representing args that will be passed to any torch.tensor calls
    """

    device: torch.device
    dtype: torch.dtype


def _broadcast_and_stack(tensors, dim=-1):
    # type: (T.List[torch.Tensor], int) -> torch.Tensor
    """
    broadcast tensors to common shape then stack along new dimension
    """

    broadcast_shape = torch.broadcast_shapes(*(x.size() for x in tensors))
    broadcast_tensors = [x.broadcast_to(broadcast_shape) for x in tensors]

    return torch.stack(broadcast_tensors, dim=dim)


def panda_hand_collision(_in0, tensor_kwargs=None):
    # type: (torch.Tensor, TensorKwargs) -> torch.Tensor
    """
    This function was autogenerated. Do not modify by hand.

    Args:
        _in0: Matrix91

    Outputs:
        out: Matrix93

    The types for inputs and outputs above are the shapes of the symbolic matrices this function was
    generated from.  Tensors for both inputs and outputs are expected to have dimensions as follows:

    - (..., N, M) for sf.Matrix types of shape (N, M) where N != 1 and M != 1
    - (..., N) for sf.Matrix types of shape (N, M) where N != 1 and M == 1 (i.e. column vectors)
    - (..., M) for sf.Matrix types of shape (N, M) where N == 1 and M != 1 (i.e. row vectors)
    - (...) for sf.Matrix types of shape (1, 1) and sf.Scalar types

    Where `...` is an arbitrary number of batch dimensions that can be present on the front of input
    tensors.  The outputs will have the same batch dimensions as the inputs.

    The tensor_kwargs argument can be used to set the device and dtype to use.  If not provided, it will
    default to the device and dtype of the first input tensor, or the empty dict if there are no inputs.
    """

    # Total ops: 354

    # Deduce expected tensor device and dtype if not provided
    if tensor_kwargs is None:
        tensor_kwargs = {"device": _in0.device, "dtype": _in0.dtype}

    # Input arrays

    cte_1 = torch.tensor(0.0636396103067607, **tensor_kwargs)
    cte_2 = torch.tensor(0.207, **tensor_kwargs)
    cte_3 = torch.tensor(0.358, **tensor_kwargs)
    cte_4 = torch.tensor(0.0825, **tensor_kwargs)
    cte_5 = torch.tensor(0.122, **tensor_kwargs)
    cte_6 = torch.tensor(0.0848528137424237, **tensor_kwargs)
    cte_7 = torch.tensor(0.0848528137423477, **tensor_kwargs)
    cte_8 = torch.tensor(1.0, **tensor_kwargs)
    cte_9 = torch.tensor(0.0212132034356059, **tensor_kwargs)
    cte_10 = torch.tensor(0.088, **tensor_kwargs)
    cte_11 = torch.tensor(0.0424264068711738, **tensor_kwargs)
    cte_12 = torch.tensor(-0.62, **tensor_kwargs)
    cte_13 = torch.tensor(0.0212132034355869, **tensor_kwargs)
    cte_14 = torch.tensor(0.384, **tensor_kwargs)
    cte_15 = torch.tensor(0.0636396103068178, **tensor_kwargs)
    cte_16 = torch.tensor(0.0424264068712119, **tensor_kwargs)
    cte_17 = torch.tensor(0.137, **tensor_kwargs)
    cte_18 = torch.tensor(0.316, **tensor_kwargs)

    # Intermediate terms (112)
    _tmp0 = torch.cos(_in0[..., 5])
    _tmp1 = torch.sin(_in0[..., 0])
    _tmp2 = torch.sin(_in0[..., 2])
    _tmp3 = cte_8 * _tmp2
    _tmp4 = _tmp1 * _tmp3
    _tmp5 = torch.cos(_in0[..., 1])
    _tmp6 = torch.cos(_in0[..., 0])
    _tmp7 = torch.cos(_in0[..., 2])
    _tmp8 = cte_8 * _tmp7
    _tmp9 = _tmp6 * _tmp8
    _tmp10 = -_tmp4 + _tmp5 * _tmp9
    _tmp11 = torch.sin(_in0[..., 3])
    _tmp12 = cte_8 * _tmp11
    _tmp13 = torch.sin(_in0[..., 1])
    _tmp14 = torch.cos(_in0[..., 3])
    _tmp15 = cte_8 * _tmp14
    _tmp16 = _tmp13 * _tmp15
    _tmp17 = -_tmp10 * _tmp12 + _tmp16 * _tmp6
    _tmp18 = _tmp0 * _tmp17
    _tmp19 = torch.sin(_in0[..., 4])
    _tmp20 = _tmp1 * _tmp8
    _tmp21 = _tmp3 * _tmp6
    _tmp22 = (
        cte_8 * _tmp20
        + cte_8 * _tmp21 * _tmp5
    )
    _tmp23 = torch.cos(_in0[..., 4])
    _tmp24 = _tmp12 * _tmp13
    _tmp25 = (
        cte_8 * _tmp10 * _tmp15
        + cte_8 * _tmp24 * _tmp6
    )
    _tmp26 = -_tmp19 * _tmp22 + _tmp23 * _tmp25
    _tmp27 = torch.sin(_in0[..., 5])
    _tmp28 = cte_5 * _tmp27
    _tmp29 = cte_14 * _tmp11
    _tmp30 = cte_4 * _tmp14
    _tmp31 = cte_18 * _tmp13
    _tmp32 = cte_4 * _tmp2
    _tmp33 = cte_10 * _tmp27
    _tmp34 = cte_10 * _tmp0
    _tmp35 = _tmp5 * _tmp7
    _tmp36 = cte_4 * _tmp6
    _tmp37 = cte_14 * _tmp14
    _tmp38 = _tmp13 * _tmp37
    _tmp39 = _tmp11 * _tmp13
    _tmp40 = (
        -_tmp1 * _tmp32
        - _tmp10 * _tmp29
        - _tmp10 * _tmp30
        + _tmp17 * _tmp33
        + _tmp26 * _tmp34
        + _tmp31 * _tmp6
        + _tmp35 * _tmp36
        - _tmp36 * _tmp39
        + _tmp38 * _tmp6
        + cte_12
    )
    _tmp41 = torch.sin(_in0[..., 6])
    _tmp42 = cte_8 * _tmp27
    _tmp43 = cte_8 * _tmp0
    _tmp44 = _tmp17 * _tmp42 + _tmp26 * _tmp43
    _tmp45 = cte_16 * _tmp44
    _tmp46 = _tmp41 * _tmp45
    _tmp47 = torch.cos(_in0[..., 6])
    _tmp48 = cte_11 * _tmp44
    _tmp49 = _tmp47 * _tmp48
    _tmp50 = _tmp19 * _tmp25 + _tmp22 * _tmp23
    _tmp51 = _tmp47 * _tmp50
    _tmp52 = cte_16 * _tmp51
    _tmp53 = cte_11 * _tmp50
    _tmp54 = _tmp41 * _tmp53
    _tmp55 = _tmp46 - _tmp49 - _tmp52 - _tmp54
    _tmp56 = _tmp26 * _tmp27
    _tmp57 = (
        -cte_17 * _tmp18
        + _tmp40
        + cte_17 * _tmp56
    )
    _tmp58 = (
        -cte_2 * _tmp18
        + _tmp40
        + cte_2 * _tmp56
    )
    _tmp59 = cte_13 * _tmp41
    _tmp60 = cte_9 * _tmp47
    _tmp61 = cte_9 * _tmp41
    _tmp62 = cte_1 * _tmp41
    _tmp63 = cte_15 * _tmp47
    _tmp64 = cte_15 * _tmp41
    _tmp65 = cte_7 * _tmp41
    _tmp66 = cte_6 * _tmp47
    _tmp67 = cte_6 * _tmp41
    _tmp68 = _tmp20 * _tmp5 + _tmp21
    _tmp69 = (
        cte_8 * _tmp1 * _tmp24
        + cte_8 * _tmp15 * _tmp68
    )
    _tmp70 = (
        cte_8 * _tmp4 * _tmp5
        - cte_8 * _tmp9
    )
    _tmp71 = -_tmp19 * _tmp70 + _tmp23 * _tmp69
    _tmp72 = _tmp27 * _tmp71
    _tmp73 = _tmp1 * _tmp16 - _tmp12 * _tmp68
    _tmp74 = _tmp0 * _tmp73
    _tmp75 = cte_4 * _tmp1
    _tmp76 = (
        _tmp1 * _tmp31
        + _tmp1 * _tmp38
        - _tmp29 * _tmp68
        - _tmp30 * _tmp68
        + _tmp32 * _tmp6
        + _tmp33 * _tmp73
        + _tmp34 * _tmp71
        + _tmp35 * _tmp75
        - _tmp39 * _tmp75
    )
    _tmp77 = _tmp42 * _tmp73 + _tmp43 * _tmp71
    _tmp78 = cte_16 * _tmp77
    _tmp79 = _tmp41 * _tmp78
    _tmp80 = cte_11 * _tmp77
    _tmp81 = _tmp47 * _tmp80
    _tmp82 = _tmp19 * _tmp69 + _tmp23 * _tmp70
    _tmp83 = _tmp41 * _tmp82
    _tmp84 = cte_11 * _tmp83
    _tmp85 = _tmp47 * _tmp82
    _tmp86 = cte_16 * _tmp85
    _tmp87 = _tmp79 - _tmp81 - _tmp84 - _tmp86
    _tmp88 = (
        cte_17 * _tmp72
        - cte_17 * _tmp74
        + _tmp76
    )
    _tmp89 = (
        cte_2 * _tmp72
        - cte_2 * _tmp74
        + _tmp76
    )
    _tmp90 = _tmp11 * _tmp5
    _tmp91 = _tmp13 * _tmp7
    _tmp92 = (
        -cte_8 * _tmp15 * _tmp91
        + cte_8 * _tmp90
    )
    _tmp93 = _tmp13 * _tmp3
    _tmp94 = _tmp19 * _tmp93 + _tmp23 * _tmp92
    _tmp95 = _tmp12 * _tmp91 + _tmp15 * _tmp5
    _tmp96 = _tmp0 * _tmp95
    _tmp97 = (
        _tmp29 * _tmp91
        + _tmp30 * _tmp91
        + _tmp33 * _tmp95
        + _tmp34 * _tmp94
        + _tmp37 * _tmp5
        + cte_18 * _tmp5
        - cte_4 * _tmp90
        - cte_4 * _tmp91
        + cte_3
    )
    _tmp98 = _tmp42 * _tmp95 + _tmp43 * _tmp94
    _tmp99 = cte_11 * _tmp98
    _tmp100 = _tmp47 * _tmp99
    _tmp101 = cte_16 * _tmp98
    _tmp102 = _tmp101 * _tmp41
    _tmp103 = _tmp19 * _tmp92 - _tmp23 * _tmp93
    _tmp104 = _tmp103 * _tmp47
    _tmp105 = cte_16 * _tmp104
    _tmp106 = _tmp103 * _tmp41
    _tmp107 = cte_11 * _tmp106
    _tmp108 = -_tmp100 + _tmp102 - _tmp105 - _tmp107
    _tmp109 = _tmp27 * _tmp94
    _tmp110 = (
        cte_17 * _tmp109
        - cte_17 * _tmp96
        + _tmp97
    )
    _tmp111 = (
        cte_2 * _tmp109
        - cte_2 * _tmp96
        + _tmp97
    )

    # Output terms
    _out = _broadcast_and_stack(
        [
            _broadcast_and_stack(
                [
                    -cte_5 * _tmp18
                    + _tmp26 * _tmp28
                    + _tmp40
                    + _tmp55,
                    _tmp55 + _tmp57,
                    _tmp57,
                    -_tmp46 + _tmp49 + _tmp52 + _tmp54 + _tmp57,
                    _tmp58,
                    -_tmp44 * _tmp59
                    - _tmp44 * _tmp60
                    - _tmp50 * _tmp61
                    + cte_13 * _tmp51
                    + _tmp58,
                    -_tmp41 * _tmp48
                    - cte_16 * _tmp41 * _tmp50
                    - _tmp45 * _tmp47
                    + _tmp47 * _tmp53
                    + _tmp58,
                    -_tmp44 * _tmp62
                    - _tmp44 * _tmp63
                    - _tmp50 * _tmp64
                    + cte_1 * _tmp51
                    + _tmp58,
                    -_tmp44 * _tmp65
                    - _tmp44 * _tmp66
                    - _tmp50 * _tmp67
                    + cte_7 * _tmp51
                    + _tmp58,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    cte_5 * _tmp72
                    - cte_5 * _tmp74
                    + _tmp76
                    + _tmp87,
                    _tmp87 + _tmp88,
                    _tmp88,
                    -_tmp79 + _tmp81 + _tmp84 + _tmp86 + _tmp88,
                    _tmp89,
                    -_tmp59 * _tmp77
                    - _tmp60 * _tmp77
                    - _tmp61 * _tmp82
                    + cte_13 * _tmp85
                    + _tmp89,
                    -_tmp41 * _tmp80
                    - _tmp47 * _tmp78
                    - cte_16 * _tmp83
                    + cte_11 * _tmp85
                    + _tmp89,
                    -_tmp62 * _tmp77
                    - _tmp63 * _tmp77
                    - _tmp64 * _tmp82
                    + cte_1 * _tmp85
                    + _tmp89,
                    -_tmp65 * _tmp77
                    - _tmp66 * _tmp77
                    - _tmp67 * _tmp82
                    + cte_7 * _tmp85
                    + _tmp89,
                ],
                dim=-1,
            ),
            _broadcast_and_stack(
                [
                    _tmp108
                    + _tmp28 * _tmp94
                    - cte_5 * _tmp96
                    + _tmp97,
                    _tmp108 + _tmp110,
                    _tmp110,
                    _tmp100 - _tmp102 + _tmp105 + _tmp107 + _tmp110,
                    _tmp111,
                    -_tmp103 * _tmp61
                    + cte_13 * _tmp104
                    + _tmp111
                    - _tmp59 * _tmp98
                    - _tmp60 * _tmp98,
                    -_tmp101 * _tmp47
                    + cte_11 * _tmp104
                    - cte_16 * _tmp106
                    + _tmp111
                    - _tmp41 * _tmp99,
                    -_tmp103 * _tmp64
                    + cte_1 * _tmp104
                    + _tmp111
                    - _tmp62 * _tmp98
                    - _tmp63 * _tmp98,
                    -_tmp103 * _tmp67
                    + cte_7 * _tmp104
                    + _tmp111
                    - _tmp65 * _tmp98
                    - _tmp66 * _tmp98,
                ],
                dim=-1,
            ),
        ],
        dim=-1,
    )

    return _out
