name: Supabase Keep-Alive Project 2

on:
  schedule:
    - cron: '0 0 */3 * *' # Runs every 3 days at midnight
  workflow_dispatch:      # Allows you to test it manually

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Install psql
        run: sudo apt-get install -y postgresql-client

      - name: Poke Second Database
        env:
          DB_URL: ${{ secrets.SUPABASE_DB_URL_2 }}
        run: psql "$DB_URL" -c "SELECT 1;"
